### ISSUE TITLE
There is a recursion loop in NameResolver.

### ISSUE THREAD

**Issue by darinpetty** [grpc/grpc-java#6408] opened 2019-11-07 19:18 UTC
### What version of gRPC-Java are you using?
1.24.1

There is a recursion loop in NameResolver.
newNameResolver(URI targetUri, final Args args)
delegates to 
newNameResolver(URI targetUri, final Helper helper)
delegates to 
 newNameResolver(URI targetUri, final Attributes params)
delegates back to 
newNameResolver(URI targetUri, final Args args)

This can be triggered with 
NameResolverProvider.asFactory().newNameResolver(URI.create("localhost:22023"), NameResolver.Args.newBuilder()
                .setDefaultPort(22023)
                .setProxyDetector(pd)
                .setServiceConfigParser(new ScParser())
                .setSynchronizationContext(new SynchronizationContext(UncaughtExceptionHandlers.systemExit()))
                .build())

"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at io.grpc.NameResolver$Factory.newNameResolver(NameResolver.java:207)
	  at io.grpc.NameResolver$Factory.newNameResolver(NameResolver.java:233)
	  at io.grpc.NameResolver$Factory.newNameResolver(NameResolver.java:188)
	  at io.grpc.NameResolver$Factory.newNameResolver(NameResolver.java:205)
	  at io.grpc.NameResolver$Factory.newNameResolver(NameResolver.java:233)
	  at io.grpc.NameResolver$Factory.newNameResolver(NameResolver.java:188)
	  at io.grpc.NameResolver$Factory.newNameResolver(NameResolver.java:205)
	  at io.grpc.NameResolver$Factory.newNameResolver(NameResolver.java:233)
	  at io.grpc.NameResolver$Factory.newNameResolver(NameResolver.java:188)
	  at io.grpc.NameResolver$Factory.newNameResolver(NameResolver.java:205)
	  at io.grpc.NameResolver$Factory.newNameResolver(NameResolver.java:233)
	  at io.grpc.NameResolverRegistry$NameResolverFactory.newNameResolver(NameResolverRegistry.java:154)
	  at io.deephaven.dhservice.client.UnifiedServiceGrpcImpl.<init>(UnifiedServiceGrpcImpl.java:151)
	  at io.deephaven.dhservice.client.UnifiedServiceGrpcImpl.make(UnifiedServiceGrpcImpl.java:55)
	  at io.deephaven.dhservice.UniversalServiceTest.testSingleConnection(UniversalServiceTest.java:83)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	  at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	  at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	  at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	  at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	  at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	  at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	  at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	  at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by zhangkun83** [comment] 2019-11-08 20:28
Duplicate of #6410

**Closed by zhangkun83** 2019-11-08 20:28 UTC
Labels: bug
