### ISSUE TITLE
Channel creation best practice

### ISSUE THREAD

**Issue by BWMuller** [grpc/grpc-java#3268] opened 2017-07-24 10:19 UTC
### gRPC version?
1.4.0

### JVM
java version "1.8.0_102"

### Case:
If possible, provide a recipe for reproducing the error.
What is the best practice with regards to a channel, when using multiple (10+) grpc stream services stubs.
The channel I am using has tls enabled and generally when making the initial connection takes a few seconds to complete the full handshake. 

### Question:
Should the ManagedChannel by created in a singleton and used via that on all the grpc stubs or should the channel builder be used for every stub in order to create a new channel. 
I don't wish to go through the handshake every time, however I get random cases of unknown channel state where I don't get a error in the streamObserver, however nothing gets received on the server side either. 

### Issue:
This is specifically with regards to network connectivity changing causing the connections to drop and in my case not reconnect and no implemented option to get the channel state yet.

**Comment by BWMuller** [comment] 2017-07-24 10:23
@ejona86 Don't know if you could assist me on this one

**Comment by ericgribkoff** [comment] 2017-07-24 16:51
Channels are expensive to create, and the general recommendation is to use one per application, shared among the service stubs.

> I don't wish to go through the handshake every time, however I get random cases of unknown channel state where I don't get a error in the streamObserver, however nothing gets received on the server side either.

What do you mean by unknown channel state? If network connectivity drops off, it's possible that the socket will remain open and gRPC unaware of the loss of network. Keep-alives are one option to avoid this problem. Can you describe a little more about the environment where this is occurring? Are these mobiles client with OkHttp, or are you using Netty?

**Comment by BWMuller** [comment] 2017-07-24 20:53
>What do you mean by unknown channel state?
When creating a streamobserver I verify that there is data flow. After putting the app in the background without disconnecting the channel, I sometimes receive a endOfStream which is most likely due to the network changing, however this isn't always required to get this error.  When recreating the streamobserver the data i sent doesn't arrive server side and there are no responses or errors via the streamobserver 

>Are these mobiles client with OkHttp, or are you using Netty?
This is all done using the OkHttpChannelBuilder configured to use TLS

**Comment by ericgribkoff** [comment] 2017-07-28 22:06
@BWMuller A few questions:

1. When you say you're recreating the StreamObserver, does this mean you're starting a new RPC on a previously opened channel? 
2. When your app receives end-of-stream, do you mean it receives an HTTP/2 end-of-stream from the server? Or just that StreamObserver#{onError,onComplete} is called?
3. What device and Android API levels are you observing this on? Does the issue only occur when the network state changes while the app is in the background, or in other scenarios too?

Generally the TCP socket in use by gRPC will be terminated by the OS when the network disconnects. There could be some issues here related to gRPC being in the background when this occurs, but it sounds like something isn't working properly here. There's on-going work on handling network switches more robustly in our OkHttp transport, and that work might overlap with addressing your issue. Thanks for any additional information/reproduction code you can provide.

**Comment by lwasylkowski** [comment] 2017-11-02 15:44
@ericgribkoff Seems like OP abandoned the issue, but I'm having similar problem (~10 services on Android, single channel, unwanted state sometimes):

Once I try to make a call with a stub created on a channel with network connection disabled, I get `unknown host` exception, which is expected. But then after reenabling the network, making any call on the same channel (even with different stub) will fail with `unknown host` for some amount of time (couple of minutes? I think).

It seems like channel keeps some state longer than necessary - on new channel I can make the request as soon as the network connection comes back, but if one request fails, I need to wait.

This is on Android (api 21+), grpc 1.6.1 & 1.7.0, I'm using OkHttp channel with custom ssl socket factory (with pinned certificate)

**Comment by ericgribkoff** [comment] 2017-11-02 16:29
@lwasylkowski It sounds like you're running into gRPC's connection attempt backoffs (https://github.com/grpc/grpc-java/issues/2169). https://github.com/grpc/grpc-java/pull/3580 is out now, which adds a `reconnectNow()` method to the `ManagedChannel` API to signal gRPC to reconnect immediately rather than wait for the backoff timers to elapse. I expect this feature to make it into the next release; in the meantime, the best approach to avoid these connection delays on Android is to explicitly shutdown and recreate the channel on network drop and reconnection.

**Comment by lwasylkowski** [comment] 2017-11-02 16:34
@ericgribkoff thanks for swift response! This is probably it. Do you have any idea about the timeline for future release? I'd like to avoid unnecessary work

**Comment by ejona86** [comment] 2017-11-02 17:08
@lwasylkowski, we release every six weeks, with notes visible on the milestones: https://github.com/grpc/grpc-java/milestones . The next release (1.8) is scheduled for November 21.

**Comment by ejona86** [comment] 2017-11-08 15:59
Channel state has been implemented and there's other issues for being notified when network connectivity changes. Closing since it seems this is being handled elsewhere.

**Closed by ejona86** 2017-11-08 15:59 UTC

**Comment by wingoku** [comment] 2017-11-10 23:47
@ericgribkoff How expensive is it to shutdown and recreate a channel to connect to the server? The current work around I'm doing to immediately reconnect to the server is, I shutdown the current channel and recreate a channel on client side.

Btw there is no callback for ConnectionState either, so I've to check the connection status using good old polling method. In a different RxJava Observable, I just call `channel.getStatus(true)` to get the ConnectivityState object and then check if it's READY or Something else. Upon ready, I issue Connected callback from my observable and upon other status, I issue disconnected callback. Not an elegant solution or efficient one but it gets the job done.
