### ISSUE TITLE
memory leak in io.grpc.internal.TransportSet

### ISSUE THREAD

**Issue by alugowski** [grpc/grpc-java#1342] opened 2016-01-23 02:11 UTC
We experienced an issue where our grpc-java clients filled up their heaps and the entire cluster went down. The cause appears to be a list of futures in io.grpc.internal.TransportSet. 5 of these sets would consume 47% of a 30GB heap. The cluster was running without issue for a month.

Context: Our clients each make about 10,000 requests/s to a cluster of 80 servers. The problem began when the cluster of servers was restarted. The clients filled their heaps and effectively died. A restart of the clients resolved the immediate issue, but we want to fix the root cause.

The clients each maintain a single blocking stub for each of the 80 servers. We enforce a 10ms timeout using withDeadlineAfter(). All calling threads reuse the same blocking stub.

We did manage to get a heap dump of an offending client. We noticed that about 5 blocking stubs account for 47% of the retained heap on the machine. ~70 blocking stubs have the expected ~1kb size. I'm attaching a screenshot of the Dominator Tree report from Eclipse Memory Analyzer showing the problem. The labels on the columns are "shallow heap", "retained heap" and "retained heap %". This shows that a single io.grpc.internal.TransportSet has references to effectively a linked-list of RunnableExecutorPair objects each containing a Future. This linked list is 1.6 GB in size, where each element is about 1.5kb.

Any thoughts? What can I do to help debug this?

We are running grpc-java master as of Dec 9. v0.9 has a bug that makes it unusable for us.

![grpc_stub_heap_use](https://cloud.githubusercontent.com/assets/2730364/12527498/517abf4a-c131-11e5-854e-542dec03e347.png)

**Comment by carl-mastrangelo** [comment] 2016-01-23 02:20
Is it possible there are some very long lived connections?  The only hash map in MCI that would fill that roll is the transport set, which should be pretty small, and clean itself up after a transport has shutdown.  

@zhangkun83 thoughts?

**Comment by alugowski** [comment] 2016-01-23 02:22
@carl-mastrangelo the TransportSet is the one that filled up.

**Comment by alugowski** [comment] 2016-01-23 02:28
More precisely, the TransportSet itself has small cardinality, but it contains a very long linked list.

**Comment by carl-mastrangelo** [comment] 2016-01-23 02:34
It seems like TransportSet was changed on December 9th.  Can you confirm if you are running with https://github.com/grpc/grpc-java/commit/7ce50f76c75407d94b28cefbfa42bc0680ce7c60 in your clients?

**Comment by zhangkun83** [comment] 2016-01-23 05:39
I have found an issue which is probably the cause. In `ClientCallImpl.start()`, if the transport is not ready, we register a `StreamCreationTask` to the transport future, which originates from `TransportSet`. When the call gets cancelled because of exceeding the deadline, the callback doesn't get removed. Util the transport becomes available, callbacks get accumulated.

Because `ListenableFuture` doesn't provide a way to remove a listener/callback, we probably have to add an extra layer that is a `FutureCallback`, which is the only callback registered to the future, hosts the `StreamCreationTask`s  and has the ability to remove them once their corresponding calls are cancelled.

**Comment by alugowski** [comment] 2016-01-23 06:00
@carl-mastrangelo we do not have that commit. It looks like my latest commit is 82a79d8f93f7466138dd05c1ca593f837e7699bb from Dec 7.

@zhangkun83 We do see a lot of errors and GOAWAYs in the logs. Our connections are typically long-lived; on the order of days. Usually the clients are restarted, this was a special occasion that the servers were.

For our use case, if the transport is not ready we'd rather drop the request. Alternatively, could the timeout code remove the callback?

**Comment by alugowski** [comment] 2016-01-23 06:02
Or cap the size of that queue and drop requests if the queue is full?

**Comment by zhangkun83** [comment] 2016-01-23 06:19
> Alternatively, could the timeout code remove the callback?
> Or cap the size of that queue and drop requests if the queue is full?

This is what I was talking about in my previous comment. The Guava futures framework doesn't  provide an API to remove the callbacks or cap the number of callbacks, thus we have to do by ourselves in gRPC. While I will surely work on it next week, it doesn't seem to be a trivial change.

Before we fix the issue, you can work around it by capping the number of retries in a row. For example, if you have seen 100 `DEADLINE_EXCEEDED` errors in a row on a single stub, you stop sending more calls until the transport is ready.  If we had implemented the channel state API, you would be able to get notified when transport is ready. For now, you can add a `ping` method to your service which simply replies an empty message, then start a `ping` call with __no deadline__ when you stop sending normal calls. When the `ping` call succeeds, you will know the transport is ready and you may resume sending calls.

**Comment by alugowski** [comment] 2016-01-23 07:27
Thank you very much for looking into it! Much appreciated!

**Comment by alugowski** [comment] 2016-01-27 19:55
We've had this problem come up several more times in the last few days, so we were forced to disable grpc and go back to our old inferior messaging system until we can fix the root cause. Can I offer any more data/help in the fix?

**Comment by zhangkun83** [comment] 2016-01-27 20:35
Thank you, but we don't need anything from you at this moment. We have a proposal of refactor that may fix this problem nicely. It's not a small change. Hopefully we will see some progress by the end of next week.

**Comment by alugowski** [comment] 2016-01-27 20:44
Thank you!

**Comment by zhangkun83** [comment] 2016-02-13 00:03
With #1395 checked in, the memory leak in the case where the client fails to connect to already-resolved server addresses, should have been resolved. @alugowski I think your case falls into this category, so you should no longer have the issue. That change will be in 0.13.0.

However, if the name resolution never succeeds, and the calls keep timing out and being retried, there will still be memory leak. It will be fixed in following changes, but may not make it into 0.13.0. It will be in the release after that. I will leave this issue open until that.

**Comment by alugowski** [comment] 2016-02-13 00:57
Great!

Other than the usual disclaimers of running master, do you guys see potential roadblocks to using the build now?

If not, I'll start the process of validating this and rolling it out. Unfortunately we've only seen this problem in production, and even there it's transient, so it may be a while before I can say what the effect is for us.

**Comment by ejona86** [comment] 2016-02-13 00:59
@alugowski, no particular roadblocks to using master at this time. We've planning on releasing on Monday, so what you see now should be very similar to what we release.

**Comment by alugowski** [comment] 2016-02-13 01:03
In that case I'll just wait until Monday. Thanks for your work on this!

**Comment by alugowski** [comment] 2016-02-22 22:15
Just FYI, we've had this fix in production since last week, and so far no issues. I restarted the server cluster several times in an attempt to trigger the problem, but the clients behaved properly.

Thanks for your had work!

**Closed** 2016-02-23 17:43 UTC
Labels: bug
