### ISSUE TITLE
GRPC sometimes picks wrong Executor

### ISSUE THREAD

**Issue by schmidt-sebastian** [grpc/grpc-java#5966] opened 2019-07-09 16:11 UTC
We are using GRPC for our Firestore Android SDK. Dependencies are:

```
    implementation 'io.grpc:grpc-stub:1.21.0'
    implementation 'io.grpc:grpc-protobuf-lite:1.21.0'
    implementation 'io.grpc:grpc-okhttp:1.21.0'
    implementation 'io.grpc:grpc-android:1.21.0'
```

We have some integration tests that [set up](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/firebase/firestore/remote/GrpcCallProvider.java) two different RPC stubs: 

```
ManagedChannel channel = initChannel(context, databaseInfo);
FirestoreGrpc.FirestoreStub firestoreStub =
    FirestoreGrpc.newStub(channel).withCallCredentials(firestoreHeaders);

private ManagedChannel initChannel(Context context, DatabaseInfo databaseInfo) {
    ...
    channelBuilder.executor(asyncQueue.getExecutor());
    ...
    return channelBuilder.build();
}
```

These GRPC stubs are independent of one-another and use a different channel with a executor. 

Some of our operation verify that they run on the correct executor by looking at the thread ID, and this invariant often breaks in the GRPC callbacks when the Managed Channel is first set up. It seems like https://github.com/grpc/grpc-java/blob/f3bf250a46571db3321fc3078b55e74280bdfd87/core/src/main/java/io/grpc/internal/DelayedClientTransport.java#L290 is picking up the wrong executor.

We have since fixed this by removing the call to `channelBuilder.executor(...)` and instead calling `FirestoreGrpc.newStub(channel).withExecutor(...)`. This is then picked up correctly by https://github.com/grpc/grpc-java/blob/f3bf250a46571db3321fc3078b55e74280bdfd87/core/src/main/java/io/grpc/internal/DelayedClientTransport.java#L294

Is this the expected behavior? More details can be found in the discussion here: https://github.com/firebase/firebase-android-sdk/pull/585

**Comment by dapengzhang0** [comment] 2019-07-12 00:35
`channelBuilder.executor()` provides **Channel Executor**, that's the executor used for running connection threads. The application logic is not supposed to and may or may not run in those threads, it's not guaranteed. When you explicitly provide an **Application Executor** (by `stub.withExecutor()` or `callOptions.withExecutor()`), then your application logic will run with the Application Executor.

**Comment by schmidt-sebastian** [comment] 2019-07-12 04:37
Do you have an explanation for why a Stub that is initialized with `stub1.withExecutor(executor1)` might sometimes use `executor2` if a stub2 with `stub2.withExecutor(executor2)` exists?

That seems to be the observed behavior, but I may be wrong.

**Comment by dapengzhang0** [comment] 2019-07-12 16:16
>Do you have an explanation for why a Stub that is initialized with stub1.withExecutor(executor1) might sometimes use executor2 if a stub2 with stub2.withExecutor(executor2) exists?

I don't think it's possible. Can you provide a small reproducible example?

**Comment by schmidt-sebastian** [comment] 2019-07-12 21:36
I don't have a small example unfortunately. I'll see if I can come up with something, but so far I have seen this only in our main codebase. On top of that, the test failures are sporadic.

**Comment by ejona86** [comment] 2019-07-30 17:55
We would love a reproduction case, but this sort of thing would be harder to be a bug in gRPC. Closing since there's not much we can do at the moment. If you get a reproduction case we can reopen.

**Closed by ejona86** 2019-07-30 17:55 UTC
