### ISSUE TITLE
On Android, ManagedChannel is no more reusable (10 requests max with 1 request per second)

### ISSUE THREAD

**Issue by eltanardo** [grpc/grpc-java#10572] opened 2023-09-22 15:17 UTC
### What version of gRPC-Java are you using?
1.58.0

### What is your environment?

**- Client side**
RouteGuide example for Android, tagged v1.58.0
Tested with Android 9 to Android 13

**- Server side**
RouteGuide server example from grpc python tagged v1.58.0, linux 

### What did you expect to see?
I expect to be able to reuse the same ManagedChannel for each grpc call

### What did you see instead?
After approximately 10 requests in 10 seconds, the channel is no more usable. I have to "exit router guide" then "start router guide", because the channel is no more usable

**- On Android client side**
```
io.grpc.StatusRuntimeException: UNAVAILABLE: Refused stream
Rst Stream
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167)
	at io.grpc.routeguideexample.RouteGuideGrpc$RouteGuideBlockingStub.getFeature(RouteGuideGrpc.java:361)
	at io.grpc.routeguideexample.RouteGuideActivity$GetFeatureRunnable.getFeature(RouteGuideActivity.java:201)
	at io.grpc.routeguideexample.RouteGuideActivity$GetFeatureRunnable.run(RouteGuideActivity.java:189)
	at io.grpc.routeguideexample.RouteGuideActivity$GrpcTask.doInBackground(RouteGuideActivity.java:156)
	at io.grpc.routeguideexample.RouteGuideActivity$GrpcTask.doInBackground(RouteGuideActivity.java:141)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```
### Steps to reproduce the bug

- On Android client side
  Launch RouteGuide
  Enter server host and port
  "start route guide" 
  Click 1 time per second on "Get Feature".

**With grpc-java version from v1.29.0 to v1.46.1, it works. Above version v1.46.1, it fails** 

**- On Linux Python server side**
No error

**Comment by larry-safran** [comment] 2023-10-03 01:11
The error indicates that the endpoint has received a HEADERS frame that caused its concurrent stream limit to be exceeded.  It is surprising to me that the limit is only 10.

Are you reading the returned values from the future or just letting the results accumulate?

**Comment by eltanardo** [comment] 2023-10-03 07:31
In order to exclude a problem with my implementation (Android <-> Linux C++), I reproduced the behavior with the examples provided by [grpc-java Android java 1.58.0](https://github.com/grpc/grpc-java/tree/f9562b16efe43ae35840d86f4106ef8b577c4155/examples/android/routeguide) and [grpc python 1.58.0](https://github.com/grpc/grpc/tree/0417b882aa7abc1512f534e56f9cd97c557bb68f/examples/python/route_guide).

**On client side,** I have the issue with Android platform only, not the java desktop version. If I switch to version [1.46.1](https://github.com/grpc/grpc-java/tree/b69a1165f4e6e3d22cb552d4c5e2f0ac12bdae20/examples/android/routeguide), the ManagedChannel manages the connection well.

What I do on RouteGuide example is to click each second on the button "Get Feature".

**Comment by ejona86** [comment] 2023-10-31 21:27
The 10 is probably because [Python limits the number of workers to 10](https://github.com/grpc/grpc/blob/300eadadfee7839ff100c4efc1ccef49cf189353/examples/python/route_guide/route_guide_server.py#L119) in the example.

**Comment by ejona86** [comment] 2023-11-03 15:41
@temawi, this does line up with the [upgrades to appcompat](https://github.com/grpc/grpc-java/pull/10497). Seems that should have been low-risk. I wonder if the Android libraries changed something that means RPCs aren't getting closed now when they previously were.

**Comment by temawi** [comment] 2023-12-18 19:27
I just tried running the 1.58.0 Android route guide client against 1.58.0 Go server and no amount of clicking is reproducing the problem. This seems to point the finger at the Python server.

@eltanardo maybe you can confirm you also see the same thing? Getting a Go server running is straightforward, after installing Go:

```
git clone --branch v1.58.0 https://github.com/grpc/grpc-go.git
cd examples/route_guide
go run server/server.go
```

The server will run on port 50051

```

**Comment by eltanardo** [comment] 2023-12-20 19:43
@temawi , using v1.46.1 android client, 
I have reproduced the same behavior with Golang (just have to change the binding address that was stuck on loopback :-) ) and C++ servers. On the other hand, no issue observed with the java server.
[v1.58.1.webm](https://github.com/grpc/grpc-java/assets/142685225/06ef832b-a25f-461b-a6ad-a23749d3406f)

**Comment by temawi** [comment] 2024-01-16 22:30
@eltanardo v1.46.1 is old at this point, why did you use that version? Can you reproduce it with 1.58.0 client and 1.58.0 Go server?

**Comment by temawi** [comment] 2024-02-06 18:44
No updates on this one so maybe the issue got resolved? I will close this but it can be reopened if further discussion is needed.

**Closed by temawi** 2024-02-06 18:44 UTC
Labels: android
