### ISSUE TITLE
Implement Round Robin logic in SimpleLoadBalancerFactory

### ISSUE THREAD

**Issue by saturnism** [grpc/grpc-java#1840] opened 2016-05-19 01:58 UTC
Round robin logic is not yet implemented. Is there any timeline for this?

Thanks,

**Comment by buchgr** [comment] 2016-05-19 20:17
Seems like a duplicate of https://github.com/grpc/grpc-java/issues/1141 . According to that issue, round robin is scheduled for version 1.1. 

Maybe that's something you would like to contribute yourself @saturnism? :-)

Closing this, as duplicate.

**Closed by buchgr** 2016-05-19 20:17 UTC
