### ISSUE TITLE
maven plugin generates puzzling custom protobuf file on windows x64

### ISSUE THREAD

**Issue by testforvln** [grpc/grpc-java#1717] opened 2016-04-22 06:23 UTC
Hi, I followed the Readme.md and used the maven plugin for protobuf-based codegen of proto files. After importing the maven plugin in project from pom.xml, I executed the command of protobuf:compile and protobuf:compile-custom and got the generated protobuf files.
But the generated custom grpc-java file of *Grpc.java is not compatible of java 8. The IDE of intellij idea told me that "@java.lang.Override is not allowed to when implementing interface method". I compared the generated *Grpc.java file with the *Grpc.java file in the io.grpc.examples in grpc-java repository. The file from github (for example, RouteGuideGrpc.java)  has abstract class AbstractRouteGuide, but using maven plugin can not generate the abstracte class. 
Why the file generated by maven plugin is not compatible, and how can I generate the correct java file?
Thanks!

**Comment by testforvln** [comment] 2016-04-22 06:27
The protoc-plugins from maven repository is protoc-3.0.0-beta-2-windows-x86_64.exe and protoc-gen-grpc-java-0.13.2-windows-x86_64.exe.

**Comment by ejona86** [comment] 2016-04-22 14:43
> @java.lang.Override is not allowed to when implementing interface method
That is an old limitation, I think in Java 5 and was fixed in Java 6. Check your IDE settings; I don't think you are using Java 8 source compatibility. We compile the generated code with Java 6 compatibility and don't have any trouble.

You are generating the correct file. The example is using the codegenerator at master, which has some new features that will be released with 0.14.

**Comment by testforvln** [comment] 2016-04-25 06:24
Thanks for your reply.

**Comment by ejona86** [comment] 2016-04-29 18:00
It sounds like the issue is resolved. @testforvln, if you are still having trouble just tell us.

**Closed by ejona86** 2016-04-29 18:00 UTC
