### ISSUE TITLE
Client blocks exactly at the third call while calling the unary method in loop?

### ISSUE THREAD

**Issue by sankarvj** [grpc/grpc-java#6417] opened 2019-11-12 06:07 UTC
### What version of gRPC-Java are you using?
1.25.0
### What is your environment?

Linux centos 
### What did you expect to see?
The client should able to call the GRPC server in the remote host in a loop using the same channel.
### What did you see instead?
While calling in the loop, the client receives response 2 times and blocks at the third attempt forever. It happens only if I call a remote machine in AWS from my local machine. Local Client to Local server or AWS EC2 Client to Another EC2 server working as expected.
### Steps to reproduce the bug
Host a GRPC server in the remote machine. In the client, create a channel and use the same channel instance to call the remote method in a loop and shut down the channel after the loop.

Client code:
```
TestGrpcClientBase client = new TestGrpcClientBase(address, 8082);
        for (int i = 0; i < 5; i++) {
            long startTime = System.currentTimeMillis();
            client.creatContact();
            System.out.println("Time Taken -- "+(System.currentTimeMillis() - startTime));
        }
        client.shutdown();
```

Client logs: 
```
Calling server from client to create contact =================> 
-Dio.netty.leakDetection.level: simple
-Dio.netty.leakDetection.targetRecords: 4
-Dio.netty.buffer.checkAccessible: true
-Dio.netty.buffer.checkBounds: true
Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@16c1ce4
-Dio.netty.processId: 38201 (auto-detected)
-Djava.net.preferIPv4Stack: false
-Djava.net.preferIPv6Addresses: false
Loopback interface: lo0 (lo0, 0:0:0:0:0:0:0:1)
Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
-Dio.netty.machineId: 18:65:90:ff:fe:cc:5f:83 (auto-detected)
-Dio.netty.allocator.numHeapArenas: 16
-Dio.netty.allocator.numDirectArenas: 16
-Dio.netty.allocator.pageSize: 8192
-Dio.netty.allocator.maxOrder: 11
-Dio.netty.allocator.chunkSize: 16777216
-Dio.netty.allocator.tinyCacheSize: 512
-Dio.netty.allocator.smallCacheSize: 256
-Dio.netty.allocator.normalCacheSize: 64
-Dio.netty.allocator.maxCachedBufferCapacity: 32768
-Dio.netty.allocator.cacheTrimInterval: 8192
-Dio.netty.allocator.cacheTrimIntervalMillis: 0
-Dio.netty.allocator.useCacheForAllThreads: true
-Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
-Dio.netty.allocator.type: pooled
-Dio.netty.threadLocalDirectBufferSize: 0
-Dio.netty.maxThreadLocalCharBufferSize: 16384
-Dio.netty.recycler.maxCapacityPerThread: 4096
-Dio.netty.recycler.maxSharedCapacityFactor: 2
-Dio.netty.recycler.linkCapacity: 16
-Dio.netty.recycler.ratio: 8
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] INBOUND SETTINGS: ack=false settings={INITIAL_WINDOW_SIZE=268435456}
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] OUTBOUND SETTINGS: ack=true
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] INBOUND SETTINGS: ack=true
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=268369921
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: xxxxxxxxxxxxxx.com:8082, :path: /pb.ContactService/CreateContact, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.25.0, grpc-accept-encoding: gzip, grpc-timeout: 13634673u] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=301 bytes=00000001280a063133333233321204313231322201412201422201432a01013201013a01014201014a01015a0576696a6179620673616e6b61726a0f76696a61...
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip, x-envoy-upstream-service-time: 79, date: Tue, 12 Nov 2019 06:02:20 GMT, server: envoy] padding=0 endStream=false
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] INBOUND DATA: streamId=3 padding=0 endStream=false length=301 bytes=00000001280a063133333233321204313231322201412201422201432a01013201013a01014201014a01015a0576696a6179620673616e6b61726a0f76696a61...
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[grpc-status: 0] padding=0 endStream=true
<======================== Contact saved successfully : 133232
Time Taken -- 1910
Calling server from client to create contact =================> 
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] OUTBOUND HEADERS: streamId=5 headers=GrpcHttp2OutboundHeaders[:authority: xxxxxxxxxxxxxx.com:8082, :path: /pb.ContactService/CreateContact, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.25.0, grpc-accept-encoding: gzip, grpc-timeout: 14999830u] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] OUTBOUND DATA: streamId=5 padding=0 endStream=true length=301 bytes=00000001280a063133333233321204313231322201412201422201432a01013201013a01014201014a01015a0576696a6179620673616e6b61726a0f76696a61...
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] INBOUND HEADERS: streamId=5 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip, x-envoy-upstream-service-time: 73, date: Tue, 12 Nov 2019 06:02:21 GMT, server: envoy] padding=0 endStream=false
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] INBOUND DATA: streamId=5 padding=0 endStream=false length=301 bytes=00000001280a063133333233321204313231322201412201422201432a01013201013a01014201014a01015a0576696a6179620673616e6b61726a0f76696a61...
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] INBOUND HEADERS: streamId=5 headers=GrpcHttp2ResponseHeaders[grpc-status: 0] padding=0 endStream=true
<======================== Contact saved successfully : 133232
Time Taken -- 351
Calling server from client to create contact =================> 
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] OUTBOUND HEADERS: streamId=7 headers=GrpcHttp2OutboundHeaders[:authority: xxxxxxxxxxxxxx.com:8082, :path: /pb.ContactService/CreateContact, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.25.0, grpc-accept-encoding: gzip, grpc-timeout: 14999864u] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] OUTBOUND DATA: streamId=7 padding=0 endStream=true length=301 bytes=00000001280a063133333233321204313231322201412201422201432a01013201013a01014201014a01015a0576696a6179620673616e6b61726a0f76696a61...
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] OUTBOUND PING: ack=false bytes=1111
[id: 0x2fc20e36, L:/192.168.58.42:52335 - R:xxxxxxxxxxxxxx:8082] OUTBOUND RST_STREAM: streamId=7 errorCode=8
RPC failed: {0}Status{code=DEADLINE_EXCEEDED, description=deadline exceeded after 14999797421ns. [remote_addr=xxxxxxxxxxxxxx:8082], cause=null}
Time Taken -- 15002
```

Server logs:
```
[id: 0x6d3c9880, L:/127.0.0.1:8086 - R:/127.0.0.1:57450] OUTBOUND SETTINGS: ack=false settings={MAX_CONCURRENT_STREAMS=10, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
[id: 0x6d3c9880, L:/127.0.0.1:8086 - R:/127.0.0.1:57450] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
[id: 0x6d3c9880, L:/127.0.0.1:8086 - R:/127.0.0.1:57450] INBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, INITIAL_WINDOW_SIZE=268435456}
[id: 0x6d3c9880, L:/127.0.0.1:8086 - R:/127.0.0.1:57450] OUTBOUND SETTINGS: ack=true
[id: 0x6d3c9880, L:/127.0.0.1:8086 - R:/127.0.0.1:57450] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=268369921
[id: 0x6d3c9880, L:/127.0.0.1:8086 - R:/127.0.0.1:57450] INBOUND HEADERS: streamId=1 headers=GrpcHttp2RequestHeaders[:path: /pb.ContactService/CreateContact, :authority: xxxxxxxxxx:8082, :method: POST, :scheme: http, te: trailers, content-type: application/grpc, user-agent: grpc-java-netty/1.25.0, grpc-accept-encoding: gzip, grpc-timeout: 13634673u, x-forwarded-proto: http, x-request-id: f1e9257d-9e9e-47e6-a049-33080ff5fad7, x-envoy-expected-rq-timeout-ms: 15000] padding=0 endStream=false
[id: 0x6d3c9880, L:/127.0.0.1:8086 - R:/127.0.0.1:57450] INBOUND DATA: streamId=1 padding=0 endStream=true length=301 bytes=00000001280a063133333233321204313231322201412201422201432a01013201013a01014201014a01015a0576696a6179620673616e6b61726a0f76696a61...
[id: 0x6d3c9880, L:/127.0.0.1:8086 - R:/127.0.0.1:57450] INBOUND SETTINGS: ack=true
[id: 0x6d3c9880, L:/127.0.0.1:8086 - R:/127.0.0.1:57450] OUTBOUND HEADERS: streamId=1 headers=GrpcHttp2OutboundHeaders[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
GRPC call code latency timeMS 71
[id: 0x6d3c9880, L:/127.0.0.1:8086 - R:/127.0.0.1:57450] OUTBOUND DATA: streamId=1 padding=0 endStream=false length=301 bytes=00000001280a063133333233321204313231322201412201422201432a01013201013a01014201014a01015a0576696a6179620673616e6b61726a0f76696a61...
[id: 0x6d3c9880, L:/127.0.0.1:8086 - R:/127.0.0.1:57450] OUTBOUND HEADERS: streamId=1 headers=GrpcHttp2OutboundHeaders[grpc-status: 0] streamDependency=0 weight=16 exclusive=false padding=0 endStream=true
[id: 0x6d3c9880, L:/127.0.0.1:8086 - R:/127.0.0.1:57450] INBOUND HEADERS: streamId=3 headers=GrpcHttp2RequestHeaders[:path: /pb.ContactService/CreateContact, :authority: xxxxxxxxxx:8082, :method: POST, :scheme: http, te: trailers, content-type: application/grpc, user-agent: grpc-java-netty/1.25.0, grpc-accept-encoding: gzip, grpc-timeout: 14999830u, x-forwarded-proto: http, x-request-id: d55d432b-eb9c-48a7-bc78-5927073b359f, x-envoy-expected-rq-timeout-ms: 15000] padding=0 endStream=false
[id: 0x6d3c9880, L:/127.0.0.1:8086 - R:/127.0.0.1:57450] INBOUND DATA: streamId=3 padding=0 endStream=true length=301 bytes=00000001280a063133333233321204313231322201412201422201432a01013201013a01014201014a01015a0576696a6179620673616e6b61726a0f76696a61...
[id: 0x6d3c9880, L:/127.0.0.1:8086 - R:/127.0.0.1:57450] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
GRPC call code latency timeMS 70
[id: 0x6d3c9880, L:/127.0.0.1:8086 - R:/127.0.0.1:57450] OUTBOUND DATA: streamId=3 padding=0 endStream=false length=301 bytes=00000001280a063133333233321204313231322201412201422201432a01013201013a01014201014a01015a0576696a6179620673616e6b61726a0f76696a61...
[id: 0x6d3c9880, L:/127.0.0.1:8086 - R:/127.0.0.1:57450] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[grpc-status: 0] streamDependency=0 weight=16 exclusive=false padding=0 endStream=true
[id: 0x6d3c9880, L:/127.0.0.1:8086 - R:/127.0.0.1:57450] OUTBOUND PING: ack=false bytes=57005
[id: 0x6d3c9880, L:/127.0.0.1:8086 - R:/127.0.0.1:57450] INBOUND PING: ack=true bytes=57005

```

**Comment by zhangkun83** [comment] 2019-11-12 16:46
The IP and port of the client and server logs don't match. Can you double check if the logs are the right ones?

**Comment by sankarvj** [comment] 2019-11-13 04:59
> The IP and port of the client and server logs don't match. Can you double check if the logs are the right ones?

Sorry I didn't mention it earlier. The client calls the envoy proxy running at port 8082 and the proxy routes to its local server 8086. But the problem persists even if I call the server directly without the proxy layer.

**Comment by sankarvj** [comment] 2019-11-15 05:51
I also found that It happens only if I call a remote machine in AWS from my local machine. Local Client to Local server or AWS EC2 Client to Another EC2 server working as expected.

**Comment by dapengzhang0** [comment] 2019-11-18 19:25
Is this reproducible for any local machine anywhere? If so, can you send us a sample client code and a sample EC2 server address and let us debug locally?

**Comment by ejona86** [comment] 2020-03-26 20:18
Closing, since no additional information provided. Can be reopened if there is more information.

**Closed by ejona86** 2020-03-26 20:18 UTC
Labels: bug
