### ISSUE TITLE
gRPC-okhttp ipv6 addresses not working with TLS

### ISSUE THREAD

**Issue by andreasziegl** [grpc/grpc-java#11492] opened 2024-08-28 06:19 UTC
### What version of gRPC-Java are you using?

1.66.0
### What is your environment?

Tested with Android 13

### What did you expect to see?

I expect gRPC-okhttp be able to work with ipv6 addresses
### What did you see instead?

AndroidNegotiator inside OkHttpProtocolNegotiator.java class is using SNI_HOST_NAME.newInstance(hostname) which throws exception because SNIHostName(String hostname) doesn't accept ":".

There was already an attempt to resolve this issue in #9326, but this had to be reverted by @ejona86. @jader-eero reported, that the error only occurs, when he uses link local scoped addresses, but for me it happens with all IPV6 addresses, as ":" is also an illegal char.

### Steps to reproduce the bug

Any connection that uses configureTlsExtensions from AndroidNegotiator class which uses ipv6 addresses

**Comment by ejona86** [comment] 2024-09-10 16:59
Duplicate of #9325. Let's continue tracking this there.

**Closed by ejona86** 2024-09-10 16:59 UTC
