### ISSUE TITLE
Get Status exception with both error details and cause

### ISSUE THREAD

**Issue by SanjayVas** [grpc/grpc-java#10230] opened 2023-05-31 18:38 UTC
It looks like the only way to set error details is to use the Status proto message and then use the [`StatusProto`](https://github.com/grpc/grpc-java/blob/master/protobuf/src/main/java/io/grpc/protobuf/StatusProto.java) util to convert it to an exception. This doesn't provide a way to specify a `Throwable` cause like using the [`Status`](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/Status.java) class does.

Is there a way I'm missing to do this? The cause is really helpful in debugging (we have a server interceptor that logs it for a subset of errors).

**Comment by larry-safran** [comment] 2023-05-31 23:04
We have an example:  https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/errordetails/ErrorDetailsExample.java
The relevant code piece is:

```
            Status status = Status.newBuilder()
                .setCode(Code.INVALID_ARGUMENT.getNumber())
                .setMessage("Email or password malformed")
                .addDetails(Any.pack(DEBUG_INFO))
                .build();
            responseObserver.onError(StatusProto.toStatusRuntimeException(status));
```

**Comment by larry-safran** [comment] 2023-06-01 02:00
You can use t.printStackTrace to convert the stacktrace to a String and then include the string in the Details.

**Comment by SanjayVas** [comment] 2023-06-01 17:52
Doesn't that result in the stack trace leaking to the API caller? The goal is to have the cause logged at the server for debugging but not known to the caller.

It sounds like the without a change to grpc-java, the workaround would be to copy the implementation of the private methods in the StatusProto to both appropriately set the trailers as well as the cause.

**Comment by SanjayVas** [comment] 2023-06-01 21:01
I want the stack trace available in my server interceptor that logs a subset of errors, but not in the Status that's made available to the caller. This is the exact purpose of having the `withCause` method in io.grpc.Status.

**Comment by larry-safran** [comment] 2023-06-01 21:59
I've been assuming that you are starting with a `com.google.rpc.Status` object since you mention `StatusProto`.  If you construct an `io.grpc.Status` and use the `withCause(t)`, you can do `new StatusRuntimeException(myGrpcStatus)` which will create a StatusRuntimeException with the cause set.

**Comment by SanjayVas** [comment] 2023-06-01 22:28
The problem with that approach is that you can't set error details. You have to use a Status protobuf message for that.

The issue I've been having is that you can either specify a cause _or_ specify error details, but not both.

**Comment by larry-safran** [comment] 2023-06-01 23:26
You are correct that currently you can have one or the other, but not both if you want to use StatusProto to restore your com.google.rpc.Status object.  You could use the metadata to do your own version of the details handling, adding the error details to the Metadata with your own key and retrieving them when you wanted to consume the error details.  Since the key used by StatusProto for this is private, there is no guarantee that in the future it won't change, so I would recommend not relying on it.

**Comment by ejona86** [comment] 2023-06-02 15:11
With the current API, you can unpack and repack the exception:
```java
StatusRuntimeException sre = StatusProto.toStatusRuntimeException(status);
sre = sre.getStatus()
    .withCause(someException)
    .toRuntimeException(sre.getMetadata());
```

But I'd agree that is annoying. We could have overloads in StatusProto, but that seems unwieldy and confusing since it is for debugging-only and we have enough trouble with people thinking that exceptions will be sent over-the-wire.

Maybe we could add a convenience to Status{Runtime,}Exception, although that's looking like it'd be even worse, and creating extra exceptions isn't great performance-wise. So StatusProto tweaks still seems better. But maybe the manual unpacking+repacking is okay for now.

**Comment by SanjayVas** [comment] 2023-06-02 17:25
Thanks for the workaround!

I think the cleaner solution if making an API change would be to add a `withDetails` method `io.grpc.Status` and then let it take care of building the Status proto and sticking it into the trailers in `asException`/`asRuntimeException` methods.

**Comment by ejona86** [comment] 2023-06-02 19:24
> I think the cleaner solution if making an API change would be to add a withDetails method io.grpc.Status

Unfortunately, that is complicated by three issues:
1. Metadata (which the details are stored in) isn't part of Status. Only the exceptions have both Metadata and Status
2. io.grpc.Status is in grpc-api, which can't have a dependency on protobuf
3. The construction pattern we have ensures that the io.grpc.Status and the google.rpc.Status have matching status code (very important for security) and description (good to reduce confusion) (this is a property that is weakened by the workaround I presented)

In the lower-level APIs that things are built on (like stubs and interceptors), [Metadata and Status are separate](https://grpc.github.io/grpc-java/javadoc/io/grpc/ClientCall.Listener.html#onClose-io.grpc.Status-io.grpc.Metadata-). And from a gRPC semantics perspective, it doesn't makes sense for Metadata to be part of Status. (If anything, the other way around would be more appropriate.)

The combined Metadata+Status in StatusException is really only visible in the stubs. That was done because originally stubs had _no_ access to Metadata. But for rich error handling you do really need access to Metadata, so the exceptions were enhanced to carry both.

**Comment by SanjayVas** [comment] 2023-06-02 19:56
What I had originally expected is that io.grpc.Status would be a superset of google.rpc.Status. The fact that `Metadata` is used to pass a copy of the google.rpc.Status is only relevant when building a StatusException. io.grpc.Status doesn't really need `Metadata` in order to hold status details.

> io.grpc.Status is in grpc-api, which can't have a dependency on protobuf

This is the real sticking point. There's not really a way to have io.grpc.Status hold onto status details without this, as those are protobuf messages :( .

**Comment by ejona86** [comment] 2023-06-23 21:10
The best option at the moment is the workaround at https://github.com/grpc/grpc-java/issues/10230#issuecomment-1573893085 . With just one user needing it, that's not too bad; wrap it up in a utility in the app and move on. But if someone else stumbles across this and also needs the workaround, please tell us on this issue or a new one that references this one.

We really don't want lots of people to need the workaround, so if we see people are needing it, adding an API to StatusProto can be overall better (in a cost vs benefit way).

I'm closing this this as resolved, as the workaround is sufficient for now, but again, if this is even a lightly-common need we'd need to figure out a better solution.

**Closed by ejona86** 2023-06-23 21:10 UTC
Labels: enhancement

**Comment by andreamontanari-sumup** [comment] 2023-07-04 14:51
As feedback - I can say that we also have the same situation and it is quite annoying to implement the workaround. A proper solution would be quite welcomed
