### ISSUE TITLE
Failed to mark a promise as failure because it has succeeded already

### ISSUE THREAD

**Issue by speakless86** [grpc/grpc-java#3807] opened 2017-11-29 01:49 UTC
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.7

### What did you expect to see?
We saw the following exception occasionally on the client side so that the server didn't receive the RPC:

```
Tuesday, April 4, 2017 6:06:23 AM CST W io.netty.channel.AbstractChannelHandlerContext [warn] Failed to mark a promise as failure because it has succeeded already: DefaultChannelPromise@7cdcdb9b(success)
java.lang.UnsupportedOperationException
        at io.netty.handler.codec.http2.DefaultHttp2Connection$ConnectionStream.resetSent(DefaultHttp2Connection.java:816)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.resetStream(Http2ConnectionHandler.java:716)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.resetStream(Http2ConnectionHandler.java:694)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeRstStream(DefaultHttp2ConnectionEncoder.java:242)
        at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeRstStream(DecoratingHttp2FrameWriter.java:65)
        at io.netty.handler.codec.http2.StreamBufferingEncoder.writeRstStream(StreamBufferingEncoder.java:174)
        at io.grpc.netty.NettyClientHandler.cancelStream(NettyClientHandler.java:460)
        at io.grpc.netty.NettyClientHandler.write(NettyClientHandler.java:234)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:739)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:731)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:817)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:724)
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1022)
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:291)
        at io.grpc.netty.WriteQueue.flush(WriteQueue.java:127)
        at io.grpc.netty.WriteQueue.access$000(WriteQueue.java:47)
        at io.grpc.netty.WriteQueue$1.run(WriteQueue.java:59)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745) 
```

**Comment by carl-mastrangelo** [comment] 2017-11-29 22:26
It looks like cancel is being called before a stream ID is being assigned.  The streamid 0 is being used, which looks up the connection rather than the stream, which cannot be cancelled.

**Comment by carl-mastrangelo** [comment] 2017-12-01 02:44
cc @ejona86 any idea why the stream id would not be assigned?

**Comment by ejona86** [comment] 2017-12-01 20:27
We rely on cancels being ordered after the create. stream.start() enqueues the create; stream.cancel() enqueues the reset. Possibilities:
1) Reordering or the reset was created before the create. This looks like it is [possible](https://github.com/grpc/grpc-java/blob/v1.7.0/core/src/main/java/io/grpc/internal/AbstractClientStream.java#L137) since the addition of GET support. (writeHeaders() triggers the stream creation.)
2) The create itself failed. Any `return` or exception before [`setId()`](https://github.com/grpc/grpc-java/blob/v1.7.0/netty/src/main/java/io/grpc/netty/NettyClientHandler.java#L451) could be the cause.

In either case, the rst should probably be ignored, although with (1) it may need some thread-safety goo (say, deadline is exceeded before the call actually starts; we need to cancel iff writeHeaders() was called).

**Comment by ejona86** [comment] 2018-02-21 16:25
This is a duplicate of #3364

**Closed by ejona86** 2018-02-21 16:25 UTC
Labels: bug
