### ISSUE TITLE
Cyclic Dependency

### ISSUE THREAD

**Issue by mdetemad** [grpc/grpc-java#10682] opened 2023-11-17 03:08 UTC
Hi,

I'm using the following grpc libraries in my jaca code:
    "io.grpc:grpc-core:1.59.0",
    "io.grpc:grpc-inprocess:1.59.0",
    "io.grpc:grpc-stub:1.59.0",
    "io.grpc:grpc-testing:1.59.0",

 and getting the dependency error:
.-> @maven//:io_grpc_grpc_util (xxxxx)
|   @maven//:io_grpc_grpc_core (xxxxx)
`-- @maven//:io_grpc_grpc_util (xxxxx)

Could you please take a look and help me solve it?

**Comment by ejona86** [comment] 2023-11-17 16:01
This is a maven_install bug. See https://github.com/bazelbuild/rules_jvm_external/issues/966 . You can use maven.artifact() with exclusions to remove the grpc-util dependency as a workaround (there's a snippet in that issue and the grpc-java issue it links to).

**Comment by ejona86** [comment] 2023-11-28 16:28
Duplicate of #10576

**Closed by ejona86** 2023-11-28 16:28 UTC
Labels: question
