### ISSUE TITLE
How to instantiate a BlockRpcChannel for Generated Java

### ISSUE THREAD

**Issue by darewreck54** [grpc/grpc-java#6814] opened 2020-03-10 18:55 UTC
Not sure if this is the right place, but I'm having issue with using the generated java code from my proto.

I'm just trying to utilize the generated Java Client.  I looked at the example:

![image](https://user-images.githubusercontent.com/16171726/76348635-c1ef8280-62c5-11ea-9089-19232b79cfe7.png)

And I expected the newBlockingStub to take a Channel (ManagedChannel).  In my case, its' expecting a BlockingRpcChannel.  I can't find any examples of how to create a BlockingRpcChannel

Question:
1) Did I somehow generate the java client incorrectly from the proto
2) If I did generate it correct, how do you create a BlockingRpcChannel?
3) Also what is there a difference between the two interfaces?

More Details are posted here (build.gradle, etc):

https://stackoverflow.com/questions/60615761/how-to-implement-com-google-protobuf-blockingrpcchannel-for-grpc-generated-java/60621833#60621833

**Comment by darewreck54** [comment] 2020-03-10 20:55
Looks like something changed in https://github.com/grpc/grpc-java/releases/tag/v1.26.0 that results in the different code generation. But all the examples and tutorials refer to 1.25 and lower.

Any examples of how you would create the BlockRpcChannel since it no longer takes a ManagedChannel?

**Comment by darewreck54** [comment] 2020-03-10 21:01
Should probably update the documentation/examples on the gPRC to reflect the new interfaces as well.

**Comment by sanjaypujare** [comment] 2020-03-10 22:35
@darewreck54 @creamsoup already updated your Stackoverflow post and it seems the problem is using the option 
```
option java_generic_services = true;
```
in your proto file. This is documented here https://developers.google.com/protocol-buffers/docs/reference/java-generated#service and the option seems deprecated.

Once you confirm we'll close this issue.

**Closed** 2020-03-11 00:24 UTC
Labels: question

**Comment by darewreck54** [comment] 2020-03-11 03:28
@sanjaypujare & @creamsoup Thanks for the help.
