### ISSUE TITLE
Please consider a patch release with https:// endpoints in Bazel rules.

### ISSUE THREAD

**Issue by buchgr** [grpc/grpc-java#6618] opened 2020-01-17 12:04 UTC
On 15th January maven central turned down http:// endpoints. The v1.26 release still uses those endpoints. @ejona86 fixed this on master https://github.com/grpc/grpc-java/commit/a4299eb6bed3c2f2497f583d0c4620c9f31ec455 but the latest release still uses the turned down endpoints. Please consider doing a patch release that contains the before mentioned commit.

Thanks!

**Comment by ejona86** [comment] 2020-01-17 16:59
Duplicate of #6606. Please chime in to say which version of grpc would be helpful.

**Closed by ejona86** 2020-01-17 16:59 UTC
Labels: question
