### ISSUE TITLE
Netty server -> client messages apparently dropped in 0.13.2+

### ISSUE THREAD

**Issue by johnbcoughlin** [grpc/grpc-java#1802] opened 2016-05-06 17:25 UTC
I am observing some strange behavior on grpc 0.13.2 and above, on my Macbook Pro. Diagnostic information at the bottom of this issue.
Essentially what seems to happen is that the call is correctly handled by the server, all the way through `onComplete`, but the client never receives any of the inbound frames. This happens for, say, 5% of calls.
I've attached an example log snippet, including annotations indicating where the various callbacks are invoked, as determined by our logging interceptors.
This doesn't reproduce on 0.13.1, but is consistently reproducible on 0.13.2. Unfortunately I was unable to come up with a minimal reproduction.
Any help is *greatly* appreciated! Thanks!

Client side:
```
*** ClientCall#start() ***

*** ClientCall#halfClose() ***

2016-05-06T16:41:33.658Z DEBUG [grpc-default-worker-ELG-4-2] {} io.grpc.~.NettyClientHandler -
----------------OUTBOUND--------------------
[id: 0x9d2d086a, L:/127.0.0.1:59638 - R:/127.0.0.1:59512] HEADERS: streamId=1113, headers=DefaultHttp2Headers[:authority: 127.0.0.1:59512, :path: /inscriptive.sample.SampleService/Create, :method: POST, :scheme: http, trace_id: HJzC_U3l, grpc-accept-encoding: gzip, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.5], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=false
------------------------------------
2016-05-06T16:41:33.658Z DEBUG [grpc-default-worker-ELG-4-2] {} io.grpc.~.NettyClientHandler -
----------------OUTBOUND--------------------
[id: 0x9d2d086a, L:/127.0.0.1:59638 - R:/127.0.0.1:59512] DATA: streamId=1113, padding=0, endStream=true, length=409, bytes=00000001940a1b74733a616a76766766513370593636476b5f4732676f715052504e12f4020a3b436f6e73756d657220507269636520496e64657820666f7220...
------------------------------------
```

Server side:
```
2016-05-06T16:41:33.658Z DEBUG [grpc-default-worker-ELG-4-2] {} io.grpc.~.NettyServerHandler -
----------------INBOUND--------------------
[id: 0x50d7d3f3, L:/127.0.0.1:59512 - R:/127.0.0.1:59638] HEADERS: streamId=1113, headers=DefaultHttp2Headers[:authority: 127.0.0.1:59512, :path: /inscriptive.sample.SampleService/Create, :method: POST, :scheme: http, trace_id: HJzC_U3l, grpc-accept-encoding: gzip, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.5], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=false
------------------------------------

*** server interception chain invoked ***

2016-05-06T16:41:33.658Z DEBUG [grpc-default-worker-ELG-4-2] {} io.grpc.~.NettyServerHandler -
----------------INBOUND--------------------
[id: 0x50d7d3f3, L:/127.0.0.1:59512 - R:/127.0.0.1:59638] DATA: streamId=1113, padding=0, endStream=true, length=409, bytes=00000001940a1b74733a616a76766766513370593636476b5f4732676f715052504e12f4020a3b436f6e73756d657220507269636520496e64657820666f7220...
------------------------------------

*** ServerCall.Listener#onHalfClose() ***

...

*** ServerCall#close(Status.OK) ***

2016-05-06T16:41:33.676Z DEBUG [grpc-default-worker-ELG-4-2] {} io.grpc.~.NettyServerHandler -
----------------OUTBOUND--------------------
[id: 0x50d7d3f3, L:/127.0.0.1:59512 - R:/127.0.0.1:59638] HEADERS: streamId=1113, headers=DefaultHttp2Headers[:status: 200, grpc-encoding: gzip, grpc-accept-encoding: gzip, content-type: application/grpc], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=false
------------------------------------
2016-05-06T16:41:33.676Z DEBUG [grpc-default-worker-ELG-4-2] {} io.grpc.~.NettyServerHandler -
----------------OUTBOUND--------------------
[id: 0x50d7d3f3, L:/127.0.0.1:59512 - R:/127.0.0.1:59638] DATA: streamId=1113, padding=0, endStream=false, length=5, bytes=0000000000
------------------------------------
2016-05-06T16:41:33.676Z DEBUG [grpc-default-worker-ELG-4-2] {} io.grpc.~.NettyServerHandler -
----------------OUTBOUND--------------------
[id: 0x50d7d3f3, L:/127.0.0.1:59512 - R:/127.0.0.1:59638] HEADERS: streamId=1113, headers=DefaultHttp2Headers[grpc-status: 0], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=true
------------------------------------

*** ServerCall.Listener#onComplete() ***
```

```
$ java -version
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)
```

```
[jack:/Users/jack/src/inscriptive] (jack-grpc-14) >> uname -a
Darwin Jacks-MacBook-Pro.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
```

**Comment by ejona86** [comment] 2016-05-06 17:30
@johnbcoughlin, are any of the _other_ calls on the Channel doing cancellation (including deadline)? If so, you may be hitting #1682 which will be fixed with the next Netty release. It's taken a little longer than we initially expected to get the fix out. We should maybe send out an email to the mailing list.

**Comment by ejona86** [comment] 2016-05-06 17:31
Note that for 0.13.2 we updated Netty for bug fixes. This could have been introduced then.

**Comment by buchgr** [comment] 2016-05-06 17:35
the fix for #1682 is already in latest netty master. @johnbcoughlin you could try building grpc with the latest netty master and see if that resolves the issue.

**Comment by johnbcoughlin** [comment] 2016-05-06 17:36
No, nowhere are we cancelling or timing out any calls on the Channel. The issue described in https://github.com/netty/netty/issues/5186 as linked from #1682 seems to involve the client rejecting confusing headers from the server. In this case the client never receives anything from the server. The logs I posted came after a sequence of perfectly good calls with no confusion or interleaving.

**Comment by johnbcoughlin** [comment] 2016-05-06 17:37
@buchgr I'll give that a shot!

**Comment by buchgr** [comment] 2016-05-06 17:40
@johnbcoughlin you are probably not hitting #1682 then. might still be useful to try it with 0.14.0 as well as the latest Netty, just to be sure, the issue is still there.

**Comment by johnbcoughlin** [comment] 2016-05-06 17:41
Yup, it's definitely there in 0.14.0. I'll try with the latest Netty.

**Comment by buchgr** [comment] 2016-05-06 17:41
@johnbcoughlin thanks! your help is greatly appreciated!

**Comment by ejona86** [comment] 2016-05-06 17:45
I've confirmed the bug I was referencing is not present in Netty 4.1.0.CR1 and was introduced in CR2. We swapped from CR1 to CR3 between 0.13.1 and 0.13.2.

**Comment by johnbcoughlin** [comment] 2016-05-06 21:12
Kay, it looks like with latest netty, `netty-all-4.1.0.Final-20160506.120802-47`, the issue doesn't appear. I'm not convinced I was hitting #1682, but it could easily have been the same underlying netty issue.

**Comment by ejona86** [comment] 2016-05-06 22:35
@johnbcoughlin, thanks a lot!

Maybe there is another way to trigger the issue. All it really takes is a piece of the code throwing `Http2Exception.StreamException`, so maybe there is another location that could trigger it. Or maybe you were hitting something completely different which just happened to be fixed around the same time.

I'll go ahead and close this since it seems #1682 will address whatever issue was hit here as well.

**Closed by ejona86** 2016-05-06 22:35 UTC
