### ISSUE TITLE
Android app getting stuck in DEADLINE_EXCEEDED errors

### ISSUE THREAD

**Issue by ArturoSalazarB16** [grpc/grpc-java#9859] opened 2023-01-26 21:42 UTC
Hey there!

We have an android app which calls a GRPC service. We're currently integrated with ManagedChannelBuilder but looking to switch to AndroidChannelBuilder.

Our app polls the server on an interval and in case it hits a RPC error, then it backs off.

We have reports of a bug where user consistently hits DEADLINE_EXCEEDED errors although their phones/app have connectivity.

From our logs, we've observed that they might initially run into:

1. Hit "UNAVAILABLE: Unable to resolve host ******" a couple of times
2. Start hitting "DEADLINE_EXCEEDED: deadline exceeded after x.xxS [closed=[], open=[[buffered_nanos=10995564540, waiting_for_connection]]]"" indefinitely 

Looking at https://github.com/grpc/grpc-java/issues/9072, it seems similar except that their logs don't show "waiting_for_connection".

Do you have any pointers as to what the issue is? could it be resolved too with "keepalive"?

**Comment by sanjaypujare** [comment] 2023-01-26 22:02
Can you post stacktraces similar to the ones in https://github.com/grpc/grpc-java/issues/9072 ? Also what version of gRPC?

Although the "waiting_for_connection" part is different, I have a feeling it might be worth trying "keepalive" to address the issue

**Comment by ArturoSalazarB16** [comment] 2023-01-27 20:49
I think I got a repro locally. The app doens't necessarily have to hit a "UNAVAILABLE" to get into this state.

Repro steps:
1. Start app
2. Start RPC polling to server
3. Disable network connectivity for a few seconds and then restablish.

However, I don't see a 100% reproduction rate. It takes 3-5 times to hit the issue.

One observation. When I disable network and the RPC channel status is "TRANSIENT_FAILURE", I don't see the issue reproducing. It's only when the network is disabled and the RPC channel status is still in "READY" state.

**Comment by sanjaypujare** [comment] 2023-01-27 21:18
> ...
>  It's only when the network is disabled and the RPC channel status is still in "READY" state.

That's where the keepalive would help as per https://github.com/grpc/grpc-java/issues/9072#issuecomment-1098495269

**Comment by ArturoSalazarB16** [comment] 2023-01-27 23:21
Thanks! I was able to confirm that the "keepAlive" does fix this particular case after.

This is what I'm seeing when it kicks in: "UNAVAILABLE: Keepalive failed. The connection is likely gone" And then right after connection is reestablished.

One thing I was trying to understand a bit better is, is this a bug in the GRPC connection layer that we workaround with the "keepAlive" ping? or are things working as expecting and clients should rely on "keepAlive"?

**Comment by sanjaypujare** [comment] 2023-01-27 23:26
> ...is this a bug in the GRPC connection layer that we workaround with the "keepAlive" ping? or are things working as expecting and clients should rely on "keepAlive"?

The following text from the referenced comment tells me this is not a bug but a basic limitation in TCP:

"to detect broken TCP connections you have to do a write. Starting an RPC is a write most of the time, but if hit a rarer case or if the connection breaks after the RPC is started, then the client will be waiting for a response that will never arrive. The keepalive then can kick in and detect the broken connection"

Assuming you agree we can close this issue?

**Comment by ejona86** [comment] 2023-02-02 23:04
b/254250550

Seems like this is resolved. If not, comment, and it can be reopened.

**Closed by ejona86** 2023-02-02 23:04 UTC
Labels: question
