### ISSUE TITLE
Client certificate not sent

### ISSUE THREAD

**Issue by ChaosData** [grpc/grpc-java#2320] opened 2016-10-02 01:44 UTC
Hi,

I'm trying to use gRPC from Java (as a client) to communicate with a gRPC Node.js server.
I am trying to get TLS mutual auth between the two, but I can't seem to get the Java client to send its client cert. I've verified via packet capture that the Node server is requesting a client cert.

``` java
ManagedChannelBuilder<?> mcb = NettyChannelBuilder.forAddress("127.0.0.1", 50051)
  .sslContext(GrpcSslContexts.forClient()
    .keyManager(client_leaf.key, client_ca.cert, client_leaf.cert)
    .trustManager(server_ca.cert)
    .build()
  )
  .negotiationType(NegotiationType.TLS);

mcb.overrideAuthority("localhost");
```

I am dynamically generating CA certs and leaf certs under them to bind the communication.
Due to this, I'm using the `keyManager(PrivateKey,X509Certificate...)` overload, and the private key is generated from a `KeyPairGenerator.getInstance("RSA")` object. I'm currently generating two chains (one for the server's cert, and one for the client cert) and verification of the server cert works fine (connections work when I disable the client cert requirement on the Node server).

My relevant dependencies are below:

``` groovy
compile group: 'io.grpc', name: 'grpc-netty', version: '1.0.1'
compile group: 'io.grpc', name: 'grpc-protobuf', version: '1.0.1'
compile group: 'io.grpc', name: 'grpc-stub', version: '1.0.1'
compile group: 'io.netty', name: 'netty-tcnative-boringssl-static', version: '+'//'1.1.33.Fork19'
```

The `+` currently resolves to `1.1.33.Fork23`. I've found that the `1.1.33.Fork19` version specified in the documentation results in an exception on Linux (and OS X) caused by:

```
Caused by: javax.net.ssl.SSLHandshakeException: error:00000000:invalid library (0):OPENSSL_internal:invalid library (0)
```

As per CONTRIBUTING.md, my setup is as follows:

```
$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~14.04-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
$ uname -a
Linux ubuntu 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Any ideas on what might be causing this behavior or what I'm doing wrong?

**Comment by ejona86** [comment] 2016-10-03 16:59
@jboeuf, is there a way to enable TLS-level logging to diagnose client certs for C core w/ Node.js? I'm surprised, I just realized I know know an equivalent to -Djavax.net.debug=ssl when using tcnative in Java.

I don't have much time to look at this right now (and will be on vacation for a week), but we do have a [test for client-certs](https://github.com/grpc/grpc-java/blob/v1.0.1/interop-testing/src/test/java/io/grpc/testing/integration/TlsTest.java#L125). Granted, it is using the `keyManager(File, File)` overload, but the implementation [ends up calling the `keyManager(PrivateKey,X509Certificate...)` overload](https://github.com/netty/netty/blob/netty-4.1.5.Final/handler/src/main/java/io/netty/handler/ssl/SslContextBuilder.java#L240).

Note that although `basicClientServerIntegrationTest()` doesn't get the client cert on the server-side, `serverRejectsUntrustedClientCert()` does detect whether client cert validation logic was performed on the server-side, so the two combined do really require the client cert to be working. Understanding all the configuration of those tests isn't necessary to see how they work; the setup only differs in the cert the client uses.

The `SSLHandshakeException` is interesting. I've not seen that error. Bumping tcnative version sounds fine. It'd be nice to reproduce that, but I don't have any theories on why you hit it and we don't. Hmm...

When the connection fails, you apparently don't get any useful error on either Java or Node.js? ("useful" being something better than "ssl handshake failed" or "connection closed")

**Comment by ChaosData** [comment] 2016-10-03 23:50
I don't think these are particularly useful (since they pretty much match up w/ the client cert not sent [for unknown reasons] theme where the server rejects the connection and logs lack of client cert, and the client spews out error about failed connection), but if it helps at all, I get the following.

On the Node side (server):
```
E1003 19:44:19.207347166    3389 ssl_transport_security.c:945] Handshake failed with fatal error SSL_ERROR_SSL: error:140890C7:SSL routines:ssl3_get_client_certificate:peer did not return a certificate.
E1003 19:44:19.207499961    3389 handshake.c:128]            Security handshake failed: {"created":"@1475538259.207480122","description":"Handshake failed","file":"../src/core/lib/security/transport/handshake.c","file_line":264,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
E1003 19:44:19.207535434    3389 server_secure_chttp2.c:119] Secure transport failed with error 1
```

On the Java side (client):
```
io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.Status.asRuntimeException(Status.java:545)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:481)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:398)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:513)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.handler.codec.DecoderException: java.lang.AbstractMethodError
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	... 1 more
Caused by: java.lang.AbstractMethodError
	at org.apache.tomcat.jni.SSL.readFromSSL(Native Method)
	at io.netty.handler.ssl.OpenSslEngine.readPlaintextData(OpenSslEngine.java:381)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:748)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:855)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1088)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:966)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:900)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 16 more
```

**Comment by jboeuf** [comment] 2016-10-07 04:26
@ChaosData Just to make sure that you're not blocking on me. It looks indeed that the client cert is never sent from the java side. Am I reading this correctly?

**Comment by ChaosData** [comment] 2016-10-07 17:15
Yep. I'm not sure if I'm doing something wrong, or if something else is at play that results in the Java side failing to send it.

**Comment by ejona86** [comment] 2016-10-07 18:04
`AbstractMethodError` looks wrong. You shouldn't be seeing that. I think it's probably due to using tcnative  Fork23. Could you try with Fork20 instead?

**Comment by ChaosData** [comment] 2016-10-07 21:56
With Fork20 (of boringssl-static), I keep getting the `Caused by: javax.net.ssl.SSLHandshakeException: error:00000000:invalid library (0):OPENSSL_internal:invalid library (0)` error. I've just tried this on a more-or-less fresh Ubuntu 16.04 VM and get the same thing.

With dynamic link tcnative of both Fork20 and Fork23, I currently get:
```
io.grpc.StatusRuntimeException: INTERNAL: Connection closed with unknown cause
	at io.grpc.Status.asRuntimeException(Status.java:545)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:481)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:398)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:513)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Oct 07, 2016 5:47:31 PM io.grpc.internal.ManagedChannelImpl maybeTerminateChannel
INFO: [ManagedChannelImpl@3234e239] Terminated
```
Though I had to switch the leaf and ca cert oder in `keyManager`, as before it was giving me `X509_check_private_key:key values mismatch`. However, even after making that change, I still get `java.lang.AbstractMethodError` when using boringssl-static.

I'll try to test this with both the dynamic and `openssl` created certs using both the `File`-based overload and the one I'm using.

**Comment by vyshane** [comment] 2016-10-13 13:17
I was seeing the same `AbstractMethodError` with netty-tcnative-boringssl-static 1.1.33.Fork23 on OS X. Fork19 is what worked for me on my setup. Here's the [configuration that ended up working for me](https://github.com/vyshane/grpc-scala-microservice-kit/blob/master/app/build.sbt).

**Comment by ejona86** [comment] 2016-10-14 17:08
There are some client-cert fixes [in Netty 4.1.6](http://netty.io/news/2016/10/14/4-0-42-Final-4-1-6-Final.html). We may want to try bumping the Netty version (along with latest tcnative) and see if it resolves the strangeness. I know of issues with Netty 4.1.5; we'll be testing out Netty 4.1.6 soon.

**Comment by ejona86** [comment] 2016-11-07 19:33
@ChaosData, I just uploaded a new `1.1.0-SNAPSHOT` version of gRPC that is using Netty 4.1.5. Could you try it out? You'll need to use tcnative version `1.1.33.Fork23` (newer versions may work, but gRPC is using Fork23 during its own testing).

**Comment by ChaosData** [comment] 2016-11-08 10:14
With a `1.1.0-SNAPSHOT` built from `809cf1bc8c39967343be13116e6e4b22089b68ad` (...which seems to use Netty 4.1.6. Can you link me to the jar you uploaded or the commit it was built from?) and tcnative `1.1.33.Fork23`, I get the following error on the client:

```
io.grpc.StatusRuntimeException: UNAVAILABLE
	at io.grpc.Status.asRuntimeException(Status.java:541)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:410)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:496)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:413)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:528)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$OpenSslCertificateRequestedCallback.requested(ReferenceCountedOpenSslClientContext.java:254)
	at org.apache.tomcat.jni.SSL.readFromSSL(Native Method)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:457)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:824)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:931)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1091)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:968)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	... 1 more
Caused by: java.lang.NullPointerException
	at sun.security.ssl.SunX509KeyManagerImpl.getAliases(SunX509KeyManagerImpl.java:359)
	at sun.security.ssl.SunX509KeyManagerImpl.getClientAliases(SunX509KeyManagerImpl.java:308)
	at sun.security.ssl.SunX509KeyManagerImpl.chooseClientAlias(SunX509KeyManagerImpl.java:218)
	at sun.security.ssl.SunX509KeyManagerImpl.chooseEngineClientAlias(SunX509KeyManagerImpl.java:241)
	at io.netty.handler.ssl.OpenSslExtendedKeyMaterialManager.chooseClientAlias(OpenSslExtendedKeyMaterialManager.java:33)
	at io.netty.handler.ssl.OpenSslKeyMaterialManager.keyMaterial(OpenSslKeyMaterialManager.java:90)
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$OpenSslCertificateRequestedCallback.requested(ReferenceCountedOpenSslClientContext.java:251)
	... 24 more
```

**Comment by ejona86** [comment] 2016-11-09 18:09
@ChaosData, you're right. It is Netty 4.1.6, not 4.1.5.

What JDK version are you using? It looks like I get to read JDK code to figure out what is causing the NPE.

**Comment by ChaosData** [comment] 2016-11-11 03:24
I was running a slightly older version of OpenJDK 8, but can confirm that I get the same behavior on:
```
$ java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-3~14.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
```
so it might be best to look at that.

Relevant stack trace for (potentially modified) line numbers:
```
io.grpc.StatusRuntimeException: UNAVAILABLE
	at io.grpc.Status.asRuntimeException(Status.java:541)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:410)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:496)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:413)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:528)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$OpenSslCertificateRequestedCallback.requested(ReferenceCountedOpenSslClientContext.java:254)
	at org.apache.tomcat.jni.SSL.readFromSSL(Native Method)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:457)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:824)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:931)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1091)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:968)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	... 1 more
Caused by: java.lang.NullPointerException
	at sun.security.ssl.SunX509KeyManagerImpl.getAliases(SunX509KeyManagerImpl.java:359)
	at sun.security.ssl.SunX509KeyManagerImpl.getClientAliases(SunX509KeyManagerImpl.java:308)
	at sun.security.ssl.SunX509KeyManagerImpl.chooseClientAlias(SunX509KeyManagerImpl.java:218)
	at sun.security.ssl.SunX509KeyManagerImpl.chooseEngineClientAlias(SunX509KeyManagerImpl.java:241)
	at io.netty.handler.ssl.OpenSslExtendedKeyMaterialManager.chooseClientAlias(OpenSslExtendedKeyMaterialManager.java:33)
	at io.netty.handler.ssl.OpenSslKeyMaterialManager.keyMaterial(OpenSslKeyMaterialManager.java:90)
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$OpenSslCertificateRequestedCallback.requested(ReferenceCountedOpenSslClientContext.java:251)
	... 24 more
```

**Comment by blakesmith** [comment] 2016-11-21 01:01
Having the same issue on OS X 10.10. I ended up booting an Ubuntu Xenial Linux VM, and everything started working.

```
grpc-{netty,stub,protobuf}: 1.0.1
netty-tcnative-boringssl-static: 1.1.33.Fork23
netty: 4.1.6.Final
jdk: Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
```

```
Caused by: io.netty.handler.codec.DecoderException: java.lang.AbstractMethodError
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) ~[onegateway-master.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[onegateway-master.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) ~[onegateway-master.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) ~[onegateway-master.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) ~[onegateway-master.jar:na]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[onegateway-master.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) ~[onegateway-master.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) ~[onegateway-master.jar:na]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[onegateway-master.jar:na]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) ~[onegateway-master.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571) ~[onegateway-master.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512) ~[onegateway-master.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426) ~[onegateway-master.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398) ~[onegateway-master.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877) ~[onegateway-master.jar:na]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) ~[onegateway-master.jar:na]
        ... 1 common frames omitted
Caused by: java.lang.AbstractMethodError: null
        at org.apache.tomcat.jni.SSL.readFromSSL(Native Method) ~[onegateway-master.jar:na]
        at io.netty.handler.ssl.OpenSslEngine.readPlaintextData(OpenSslEngine.java:381) ~[onegateway-master.jar:na]
        at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:748) ~[onegateway-master.jar:na]
        at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:855) ~[onegateway-master.jar:na]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1088) ~[onegateway-master.jar:na]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:966) ~[onegateway-master.jar:na]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:900) ~[onegateway-master.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[onegateway-master.jar:na]
        ... 16 common frames omitted
Nov 20, 2016 6:51:29 PM io.grpc.internal.SerializingExecutor$TaskRunner run
```

**Comment by blakesmith** [comment] 2016-11-23 23:01
I stand corrected. I had the exact same stacktrace with openjdk 8 on Xenial, as well as OS X. I had to upgrade to openjdk-9-jre, and the issue went away.

**Comment by ejona86** [comment] 2017-11-08 16:29
Seems upgrading the jdk fixes this, and we've not seen any other reports. So closing; it can be reopened if more people end up experiencing this so that they can help narrow down the problem.

**Closed by ejona86** 2017-11-08 16:29 UTC
