### ISSUE TITLE
Variable 'features' might not have been initialized

### ISSUE THREAD

**Issue by chenbin1314** [grpc/grpc-java#4320] opened 2018-04-09 02:17 UTC
https://github.com/grpc/grpc-java/blob/d68b2cd74a6af1b0487d67e82a4ce0a443b2cf95/examples/src/main/java/io/grpc/examples/routeguide/RouteGuideServer.java#L113

**Comment by zpencer** [comment] 2018-04-09 20:38
Whatever is causing this is probably the same root cause as https://github.com/grpc/grpc-java/issues/4320, closing this as a dup.

**Closed by zpencer** 2018-04-09 20:38 UTC
