### ISSUE TITLE
I see a lot grpc related warnings in catalina log

### ISSUE THREAD

**Issue by ghost** [grpc/grpc-java#6692] opened 2020-02-09 20:47 UTC
What version of gRPC-Java are you using?
I don't know what grpc is for and why do I have it. I do use Firebase so maybe it comes from there. I see the following under maven dependencies:

> grpc-stub-1.23.0.jar
> grpc-context-1.19.0.jar
> grpc-api-1.23.0.jar
> grpc-auth-1.23.0.jar
> grpc-protobuf-1.23.0.jar
> grpc-protobuf-lite-1.23.0.jar
> grpc-netty-shaded-1.23.0.jar
> grpc-core-1.23.0.jar
> grpc-alts-1.23.0.jar
> grpc-grpclb-1.23.0.jar
> 

I see there is version 1.27.0 but because I didn't put grpc dependancies in the first place, I don't know how to update and whether it will be a good idea to do so without breaking things.

### What is your environment?
ubuntu 18.04, openjdk11, tomcat 9.0.30

### What did you expect to see?
nothing - clean log

### What did you see instead?
a lot of the following:
`WARNING [https-jsse-nio2-8443-exec-10] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [app] appears to have started a thread named XXX but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
`

Instead of XXX  I see the following in the same order I wrote here:
> Gax-1
> grpc-default-worker-ELG-1-1
> grpc-default-worker-ELG-1-2
> grpc-default-worker-ELG-1-3
> Gax-2
> Gax-3
> Gax-4
> grpc-default-worker-ELG-1-4
> grpc-shared-destroyer-0
> 

I see the above around 2 hours after tomcat server was up and running, then I saw the following 10 times:

`SEVERE [https-jsse-nio2-8443-exec-10] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [app] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@77360cd3]) and a value of type [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap] (value [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@6f166770]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
`

and then tomcat undeployed and redeployed my war. A minute after redeployment I saw this

`WARNING [grpc-default-executor-0] io.grpc.netty.shaded.io.netty.util.internal.MacAddressUtil.defaultMachineId Failed to find a usable hardware address from the network interfaces; using random bytes: 8e:4f:93:7d:6c:b4:f3:cb `

18 minutes after that I see

```
INFO [grpc-default-worker-ELG-1-2] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [android.app.Application]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [android.app.Application]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
``` 

40 minutes afterwards again the same behavior as before... until redeployment again, then I saw this again

`java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [io.grpc.internal.SharedResourceHolder$2]. The following stack trace is thrown`

and this

```
INFO [grpc-default-worker-ELG-1-4] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already... with this
java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [io.grpc.internal.ManagedChannelImpl$SubchannelImpl$3]. The following stack ....
``` 

and it's been quiet since...

Steps to reproduce the bug: I have no idea. Even though it's been quiet since, I hope someone can shed a light here about what's was going on... Thanks

**Comment by ejona86** [comment] 2020-02-11 00:11
> I see the above around 2 hours after tomcat server was up and running

All of those look like your application is being unloaded. Maybe you upgraded to a newer version? I'd reload your application to see if it reproduces. If not, then I'd reload the application _while a request is in progress_ that uses grpc. (The unload won't happen while the request is in progress, and that's okay.)

> thread named XXX but has failed to stop it

This could be two reasons:
 1. You aren't shutting down all the ManagedChannels
 2. The thread will be stopping momentarily

To test if it is (2), you can just add a sleep for 1 second in the servlet teardown function. We leave those threads around for 1 second in case the user starts using them again. I'm not saying a 1 second sleep would be a _fix_ for your application, but at least it would tell us which case it is.

> The web application [app] created a ThreadLocal with key of type

This is https://github.com/netty/netty/issues/6891#issuecomment-457809308

> io.grpc.netty.shaded.io.netty.util.internal.MacAddressUtil.defaultMachineId Failed to find a usable hardware address from the network interfaces; using random bytes

This is weird. Maybe there is a SecurityManager preventing access. I'd sort of expect there to be errors before this, like "Failed to retrieve the list of available network interfaces," which would include a bit more information (and an exception).

> Illegal access: this web application instance has been stopped already. Could not load [android.app.Application].

Please include the stack trace. You can trim your application from it, but I need to see the netty and grpc pieces.

Honestly, the collection of these make me think there is a ClassLoader bug somewhere. But it'll take more to say.

**Comment by Amosss** [comment] 2020-02-11 18:21
First of all, you were right that it happens when shutting down tomcat (I shut it down for an upgrade). Question remains on why all those logs appear while shutting down. Hopefully the below will show the way.

> You aren't shutting down all the ManagedChannels

I have no idea what do you mean by shutting down all the ManagedChannels and what did I not do to make it happen. I think grpc is there because I use Firebase so shouldn't Firebase do this?

> servlet teardown function

I have `contextInitialized` function in the servlet, by teardown, you mean `contextDestroyed`?

> This is netty/netty#6891 (comment)

Sorry for my noob question: shouldn't it be done by whatever is using grpc?

> This is weird. Maybe there is a SecurityManager preventing access. I'd sort of expect there to be errors before this

Well, the only "error" I saw before the error "io.grpc.netty.shaded.io.netty.util.internal.MacAddressUtil.defaultMachineId Failed to find a usable hardware" was

> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation

Following is a complete log with exception's stacktrace 

> INFO [grpc-default-worker-ELG-1-4] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [io.grpc.internal.ManagedChannelImpl$SubchannelImpl$3]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.

> java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [io.grpc.internal.ManagedChannelImpl$SubchannelImpl$3]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
>                 at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1385)
>                 at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1373)
>                 at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1226)
>                 at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
>                 at io.grpc.internal.ManagedChannelImpl$SubchannelImpl.shutdown(ManagedChannelImpl.java:1533)
>                 at io.grpc.internal.PickFirstLoadBalancer.shutdown(PickFirstLoadBalancer.java:113)
>                 at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.shutdown(AutoConfiguredLoadBalancerFactory.java:181)
>                 at io.grpc.internal.ManagedChannelImpl.shutdownNameResolverAndLoadBalancer(ManagedChannelImpl.java:348)
>                 at io.grpc.internal.ManagedChannelImpl.panic(ManagedChannelImpl.java:777)
>                 at io.grpc.internal.ManagedChannelImpl$1.uncaughtException(ManagedChannelImpl.java:157)
>                 at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:97)
>                 at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
>                 at io.grpc.internal.Rescheduler$FutureRunnable.run(Rescheduler.java:80)
>                 at io.grpc.netty.shaded.io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
>                 at io.grpc.netty.shaded.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
>                 at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
>                 at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
>                 at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:331)
>                 at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
>                 at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
>                 at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>                 at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ejona86** [comment] 2020-02-11 18:48
Okay. The leftover Threads is mostly understood what is going wrong. Still a bit unclear what changes should be made, but this seems the main thing to fix.

> I think grpc is there because I use Firebase so shouldn't Firebase do this?

Sorry, I didn't realize you aren't using grpc directly. Yes, Firebase should do this, although you may need to call a method in Firebase to get it to clean itself up. I'm not familiar with the Firebase API.

> I have contextInitialized function in the servlet, by teardown, you mean contextDestroyed?

contextDestroyed sounds like the right method. I didn't remember the name off the top of my head.

> Sorry for my noob question: shouldn't it be done by whatever is using grpc?

This case is pretty ugly and can't really be done automatically by anybody. It is a fundamental problem with ClassLoaders and Thread pools (as implemented by Tomcat) and ThreadLocals. Basically after that "clear the thread locals" call the library is broken and can't be used at all any more. That isn't a normal lifecycle event for libraries.

Tomcat could avoid this problem with ThreadLocals by replacing threads in its thread pool when it shuts down a container. Which is what it does after it spews those warnings: "Threads are going to be renewed over time to try and avoid a probable memory leak." Replacing the threads costs performance, so that's why Tomcat wants to avoid this. But it also is an unreasonable expectation for an app.

> Illegal access: this web application instance has been stopped already. Could not load [io.grpc.internal.ManagedChannelImpl$SubchannelImpl$3].

Thanks for this log. Good news and bad news. Good news: it seems things were cleaned up mostly correctly by Firebase. Bad news: _Tomcat_ prevented us from cleaning up those threads.

But it's not entirely Tomcat's fault. It appears that Firebase _started_ shutdown, but didn't wait for it to complete (which avoids blocking the thread). So grpc was trying to shut down after the servlet was terminated.

I tried to find a Firebase example and saw a Firestore example. It doesn't seem there is any lifecycle for the object, so I'm not entire sure how this all works. Which is the top-level Firebase class you are using (or what part of Firebase are you using)?

**Comment by ejona86** [comment] 2020-02-11 18:56
Okay... it seems "Admin SDK" in https://firebase.google.com/docs/reference is the thing I need to look at.

@Amosss, do you call `FirebaseApp.delete()` anywhere? If you don't create your own FirebaseApp, it seems like you may want to call `FirebaseApp.getInstance().delete()` from within `contextDestroyed`. But something still doesn't add up. It is unclear to me how firebase was shut down in your existing servlet.

**Comment by Amosss** [comment] 2020-02-11 19:32
I use Admin SDK for Firestore. 

I don't see `.delete()` for the object, but I do see `.close()` and I will use it in `contextDestroyed`, hopefully this event is not too late.

To check this, I won't need just to restart with the new WAR but also shut it down, because it happens only on the production server, I will do it later this week and check if it helped.

Thanks a lot for the tip.

**Comment by ejona86** [comment] 2020-02-11 20:29
Note: even with `close()` I would expect you to see some of the same warnings. But I'd hope the "Illegal access" warnings are gone, since they are preventing grpc from cleaning up after itself (even if that cleanup happens a second after Tomcat checks for it to happen).

**Comment by Amosss** [comment] 2020-02-11 22:25
Do you recommend on other things that I should do in contextDestroyed? You mentioned something about sleeping for a second or maybe something else?

Thanks

ps: I did get those problems in my testing environment but then I tried to reproduce it and it didn't happen.... weird....

**Comment by Amosss** [comment] 2020-02-13 06:45
I did the following
```
    @Override
    public void contextDestroyed(ServletContextEvent sce) {
    	if (APIs.db != null)
			try {
				APIs.db.close();
				if (APIs.firebaseApp != null)					
					APIs.firebaseApp.delete();
				TimeUnit.SECONDS.sleep(1);
			} catch (Exception e) {}    	
    }

```

but still it had the same errors when shutting down...
I also remind you this

> WARNING [grpc-default-executor-0] io.grpc.netty.shaded.io.netty.util.internal.MacAddressUtil.defaultMachineId Failed to find a usable hardware address from the network interfaces; using random bytes: 8e:4f:93:7d:6c:b4:f3:cb 

When tomcat starts up
Thanks

**Comment by trajano** [comment] 2021-02-15 07:26
Here's a servlet I created and it still gives the following warning.

```
DEBUG GRPC server ServerImpl{logId=6, transportServers=[NettyServer{logId=5, address=0.0.0.0/0.0.0.0:6565}]} started
DEBUG grpc ServerImpl{logId=6, transportServers=[NettyServer{logId=5, address=0.0.0.0/0.0.0.0:6565}]} shutting down
DEBUG grpc ServerImpl{logId=6, transportServers=[NettyServer{logId=5, address=0.0.0.0/0.0.0.0:6565}]} terminated true
WARNING: The web application [ROOT] appears to have started a thread named [grpc-shared-destroyer-0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
 java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
 java.base@11.0.9.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1170)
 java.base@11.0.9.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
 java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
 java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
 java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)
```

```java
@WebServlet(loadOnStartup = 1)
@Slf4j
public class GrpcServerContext extends HttpServlet {

    private Server server;

    @Override
    public void destroy() {

        try {
            log.debug("grpc {} shutting down", server);
            server.shutdown();
            server.awaitTermination(5, TimeUnit.SECONDS);
            log.debug("grpc {} terminated {}", server, server.isTerminated());

        } catch (InterruptedException e) {
            log.warn("shutdown interrupted, ignoring");
            Thread.currentThread().interrupt();
        }

    }

    @Override
    public void init() throws ServletException {

        log.info("GrpcServer starting");

        final WebApplicationContext applicationContext = WebApplicationContextUtils.getRequiredWebApplicationContext(getServletContext());

        final int grpcPort = applicationContext.getEnvironment().getProperty("grpc.port", Integer.class, 6565);
        final int messageLimitInBytes = applicationContext.getEnvironment().getProperty("grpc.messageLimitInBytes", Integer.class, 20000000);
        final Tracing tracing = applicationContext.getBean(Tracing.class);

        /// ...
        server = serverBuilder.build();
        try {
            server.start();
        } catch (IOException e) {
            throw new ServletException(e);
        }
        log.debug("GRPC server {} started", server);
    }

}

```

**Comment by trajano** [comment] 2021-02-15 14:26
So I changed the `destroy` method as follows to dump what's inside the SharedResourceHolder immediately and two seconds after.

```
    @Override
    @SneakyThrows
    public void destroy() {

        try {
            log.debug("grpc {} shutting down", server);
            server.shutdown();
            server.awaitTermination(5, TimeUnit.SECONDS);
            log.debug("grpc {} terminated {}", server, server.isTerminated());

            final Class<?> aClass = Class.forName("io.grpc.internal.SharedResourceHolder");
            final Field instances = aClass.getDeclaredField("instances");
            instances.setAccessible(true);
            final Field holder = aClass.getDeclaredField("holder");
            holder.setAccessible(true);
            final Object o = holder.get(null);
            final Object o1 = instances.get(o);
            System.out.println(o1);
            Thread.sleep(2000);
            System.out.println(o1);


        } catch (InterruptedException e) {
            log.warn("shutdown interrupted, ignoring");
            Thread.currentThread().interrupt();
        }

    }
```

This is what I got for the System.outs formatted for legibility

```
{
    grpc-default-executor=io.grpc.internal.SharedResourceHolder$Instance@75f384c7, 
    grpc-default-boss-ELG=io.grpc.internal.SharedResourceHolder$Instance@234e4dd6, 
    grpc-default-worker-ELG=io.grpc.internal.SharedResourceHolder$Instance@21c73f6}

{
    grpc-default-executor=io.grpc.internal.SharedResourceHolder$Instance@75f384c7, 
    grpc-default-worker-ELG=io.grpc.internal.SharedResourceHolder$Instance@21c73f6
}
```

Seems like the `boss` disappears which I guess is the server.  But two other resources the default-worker and default executor remain.

**Comment by trajano** [comment] 2021-02-15 14:39
I tried to specify my own Executor using `.executor` and it still has those entries.

**Comment by trajano** [comment] 2021-02-15 15:54
OK I was able to clean it off by calling the internal API.  I put it in `destroy()` and created a method that just performs the necessary API calls.
```
    @SneakyThrows
    @SuppressWarnings("java:S3011")
    private void cleanGrpcSharedResources() throws InterruptedException {

        final Field instances = SharedResourceHolder.class.getDeclaredField("instances");
        instances.setAccessible(true);

        final Field holder = SharedResourceHolder.class.getDeclaredField("holder");
        holder.setAccessible(true);

        final Map<?, ?> o1 = (Map<?, ?>) instances.get(holder.get(null));
        while (!o1.isEmpty()) {
            Thread.sleep(2000);
            for (final Object entry : o1.keySet()) {
                @SuppressWarnings("unchecked") final SharedResourceHolder.Resource<Object> resource = (SharedResourceHolder.Resource<Object>) entry;
                final Object instance = SharedResourceHolder.get(resource);
                log.debug("releasing left-over GRPC resource {} {}", entry, instance);
                SharedResourceHolder.release(resource, instance);
            }
        }

    }

    @Override
    public void destroy() {

        try {
            log.debug("grpc {} shutting down", server);
            server.shutdown();
            server.awaitTermination(5, TimeUnit.SECONDS);
            log.debug("grpc {} terminated {}", server, server.isTerminated());
            threadPool.shutdown();
            threadPool.awaitTermination(5, TimeUnit.SECONDS);
            log.debug("{} terminated {}", threadPool, threadPool.isTerminated());
            cleanGrpcSharedResources();
        } catch (InterruptedException e) {
            log.warn("shutdown interrupted, ignoring");
            Thread.currentThread().interrupt();
        }

    }
```

Maybe there should be a method exposed on SharedResourceHolder that does the cleanup.  Something along the lines of

```
public static shutdownRemainingResources() throws InterruptedException {
  while (!instances.isEmpty()) {
    Thread.sleep(DESTROY_DELAY_SECONDS*1000);
    instances.keySet()
      .forEach(resource ->holder.release(resource, holder.getInternal(resource));
}
```

**Comment by trajano** [comment] 2021-02-15 16:02
Here's a slightly improved? (I am not sure if it is TBH) but it gets rid of the Thread.sleep()  I had to remove the logging.

```
@SneakyThrows
    @SuppressWarnings("java:S3011")
    private void cleanGrpcSharedResources() {

        final Field instancesField = SharedResourceHolder.class.getDeclaredField("instances");
        instancesField.setAccessible(true);

        final Field holderField = SharedResourceHolder.class.getDeclaredField("holder");
        holderField.setAccessible(true);

        final Map<?, ?> instances = (Map<?, ?>) instancesField.get(holderField.get(null));
        while (!instances.isEmpty()) {
            instances.keySet()
                .stream()
                .map(entry -> (SharedResourceHolder.Resource<Object>) entry)
                .forEach(resource -> {
                    final Object instance = SharedResourceHolder.get(resource);
                    SharedResourceHolder.release(resource, instance);
                });
            Thread.yield();
        }

    }
```

**Comment by ejona86** [comment] 2021-02-16 18:29
@trajano, you can't go around just releasing those executors, and don't reference gRPC internals via reflection. I'd be strongly tempted to rename those fields just so it would break your code. Using `setAccessible(true)` is essentially never appropriate.

The message about `grpc-shared-destroyer-0` is related to this issue, but is benign as it will be cleaned up and is evidenced by adding a `Thread.sleep(2000)` to your servlet shutdown.

`grpc-default-executor` and `grpc-default-worker-ELG` hanging around is unrelated to this issue. Any more discussion about them should be in a separate issue. Those being alive mean they are still used somewhere (or there's a leak that we haven't noticed; possible, but not the most likely reason). In this case it is probably because the server is still running; you don't actually verify it terminated (return value of awaitTermination) and you don't call shutdownNow() to kill any in-flight RPCs. So if some RPCs are slow-running or long-lived they will be keeping the server alive.

**Comment by trajano** [comment] 2021-02-16 18:49
Adding a Thread.sleep(2000) didn't work in https://github.com/grpc/grpc-java/issues/6692#issuecomment-779256254 I didn't have the cleanup code.  Just querying the internal structures.

**Comment by larry-safran** [comment] 2023-06-22 00:35
We now have a servlet module and this hasn't had any activity in over 2 years, so closing it.

**Closed** 2023-06-22 17:49 UTC
Labels: bug
