### ISSUE TITLE
How to catch the threadpool RejectedException in the grpc server side

### ISSUE THREAD

**Issue by dcrty90** [grpc/grpc-java#8070] opened 2021-04-09 06:46 UTC
How to catch the threadpool RejectedException in the grpc server side? Reference issue: https://github.com/grpc/grpc-java/issues/636

For example, I have below setting for the grpc server executor: corePoolSize=2, maxPoolSize=4, queueCapacity=2. When the client has more than 6 requests, the server executor theadpool may throw TaskRejectedException, like:

[grpc-nio-worker-ELG-3-2-41] WARN NettyServerHandler:463 - Exception in onHeadersRead()
org.springframework.core.task.TaskRejectedException: Executor [java.util.concurrent.ThreadPollExecutor@6f636d4c[Running, pool size = 3, active threads = 3, queued tasks = 2, completed tasks = 0]] did not accept taks: io.grpc.internal.SerializingExecutor@6f636d4c

I have tried

1. catch the exception in my service class(extends XXXImplBase)

2. implement ServerInterceptor interface to override the onHalfClose()/onCancel method to catch exception

but both does't work.

Can someone please suggest where can I catch this kind of exception? Thanks a lot in advance.

**Comment by sanjaypujare** [comment] 2021-04-09 07:14
Based on #636 it seems to be an open issue still. Also looking at `NettyServerHandler.onHeadersRead()` (your example) any exception like `TaskRejectedException` is wrapped inside an `Http2Exception` so you cannot catch it.

Unless @ejona86 has some ideas.... Also curious: what will you do after catching the exception?

**Comment by dcrty90** [comment] 2021-04-09 08:51
Thanks @sanjaypujare for your response.

In this case, if the exception is not catched, the connection will be interruppted, then the left concurrent tasks will be cancelled. And no notifications will be sent to the client. In a word, some requests will be hang there.

If we have the ability to catch the exception, from the server side, we can response an error code. When clients receive the error code, it can pop up a retry window.

**Comment by sanjaypujare** [comment] 2021-04-09 15:55
The wrapping Http2Exception would be sent to the client, right? Although it might be a generic error code can't that be made to work?

**Comment by ejona86** [comment] 2021-04-09 15:57
Bad things happen if the executor throws, and there's no workaround other than "don't throw."

**Comment by ejona86** [comment] 2021-04-27 23:31
We agree this is an issue, and I'm happy you are reporting that it is causing you trouble as it helps prioritize #636, but it seems just a duplicate of #636

**Closed by ejona86** 2021-04-27 23:31 UTC
Labels: question
