### ISSUE TITLE
Why is the message input stream not closed? Possible memory leak?

### ISSUE THREAD

**Issue by thashimalayaratnam** [grpc/grpc-java#3648] opened 2017-10-31 23:51 UTC
I discovered this while sending a relatively high throughput of requests (about 500 messages per second). Which started causing undefined behavior in my application.

According to, https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ClientCallImpl.java#L409 
each `InputStream` instance is never closed after putting it on the wire. When sending many messages at once, this can cause a possible memory leak? 

Thanks in advance!

**Comment by carl-mastrangelo** [comment] 2017-11-01 00:14
cc @zpencer

**Comment by zpencer** [comment] 2017-11-01 00:26
Thanks for the report. This is a duplicate of https://github.com/grpc/grpc-java/pull/3419, we will raise the priority on it.

**Closed by zpencer** 2017-11-01 00:26 UTC
