### ISSUE TITLE
Can I use direct memory pool for ByteString

### ISSUE THREAD

**Issue by coffee-core** [grpc/grpc-java#9704] opened 2022-11-21 09:47 UTC
Is there way to hook up a callback from grpc after each message is sent done? Or it could be after the data is serialized to a different memory space.
I am trying to use Netty's DirectByteBuf for Created ByteString(use UnsafeByteOperations#unsafeWrap(ByteBuffer)） in the msg object and want to release those for reuse after the transmission is done.
Also, I'm wondering if it's possible to achieve zero-copy when sending messages if I do this.

**Comment by ejona86** [comment] 2022-12-20 18:39
Closing as a duplicate of #1054.

**Closed by ejona86** 2022-12-20 18:39 UTC
Labels: question
