### ISSUE TITLE
AbstractClientStream - Received data on closed stream

### ISSUE THREAD

**Issue by elmodeer** [grpc/grpc-java#8329] opened 2021-07-18 13:11 UTC
### What version of gRPC-Java are you using?
1.34.1

### What is your environment?

Linux alpine image on a pod.
JDK 11

### What did you expect to see?
no log messages 

### What did you see instead?
many log messages with message : AbstractClientStream - Received data on closed stream

### Steps to reproduce the bug
I don't know how exactly to reproduce but with me, it is a persistent behavior when I pull async huge amount of messages 2-3 Million with 2-3Kb size from pubSub subscribtion.

<html>
<body>

15:06:44.826 [grpc-default-worker-ELG-1-3] INFO  i.grpc.internal.AbstractClientStream - Received data on closed stream
--
  | 15:06:44.827 [grpc-default-worker-ELG-1-3] INFO  i.grpc.internal.AbstractClientStream - Received data on closed stream
  | 15:06:44.828 [test.topic.4-sub] INFO  BusinessLogger - Sending 21150 messages to esb.pubsub.test.dest.4
  | 15:06:44.829 [grpc-default-worker-ELG-1-3] INFO  i.grpc.internal.AbstractClientStream - Received data on closed stream
  | 15:06:44.829 [grpc-default-worker-ELG-1-3] INFO  i.grpc.internal.AbstractClientStream - Received data on closed stream
  | 15:06:44.831 [grpc-default-worker-ELG-1-3] INFO  i.grpc.internal.AbstractClientStream - Received data on closed stream
  | 15:06:44.833 [grpc-default-worker-ELG-1-3] INFO  i.grpc.internal.AbstractClientStream - Received data on closed stream
  | 15:06:44.836 [grpc-default-worker-ELG-1-3] INFO  i.grpc.internal.AbstractClientStream - Received data on closed stream
  | 15:06:44.837 [grpc-default-worker-ELG-1-3] INFO  i.grpc.internal.AbstractClientStream - Received data on closed stream

</body>
</html>

**Comment by dapengzhang0** [comment] 2021-07-20 16:28
Does it causing any application failure? What type of RPC was it, Unary, Server Streaming, Bidi-streaming, etc? Was the RPC cancelled early? This can be normal in some cases.

**Comment by elmodeer** [comment] 2021-07-21 04:40
It is causing many duplicated received messages.  
I would say it is server streaming.  as I am using async pull from a pubSub topic.

**Comment by dapengzhang0** [comment] 2021-08-09 18:15
@elmodeer Unfortunately from the given information, we can not find anything obviously went wrong. It would be very helpful if you can provide something like a small github project that can reproduce the issue if running it for sufficient many times.

**Comment by dapengzhang0** [comment] 2021-09-02 17:18
This looks like a bug and we really would like to find out the cause. However, we can not investigate further with current limited information. Closing for now. Can be reopened if more information especially on reproducibility is provided.

**Closed by dapengzhang0** 2021-09-02 17:18 UTC
