### ISSUE TITLE
StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence

### ISSUE THREAD

**Issue by sduskis** [grpc/grpc-java#831] opened 2015-08-18 13:53 UTC
A user of Cloud Bigtable reported a bug on a really large streaming response: https://github.com/GoogleCloudPlatform/cloud-bigtable-client/issues/407.  Any advice on how to address the stack trace below? 

```
8, 2015 3:21:15 PM io.grpc.SerializingExecutor$TaskRunner run
GRAVE: Exception while executing runnable io.grpc.ChannelImpl$CallImpl$ClientStreamListenerImpl$2@6965a9c6
io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
at io.grpc.Status.asRuntimeException(Status.java:428)
at io.grpc.protobuf.ProtoUtils$1.parse(ProtoUtils.java:64)
at io.grpc.protobuf.ProtoUtils$1.parse(ProtoUtils.java:52)
at io.grpc.MethodDescriptor.parseResponse(MethodDescriptor.java:105)
at io.grpc.ChannelImpl$CallImpl$ClientStreamListenerImpl$2.run(ChannelImpl.java:384)
at io.grpc.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.bigtable.repackaged.com.google.protobuf.InvalidProtocolBufferException: Protocol message was too large. May be malicious. Use CodedInputStream.setSizeLimit() to increase the size limit.
at com.google.bigtable.repackaged.com.google.protobuf.InvalidProtocolBufferException.sizeLimitExceeded(InvalidProtocolBufferException.java:110)
at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.tryRefillBuffer(CodedInputStream.java:1131)
at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:1081)
at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.ensureAvailable(CodedInputStream.java:1068)
at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.readRawBytesSlowPath(CodedInputStream.java:1203)
at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.readBytes(CodedInputStream.java:517)
at com.google.bigtable.v1.Column.(Column.java:52)
at com.google.bigtable.v1.Column.(Column.java:13)
at com.google.bigtable.v1.Column$1.parsePartialFrom(Column.java:822)
at com.google.bigtable.v1.Column$1.parsePartialFrom(Column.java:816)
at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:495)
at com.google.bigtable.v1.Family.(Family.java:61)
at com.google.bigtable.v1.Family.(Family.java:13)
at com.google.bigtable.v1.Family$1.parsePartialFrom(Family.java:923)
at com.google.bigtable.v1.Family$1.parsePartialFrom(Family.java:917)
at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:495)
at com.google.bigtable.v1.ReadRowsResponse$Chunk.(ReadRowsResponse.java:185)
at com.google.bigtable.v1.ReadRowsResponse$Chunk.(ReadRowsResponse.java:145)
at com.google.bigtable.v1.ReadRowsResponse$Chunk$1.parsePartialFrom(ReadRowsResponse.java:904)
at com.google.bigtable.v1.ReadRowsResponse$Chunk$1.parsePartialFrom(ReadRowsResponse.java:898)
at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:495)
at com.google.bigtable.v1.ReadRowsResponse.(ReadRowsResponse.java:60)
at com.google.bigtable.v1.ReadRowsResponse.(ReadRowsResponse.java:13)
at com.google.bigtable.v1.ReadRowsResponse$1.parsePartialFrom(ReadRowsResponse.java:1651)
at com.google.bigtable.v1.ReadRowsResponse$1.parsePartialFrom(ReadRowsResponse.java:1645)
at com.google.bigtable.repackaged.com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:192)
at com.google.bigtable.repackaged.com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
at com.google.bigtable.repackaged.com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:215)
at com.google.bigtable.repackaged.com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
at io.grpc.protobuf.ProtoUtils$1.parse(ProtoUtils.java:61)
... 7 more
```

**Comment by ejona86** [comment] 2015-08-18 14:02
This looks to be the most interesting part:
> Protocol message was too large. May be malicious. Use CodedInputStream.setSizeLimit() to increase the size limit.

It looks like CodedInputStream has a [default size limit of 64 MB](https://github.com/google/protobuf/blob/master/java/src/main/java/com/google/protobuf/CodedInputStream.java#L886).

**Comment by nmittler** [comment] 2015-08-18 15:06
Yep, we need to sort out how we're going to support larger payloads.  Perhaps now is a good time to implement message size limit?

**Comment by nmittler** [comment] 2015-08-18 15:07
Closing this as a duplicate of #832.

**Closed by nmittler** 2015-08-18 15:07 UTC
Labels: duplicate
