### ISSUE TITLE
IllegalStateException: listener unset

### ISSUE THREAD

**Issue by asarkar** [grpc/grpc-java#6795] opened 2020-03-03 01:03 UTC
### What version of gRPC-Java are you using?
1.21.0

### What is your environment?
CentOS Linux release 7.6.1810
OpenJDK 64-Bit Server VM (Zulu 8.38.0.13-CA-linux64) (build 25.212-b04, mixed mode)

### What did you expect to see?
No errors

### What did you see instead?
```
java.lang.IllegalStateException: listener unset
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.getListener(ServerImpl.java:706)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.access$2700(ServerImpl.java:685)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:793)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
### Steps to reproduce the bug
Found by internal load testing

I found https://github.com/grpc/grpc-java/issues/6486 but there OP is using a 
`ArrayBlockingQueue` with capacity 1024, whereas I'm using a `SynchronousQueue`, which is unbounded. Unlike the OP, I'm not seeing a `RejectedExecutionException`. The only thing we do is set a bounded thread pool executor that sends out usage metrics. A test project is available on GitHub.
https://github.com/asarkar/kotlin/blob/master/grpc-learning/src/main/kotlin/org/asarkar/greeting/server/GreetingServer.kt#L47

**Comment by creamsoup** [comment] 2020-03-04 19:37
`SynchronousQueue` works in very special way. Especially the `offer` may return false if no waiting thread which is used by `ThreadPoolExecutor`. Using `SynchrousQueue` backed `ThreadPoolExecutor`  is not a great idea for executor in gRPC. 
when it calls the execute to set the listener, it checks the `ctl` which is 0 (no worker yet) so it can simply ignore the `Runnable`. because of this behavior, grpc doesn't work as expected.

**Comment by asarkar** [comment] 2020-03-04 20:08
> when it calls the execute to set the listener

@creamsoup What's "it" and `ctl`? Please don't assume that I know gRPC internals.

> Using `SynchrousQueue` backed `ThreadPoolExecutor` is not a great idea for executor in gRPC.

What would be better then?

**Comment by creamsoup** [comment] 2020-03-04 20:23
sorry, `it` as server or anything interacts with the `ThreadPoolExecutor` backed  by `SynchronousQueue`. `ctl` is an internal variable of the ThreadPoolExecutor (should have mentioned it) count of workers. if you read the `ThreadPoolExecute#execute` you can see why.

**Comment by creamsoup** [comment] 2020-03-04 22:00
Please ignore what I said before. 

actually it looks like there could be a race case. but i can't verify if this is really happening or not. how easy to reproduce the exception?

the potential fix is moving the [finally block](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ServerImpl.java#L565) inside (double try block unfortunately).

can you tell me how to run the loadtest?

**Comment by creamsoup** [comment] 2020-03-04 22:15
btw, if you are using java8+, `ForkJoinPool` performs very good.

**Comment by creamsoup** [comment] 2020-03-06 21:21
I ran gRPC transport benchmark with `ThreadPoolExecutor` with `SynchronousQueue`. It throws `RejectedExecutionException` if the pool is small, or it runs fine if the pool is large enough. 
if I can't reproduce, I can't identify the root cause. can you provide instruction?

**Comment by asarkar** [comment] 2020-03-06 21:49
We also see `RejectedExecutionException` but like you said, if it's a race condition, I don't know of any instructions to specifically reproduce the bug. The bug exists, however, as we can clearly see. The application is internal and complicated, so I'm not sure there's much I can take from it to show you.

**Comment by creamsoup** [comment] 2020-03-06 22:07
I am very confused, the original report says you don't see any `RejectedExecutionException`.
if it is not reproducible, we can't fix it.

**Comment by asarkar** [comment] 2020-03-06 22:59
The original report was wrong about that, there are `RejectedExecutionException` indeed, but not logged at error level, so I missed those at first.

As for how to reproduce the problem, I've tried to provide as much pertinent information as possible. If you believe you've tried enough, and still can't find the problem, that's unfortunate. I'm not able to generate an error report that points to a particular line in the code.

FWIW, we were running a `ThreadPoolExecutor` with core pool size = 1, max = 10, and `SynchronousQueue` on both server and client side with a load of 5 request/second. I've since switched to a `ForkJoinPool` but have yet to reach conclusive results.

**Comment by creamsoup** [comment] 2020-03-06 23:42
if you see the `RejectedExecutionException`, this is a known bug #636. We have some idea to handle gracefully, but it is not very high priority hence the bug is marked as P2. i'll close this issue since it is a duplicate. more discussion or suggestion can be done in the other bug.

side note for the `ForkJoinPool`, it performed best and it is desired imo. it is not default because we support java 7.

**Closed by creamsoup** 2020-03-06 23:42 UTC
Labels: bug

**Comment by asarkar** [comment] 2020-03-10 00:02
> `ForkJoinPool`, it performed best and it is desired imo. it is not default because we support java 7.

It doesn't sound like a great idea to support a JDK release from 9 years ago at the expense of good performance.
