### ISSUE TITLE
io.grpc.StatusRuntimeException: INTERNAL: Protocol error Rst Stream

### ISSUE THREAD

**Issue by jhawk28** [grpc/grpc-java#7044] opened 2020-05-15 15:05 UTC
### What version of gRPC-Java are you using?
1.29.0

### What is your environment?
Linux. Java gRPC client talking to a Go gRPC server.

We have a multithreaded client that makes different calls to the gRPC server. We reuse the ManagedChannel, but create a separate blocking stub for each thread. We see the error when the server takes a long time (a few minutes) to process and returns a large error message.

If I change the code to use a ManagedChannel per thread, the problem goes away. This makes it appear that there is a concurrency issue with the ManagedChannel.

**Comment by dapengzhang0** [comment] 2020-05-15 17:39
How many threads are running in your client and what is the [MaxConcurrentStreams](https://godoc.org/google.golang.org/grpc#MaxConcurrentStreams) of your go server?

**Comment by jhawk28** [comment] 2020-05-15 17:44
there are 5 threads on the client side. We didn't change the MacConcurrentStreams.

**Comment by dapengzhang0** [comment] 2020-05-15 18:51
>there are 5 threads on the client side

That number is super low and shouldn't cause such problem. We have interop and stress testing across different languages, and didn't have this issue. Can you please share some code that could reproduce the issue?

**Comment by jhawk28** [comment] 2020-05-15 19:11
I'll see what I can do to create a test case.

**Comment by ejona86** [comment] 2020-06-12 16:41
Since you mentioned the server "returns a large error message," this may be caused by the max metadata size. Try increasing [`channelBuilder.maxInboundMetadataSize()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#maxInboundMetadataSize-int-) to something larger than the response error size.

I've reproduced this in the helloworld example by modifying the Go server:
```diff
--- a/examples/helloworld/greeter_server/main.go
+++ b/examples/helloworld/greeter_server/main.go
@@ -23,8 +23,10 @@ import (
        "context"
        "log"
        "net"
+       "strings"
 
        "google.golang.org/grpc"
+       "google.golang.org/grpc/metadata"
        pb "google.golang.org/grpc/examples/helloworld/helloworld"
 )
 
@@ -40,6 +42,9 @@ type server struct {
 // SayHello implements helloworld.GreeterServer
 func (s *server) SayHello(ctx context.Context, in *pb.HelloRequest) (*pb.HelloReply, error) {
        log.Printf("Received: %v", in.GetName())
+       md := make(metadata.MD)
+       md["hello"] = []string{strings.Repeat("world", 1024*1024)}
+       grpc.SetTrailer(ctx, md)
        return &pb.HelloReply{Message: "Hello " + in.GetName()}, nil
 }
 
````

I'm surprised that Java only says "HTTP/2 error code: INTERNAL_ERROR Received Rst Stream." I expected it to include the error code from the RST_STREAM as well. We may want to look into that, but it doesn't change _much_.

**Comment by dapengzhang0** [comment] 2020-06-12 16:54
@ejona86 Is the failure you reproduced also ONLY happening for a multithreaded client?

**Comment by ejona86** [comment] 2020-06-12 17:39
@dapengzhang0, no. Single RPC is enough to trigger it.

**Comment by ejona86** [comment] 2020-06-12 19:36
Actually, it the code was included in my error: INTERNAL_ERROR. If the error message is "Rst Stream" instead of "Received Rst Stream", then that string only shows up in OkHttp. OkHttp does not reproduce this error with the snippet I provided.

@jhawk28, are you using OkHttp?

"Protocol error" is the http2 error code PROTOCOL_ERROR. That's a serious error. We'd probably need a reproduction test to dig into what is going wrong.

**Comment by jhawk28** [comment] 2020-06-13 02:00
I'm using netty:

def grpcVersion = '1.29.0'

dependencies {
    compile "io.grpc:grpc-netty:${grpcVersion}"
    compile "io.grpc:grpc-protobuf:${grpcVersion}"
    compile "io.grpc:grpc-stub:${grpcVersion}"
}

Trying to reproduce the issue. The Java client -> Java server is working fine. It must be something that happens with the Java client -> go server.

Joshua
On 6/12/2020 3:36:52 PM, Eric Anderson <notifications@github.com> wrote:
Actually, it the code was included in my error: INTERNAL_ERROR. If the error message is "Rst Stream" instead of "Received Rst Stream", then that string only shows up in OkHttp. OkHttp does not reproduce this error with the snippet I provided.
@jhawk28 [https://github.com/jhawk28], are you using OkHttp?
"Protocol error" is the http2 error code PROTOCOL_ERROR. That's a serious error. We'd probably need a reproduction test to dig into what is going wrong.

**Comment by ejona86** [comment] 2020-06-15 16:54
Hmm... "Protocol error" and "Rst Stream" only exist in okhttp transport. I don't see those strings in grpc-go. And netty is automatically preferred over okhttp, unless Android classes are found.

It's interesting it isn't triggered by Java→Java.

**Comment by jhawk28** [comment] 2020-06-15 17:09
I'm also not getting it to trigger on my Java -> Go server test either so I'm missing something.

Joshua
On 6/15/2020 12:54:56 PM, Eric Anderson <notifications@github.com> wrote:
Hmm... "Protocol error" and "Rst Stream" only exist in okhttp transport. I don't see those strings in grpc-go. And netty is automatically preferred over okhttp, unless Android classes are found.
It's interesting it isn't triggered by Java→Java.

**Comment by ejona86** [comment] 2020-07-20 21:45
I'm going to close this since we are unable to reproduce. I'd _love_ to track it down and fix, but it has been elusive. This can be reopened when we have an idea how to make it trigger.

**Closed by ejona86** 2020-07-20 21:45 UTC
