### ISSUE TITLE
Example RouteGuideGrpc Can not found

### ISSUE THREAD

**Issue by icesparrow0** [grpc/grpc-java#6469] opened 2019-11-28 06:02 UTC
I use maven to generate the protocol source code, and I can not found the RouteGuideGrpc class in the target generated-sources

**Comment by creamsoup** [comment] 2019-12-02 18:13
did you follow steps in [README](https://github.com/grpc/grpc-java/blob/master/examples/README.md)? 

most common issue is running on snapshot version. make sure running the command on release branch. if you are already tried on the release branch (or tag), please provide steps to reproduce the issue.

**Comment by ejona86** [comment] 2019-12-10 00:27
Closing since there was no more information. If more information is provided we can reopen.

**Closed by ejona86** 2019-12-10 00:27 UTC
Labels: question
