### ISSUE TITLE
Should the java compiler version be unified as 1.8 or newer

### ISSUE THREAD

**Issue by letuer** [grpc/grpc-java#8705] opened 2021-11-13 07:19 UTC
There is two java compiler version in master branch，1.7 and 1.8. 
![image](https://user-images.githubusercontent.com/8286829/141609387-89efe04b-40ab-4bd6-8a19-122d849d67df.png)

Should we upgarde it to 1.8 or newer. For the following reasons:
1. Java8 and 11 is most popular Java version。Few applications  still use Java7。 See [2020-java-technology-report](https://www.jrebel.com/blog/2020-java-technology-report#java-version).
2. Java8 new features, like lambda、stream，can improve development efficiency， make code implementation cleaner。

Please think about it. Thanks.

**Comment by ejona86** [comment] 2021-11-15 03:36
Duplicate of #4671.

Note that there is nothing to "unify" here. The 1.8s you see there are all Android, which can do language desugaring for older platforms but isn't actually Java 8 (e.g., stream is not available; although there is also some library desugaring available). But why it is needed is because of some fallout from Guava _warning_ about dropping Java 7 support (see https://github.com/grpc/grpc-java/releases/tag/v1.38.0 and https://github.com/google/guava/releases/tag/v30.1).

**Closed by ejona86** 2021-11-15 03:36 UTC
Labels: question

**Comment by letuer** [comment] 2021-11-15 06:25
Thanks, I get it. If not necessary, compatibility for older platforms is more important.
