### ISSUE TITLE
Netty caused "onStreamAllocated was not called, but it seems the stream is active"

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#3007] opened 2017-05-15 23:29 UTC
Reported by https://groups.google.com/d/topic/grpc-io/gpapLCscalk/discussion

Seen in grpc 1.3.0

```
22:42:37.609 |- WARN  i.n.u.c.DefaultPromise - An exception was thrown by io.grpc.netty.NettyClientStream$Sink$2.operationComplete()
java.lang.IllegalStateException: onStreamAllocated was not called, but it seems the stream is active
        at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
        at io.grpc.internal.AbstractStream2$TransportState.onSentBytes(AbstractStream2.java:287)
        at io.grpc.netty.NettyClientStream$Sink$2.operationComplete(NettyClientStream.java:172)
        at io.grpc.netty.NettyClientStream$Sink$2.operationComplete(NettyClientStream.java:166)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)
        at io.netty.channel.DefaultChannelPromise.setSuccess(DefaultChannelPromise.java:76)
        at io.netty.channel.DefaultChannelPromise.setSuccess(DefaultChannelPromise.java:71)
        at io.netty.handler.codec.http2.StreamBufferingEncoder$Frame.release(StreamBufferingEncoder.java:309)
        at io.netty.handler.codec.http2.StreamBufferingEncoder$DataFrame.release(StreamBufferingEncoder.java:357)
        at io.netty.handler.codec.http2.StreamBufferingEncoder$PendingStream.close(StreamBufferingEncoder.java:292)
        at io.netty.handler.codec.http2.StreamBufferingEncoder.writeRstStream(StreamBufferingEncoder.java:184)
        at io.grpc.netty.NettyClientHandler.cancelStream(NettyClientHandler.java:470)
        at io.grpc.netty.NettyClientHandler.write(NettyClientHandler.java:244)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:739)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:731)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:817)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:724)
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1022)
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:291)
        at io.grpc.netty.WriteQueue.flush(WriteQueue.java:127)
        at io.grpc.netty.WriteQueue.access$000(WriteQueue.java:47)
        at io.grpc.netty.WriteQueue$1.run(WriteQueue.java:59)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by sduskis** [comment] 2017-08-01 21:27
I've seen the same thing in grpc 1.4.0.  Has there been any update on this issue?

**Comment by ericgribkoff** [comment] 2017-08-04 00:48
The following "test" case (it doesn't actually assert anything) added to `NettyClientTransportTest` reproduces the logged exception:

```
  @Test
  public void cancelBufferedStream() throws Exception {
    // Only allow a single stream active at a time.
    startServer(1, GrpcUtil.DEFAULT_MAX_HEADER_LIST_SIZE);

    NettyClientTransport transport = newTransport(newNegotiator());
    callMeMaybe(transport.start(clientTransportListener));

    // Send a dummy RPC in order to ensure that the updated SETTINGS_MAX_CONCURRENT_STREAMS
    // has been received by the remote endpoint.
    new Rpc(transport).halfClose().waitForResponse();

    // Create 2 streams, but don't half-close. The transport will buffer the second.
    Rpc[] rpcs = new Rpc[]{new Rpc(transport), new Rpc(transport)};

    // Wait for the response for the stream that was actually created.
    rpcs[0].waitForResponse();

    rpcs[1].stream.cancel(Status.ABORTED);
  }
```

As seen in the stack trace, the invocation of `NettyClientHandler#cancelStream` triggers release of the frames queued on the pending stream. After `NettyClientStream.Sink#writeFrame` queues a frame to the pending stream, releasing it triggers its [`onComplete(ChannelFuture future)`](https://github.com/grpc/grpc-java/blob/02cb718767fbf01da45ba541a2d6bfa7ad979d40/netty/src/main/java/io/grpc/netty/NettyClientStream.java#L154) listener where `future.isSuccess() == true`, in turn causing a notification to the transport state that the written frame's bytes can be removed from flow control. But the stream was never allocated, because it was cancelled before it could begin, and so the exception is thrown.  See [`NettyClientHandler#createStream`](https://github.com/grpc/grpc-java/blob/02cb718767fbf01da45ba541a2d6bfa7ad979d40/netty/src/main/java/io/grpc/netty/NettyClientHandler.java#L423) for the initial check if the HTTP/2 stream was actually created before attaching it to the client stream.

@ejona86 One seemingly cheap fix for this is to just check in [`NettyClientStream.Sink#writeFrame`](https://github.com/grpc/grpc-java/blob/02cb718767fbf01da45ba541a2d6bfa7ad979d40/netty/src/main/java/io/grpc/netty/NettyClientStream.java#L155)'s listener if `http2Stream` has been set on the transport state:

```
              @Override
              public void operationComplete(ChannelFuture future) throws Exception {
                if (future.isSuccess() && transportState().http2Stream() != null) {
                  // Remove the bytes from outbound flow control, optionally notifying
                  // the client that they can send more bytes.
                  transportState().onSentBytes(numBytes);
                }
              }
```

Is this the right approach? According to the comments on Netty's [StreamBufferingEncoder](https://github.com/netty/netty/blob/4448b8f42f599e79db1744cd8f5fdfee702c195e/codec-http2/src/main/java/io/netty/handler/codec/http2/StreamBufferingEncoder.java#L180), the promises on the cancelled stream are succeeded because the cancellation indicates that no one "cares" about the stream anymore, so there's no point triggering error handling.

**Comment by ericgribkoff** [comment] 2017-08-11 14:30
Fixed by https://github.com/grpc/grpc-java/pull/3314

**Closed by ericgribkoff** 2017-08-11 14:30 UTC
Labels: bug, usability
