### ISSUE TITLE
There are a large number of internal classes in grpc java source code. It is strongly recommended to move to a separate java file

### ISSUE THREAD

**Issue by brucelwl** [grpc/grpc-java#8404] opened 2021-08-12 16:28 UTC
There are a large number of internal classes in grpc java source code. It is strongly recommended to move to a separate java file.  A large number of internal classes make the code look very messy

for example:

io.grpc.ServerInterceptors.java

io.grpc.internal.ManagedChannelImpl.java

There are many more,

**Comment by YifeiZhuang** [comment] 2021-08-12 21:50
Do you mean breaking down `ManagedChannelImpl` into several separate java files? It looks `ManagedChannelImpl` is quite concise regarding the key tasks it is handling: e.g. channel lifecycle management, API installations.  It is as a connection point between different components, e.g. name resolvers, load balancers, transports. Those components are in separate files.  It looks this way fits grpc complexity well.

Do you mean moving `ServerInterceptors ` to other directory/sub-projects? This was a utility function and we exposed in grpc-api by design.

Marking it as duplicate of https://github.com/grpc/grpc-java/issues/8384 and closing.

**Closed by YifeiZhuang** 2021-08-12 21:50 UTC
Labels: enhancement
