### ISSUE TITLE
Can't run protoc-gen-grpc-java on Mac on M1 arm64

### ISSUE THREAD

**Issue by zaninime** [grpc/grpc-java#9678] opened 2022-11-04 13:20 UTC
### What version of gRPC-Java are you using?

`1.50.1`

### What is your environment?

MacOS on arm64

### What did you expect to see?

Native binaries being packaged, instead of a copy of the x86-64 ones, as done by this commit: https://github.com/grpc/grpc-java/commit/6518d7bd6dc496c89ff320e06c73424f26af364a

### What did you see instead?

```
protoc-gen-grpc-java-1.50.1-osx-aarch_64.exe: Mach-O 64-bit x86_64 executable
```

### Steps to reproduce the bug

Pull the binary from Maven and run `file` on it. It should print: `Mach-O universal binary with 2 architectures [...]` or `Mach-O 64-bit arm64e executable`

I understand I can just let it run with Rosetta, however I was expecting this to work the same as `protoc` (which is already packaged as an universal binary in Maven).

**Comment by ejona86** [comment] 2022-11-09 17:32
Duplicate of #7690. I don't have an M1, so I can't try any of the changes needed. It is mostly dependent on someone doing the work.

**Closed by ejona86** 2022-11-09 17:32 UTC
