### ISSUE TITLE
RPC failed: Network closed for unknown reason

### ISSUE THREAD

**Issue by greenbice** [grpc/grpc-java#7065] opened 2020-05-27 09:55 UTC
Hi 

i have this issue appearing once in a while. I have a system A talking to the system B via rpc, and once in a while i get this error with connection. Full log see below. The strange thing is, this time i don't see connection issue with my server boxes , A can talk to B with same call with no issue. But when i try run A locally this error appears. I can ping locally to the port and ip with no issue.  Please advise. 

```
09:10:06.334 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x18dd8fcb, L:/10.44.24.82:52619 - R:serviceB/10.41.17.116:80] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=59 bytes=00000000360a340a3242300a144252454e545f4950452e502e45584348414e474512024d311204323032301a060880ece1e305220608809bfce305
09:10:06.376 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x18dd8fcb, L:/10.44.24.82:52619 - R:serviceB/10.41.17.116:80] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=59
09:10:06.414 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x18dd8fcb, L:/10.44.24.82:52619 - R:serviceB/10.41.17.116:80] INBOUND HEADERS: streamId=1 headers=GrpcHttp2ResponseHeaders[grpc-status: 0] padding=0 endStream=true
09:10:06.414 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x18dd8fcb, L:/10.44.24.82:52619 - R:serviceB/10.41.17.116:80] OUTBOUND RST_STREAM: streamId=1 errorCode=5
09:10:06.425 [main] WARN com.server.ExampleClient - RPC failed: Network closed for unknown reason 
```

**Comment by sanjaypujare** [comment] 2020-05-27 16:55
@greenbice I am trying to understand the issue from the description. What you are saying is when both A and B are run on the same computer (local case) you see connection errors that you don't see when they are run on different computers.  If the log you posted is for the local case I see different IP addresses for the local end (10.44.24.82) and the remote end (10.41.17.116):
```
L:/10.44.24.82:52619 - R:serviceB/10.41.17.116:80
```
If they indeed belong to the same machine they are different network interfaces. You can instead use the localhost address (127.0.0.1) for the same test. When you said local ping succeeds which IP address did you use?

**Comment by greenbice** [comment] 2020-05-28 12:25
Hi thanks for the response. A and B was always on different computer, when they are running on the servers, they seems working fine. When i try to run A locally on my pc, to talk to B, it fail with that error. When i look into B(grpc server) the log showing the request has been processed and returned successfully. But my local was failed to receive that response with the error i attached. I was trying to ping the location and port of B on my local pc, and it can reach it.

**Comment by greenbice** [comment] 2020-05-28 12:27
my local is 10.44.24.82

**Comment by greenbice** [comment] 2020-05-28 12:36
When i ran both A,B locally to point to each other , i don't get any issue.

**Comment by greenbice** [comment] 2020-05-28 12:49
My server side log is showing response coming back like below 
`May 28th 2020, 13:08:14.094	 - 	[id: 0x42644149, L:/10.254.3.150:50051 - R:/10.254.3.23:57194] OUTBOUND DATA: streamId=31 padding=0 endStream=false length=824 bytes=00000003330ab0060aad060a40423e0a144252454e545f4943452e502e45584348414e474512024d3112024d3212024d331a0c088cd7b0f5051080dadff70222...
May 28th 2020, 13:08:14.094	 - 	[id: 0x42644149, L:/10.254.3.150:50051 - R:/10.254.3.23:57194] OUTBOUND HEADERS: streamId=31 headers=GrpcHttp2OutboundHeaders[grpc-status: 0] streamDependency=0 weight=16 exclusive=false padding=0 endStream=true
May 28th 2020, 13:08:14.093	 - 	[id: 0x42644149, L:/10.254.3.150:50051 - R:/10.254.3.23:57194] OUTBOUND HEADERS: streamId=31 headers=GrpcHttp2OutboundHeaders[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
May 28th 2020, 13:08:14.092	 - 	GRPC call to DataServiceImpl.resolve returning data: resolvedMarketData ....`


But my client side can only receive below

`2020-05-28 13:08:09,515 [grpc-default-executor-74]  DEBUG ...components.GRPCLoggingInterceptor - GRPC call detected: MethodDescriptor{fullMethodName=...api.DataResolverService/Resolve, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@61c82217, responseMarshaller=io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@78dcde39, schemaDescriptor=...api.DataResolverServiceGrpc$DataResolverServiceMethodDescriptorSupplier@19219554}
2020-05-28 13:08:09,515 [grpc-default-executor-74]  INFO  ...util.ProtobufUtils - MarketDataRequest=...
2020-05-28 13:08:14,123 [grpc-default-executor-74]  ERROR ...service.DataResolverService - Failure during resolving key {...}
io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at io.grpc.Status.asRuntimeException(Status.java:532) ~[grpc-core-1.19.0.jar:1.19.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434) ~[grpc-stub-1.19.0.jar:1.19.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-core-1.19.0.jar:1.19.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-core-1.19.0.jar:1.19.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-core-1.19.0.jar:1.19.0]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:699) ~[grpc-core-1.19.0.jar:1.19.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-core-1.19.0.jar:1.19.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-core-1.19.0.jar:1.19.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-core-1.19.0.jar:1.19.0]
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397) ~[grpc-core-1.19.0.jar:1.19.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459) ~[grpc-core-1.19.0.jar:1.19.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) ~[grpc-core-1.19.0.jar:1.19.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546) ~[grpc-core-1.19.0.jar:1.19.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467) ~[grpc-core-1.19.0.jar:1.19.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584) ~[grpc-core-1.19.0.jar:1.19.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.19.0.jar:1.19.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.19.0.jar:1.19.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
`

**Comment by sanjaypujare** [comment] 2020-05-28 17:19
Okay, thanks for the clarification - now I understand the problem description.

Your latest log snippets on the client side don't show any IP addresses (which were there in your first comment). The server side log shows this `L:/10.254.3.150:50051 - R:/10.254.3.23:57194` so the server address is `10.254.3.150` and the client is `10.254.3.23`. But no such info on the client side. Can you capture both the logs when the failure happens and post them here that include the IP addresses of both sides in both logs?

Also:
- what sort of firewall/NAT devices exist between your local PC and the server?
- how much time is spent on the server side between request and response?

**Comment by greenbice** [comment] 2020-05-28 17:58
Hi thanks for your time. My client side logs are above (the part after the server log),  and i currently don't have the ip information logged on client side. 
I actually don;t know our firewall set up, i'm finding it out now.
It does take around few seconds for the response to complete. 


Thanks

**Comment by sanjaypujare** [comment] 2020-05-28 18:10
@greenbice yes I did notice the client logs in your previous comment but was looking for IP address info. Your first comment's log did have the `L:/10.44.24.82:52619 - R:serviceB/10.41.17.116:80` text so I was wondering if you could rerun the test, reproduce the error and post the log contents from both sides after ensuring the IP addresses are present in both.

Regarding the response delay, if you observe a correlation between connection issues and response delays then that is a good data point.

**Comment by greenbice** [comment] 2020-05-28 19:35
Here is the client side log 
`20:29:51.996 [grpc-nio-worker-ELG-1-3] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x0608c598, L:/10.44.24.82:64214 - R:ODY-759-grpccurveservice..../10.41.17.251:80] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
20:29:51.997 [grpc-nio-worker-ELG-1-3] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x0608c598, L:/10.44.24.82:64214 - R:ODY-759-grpccurveservice..../10.41.17.251:80] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
20:29:52.042 [grpc-nio-worker-ELG-1-3] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x0608c598, L:/10.44.24.82:64214 - R:ODY-759-grpccurveservice..../10.41.17.251:80] INBOUND SETTINGS: ack=false settings={HEADER_TABLE_SIZE=4096, MAX_CONCURRENT_STREAMS=250, INITIAL_WINDOW_SIZE=1048576, MAX_FRAME_SIZE=1048576, MAX_HEADER_LIST_SIZE=1048896}
20:29:52.042 [grpc-nio-worker-ELG-1-3] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x0608c598, L:/10.44.24.82:64214 - R:ODY-759-grpccurveservice..../10.41.17.251:80] OUTBOUND SETTINGS: ack=true
20:29:52.042 [grpc-nio-worker-ELG-1-3] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x0608c598, L:/10.44.24.82:64214 - R:ODY-759-grpccurveservice..../10.41.17.251:80] INBOUND SETTINGS: ack=true
20:29:52.042 [grpc-nio-worker-ELG-1-3] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x0608c598, L:/10.44.24.82:64214 - R:ODY-759-grpccurveservice..../10.41.17.251:80] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
20:29:52.042 [grpc-nio-worker-ELG-1-3] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x0608c598, L:/10.44.24.82:64214 - R:ODY-759-grpccurveservice..../10.41.17.251:80] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: ODY-759-grpccurveservice....:80, :path: /....MarketDataService/Resolve, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.29.0, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
20:29:52.043 [grpc-nio-worker-ELG-1-3] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x0608c598, L:/10.44.24.82:64214 - R:ODY-759-grpccurveservice..../10.41.17.251:80] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=33 bytes=000000001c0a1a0a1812160a144252454e545f4950452e502e45584348414e4745
20:29:52.088 [grpc-nio-worker-ELG-1-3] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x0608c598, L:/10.44.24.82:64214 - R:ODY-759-grpccurveservice..../10.41.17.251:80] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=33
20:29:52.229 [grpc-nio-worker-ELG-1-3] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x0608c598, L:/10.44.24.82:64214 - R:ODY-759-grpccurveservice..../10.41.17.251:80] INBOUND DATA: streamId=1 padding=0 endStream=false length=1896 bytes=00000007630ae00e0add0e0a21121f0a144252454e545f4950452e502e45584348414e4745120708e40f1005181a12b70e0ab40e0aba070a044461746552b107...
20:29:52.230 [grpc-nio-worker-ELG-1-3] DEBUG io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler - [id: 0x0608c598, L:/10.44.24.82:64214 - R:ODY-759-grpccurveservice..../10.41.17.251:80] OUTBOUND RST_STREAM: streamId=1 errorCode=5
20:29:52.232 [main] WARN com.....server.ExampleClient - RPC failed: Network closed for unknown reason `

**Comment by greenbice** [comment] 2020-05-28 19:37
server side 
`Response status from Odyssey REST: OK 
[id: 0x494e3015, L:/10.254.3.94:50051 - R:/10.254.3.23:44726] OUTBOUND DATA: streamId=37 padding=0 endStream=false length=1896 bytes=00000007630ae00e0add0e0a21121f0a144252454e545f4950452e502e45584348414e4745120708e40f1005181a12b70e0ab40e0aba070a044461746552b107...
[id: 0x494e3015, L:/10.254.3.94:50051 - R:/10.254.3.23:44726] OUTBOUND HEADERS: streamId=37 headers=GrpcHttp2OutboundHeaders[grpc-status: 0] padding=0 endStream=true
[id: 0x494e3015, L:/10.254.3.94:50051 - R:/10.254.3.23:44726] OUTBOUND HEADERS: streamId=37 headers=GrpcHttp2OutboundHeaders[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip] padding=0 endStream=false
GRPC call to MarketDataServiceImpl.resolve returning data: resolvedMarketData {...}`

**Comment by greenbice** [comment] 2020-05-28 19:38
seems we do not have firewall between my server and local

**Comment by sanjaypujare** [comment] 2020-05-28 20:22
Summarizing what I gathered from the logs:

From the client side:
L:/10.44.24.82:64214 - R:ODY-759-grpccurveservice..../10.41.17.251:80

The local IP is 10.44.24.82 and remote (server) IP is 10.41.17.251.
And timestamps show the request was sent out at 20:29:51.996 and the error generated (i.e. network closed) at 20:29:52.232 i.e. very quickly.

From the server side:
L:/10.254.3.94:50051 - R:/10.254.3.23:44726

The local (server) IP is 10.254.3.94 and the remote (client) IP is 10.254.3.23 

On the server side I don't see any time stamps - you probably removed them in the edits?

But the IP addresses don't match at all e.g. the remote from client doesn't match local at server so that means there is at least one network device doing NATting and that could be the cause of network failure. Ping may succeed because there is routability but TCP connections could still be impacted by these intermediate network devices.

You may need to dig deeper into the network topology and use tools like Wireshark to figure where network failures are happening.

**Comment by greenbice** [comment] 2020-05-28 20:53
Hi sanjaypujare , many thanks for your help. Yes i left the timestamp out as the format wasn't right. But i did see the all in line with client side and all logs are within 1sec. 
My client request is done with usePlaintext(), i thought that should avoid the tcp issue. But you are right, i need to find out what is the network in between which is likely to be the cause. Thanks. i'll do some more dig on that. 
One more question, if it's to do with firewall/network issue. Shouldn't the request fail to get to the server? seems the server got the request and processed with the Ok response. But failed to send the respond back. I thought if it's to do with network, shouldn't it fail to even get to the server?


Thanks

**Comment by sanjaypujare** [comment] 2020-05-28 21:09
Note that this is happening intermittently (based on your first comment) and also when it fails, the request comes thru but the response does not. This indicates there is no connectivity or routing issue so connections can be established but for some reason the connection unexpectedly closes and my suspicion is an intermediate device (NAT firewall etc) is causing these connection failures (see [this](https://en.wikipedia.org/wiki/Network_address_translation#Type_of_NAT_and_NAT_traversal,_role_of_port_preservation_for_TCP)) but this needs to be confirmed and understanding the network topology and wireshark dumps could help you there.

**Comment by greenbice** [comment] 2020-05-29 08:19
Many thanks, will check it out.

**Comment by sanjaypujare** [comment] 2020-06-02 21:17
I am closing it for now. Pls add a comment (so we can reopen) or open another issue with details.

**Closed by sanjaypujare** 2020-06-02 21:17 UTC
Labels: question
