### ISSUE TITLE
Implement idle channel state or swap back to lazy TCP creation

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1191] opened 2015-11-05 20:39 UTC
With the addition of load balancing we are now actively reconnecting. If no RPCs are occurring on the channel we really want to drop all TCP connections, especially on mobile. Since GFE and other servers are likely to shut down idle connections, swapping back to lazy connection creation should be "good enough" for now, in case that is easier than implementing idle detection.

**Comment by zhangkun83** [comment] 2015-12-11 18:57
This is a duplicate of

**Closed by zhangkun83** 2015-12-11 18:57 UTC
