### ISSUE TITLE
Example HelloWorldServer does not gracefully shutdown

### ISSUE THREAD

**Issue by dounan** [grpc/grpc-java#6511] opened 2019-12-11 02:53 UTC
### What version of gRPC-Java are you using?
On a fork up at commit https://github.com/grpc/grpc-java/commit/d168632f8229e387c19e820c26cf1d0f25bb0c84

### What is your environment?
Mac OSX 10.14.6
Java 11.0.2

### What did you expect to see?
The server should allow in-flight RPCs to finish

### What did you see instead?
The client receives error `WARNING: RPC 1 failed: Status{code=UNAVAILABLE, description=Network closed for unknown reason, cause=null}`

### Steps to reproduce the bug
- Add a call to `Thread.sleep(15000)` in `io.grpc.examples.helloworld.HelloWorldServer.GreeterImpl.sayHello`
- Build and run the server
- Run the client
- Ctrl+C the server once it gets the request

It seems like `server.shutdown()` does not wait for in-flight RPCs to finish before returning. The documentation makes it seem like that it should block. 

I am able to "fix" the issue by adding a call to `server.awaitTermination()` in the `stop` method.

**Comment by sanjaypujare** [comment] 2019-12-11 03:40
This is behaving as designed/expected. The doc for `server.shutdown()` does say "..preexisting calls continue..." but does not imply that `shutdown()` blocks until the calls end. So `shutdown` will return after initiating orderly shutdown but you need to wait using `server.awaitTermination()` for the inflight calls to finish. If the doc seems unclear/ambiguous suggest new wording.

**Comment by dounan** [comment] 2019-12-11 04:28
Would it make sense to update all the example code servers to reflect the fact that `awaitTermination()` needs to be called? Both that and the wording on the documentation is a bit misleading. I can try putting together a PR for that change

**Comment by sanjaypujare** [comment] 2019-12-11 07:00
> Would it make sense to update all the example code servers to reflect the fact that `awaitTermination()` needs to be called? 

Seems like a good idea since `awaitTermination()` is currently not called in case of control-C termination (shutdown-hook).

> Both that and the wording on the documentation is a bit misleading. I can try putting together a PR for that change

Even if not misleading, more clarification cannot hurt.

**Comment by dounan** [comment] 2019-12-11 07:17
Created a PR here: https://github.com/grpc/grpc-java/pull/6512

**Comment by ejona86** [comment] 2019-12-11 19:02
Taken from #6512:
Hmmm... something else is going on. The blockUntilShutdown() in the main() should be enough...

On ctrl-c, the JVM simply calls start() on the threads registered, and nothing really more. What causes JVM shutdown is when there are no non-daemon threads. The main thread is non-daemon, so it should keep the JVM alive.

------

I'm going to try to reproduce and see if I can find the root cause. The problem may be that the server is considering itself terminated prematurely. It might also be some of the subtleties with how RST vs graceful close is triggered (see SO_LINGER documentation for a small glimpse).

**Comment by dounan** [comment] 2019-12-11 19:05
Thanks @ejona86! Interested to see what you find out

**Comment by ejona86** [comment] 2019-12-11 19:28
Hmm... it appears my understand was wrong. Based on the [addShutdownHook() documentation](https://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#addShutdownHook-java.lang.Thread-), after a Ctrl-C the jvm will exit after all the hooks are run, and it seems to imply it will ignore any non-daemon threads. I guess that makes sense, since the jvm will exit on Ctrl-c if you haven't registered any shutdown hooks.

That does disagree with the [Thread documentation](https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html), since it only lists two ways (System.exit() and no more non-daemon threads). But I guess some language lawyering would say that doesn't apply in _termination_ scenarios.

**Comment by dounan** [comment] 2019-12-11 19:31
The `Thread` documentation is a bit vague. I wonder if it's because SIGINT actually triggers the `Runtime.exit()` call that the documentation refers to

**Comment by sanjaypujare** [comment] 2019-12-11 19:48
> The `Thread` documentation is a bit vague. I wonder if it's because SIGINT actually triggers the `Runtime.exit()` call that the documentation refers to

`exit` signifies proper exit (from the code) and cannot be triggered by SIGINT AFAIK

**Comment by ejona86** [comment] 2019-12-11 22:30
exit() in Java != exit() in C; it does a lot behind the scenes in Java. I did feel like SIGINT behaves similar to exit() having been called. But the documentation considers ctrl-C separate from exit(), but then calls out the exit() case as a special case, but that special case should also appears to apply to ctrl-c even though the documentation doesn't say it applies to ctrl-c.

Whatever.

**Comment by dounan** [comment] 2019-12-11 22:32
🤡

**Comment by ejona86** [comment] 2019-12-17 18:37
Fixed by #6512

**Closed by ejona86** 2019-12-17 18:37 UTC
Labels: bug
