### ISSUE TITLE
ServerBuilder should warn/error if a service impl is registered twice

### ISSUE THREAD

**Issue by ST-DDT** [grpc/grpc-java#7125] opened 2020-06-13 12:54 UTC
### What version of gRPC-Java are you using?

1.30.0

### What is your environment?

Windows 10
Java 8 + 11 (64bit)

### What did you expect to see?

A warning/error that the user registered a service twice.

### What did you see instead?

Nothing, the second implementation was ignored silently.

### Steps to reproduce the bug

````java
public class TestA extends SimpleGrpc.SimpleImplBase {
// Implement only method A
}
````

````java
public class TestB extends SimpleGrpc.SimpleImplBase {
// Implement only method B
}
````

````java
NettyServerBuilder.forPort(8080)
                .addService(new TestA())
                .addService(new TestB())
                .build()
                .start();
````

I can add/register both implementations, but I can only access one of them.

### Additional context

Originally reported:
https://github.com/yidongnan/grpc-spring-boot-starter/issues/365
Demo-Project:
https://github.com/yidongnan/grpc-spring-boot-starter/issues/365#issuecomment-640258488

**Comment by ejona86** [comment] 2020-06-15 16:05
The second implementation was ignored? That isn't right. The first implementation should have been overwritten. Looking at the code, it seems the first should have been replaced by the second. Are you sure the second implementation was ignored?

We allow `serverBuilder.build()` to be called multiple times and to reconfigure things fairly dramatically. I don't think it matches the builder's design to throw, and we try very hard not to log warnings.

If the second one was used (not the first), then I think this is "working as intended." I can understand it can bite you, but it seems part of the problem is because the services could come from many different places as injected by the framework. I suggest having a check in the framework to detect duplication.

**Comment by ST-DDT** [comment] 2020-06-15 22:28
I didnt check which one was used.

If your conclusion is "wont fix", then I will add the check to the spring framework or maybe I just follow your design. I just consider registering a service twice an error, thats why I reported it here. But with the reusability of the builder it doesn't make sense to warn or error.

**Comment by ejona86** [comment] 2020-06-15 22:38
I agree that in isolation it would be nice to throw, but it would also go against the pattern of the builder. So, yeah, "won't fix." I think it was quite fair to open the issue, it just doesn't quite work out in this case.

**Closed by ejona86** 2020-06-15 22:38 UTC
Labels: bug, wontfix
