### ISSUE TITLE
Impossible to ignore ALPN negotiation failure

### ISSUE THREAD

**Issue by samantmaharaj-rhapsody** [grpc/grpc-java#5543] opened 2019-04-03 20:34 UTC
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.18.0

### What did you expect to see?
Setting the `ApplicationProtocolConfig` to `SelectedListenerFailureBehavior.CHOOSE_MY_LAST_PROTOCOL` should unconditionally choose the last protocol even if ALPN negotiation didn't yield any protocols.

Related to #5167 

Looking at the logic in `io.netty.handler.ssl.ReferenceCountedOpenSslEngine.DefaultOpenSslSession.selectApplicationProtocol()`, `selectApplicationProtocol()` is only invoked if 
`applicationProtocol` is not null. The method `selectApplicationProtocol()` will ignore the negotiated protocol if `CHOOSE_MY_LAST_PROTOCOL` is selected and the selected protocol is not in the list of protocols.

It seems inconsistent to be able to ignore the results of the ALPN negotiation only in the case that the negotiation yielded some protocol but not in the case that it yielded no protocols.

### Use Case
I am using an AWS Network Load Balancer (NLB) to perform TLS termination for a gRPC application. The NLB cannot perform ALPN but the backend server which is implemented using grpc-java is HTTP/2 capable and tests using Go or Python based gRPC clients succeed against the server via the NLB.

I would like to be able to invoke the application using grpc-java and force the use of HTTP/2 even though ALPN negotiation will not succeed as I know the backend is HTTP/2 capable.

**Comment by ejona86** [comment] 2019-04-03 21:18
Did you need to configure Go and Python explicitly to support this case? What does that configuration look like?

Well, CHOOSE_MY_LAST_PROTOCOL is technically illegal with ALPN (and it is mentioned as such in the documentation). But I see your use-case. We don't really want to be encouraging that too much, but if you control your clients it isn't outrageous. This feels like a change that should happen in Netty, but I also sort of imagine it would be too invasive of a change there.

Where do you get a failure today? Is it at https://github.com/grpc/grpc-java/blob/v1.19.0/netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java#L680 ?

**Comment by samantmaharaj-rhapsody** [comment] 2019-04-03 21:37
> Did you need to configure Go and Python explicitly to support this case? What does that configuration look like?

I used [grpcurl](https://github.com/fullstorydev/grpcurl) which is implemented in Go as a test client. I didn't have to choose any specific configuration for the application to successfully interact with my server.

> 
> Well, CHOOSE_MY_LAST_PROTOCOL is technically illegal with ALPN (and it is mentioned as such in the documentation). But I see your use-case. We don't really want to be encouraging that too much, but if you control your clients it isn't outrageous. This feels like a change that should happen in Netty, but I also sort of imagine it would be too invasive of a change there.
> 
> Where do you get a failure today? Is it at https://github.com/grpc/grpc-java/blob/v1.19.0/netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java#L680 ?

Yes, that's exactly the point at which it fails. I was able to test that ignoring the ALPN result would work by monkey patching the [NEXT_PROTOCOL_VERSIONS](https://github.com/grpc/grpc-java/blob/v1.19.0/netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java#L659) List using reflection and nulling out the first element.

**Comment by ejona86** [comment] 2019-04-03 21:46
> I used grpcurl which is implemented in Go as a test client. I didn't have to choose any specific configuration for the application to successfully interact with my server.

Uh, oh. That sounds like a Go bug.

You mentioned Python as well. Did it need any configuration?

> Yes, that's exactly the point at which it fails.

So my thought is that grpc could see that the protocol selected is `null`and if CHOOSE_MY_LAST_PROTOCOL is being used then we could ignore the problem. But it looks like I need to resolve issues with the other clients, because ignoring ALPN shouldn't be happening by default!

**Comment by ejona86** [comment] 2019-04-03 22:06
@samantmaharaj-rhapsody, I just tested the Go client, and it seems to (properly) fail if the server does not support ALPN. I looked and I don't see how grpcurl could change that behavior. So I'm not sure how you're seeing your behavior...

**Comment by ejona86** [comment] 2019-04-04 00:03
Arg. My test of the Go client was broken. I'll need to fiddle with it more and try again.

**Comment by samantmaharaj-rhapsody** [comment] 2019-04-04 00:53
> 
> You mentioned Python as well. Did it need any configuration?
> 
I wrote a simple test client based on the gRPC Python tutorial. I've included the code below

```python
import grpc

import ping_pb2
import ping_pb2_grpc

import google.protobuf.empty_pb2 as empty

if __name__ == '__main__':

    credentials = grpc.ssl_channel_credentials()

    with grpc.secure_channel('foobar:443', credentials) as channel:
        stub = ping_pb2_grpc.PingServiceStub(channel)
        result = stub.Ping(empty.Empty())
        print(type(result).__name__)
```

When run, it successfully connects and returns an Empty response as per the service definition below

```protobuf
service PingService {

  // Ping service
  rpc Ping(google.protobuf.Empty) returns (google.protobuf.Empty) {}

}
```

**Comment by ejona86** [comment] 2019-04-04 17:41
Thanks. I've reproduced the Go and Python/C behavior. Filed grpc/grpc-go#2742 and grpc/grpc#18645 .

**Comment by nicolasnoble** [comment] 2019-04-04 18:15
Isn't it a duplicate of grpc/grpc#18549?

**Comment by ejona86** [comment] 2019-04-04 19:34
This Java issue is not a duplicate, because it is a feature request to allow connecting to ALPN-less servers.

**Comment by nicolasnoble** [comment] 2019-04-04 19:49
Right, I mean the one you filed for Python/C :-)

**Comment by nicolasnoble** [comment] 2019-04-04 19:50
Oh, I see.

**Comment by ejona86** [comment] 2019-04-05 00:19
@samantmaharaj-rhapsody, FYI, the fact Python worked was a regression introduced in v1.17.0. I checked and v1.16.0 correctly fails.

**Comment by ejona86** [comment] 2019-04-17 17:28
There was more discussion about this in https://github.com/grpc/grpc/issues/18710 . I had a cross-language discussion and we were against supporting this. It just is asking for too many ecosystem problems. The root problem is that TLS terminators don't support HTTP/2, architecturally. This isn't a grpc-specific problem.

**Closed by ejona86** 2019-04-17 17:28 UTC
