### ISSUE TITLE
Message with Compressed-Flag bit set but lacking a non-identity grpc-encoding MUST fail with INTERNAL status

### ISSUE THREAD

**Issue by drice-buf** [grpc/grpc-java#10971] opened 2024-02-29 19:45 UTC
### What version of gRPC-Java are you using?
1.61.1

### What is your environment?
MacOS 13.6.4, Oracle OpenJDK version 21.0.2

### What did you expect to see?
RPC should return an `internal` error (code 13)

### What did you see instead?
RPC returns a `canceled` error (code 1)

### Steps to reproduce the bug
Send a request one of the message frames has the "compressed" flag set in its 5-byte preface but the current encoding is "identity".

The expectation of an "internal" error comes from the set of test cases at the bottom of this doc on gRPC compression: https://github.com/grpc/grpc/blob/master/doc/compression.md#test-cases:

> An ill-constructed message with its [Compressed-Flag bit](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#compressed-flag) set but lacking a [grpc-encoding](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#message-encoding) entry different from identity in its metadata MUST fail with INTERNAL status, its associated description indicating the invalid Compressed-Flag condition.

The grpc-java server is not actually serializing any status exception to trailers in this scenario. Instead, it is sending a RST_STREAM HTTP/2 frame with code CANCEL, which results in the client observing a "CANCELLED" error code.

**Comment by ejona86** [comment] 2024-02-29 22:43
We can't easily respond with a pretty status, because the sending direction is not thread-safe. We simply accept it is less than an ideal error message. This comes up a bit more often when the message size is exceeded, but the problem is the same.

**Comment by temawi** [comment] 2024-03-08 19:04
Hopefully the explanation is sufficient - I will close this issue. If further discussion is needed we can open it up again.

**Closed by temawi** 2024-03-08 19:04 UTC
Labels: Waiting on reporter
