### ISSUE TITLE
Http2Exception Frame length: 14552922 exceeds maximum: 16384

### ISSUE THREAD

**Issue by njimenezotto** [grpc/grpc-java#10830] opened 2024-01-17 12:16 UTC
Having a grpc server using micronaut-grpc with the following configuration:

```
      grpc:
        server:
          port: 50054
          health.enabled: true
          max-inbound-metadata-size: 300720 # default 8kb 8192
          max-inbound-message-size: 21552922 # default 4194304, max frame size is 16777215
          ssl:
            cert-chain: 'file://etc/nginx/tls/tls.crt'
            private-key: 'file://etc/nginx/tls/tls.key'
```
The server shows on the log:
```
OUTBOUND SETTINGS: ack=false settings={MAX_CONCURRENT_STREAMS=2147483647, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=21552922}
```
And having a grpc client with `io.grpc:grpc-netty-shaded:1.59.1` that creates the channel like this:

```
 Grpc.newChannelBuilder(getGrpcServer(), getChannelCredentials())
          .maxInboundMetadataSize(300720)
          .maxInboundMessageSize(21552922)
          .intercept(new TicketClientRequestInterceptor())
          .defaultServiceConfig(getServiceConfig(SERVICE_CONFIG_FILENAME))
          .build();
```

where service config is

```
{
  "loadBalancingConfig": [ { "round_robin": {} } ],
  "healthCheckConfig": {
    "serviceName": ""
  },
  "methodConfig": [
    {
      "name": [{}],
      "timeout": "300s",
      "waitForReady": true,
      "maxResponseMessageBytes": 21852922,
      "maxRequestMessageBytes": 21852922
    }
  ]
}
```

The grpc server sends a big header in `grpc-status-details-bin` and that makes the problem on the grpc client that throws the error:

`Http2Exception Frame length: 14552922 exceeds maximum: 16384`

So am I missing any extra configuration to fit this use case of having a header of ~150-200Kb?
I have looked for a way to increase the max frame size of http2 settings but I don't see how in grpc-java.
I have seen this not merged PR: https://github.com/grpc/grpc-java/pull/7029/files
There is also the grpc args (https://grpc.github.io/grpc/core/group__grpc__arg__keys.html#ga2ef6e079e5d61b34ce236f50fd38fc83) but I don't see how to inject it in the client.

**Comment by ejona86** [comment] 2024-01-17 17:25
> Http2Exception Frame length: 14552922 exceeds maximum: 16384

This sounds like a bug in micronaut-grpc. IIRC, they are a separate implementation, not using grpc-java.

The server is able to send larger headers, but it has to split them at 16 KB (or a larger limit the receiver permits) into HEADERS and multiple CONTINUATIONS. Seems the server is broken in this regard.

Even if the client supported changing the maximum frame size, changing it in this situation would just be a workaround for a broken server. The server needs fixing.

**Comment by njimenezotto** [comment] 2024-01-18 11:01
I created the grpc server and client reproducing the issue.

https://github.com/noeliajimenezg/errorHeader/tree/master

The frame size issue only shows up when using TLS. 
In that case, changing the inbound metadata/message size changes nothing even if I see my values in the NettyServerBuilder (inspecting on debug grpcEmbeddedServer).
In plaintext, I have tuned a size value to reproduce that those values are well assigned by having the response in one case (sendOk sends a shorter response than sendWithError). 

That make me think that Micronaut is setting the size values in a correct way.

**Comment by ejona86** [comment] 2024-01-19 16:15
If using a Netty server, then that would be a grpc-java problem. It seems this is fixed by https://github.com/netty/netty/pull/13786 (see the linked issue https://github.com/line/armeria/issues/5385 ). Unfortunately, I expect you can't test with the newer Netty, because of https://github.com/grpc/grpc-java/issues/10837

**Comment by njimenezotto** [comment] 2024-01-19 22:01
You're totally right, armeria had the same issue.
Very glad the PR is already merged 😄

**Comment by larry-safran** [comment] 2024-01-22 20:18
Great to hear that the issue is fixed.

**Closed by larry-safran** 2024-01-22 20:18 UTC
Labels: question
