### ISSUE TITLE
Question regarding the behavior of ServerInterceptor.interceptCall

### ISSUE THREAD

**Issue by daniellin215** [grpc/grpc-java#6836] opened 2020-03-16 22:04 UTC
Hi I am trying to figure out why my two interceptors are bouncing back and forth repeatedly. I have a RpcServiceModule that provides an ExtendedServerServiceDefinition:
`ExtendedServerServiceDefinition providePortalService(
            PortalServiceRpc portalServiceRpc,
            UserStatusInterceptor userStatusInterceptor,
            RequestValidationInterceptorFactory requestValidationInterceptorFactory,
            ClientStatusInterceptor clientStatusInterceptor) {
        return new ExtendedServerServiceDefinition(
                portalServiceRpc.bindService(),
                List.of(
                        clientStatusInterceptor,
                        userStatusInterceptor));
    }`

After stepping through the code, I saw that the userStatusInterceptor always gets called first, meaning that the interceptors in the list are called from the last to first? 

Secondly, in my Interceptor's implementation, I only override `interceptCall`, which checks the status and throws if the status is not proper. Each interceptor`return Contexts.interceptCall(current(), call, headers, next)`, but it seems like the calls are bouncing back and forth even though to my understanding it should just go from one interceptor then on to the next and finish if all is good right? Please let me know if I am overriding the correct method or if I should be overriding `interceptForward` instead. Thank you!

**Comment by voidzcy** [comment] 2020-03-16 23:46
I do not quite understand your implementation based on your information above. But here are a couple of general answers regarding `ServerInterceptor`:

> After stepping through the code, I saw that the userStatusInterceptor always gets called first, meaning that the interceptors in the list are called from the last to first?

If you added your `ServerInterceptor`s via `ServerBuilder#intercept(...)` API. As its [javadoc](https://grpc.github.io/grpc-java/javadoc/io/grpc/ServerBuilder.html#intercept-io.grpc.ServerInterceptor-) mentions, "interceptors run in the reverse order in which they are added". That is, the last added `ServerInterceptor`'s `interceptCall(...)` will be invoked first. Another option is to intercept `ServerServiceDefinition` yourself with provided utility methods in [`ServerInterceptors`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ServerInterceptors.html). Read its javadoc and choose the right method to use.


> Secondly, in my Interceptor's implementation, I only override interceptCall, which checks the status and throws if the status is not proper. Each interceptorreturn Contexts.interceptCall(current(), call, headers, next), but it seems like the calls are bouncing back and forth even though to my understanding it should just go from one interceptor then on to the next and finish if all is good right?

You should not need to use `Context.interceptCall(...)` without augmenting the `Context` that the server call will be running in. Instead, you should just return `next.startCall(...)` with the wrapped `ServerCall` instance.

**Comment by daniellin215** [comment] 2020-03-17 00:55
Hey @voidzcy , thanks for the answer! I see, I was using an internal class we have that extends the `ServerServiceDefinition` but the `intercept` documentation answered my first problem. Regarding the second, the `UserStatusInterceptor` constructs returns `Context.interceptCall()` because it adds data to the metadata. Then, the `ClientStatusInterceptor` does not augment the context but will read from the existing context and uses the metadata set beforehand. That means the `UserStatusInterceptor` should return `Context.interceptCall()` and the later interceptor should return `next.startCall`  instead? Usually, after `next.startCall()`, in the returned `ServerCall.Listener`, do applications usually call methods such as `onMessage` to check/modify the incoming protobuf request messages?

**Comment by voidzcy** [comment] 2020-03-17 01:23
> the `UserStatusInterceptor` constructs returns `Context.interceptCall()` because it adds data to the metadata.
> Then, the ClientStatusInterceptor does not augment the context but will read from the existing context and uses the metadata set beforehand.

I am assuming "adds data to the __metadata__" is adding data to `Context`, not the headers (which is [`Metadata`](https://grpc.github.io/grpc-java/javadoc/io/grpc/Metadata.html)). Then your implementation sounds right.

Btw, the point in my previous answer is that `Contexts.interceptCall(...)` seems not necessary if you are not augmenting the `Context`, but it does [call `next.startCall(...)` internally](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/Contexts.java#L52). So behavior-wise, it should be the same, just unnecessary.

> Usually, after `next.startCall()`, in the returned `ServerCall.Listener`, do applications usually call methods such as `onMessage` to check/modify the incoming protobuf request messages?

Yes, that's how this API is used. Our [Binary Logging](https://github.com/grpc/grpc-java/blob/58e6ad71cc5fcdfab5d523049e925e2f5349aa8b/services/src/main/java/io/grpc/services/BinlogHelper.java#L425-L434) records the incoming message at `ServerCall.Listener`.


Regarding your observation of interceptors bouncing back and forth. I suspect some interceptor implementation wraps the wrong `ServerCall` instance or invoking the wrong `ServerHandler` instance. The overridden method `ServerInterceptor#interceptCall(ServerCall<ReqT, RespT> call, Metadata headers, ServerCallHandler<ReqT, RespT> next)` should invoke this `next`'s `startCall(...)` with a `ServerCall` wrapping this `call`. You might want to double check if one interceptor invokes another interceptor's  `ServerHandler`.

**Comment by voidzcy** [comment] 2020-03-27 00:52
Closing. If the problem is unresolved, please let us know and we can reopen.

**Closed by voidzcy** 2020-03-27 00:52 UTC
Labels: question
