### ISSUE TITLE
Add getPort() or similar to ServerImpl

### ISSUE THREAD

**Issue by buchgr** [grpc/grpc-java#72] opened 2015-02-11 20:28 UTC
I noticed that there doesn't seem to be a way to programatically retrieve a way to get the port a `ServerImpl` is listening on. Could we add a method that provides this information?

I would argue it's useful for when one wants to bind to port `0` i.e.

```java
ServerImpl server = NettyServerBuilder.build();
server.start()

System.out.println("Server listening on port " + server.getPort());
```

**Comment by stepancheg** [comment] 2016-02-14 22:50
Any news on the issue? It is super-important for unit-tests. When running unit-tests you need to bind on random port, because otherwize tests occasionally fail giving headaches to developers.

AFAIU, this feature can be implemented easily, it just needs to be decided what API should look like.

I'd prefer `ServerImpl` to have `getPort()` function that returns `0` if server is not listening on `IP`.

**Comment by ejona86** [comment] 2016-02-16 17:18
The problem is that not all transports will have a port. The InProcess transport, the Netty-LocalChannel transport, a Unix Domain Socket transport (doesn't exist today, but easily could), and a shared memory transport (also doesn't exist) don't have a port but could use a similar feature. In addition, even normal-Netty could need to provide more than just a port, since it could listen only on particular interfaces.

That still leaves me thinking exposing a `SocketAddress` on `Server` may be a pretty reasonable way to go (but I'm also aware of cases that could break down). We should probably just go with `SocketAddress`, since it is true this has lingered enough.

@stepancheg, note that we do have a workaround in the form of [TestUtils.pickUnusedPort()](https://github.com/grpc/grpc-java/blob/master/testing/src/main/java/io/grpc/testing/TestUtils.java#L133). I will try to delete the method though once this issue is fixed.

**Comment by ejona86** [comment] 2016-02-16 17:22
We could maybe _also_ have a `getPort()` convenience method that gets the `SocketAddress` casts and gets the port, throwing some exception (`IllegalStateException`?) or maybe returning `-1` if not using ip. I'm not sure how well `0` will work out, since it is a valid argument to `InetSocketAddress` constructor.

**Comment by carl-mastrangelo** [comment] 2016-04-13 20:56
I am marking this as closed, even though there may be more followup work for exposing the SocketAddress.

**Closed by carl-mastrangelo** 2016-04-13 20:56 UTC
Labels: enhancement
