### ISSUE TITLE
Creating a channel with a tls address cause NameResolver issue on Android

### ISSUE THREAD

**Issue by holysheep** [grpc/grpc-java#3319] opened 2017-08-07 17:02 UTC
### What version of gRPC are you using?
1.5.0

### What JVM are you using (`java -version`)?

java version "1.8.0_144"

I try to establish connection to tls address (https://srv-1.app.somehost.im or this one https://geo.app.im:9000) with
``` OkHttpChannelBuilder.forTarget(address).usePlaintext(true) ```

 but NameResolver cannot recognize such address. I tried the same with localhost, where NameResolver is not used and it works good. Proguard is off.

```
 Caused by: java.lang.IllegalArgumentException: cannot find a NameResolver for https://geo.app.im:9000
                                                                   at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:449)
                                                                   at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:378)
                                                                   at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:331)
                                                                   at im.app.location.grpc.ApiClient.<init>(ApiClient.kt:35)
```

**Comment by holysheep** [comment] 2017-08-08 19:11
I found out that NameResolverFactory takes only DnsNameResolverProvider in case, if I use android:

```
 @VisibleForTesting
  static List<NameResolverProvider> load(ClassLoader classLoader) {
    Iterable<NameResolverProvider> candidates;
    if (isAndroid()) {
      candidates = getCandidatesViaHardCoded(classLoader);
    } else {
      candidates = getCandidatesViaServiceLoader(classLoader);
    }
    List<NameResolverProvider> list = new ArrayList<NameResolverProvider>();
    for (NameResolverProvider current : candidates) {
      if (!current.isAvailable()) {
        continue;
      }
      list.add(current);
    }
    // Sort descending based on priority.
    Collections.sort(list, Collections.reverseOrder(new Comparator<NameResolverProvider>() {
      @Override
      public int compare(NameResolverProvider f1, NameResolverProvider f2) {
        return f1.priority() - f2.priority();
      }
    }));
    return Collections.unmodifiableList(list);
  }
```
Is it the right way?

```
 @VisibleForTesting
  public static Iterable<NameResolverProvider> getCandidatesViaHardCoded(ClassLoader classLoader) {
    List<NameResolverProvider> list = new ArrayList<NameResolverProvider>();
    try {
      list.add(create(
          Class.forName("io.grpc.internal.DnsNameResolverProvider", true, classLoader)));
    } catch (ClassNotFoundException ex) {
      // ignore
    }
    return list;
  }```

**Comment by ericgribkoff** [comment] 2017-08-08 19:13
Are you providing a custom name resolver factory to the channel builder?

**Comment by holysheep** [comment] 2017-08-08 19:16
@ericgribkoff I don't use any. But for now I implemented my own NameResolverFactory and it works. But i'm not sure, that default should be hardcoded as it is.

**Comment by ericgribkoff** [comment] 2017-08-08 22:43
I'm not familiar enough with URI schemes to know if we intentionally are not resolving https or not, but that's the current behavior. For now, just dropping the https prefix from your URI is the intended usage pattern for this and will work just fine - e.g., use `OkHttpChannelBuilder.forAddress("srv-1.app.somehost.com", 443)` (you probably don't want to invoke `usePlaintext(true)` for a secure connection).

**Comment by ericgribkoff** [comment] 2017-08-08 22:59
This is intended behavior; including "https" as the URI scheme means you need to have provided a NameResolverFactory for this scheme. With the scheme specified as "dns" (or omitted), we will use the built-in name resolver on Android.

**Closed by ericgribkoff** 2017-08-08 22:59 UTC
