### ISSUE TITLE
why the non-shaded netty  has no UnixChannelOption

### ISSUE THREAD

**Issue by fogan** [grpc/grpc-java#7850] opened 2021-01-28 03:01 UTC
why the non-shaded netty  has no UnixChannelOption

**Comment by dapengzhang0** [comment] 2021-01-28 05:07
Can you show the error/stack trace you have seen?

**Comment by fogan** [comment] 2021-01-28 08:25
![image](https://user-images.githubusercontent.com/6187904/106109889-00638980-6185-11eb-8a06-c5f8fc4a3001.png)
why  is shaded lib different with  no-shaded lib?for example, the no-shaded has no UnixChannelOption  class

**Comment by dapengzhang0** [comment] 2021-01-28 23:11
`UnixChannelOption`  is in netty's library `io.netty:netty-transport-native-unix-common` which grpc-netty does not depend on. If you want to use epoll, you need add dependency `io.netty:netty-transport-native-epoll` to your project.

On the other hand, grpc-netty-shaded depends on `io.netty:netty-transport-native-epoll` and `io.netty:netty-tcnative-boringssl-static`, because they also need to be shaded.

**Comment by dapengzhang0** [comment] 2021-02-08 21:40
Closing as this is expected behavior. Feel free to make more comments and we can reopen it.

**Closed by dapengzhang0** 2021-02-08 21:40 UTC
Labels: question
