### ISSUE TITLE
How many clients can supported to a single Server? Something goes wrong in my stress testing.

### ISSUE THREAD

**Issue by shiyiyue1102** [grpc/grpc-java#8025] opened 2021-03-29 03:57 UTC
Grpc version: 1.24.0    cpu&memory ：8C16G

Each Client   build a ManagedChannel and create a newFutureStub & biStreamStub on this channel.

When my clients count is below about 23K , everything  goes well， cpu is 1， load is 0.5 
But when I add more clients , server  does not  accept more clients, and the load rise to 5 ，cpu rise to 15%。
below 23K
![image](https://user-images.githubusercontent.com/20452676/112785910-aa796800-9087-11eb-95cf-94ea3e5b1d1a.png)
above 23K
![image](https://user-images.githubusercontent.com/20452676/112785951-c4b34600-9087-11eb-938d-28dfeabd844c.png)

According to log , I found many abnormal log of ServerTransportFilter.
transportTerminated invoked  8730663 times  and transportReady invoked 8746526 times.
![image](https://user-images.githubusercontent.com/20452676/112784758-07275380-9085-11eb-818e-82dc29c99ac6.png)

And the time bettween a connection ready &terminated is very close.
![image](https://user-images.githubusercontent.com/20452676/112784967-7b61f700-9085-11eb-8302-984bba1ce7ea.png)
 
It seems that the load is cost at connection build & close.

Could anyone give some instructions? It bothers me for a long time.
Thank you very much.

**Comment by ejona86** [comment] 2021-03-29 17:09
grpc-java 1.24.0 is 18 months old. We can't provide detailed support for versions that old.

I'd expect the problem is os-level. In particular, I'd suggest checking your process fd limit (`ulimit -n`). The other main option is your server is GC-thrashing; you'd want to check your heap size and see how close it is to the max heap size.

**Comment by dapengzhang0** [comment] 2021-04-06 16:56
Seems the original question was answered, so closing. We can reopen one new comment or followup questions.

**Closed by dapengzhang0** 2021-04-06 16:56 UTC
Labels: question
