### ISSUE TITLE
server performance issues

### ISSUE THREAD

**Issue by xiaoshuang-lu** [grpc/grpc-java#3826] opened 2017-12-04 07:35 UTC
Hi grpc-java guys, I have wrote some programs to do the performance testing for grpc-java. The service is very simple, just echo the strings (about 400 bytes per request) received from clients. (Actually, I disabled servers' log.) Appears that it's is difficult for me to archive high requests-per-second and low response-time.

requests-per-second: about 220k (expected: 1000MB/400B)
reponse-time: p99 25ms, p999 33ms (expected: p99 below 4ms)

My environment and configurations are listed as follows.

Environment: 48 cores/128GB memory/10000Mbps net/CentOS Linux release 7.2.1511
gRPC Version: 1.8.0
JVM options: JDK 1.7.80 -Xms4g -Xmx8g
bossGroup: 4 threads
workerGroup: 160 threads
executor: ThreadPoolExecutor(64, 64, 1000 * 60 * 10, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<Runnable>(65536))

[threaddump.txt](https://github.com/grpc/grpc-java/files/1526044/threaddump.txt)

According to the thread dump, many worker threads stick to SerializingExecutor.

**Comment by anhldbk** [comment] 2017-12-04 08:11
@xiaoshuang-lu would you mind sharing the code to construct your gRPC server? The following is mine and it works well:

```java
        Executor executor = Utils.getDefaultExecutor(threadNum);
        bossEventGroup = new EpollEventLoopGroup();
        workerEventGroup = new EpollEventLoopGroup();
        server = NettyServerBuilder.forPort(port)
                .addService(
                        ServerInterceptors.intercept(
                                new Service(backendFutureStub),
                                new AuthInterceptor()
                        )
                )
                .bossEventLoopGroup(bossEventGroup)
                .workerEventLoopGroup(workerEventGroup)
                .channelType(EpollServerSocketChannel.class)
                .executor(executor)
                .build();
```

**Comment by xiaoshuang-lu** [comment] 2017-12-04 08:14
```
        Class<? extends ServerChannel> channelClass;
        if (RuntimeUtils.isLinux() && this.config.getLeverageEPoll()) {
            this.bossGroup =
                new EpollEventLoopGroup(
                    this.config.getAcceptorThreadNumber(),
                    new AtomThreadFactory("ServerAcceptor"));
            this.workerGroup =
                new EpollEventLoopGroup(
                    this.config.getWorkerThreadNumber(),
                    new AtomThreadFactory("ServerWorker"));

            channelClass = EpollServerSocketChannel.class;
        } else {
            this.bossGroup =
                new NioEventLoopGroup(
                    this.config.getAcceptorThreadNumber(),
                    new AtomThreadFactory("ServerAcceptor"));
            this.workerGroup =
                new NioEventLoopGroup(
                    this.config.getWorkerThreadNumber(),
                    new AtomThreadFactory("ServerWorker"));

            channelClass = NioServerSocketChannel.class;
        }

        if (this.config.getBusinessLogicThreadType() == BusinessLogicThreadType.DEDICATED) {
            ThreadPoolExecutor threadPoolExecutor =
                new ThreadPoolExecutor(
                    this.config.getThreadPoolCoreSize(),
                    this.config.getThreadPoolMaxSize(),
                    this.config.getThreadPoolKeepAliveTime(),
                    TimeUnit.MILLISECONDS,
                    new LinkedBlockingQueue<Runnable>(this.config.getThreadPoolQueueSize()),
                    new AtomThreadFactory("BusinessLogicThread"));

            threadPoolExecutor.allowCoreThreadTimeOut(this.config.getThreadPoolAllowCoreThreadTimeout());

            threadPoolExecutor.prestartAllCoreThreads();

            if (this.config.getMetricEnabled() && this.metricRegistry != null) {
                MetricUtils.prepareThreadPoolExecutorMetricItems(this.metricRegistry, threadPoolExecutor);
            }

            this.executorService = threadPoolExecutor;
        }

        this.serverBuilder = NettyServerBuilder.forPort(this.compositeConfig.getInteger(ServerConfigKeys.port));

        NettyServerBuilder nettyServerBuilder = (NettyServerBuilder)(this.serverBuilder);

        nettyServerBuilder.bossEventLoopGroup(this.bossGroup);
        nettyServerBuilder.workerEventLoopGroup(this.workerGroup);
        nettyServerBuilder.channelType(channelClass);
        nettyServerBuilder.executor(this.executorService);
        nettyServerBuilder.flowControlWindow(this.config.getHttp2SettingsInitialWindowSize());
        nettyServerBuilder.maxConcurrentCallsPerConnection(this.config.getHttp2SettingsMaxConcurrentStreams());
        nettyServerBuilder.maxHeaderListSize(this.config.getHttp2SettingsMaxHeaderListSize());
        nettyServerBuilder.keepAliveTime(this.config.getPingInterval(), TimeUnit.MILLISECONDS);
        nettyServerBuilder.keepAliveTimeout(this.config.getPingTimeout(), TimeUnit.MILLISECONDS);
        if (this.config.getTlsEnabled()) {
            //nettyServerBuilder.sslContext(this.sslContext);
        }

        for (int i = 0; i < this.serviceDefinitionList.size(); ++ i) {
            nettyServerBuilder.addService(
                (BindableService)(this.serviceDefinitionList.get(i).getServiceImpl()));
        }
        MetricsServerTransportFilter metricsServerTransportFilter = new MetricsServerTransportFilter(this.metricRegistry);

        this.serverBuilder.addTransportFilter(metricsServerTransportFilter);

        MetricsServerStreamTracerFactory metricsServerStreamTracerFactory = new MetricsServerStreamTracerFactory();

        metricsServerStreamTracerFactory.setStopwatchSupplier(GrpcUtil.STOPWATCH_SUPPLIER);
        metricsServerStreamTracerFactory.setSlowCallTimeThreshold(this.config.getSlowCallTimeThreshold());
        metricsServerStreamTracerFactory.setMetricRegistry(this.metricRegistry);

        this.serverBuilder.addStreamTracerFactory(metricsServerStreamTracerFactory);

        for (ServerTransportFilter transportFilter : this.transportFilterList) {
            this.serverBuilder.addTransportFilter(transportFilter);
        }

        for (ServerInterceptor interceptor : this.interceptorList) {
            this.serverBuilder.intercept(interceptor);
        }

        for (ServerStreamTracer.Factory streamTracerFactory : this.streamTracerFactoryList) {
            this.serverBuilder.addStreamTracerFactory(streamTracerFactory);
        }
```

**Comment by carl-mastrangelo** [comment] 2017-12-04 22:16
@xiaoshuang-lu Can you try using ForkJoinPool instead of ThreadPoolExecutor?  It's what we use for gRPC benchmarks because it has better behavior under thread contention.

**Comment by carl-mastrangelo** [comment] 2017-12-05 01:56
@xiaoshuang-lu I think they are created as needed.  They don't go above the desired parallelism unless you use ManagedBlocker. (this is rare).

**Comment by xiaoshuang-lu** [comment] 2017-12-05 08:50
Thread dump indicates that most netty workers are in SerializingExecutor.execute().

**Comment by carl-mastrangelo** [comment] 2017-12-05 18:25
@xiaoshuang-lu that means they are running your application code.  What is the QPS you get?

**Comment by xiaoshuang-lu** [comment] 2017-12-06 01:21
> requests-per-second: about 220k (expected: 1000MB/400B)
> reponse-time: p99 25ms, p999 33ms (expected: p99 below 4ms)
> 
> My environment and configurations are listed as follows.
> 
> Environment: 48 cores/128GB memory/10000Mbps net/CentOS Linux release 7.2.1511
> gRPC Version: 1.8.0
> JVM options: JDK 1.7.80 -Xms4g -Xmx8g
> bossGroup: 4 threads
> workerGroup: 160 threads
> executor: ThreadPoolExecutor(64, 64, 1000 * 60 * 10, TimeUnit.MILLISECONDS, new LinkedBlockingQueue(65536))

**Comment by carl-mastrangelo** [comment] 2017-12-06 01:35
From the output of that text, it looks like you didn't use ForkJoinPool.

**Comment by xiaoshuang-lu** [comment] 2017-12-06 02:02
Yes.

Yesterday I have tried ForkJoinPool instead of ThreadPoolExecutor. Unfortunately JVM crashed. I will investigate this problem. Thread dump hints that bottlenecks are in SerializingExecutor.

**Comment by xiaoshuang-lu** [comment] 2017-12-06 02:15
Hi @carl-mastrangelo, are there some performance testing reports the users can refer to?

**Comment by carl-mastrangelo** [comment] 2017-12-06 18:23
We have a live dashboard of performance by language:  
https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5652536396611584

You can also look at our benchmarks/ directory to see the code that performs the benchmarks

We don't have any tutorials yet on how to optimize.

**Comment by xiaoshuang-lu** [comment] 2017-12-07 08:48
Thank you, @carl-mastrangelo. I will try the programs in benchmarks directory.

**Comment by xiaoshuang-lu** [comment] 2017-12-07 11:58
QPS in [Unary secure throughput server CPU (32 core client to 32 core server)](https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5652536396611584) is about 850k. I ran the benchmarks (qps_server and qps_client) in my environment. I just cannot achieve QPS as dashboard shows. Here are my commands. Did I make something wrong?

```
nohup sh bin/qps_server --address=10.110.60.40:9999 --transport=netty_nio > nohup.log 2>&1 &
nohup sh bin/qps_client --address=10.110.60.40:9999 --channels=10 --outstanding_rpcs=100 --client_payload=256 --server_payload=256 --duration=100000000 > nohup.log 2>&1 &
```

PS: I used 40 threads as netty workers.

**Comment by carl-mastrangelo** [comment] 2017-12-07 18:01
And what QPS did you get with that configuration?  If you could include information like the load averages, or strace output, or running `perf record` when running that would be helpful.  40 Netty threads is a lot.  You should be able to get by with a lot fewer.

Alternatively, if you could post your code it would reduce the number of roundtrips on this issue.

**Comment by xiaoshuang-lu** [comment] 2017-12-08 12:11
I will upload my code next week. Thanks.

**Comment by xiaoshuang-lu** [comment] 2017-12-14 11:07
@carl-mastrangelo Here is my code package. :-)

[grpc-benchmark.zip](https://github.com/grpc/grpc-java/files/1558928/grpc-benchmark.zip)

**Comment by carl-mastrangelo** [comment] 2017-12-14 18:59
So as I mentioned up above, you need to replace `ThreadPoolExecutor` with `ForkJoinPool in both `GRPCTestServiceServer` and `GRPCTestServiceClient`.    You can even use the same pool on both.     Consider using `ForkJoinPool.commonPool()`.    

Second, you have too many netty threads.   In normal, non-grpc netty, worker threads do most of the work.  In gRPC, we move work off the net threads as soon as possible.   The net effect to you is that you really only need ~1-2 workers in your Event Loop.

**Comment by xiaoshuang-lu** [comment] 2017-12-21 05:52
It does not make any difference.

**Comment by carl-mastrangelo** [comment] 2018-01-03 19:39
If you can give a reproducible example I can look into this further.  I will need the exact command you used to run and the specs of the hardware you ran on.

**Comment by xiaoshuang-lu** [comment] 2018-01-04 02:05
Hardware specs
> Environment: 48 cores/128GB memory/10000Mbps net/CentOS Linux release 7.2.1511
> gRPC Version: 1.8.0
> JVM options: JDK 1.7.80 -Xms4g -Xmx8g

Server Command
````
nohup java -Xms4g -Xmx8g -Dcom.sun.management.jmxremote.host=10.1.1.1 -Dcom.sun.management.jmxremote.port=54321 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/grpc -cp grpc-benchmark-1.0.0-SNAPSHOT-jar-with-dependencies.jar:. root.GRPCTestServiceServer 9999 > nohup.log 2>&1 &
````

Client Command
````
nohup java -Xms4g -Xmx8g -Dcom.sun.management.jmxremote.host=10.1.1.2 -Dcom.sun.management.jmxremote.port=54321 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/grpc -cp grpc-benchmark-1.0.0-SNAPSHOT-jar-with-dependencies.jar:. root.GRPCTestServiceClient 10.1.1.1 9999 50 10 > nohup.log 2>&1 &
````

**Comment by carl-mastrangelo** [comment] 2018-01-04 19:59
@xiaoshuang-lu 

I ran the code you provided in grpc-benchmark.  I made the following changes:

* Used `ForkJoinPool.commonPool()` instead of `ThreadPoolExecutor`.  
* Reduced the NioEventLoopGroup size to 1.

Some things are kind of odd:

* In the Client, the number of threads is wrong.  You should make 1 _Channel_, and give it an executor with the correct number of threads.  As is, you are making many 1 Channel per "Thread", which in turn creates a threadpool.  This results in threadCount^2 number of threads!
* You are making an event loop group per channel.  This is extremely inefficient.  Netty works best when there is a lot of network activity, because it polls for work.   If it doesn't find any work, it goes to sleep waiting for more work to arrive.  Each time it goes to sleep and wakes, it wastes a lot of time.  Since you are making a group per channel, you silo the work and ensure there is never more work to do.  
* The code as provided never finishes, and doesn't print out results.  I can't tell how fast it is going because it doesn't tell me.  The tracers look like they record info, but they don't seem to ever be read.

**Comment by xiaoshuang-lu** [comment] 2018-01-05 02:52
@carl-mastrangelo Thank you very much. I appreciate your reply.

> - In the Client, the number of threads is wrong. You should make 1 Channel, and give it an executor with the correct number of threads. As is, you are making many 1 Channel per "Thread", which in turn creates a threadpool. This results in threadCount^2 number of threads!

Each client has 4 threads, a thread pool with 2 threads and a event loop group with 2 threads. So the total thread number should be clientNumber * 4.

> - You are making an event loop group per channel. This is extremely inefficient. Netty works best when there is a lot of network activity, because it polls for work. If it doesn't find any work, it goes to sleep waiting for more work to arrive. Each time it goes to sleep and wakes, it wastes a lot of time. Since you are making a group per channel, you silo the work and ensure there is never more work to do.

I limited the event loop group thread number per client to 2. As mentioned above this may be not a problem.

> - The code as provided never finishes, and doesn't print out results. I can't tell how fast it is going because it doesn't tell me. The tracers look like they record info, but they don't seem to ever be read.

I leveraged [dropwizard metrics](https://github.com/dropwizard/metrics) to collect statistics data. The code can be found in GRPCTestServiceServer.java line 45 and GRPCTestServiceClient.java line 90. You can add reporters (e.g. GraphiteReporter) to [MetricRegistry](http://metrics.dropwizard.io/4.0.0/getting-started.html).

Again,  thanks Carl.

**Comment by ejona86** [comment] 2018-03-08 21:52
Looks like this is resolved. Closing.

**Comment by xiaoshuang-lu** [comment] 2018-03-09 01:25
I am afraid this issue is not resolved... :(

**Comment by ejona86** [comment] 2018-04-02 21:46
@carl-mastrangelo, do you know what needs to be done here?

**Comment by carl-mastrangelo** [comment] 2018-04-09 22:56
Without more data about the actual run, I don't know what more can be done here.  @xiaoshuang-lu If you follow the instructions here: https://medium.com/netflix-techblog/java-in-flames-e763b3d32166

It can give you much more detailed data about why grpc is slow.

**Comment by xiaoshuang-lu** [comment] 2018-04-12 03:41
Hi, I think it may not be difficult to reproduce this issue if there is a [ganglia](http://metrics.dropwizard.io/3.1.0/manual/ganglia/#) server or something similar.

Add `GangliaReporters`s to GRPCTestServiceServer.java line 46 and GRPCTestServiceClient.java line 91.

**Comment by zhangkun83** [comment] 2018-10-09 17:29
@xiaoshuang-lu, did you have success on getting a repro?

**Comment by zhangkun83** [comment] 2018-10-16 16:41
Closing it due to inactivity. @xiaoshuang-lu, feel free to reopen if you have new updates.

**Closed by zhangkun83** 2018-10-16 16:41 UTC
Labels: question
