### ISSUE TITLE
Dns rr balancing does not refresh after dns change

### ISSUE THREAD

**Issue by z0mb1ek** [grpc/grpc-java#2884] opened 2017-04-09 11:59 UTC
grpc-all 1.2.0

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

Hi. I use grpc RoundRobinLoadBalancerFactory and DnsNameResolverProvider. As well I use docker swarm. When i do replica of my service, I see that dns has second entry of my service, but grpc client to this service does not see it and not balancing. I has networkaddress.cache.ttl=10 in jvm for this service and -Dsun.net.inetaddr.ttl=10. But if I kill all my instances and start it again with two nodes at the same time, then client will see 2 dns entry and rr well.

**Comment by carl-mastrangelo** [comment] 2017-04-10 23:11
cc: @zhangkun83

**Comment by zhangkun83** [comment] 2017-04-10 23:23
#2514

**Comment by ejona86** [comment] 2017-04-11 16:19
Closing as duplicate of #2514.

**Closed by ejona86** 2017-04-11 16:19 UTC
