### ISSUE TITLE
Running gRPC with Tomcat is problematic

### ISSUE THREAD

**Issue by joaoandremartins** [grpc/grpc-java#2996] opened 2017-05-11 19:28 UTC
I ran into this issue trying to use the Google Cloud PubSub API from a Spring Boot app, using Tomcat by default. The issue is explained [here](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2039).

`Jetty ALPN/NPN has not been properly configured`

A workaround is basically to use Jetty instead of Tomcat. However, ideally this should work with Tomcat too.

After reading around a bit, I tried pulling in the netty-tcnative-boringssl-static dependency, and org.eclipse.jetty.npn.npn-api since the code appears to be checking for a `org.eclipse.jetty.npn.NextProtoNego` class in the classpath, to no avail.

What can be done to make this work with Tomcat as well?

### What version of gRPC are you using?
grpc-netty 1.2.0

### What JVM are you using (`java -version`)?
1.8.0_121

**Comment by ejona86** [comment] 2017-05-12 00:39
Tomcat compatibility problems were expected to be resolved with netty-tcnative 2.0. We had trouble upgrading to the last couple of Netty releases, but it seems 4.1.11 may work out. Upgrading to 4.1.11 would allow using netty-tcnative 2.0 and thus hopefully resolve the problem you're experiencing. This is being done in #2973. This seems a duplicate of #2936 at this point, so closing. But if for some reason it's not, feel free to comment more and we can reopen.

**Closed by ejona86** 2017-05-12 00:39 UTC

**Comment by meltsufin** [comment] 2017-05-16 14:16
@joaoandremartins It looks like #2973 has been merged. Can you try again?

**Comment by joaoandremartins** [comment] 2017-05-17 13:55
Running google-cloud-pubsub version 0.17.2-alpha, still seeing the same issue.

**Comment by lukaszx0** [comment] 2017-05-19 17:12
New gRPC version which will include the fix was not released yet, and when it will be the google-cloud-pubsub will have to upgrade to it to see any changes.
