### ISSUE TITLE
Request got cancelled by RST_STREAM - race condition

### ISSUE THREAD

**Issue by chrjohn** [grpc/grpc-java#6323] opened 2019-10-23 12:01 UTC
Revised version of #6166. We actually thought that the elapsed time was a factor but it seems it is a race condition and can be observed instantly.

grpc-java 1.24.0 
Ubuntu 19.04

We implemented a service that receives a request from a gRPC client and then waits for a condition to trigger. When this condition is finally met, the gRPC server sends a message to the client and completes the connection.
In our service it can happen that a trigger is fired by a few threads concurrently since we receive updates via several input sources. This is where we sometimes run into the described problem.

When creating the reproducer it could be observed that the request is always answered and the `RST_STREAM` comes in later. However, `onComplete()` is not called.
NB: In our full-blown service (Spring Boot based) we only saw the reply in the tcp dump but not in our application. But this is probably due to the nature of a race condition.
We also see this message in the logs:

```
io.grpc.internal.ServerCallImpl internalClose WARNING: Cancelling the stream with status Status{code=INTERNAL, description=Too many responses, cause=null}
```

This is probably where the `RST_STREAM` originates from that causes our service to not get the response or have `onCompleted()` not called.
I read that `StreamObservers` are not thread-safe but I don't know how `StreamObserver` and `ServerCallImpl` are connected.
I was wondering if `ServerCallImpl` could be made thread safe in this regard. Looking at the `ServerCallImpl` source code I can see that there are several fields representing the state but only one is `volatile`.

So after all it seems we are simply using gRPC wrong. Do you think there is a chance that gRPC can behave better in such cases because we wasted quite some time finding the root cause of this issue.

We now prevented this problem by guarding the triggering by an `AtomicBoolean` that only lets the first thread pass. Another approach was to create a synchronized method in our `StreamObserver` that calls `onNext()` and subsequently `onCompleted()`.

See reproducer at https://github.com/chrjohn/grpc-reset-reproducer

**Comment by creamsoup** [comment] 2019-10-24 21:52
I was able to run the reproduce, thanks @chrjohn.

To me, it is working as intended. The trigger RPC is a unary RPC, server expect to response up to 1 message back to client. If the server responses more than 1 response is violating the contract, therefore it cancels the stream. That's the error message you are seeing. 

if you want to send only the 1st response, you can simply add `boolean` to prevent re-entrance problem in the `SynchronizedStreamObserver`.

```java
    private volatile boolean sent = false;

    @Override
    public synchronized void onNext(V v) {
        if (sent) {
            return;
        }
        sent = true;
        streamObserver.onNext(v);
    }
```

**Comment by chrjohn** [comment] 2019-10-25 08:28
Hi @creamsoup, yes, that's another way to do it. As stated we now guard the trigger by an `AtomicBoolean`. Cf. here:

https://github.com/chrjohn/grpc-reset-reproducer/blob/f2b1be5d56dd7bf9cc4630c7a66ef8128671ec41/src/main/java/com/macd/dummytrigger/DummyTriggerServer.java#L147

We **now** (i.e. a few days before we created this issue) understand that it is working as intended and that it was our fault but the problem for us was that the response is only sometimes received but mostly not received because of the `RST_STREAM` which was received before `onCompleted()` was called. Finding the root cause of the problem was pretty hard and time consuming.

So the real point is whether there could be an improvement made on gRPC side that will not exhibit the race condition in user code. But I assume this is difficult since it will involve some sort of synchronization and hence has performance implications. But since it only applies to unary calls the performance impact would maybe be negligible.

**Comment by creamsoup** [comment] 2019-10-25 21:11
yes, I saw the `AtomicBoolean` approach. This upper level approach is indeed better than handling it in the StreamObserver.

We clearly stated in the [javadoc of StreamObserver](https://github.com/grpc/grpc-java/blob/master/stub/src/main/java/io/grpc/stub/StreamObserver.java#L32) that StreamObserver is not thread safe. I hear your pain, but adding synchronization for unary call is not the right solution. Unary call by nature is not accessed by multiple threads in the application, so cost of synchronization is hard to be justified. Thus, unary call is a one use case of async streaming call. under the hood, it is treated as bidirectional single message streaming call.

Generally, unless it claims thread safety, it is safe to assume anything in java is not thread safe. We are trying to make it clear in the javadoc and in the error message. Beyond those, there isn't any better way I can think of without performance penalty. If you have any idea, please let us know.

**Comment by ejona86** [comment] 2019-10-31 17:55
Seems resolved. Closing.

**Closed by ejona86** 2019-10-31 17:55 UTC
Labels: enhancement
