### ISSUE TITLE
Retry throttling not being respected with default service config

### ISSUE THREAD

**Issue by JoaoVitorStein** [grpc/grpc-java#11274] opened 2024-06-10 14:17 UTC
### What version of gRPC-Java are you using?
1.63

### What is your environment?
macOS 14.4.1
openjdk 17.0.1 2021-10-19 LTS 
Gradle 8.5

### What did you expect to see?
I'm setting a default service config with a retry policy and a retry throttling policy.
The retry throttling policy is not being respected and retries are always being executed.
Please check the following [serviceConfig](https://github.com/JoaoVitorStein/grpc-retry-throttling/blob/main/src/main/resources/service_config.json)

### What did you see instead?
Retries are always being executed 

### Steps to reproduce the bug
Check [this](https://github.com/JoaoVitorStein/grpc-retry-throttling/tree/main) repo, it reproduces this issue. You can check the steps to run it in the readme of that project.
This is a modified version of the retry example given in gRPC documentation, adding a retryThrottling policy to it.

As you can see, the retry throttling is being correctly configured in the defaultServiceConfig
![image](https://github.com/grpc/grpc-java/assets/46487789/b465dafe-3c72-4ab1-84f9-61caa02e52d2)

With this configuration, I would expect that after 5 failed RPCs, retries would be throttled. However, all retries are executed in this case.
![image](https://github.com/grpc/grpc-java/assets/46487789/ebab55af-df21-4d46-b085-4146403e75d1)

### Possible root cause
After some investigation, I was able to figure out that the throttling policy is only being used if it comes from the NameResolver, check [here](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L1766). This happens because `effectiveServiceConfig` and `lastServiceConfig` are equal when you have a defaultServiceConfig and NameResolver doesnt retrieve a `serviceConfig`

I guess that we need to also set the `transportProvider.throttle` when instantiating the `ManagedChannelImpl` ([here](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L610))

**Comment by JoaoVitorStein** [comment] 2024-06-10 14:24
If this is not expected, I can open the PR with the fix.

**Comment by kannanjgithub** [comment] 2024-06-12 06:41
We need to make set the lastServiceConfig to null [here](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L621) when instantiating the ManagedChannelImpl so that the service config is actually applied during the name resolution result. Can you open a PR with this fix?

**Comment by JoaoVitorStein** [comment] 2024-06-12 10:59
Sure, let me work on it.

**Comment by kannanjgithub** [comment] 2024-06-14 11:51
A correction - We should just delete [this line](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L619), so that lastService config remains EMPTY_SERVICE_CONFIG and gets assigned to the value from the NR callback.

**Comment by kannanjgithub** [comment] 2024-06-20 12:13
I think that is by design - if serviceConfigLookup is false the config from the name resolver is not used for the whole of the service config, not just the throttling config, and the default service config.

**Comment by ejona86** [comment] 2024-06-20 17:04
We do want the default service config to be fully-functional when `serviceConfigLookup=false`. Yeah, I think that means the only easy approach is to initialize throttle in the constructor.

**Comment by JoaoVitorStein** [comment] 2024-06-25 14:43
@ejona86 updated the PR with this change, however my CLA manager is currently OOO. I think I will get his approval next week.

**Comment by ejona86** [comment] 2024-06-25 14:45
@JoaoVitorStein, okay, that's fine. When you are able to complete the CLA, make a comment on the PR. Even though the CLA will turn green, it modifies the existing comment so there's no email notification to us.

**Comment by ejona86** [comment] 2024-07-03 15:20
Fixed by #11290

**Closed by ejona86** 2024-07-03 15:20 UTC
Labels: bug
