### ISSUE TITLE
grpc-java 1.33.0 Futures.addCallback(responseFuture, ResponseCallback) delayed for 60seconds

### ISSUE THREAD

**Issue by chowtin** [grpc/grpc-java#8217] opened 2021-05-27 16:47 UTC
This issue is in production environment.

*grpc-java futureStub* client sends request  *grpc-cpp* server. (futureStub is set `withDeadlineAfter()`)

`Futures.addCallback` is used to wait for *ResponseCallback*. (sample code part)

Intermittently (not always, not easy to reproduce), *ResponseCallback* call is delayed ~60seconds. 
From io.grpc.netty log, it seems grpc-java client received response from grpc-cpp server (15:56:38,494), but *ResponseCall* is not called immediately. (15:57:38,494 showed in the log)

client host is not in high load, threads are all alive.
is there any possible racing issue, or any magic wait for that 60 seconds, or my usage error?

===
OS:
aws EC2: Linux 4.14.193-149.317.amzn2.aarch64

4core 8G memory

Java:
build 1.8.0_271-b09

grpc-java version: 1.33.0

sample code:
```
class OrderGrpcClient {
  public OrderGrpcClient(String addr) {
    this.channel =  ManagedChannelBuilder.forTarget(address)
        .usePlaintext()
        .idleTimeout(10, TimeUnit.MINUTES)
        .build();

    this.orderFutureStub = TradingEngineGrpc
        .newFutureStub(channel);
  }

  public ListenableFuture<OrderResponse> createOrder(int id, String args, ...) {
    OrderRequest request = OrderRequest.newBuilder()
        .setArgs(args)
        ...
        .build()

        return this.orderFutureStub
        .withDeadlineAfter(timeoutMs,TimeUnit.MILLISECONDS)
        .createOrder(orderRequestBuilder.build());
  }
}
class OrderService {

  OrderGrpcClient grpClient = new OrderGrpcClient("10.xx.xx.xx:5555");

  private Executor resultExecutor =  Executors.newFixedThreadPool(worker, new ThreadFactory() {
    @Override
    public Thread newThread(Runnable r) {
        Thread t = new Thread(r, "grpc-reader");
        return t;
    }
  });

  public void createOrderFunc() {

    log.info("GRPC REQ  xxx");

    ListenableFuture<OrderResponse> resFuture = grpClient.createOrder(1, "order-id-xxx", ...);

    Futures.addCallback(resFuture, new FutureCallback<CreateOrderResponse>() {
        @Override
        public void onSuccess(@NullableDecl CreateOrderResponse res) {
            log.info("GRPC Acked  xxx");
            ...
        }

        @Override
        public void onFailure(Throwable t) {
            log.info("GRPC Error xxx" );
            ...
        }
    }, resultExecutor);
  }
}


```

LOG: 
```
 2021-05-27 15:56:38,493 INFO c.p.g.c.OrderService[boundedElastic-1467] GRPC REQ xxxxxx
 2021-05-27 15:56:38,493 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111 - R:/10.xx.xx.xx:5555] OUTBOUND HEADERS: streamId=611481                           headers=GrpcHttp2OutboundHeaders[:authority: 10.xx.xx.xx:5555, :path: /xx.cppservice/CreateOrder, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.33.0, grpc-accept-encoding: gzip, grpc-timeout: 59999990u] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
 2021-05-27 15:56:38,493 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111 - R:/10.xx.xx.xx:5555] OUTBOUND DATA: streamId=611481 padding=0 endStream=true     length=42 bytes=00000000250a0c100548e5933050d2828ab21d301f3802400248c6cb1450c80160027801880103900101
 2021-05-27 15:56:38,494 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111  - R:/10.xx.xx.xx:5555] INBOUND HEADERS: streamId=611481                            headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, grpc-accept-encoding: identity,deflate,gzip, accept-encoding: identity,gzip] padding=0 endStream=false
 2021-05-27 15:56:38,494 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111  - R:/10.xx.xx.xx:5555] INBOUND DATA: streamId=611481 padding=0 endStream=false     length=173 bytes=00000000a81a084e4f5f4552524f52229b0110a7e9d11a1a0c08b682bf850610b0c6b0e90120e5933028d2828ab21d301f380240014801522463653466666430...
 2021-05-27 15:56:38,494 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111  - R:/10.xx.xx.xx:5555] OUTBOUND PING: ack=false bytes=1234
 2021-05-27 15:56:38,494 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111  - R:/10.xx.xx.xx:5555] INBOUND HEADERS: streamId=611481                            headers=GrpcHttp2ResponseHeaders[grpc-status: 0] padding=0 endStream=true
 2021-05-27 15:56:38,494 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111 - R:/10.xx.xx.xx:5555] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=42    2021-05-27 15:56:38,495 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.88.20.46:42294 - R:/10.88.20.90:9081] INBOUND PING: ack=true bytes=1234
 
 ....
 2021-05-27 15:57:38,494 INFO c.p.g.c.OrderService [gRPC-Reader-2] GRPC Acked xxxx
```

**Comment by YifeiZhuang** [comment] 2021-05-27 22:05
Sorry I don't think I have enough information to tell what is the problem here.
> From io.grpc.netty log, it seems grpc-java client received response from grpc-cpp server (15:56:38,494), but ResponseCall is not called immediately. (15:57:38,494 showed in the log)

Even if the client received the response from netty layer, it is still far from delivering the completing the RPC. The netty response is still executing at network thread, it will callback to the application thread in [client call](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ClientCallImpl.java#L747) to finish delivering the results.
Then after response is delivered, it is not clear the resultExecutor has enough worker to schedule properly.  We previously saw similar issue that cased by this executor (https://github.com/grpc/grpc-java/issues/5286).  I encourage you to add more logs to narrow the problem down.

**Comment by chowtin** [comment] 2021-05-31 13:31
Thanks for your reply.

The chance of resultExecutor issue is very slim, because most of the delay is around 60seconds.
I'll add more logs to narrow down as you suggested.

Meanwhile, there are some reset stream logs `RST_STREAM: streamId=611481 errorCode=8` and too many PING logs.
Not sure if there is an impact on  grpc-ack latency.

```
2021-05-27 15:57:38,494 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111 - R:/10.xx.xx.xx:5555] OUTBOUND RST_STREAM: streamId=611481 errorCode=8
```

PING logs:

```
2021-05-27 16:02:22,288 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111 - R:/10.xx.xx.xx:5555] INBOUND PING: ack=true bytes=1234
2021-05-27 16:02:22,482 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111 - R:/10.xx.xx.xx:5555] OUTBOUND PING: ack=false bytes=1234
2021-05-27 16:02:22,482 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111 - R:/10.xx.xx.xx:5555] INBOUND PING: ack=true bytes=1234
2021-05-27 16:02:23,327 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111 - R:/10.xx.xx.xx:5555] OUTBOUND PING: ack=false bytes=1234
2021-05-27 16:02:23,327 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111 - R:/10.xx.xx.xx:5555] INBOUND PING: ack=true bytes=1234
2021-05-27 16:02:23,540 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111 - R:/10.xx.xx.xx:5555] OUTBOUND PING: ack=false bytes=1234
2021-05-27 16:02:23,540 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111 - R:/10.xx.xx.xx:5555] INBOUND PING: ack=true bytes=1234
2021-05-27 16:02:23,730 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111 - R:/10.xx.xx.xx:5555] OUTBOUND PING: ack=false bytes=1234
2021-05-27 16:02:23,731 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111 - R:/10.xx.xx.xx:5555] INBOUND PING: ack=true bytes=1234
2021-05-27 16:02:23,860 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111 - R:/10.xx.xx.xx:5555] OUTBOUND PING: ack=false bytes=1234
2021-05-27 16:02:23,860 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111 - R:/10.xx.xx.xx:5555] INBOUND PING: ack=true bytes=1234
2021-05-27 16:02:24,207 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111 - R:/10.xx.xx.xx:5555] OUTBOUND PING: ack=false bytes=1234
2021-05-27 16:02:24,207 DEBUG i.g.n.NettyClientHandler [grpc-nio-worker-ELG-5-1] [id: 0xabe30722, L:/10.yy.yy.yy:11111 - R:/10.xx.xx.xx:5555] INBOUND PING: ack=true bytes=1234
```

**Comment by Nilesh-Agrawal** [comment] 2021-06-01 04:41
Hi @chowtin 
Can you guide how you have collected the RST logs from netty layer.
By adding below commands in logging.properties file I am not able to get all logs.
.level=FINEST
io.level=FINEST
java.util.logging.FileHandler.level=FINEST

**Comment by YifeiZhuang** [comment] 2021-06-01 17:30
@ejona86 it looks the client exhausted the server with too many pings and thus RST_STREAM.  I suppose connection would GO_AWAY and stream closed and the call will be closed?
But how come user still see the call successfully finished after 60second?

**Comment by joe-bq** [comment] 2021-06-02 03:41
@YifeiZhuang @ejona86 
What is the normal rate of CLIENT to SERVER ping ? is ti configurable , in @chowtin case, there is no explicit setting in code or in configuration.

Does it relate to the gRPC worker thread ?  It uses fixed pool size of 5 thread as the gRPC worker thread.

**Comment by chowtin** [comment] 2021-06-02 13:37
> @ejona86 it looks the client exhausted the server with too many pings and thus RST_STREAM. I suppose connection would GO_AWAY and stream closed and the call will be closed?
> But how come user still see the call successfully finished after 60second?

From my tests, it indicates RST_STREAM relates to `withDeadlineAfter(timeout, TimeUnit)`.

In my test:
timeout = 5 millis, many RST_STREAM, errorCode = 8
timeout = 50 seconds, RST_STREAM disappeared.

**Comment by ejona86** [comment] 2021-06-02 17:50
This doesn't seem PING-related, although maybe that part of the log was not shown. The RST_STREAM is from client→server with CANCEL status code, so that is just normal cancellation (e.g., after the timeout).

I don't have an immediate explanation on what could cause this. I'd love to blame the application for something weird like this, but I don't see any evidence to support that. _Clearly_ there is a timer involved, though.

@chowtin, you said there wasn't high load. Did it seem like the connection had no activity for a minute? I'm wondering if something is getting stuck in an executor, but that would require no I/O for the 60 seconds.

I don't see any obvious hard-coded wakeup polling in either of Netty's NioEventLoop nor EpollEventLoop. Maybe there is something in the NIO code of the JDK. Grepping Netty and grpc-java doesn't show up anything suspicious for "MINUTES" or "60".

@chowtin, you don't have any fault-injection system do you? Like, there's no interceptor that delays responses? (I doubt it, as such an interceptor should probably delay the request and not the response, but this is a strange enough puzzle it seemed fair to ask.)

Maybe something in the `resultExecutor` does a `Thread.sleep(60*1000)` which blocks the notification callback.

@chowtin, it seems you can reproduce this well enough to add logging. I think we should add a ClientStreamTracer to help determine whether the problem is at a high level or low level. Try adding this interceptor and comparing the log times:

```java
  class TracerLoggerInterceptor implements ClientInterceptor {
    @Override
    public <ReqT, RespT> ClientCall<ReqT, RespT> interceptCall(
        MethodDescriptor<ReqT, RespT> method, CallOptions callOptions, Channel next) {
      callOptions = callOptions.withStreamTracerFactory(new ClientStreamTracer.Factory() {
        @Override
        public ClientStreamTracer newClientStreamTracer(
            ClientStreamTracer.StreamInfo info, Metadata headers) {
          return new ClientStreamTracer() {
            @Override public void streamClosed(Status status) {
              log.info("gRPC Stream closed");
            }
          };
        }
      });
      return next.newCall(method, callOptions);
    }
  }
```

If the stream is closed without the 60s delay, it seems likely the delay is introduced by the executor.

**Comment by chowtin** [comment] 2021-06-07 12:12
As you suggested I added `TracerLoggerInterceptor`, and check the logs if issues happen again.

==
There are too many PINGs in the logs, what is the best way to reduce PING.

**Comment by ejona86** [comment] 2021-06-07 15:26
Since you don't have keepalive enabled, the pings are probably from the bandwidth-delay product monitoring (aka "auto flow control tuning"). They ensure gRPC does enough buffering for your network. You can disable it by calling [`nettyChannelBuilder.flowControlWindow()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/netty/NettyChannelBuilder.html#flowControlWindow-int-).

**Comment by chowtin** [comment] 2021-06-08 14:40
From bottom log,  `TracerLoggerInterceptor ` printed the log at `2021-06-08 04:34:14,510`, executor printed its log at `2021-06-08 04:35:14,510`

Executor task was delayed *60 seconds* after response stream was received.

Does this indicate executor has problem? (it is not busy from my observation, event if it is busy, why it was delay 60seconds at most time.) 
or nio-loop thread is not calling executor.executor() promptly due to excessive PING, [callExecutor.execute(new StreamClosed())](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ClientCallImpl.java#L747) 

@ejona86  Thanks for your help so far, I also have several questions.

1. Can it reduce the delay by removing `bandwidth-delay product monitoring ` ping, because it can save nio-loop-thread work load?

2. Can ` nettyChannelBuilder.directExecutor()`  outperform `Futures.addCallback(future, callback, exeuctor)`?

3. What is the function of `grpc-default-executor` threads, can it be removed to reduce total threads number ?

==
In order to give a more clear picture of our prod application, key informations are listed below

1. it is a gateway application, it is I/O bounded.
2. 4c8G host
3. 70+ grpc-clients shares 2 Nio-event-loop threads 
4. in *AWS ARM CPU*, grpc-client use nio-event-loop not epoll-event-loop, the delay is 60 seconds. 
5. 40 msg per second on average, one message is about 0.5k


```
2021-06-08 04:34:14,508 INFO c.p.g.c.OrderController [boundedElastic-28] GRPC REQ xxx trace 1623126854504956
2021-06-08 04:34:14,509 DEBUG i.g.n.NettyClientHandler [Nio-Loop] [id: 0x91a61674, L:/10.xx.xx.xxx:55555 - R:/10.yy.yy.yy:88888] OUTBOUND HEADERS: streamId=633 headers=GrpcHttp2OutboundHeaders[:authority: 10.yy.yy.yy:88888, :path: /Order, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.33.0, grpc-accept-encoding: gzip, grpc-timeout: 59999986u] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
2021-06-08 04:34:14,509 DEBUG i.g.n.NettyClientHandler [Nio-Loop] [id: 0x91a61674, L:/10.xx.xx.xxx:55555 - R:/10.yy.yy.yy:88888] OUTBOUND DATA: streamId=633 padding=0 endStream=true length=69 bytes=00000000400a0c100548a195655092e2ccdf3d122430336332396632632d393361352d346263372d386432362d65356463626139393635646130c90148c21950...
2021-06-08 04:34:14,510 DEBUG i.g.n.NettyClientHandler [Nio-Loop] [id: 0x91a61674, L:/10.xx.xx.xxx:55555 - R:/10.yy.yy.yy:88888] INBOUND HEADERS: streamId=633 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, grpc-accept-encoding: identity,deflate,gzip, accept-encoding: identity,gzip] padding=0 endStream=false
2021-06-08 04:34:14,510 DEBUG i.g.n.NettyClientHandler [Nio-Loop] [id: 0x91a61674, L:/10.xx.xx.xxx:55555 - R:/10.yy.yy.yy:88888] INBOUND DATA: streamId=633 padding=0 endStream=false length=264 bytes=00000001031a084e4f5f4552524f5222f60110c8d9c0011a0c08c6e6fb850610f9b6a2f10120a195652892e2ccdf3d30c9013802400348015224303363323966...
2021-06-08 04:34:14,510 DEBUG i.g.n.NettyClientHandler [Nio-Loop] [id: 0x91a61674, L:/10.xx.xx.xxx:55555 - R:/10.yy.yy.yy:88888] OUTBOUND PING: ack=false bytes=1234
2021-06-08 04:34:14,510 DEBUG i.g.n.NettyClientHandler [Nio-Loop] [id: 0x91a61674, L:/10.xx.xx.xxx:55555 - R:/10.yy.yy.yy:88888] INBOUND HEADERS: streamId=633 headers=GrpcHttp2ResponseHeaders[grpc-status: 0] padding=0 endStream=true
2021-06-08 04:34:14,510 INFO c.p.g.f.h.TradingEngineGrpcClient [Nio-Loop] GRPC STREAM closed 10.yy.yy.yy:88888
2021-06-08 04:34:14,510 DEBUG i.g.n.NettyClientHandler [Nio-Loop] [id: 0x91a61674, L:/10.xx.xx.xxx:55555 - R:/10.yy.yy.yy:88888] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=69
2021-06-08 04:34:14,510 DEBUG i.g.n.NettyClientHandler [Nio-Loop] [id: 0x91a61674, L:/10.xx.xx.xxx:55555 - R:/10.yy.yy.yy:88888] INBOUND PING: ack=false bytes=74
2021-06-08 04:34:14,510 DEBUG i.g.n.NettyClientHandler [Nio-Loop] [id: 0x91a61674, L:/10.xx.xx.xxx:55555 - R:/10.yy.yy.yy:88888] OUTBOUND PING: ack=true bytes=74
2021-06-08 04:34:14,510 DEBUG i.g.n.NettyClientHandler [Nio-Loop] [id: 0x91a61674, L:/10.xx.xx.xxx:55555 - R:/10.yy.yy.yy:88888] INBOUND PING: ack=true bytes=1234
2021-06-08 04:35:14,510 INFO c.p.g.c.OrderController [ForkJoinPool-1-worker-0] GRPC Acked xxxx trace 1623126854504956

```

**Comment by ejona86** [comment] 2021-06-08 15:02
Because there is a WINDOW_UPDATE _immediately_ after "GRPC STREAM closed", double-guarantees there is no problem on the netty event loop.

I'd suggest you continue adding debug points through the code flow to bisect the problem. I would suggest adding a log-only FutureCallback to `resFuture` using a direct executor (keeping the current callback that uses `resultExecutor` in-place). I'm still most suspicious of `resultExecutor` and some Runnable being scheduled on it that blocks for a minute. That said, it is unclear why it would reliably delay the FutureCallback by 60 seconds; if they were independent events the delay would vary between 0-60 seconds.

-----

> Can it reduce the delay by removing bandwidth-delay product monitoring ping, because it can save nio-loop-thread work load?

No. The tracer has shown there is no issues with the nio/netty thread.

> Can nettyChannelBuilder.directExecutor() outperform Futures.addCallback(future, callback, exeuctor)?

I would not dare do that in your case to "solve" this problem. _Something_ is blocking your threads, so using `directExecutor()` would risk moving that "something" to the nio/netty thread.

> What is the function of grpc-default-executor threads, can it be removed to reduce total threads number ?

It is used by default to callback into the application, so that there is no risk of the application blocking the network thread (nio/netty). It is an unbounded thread pool, so it is _guaranteed_ to not be causing this delay.

You can change the thread gRPC uses to notify the application (in this case, "complete the future") by using `managedChannelBuilder.executor()` or `managedChannelBuilder.directExecutor()`. You can also change it on a per-RPC basis with `stub.withExecutor()`.

We do tend to recommend you use your own thread for that, so that you can manage how many threads are created. But it is unrelated to the problem you are experiencing.

> in AWS ARM CPU, grpc-client use nio-event-loop not epoll-event-loop, the delay is 60 seconds.

nio vs epoll should not be important for this problem. It is good to know it is ARM, but still, that shouldn't contribute to this problem.

**Comment by ejona86** [comment] 2021-06-17 17:27
Closing as I don't see a way we can really help more at the moment. If something more turns up (even if it is just a related question), comment and we can reopen.

I don't see a smoking gun proving this is a gRPC issue, and this sort of issue is _trivial_ to cause in an application with a fixed-size thread pool, but that doesn't mean it isn't gRPC. If it were occurring more within gRPC we might try to add ways to make debugging this easier, but it seems this is really in the application's purview and so I don't see a way we can help. I fully recognize finding the bug here will likely be maddening, but I think I can only offer good luck.

**Closed by ejona86** 2021-06-17 17:27 UTC

**Comment by chowtin** [comment] 2021-07-02 04:12
We analyzed full logs (every requests) by comparing ARM and X86 for about 12 days, which showed grpc-ack-latency only happens Intermittently on ARM.

so we concluded the root cause to ARM CPU related issues .

ARM host has been decommissioned from out prod environment, everything runs well now.

Thanks for your support. @ejona86

**Comment by ejona86** [comment] 2021-07-02 14:10
> so we concluded the root cause to ARM CPU related issues .

Ugh. Hardware issues are painful to diagnose. Glad you found the culprit!
