### ISSUE TITLE
LoadBalancer open too many connection

### ISSUE THREAD

**Issue by Gordiychuk** [grpc/grpc-java#7652] opened 2020-11-20 14:31 UTC
### What version of gRPC-Java are you using?
Latest

### What is your environment?
Linux

### What did you expect to see?
LoadBalancer keeps limited number open connections.

### What did you see instead?
On each address that return NameResolver to RoundRobinLoadBalancer opened by connection. It's difficult to scale when
NameResolver return more then hundred hosts.

The result of call one request on ManagedChannel that has NameResolver with 1k+ hosts:
```  
gordiychuk@gordiychuk-ub14:~$ netstat -atn | tr -s ' '| cut -f5 -d ' ' | wc -l
46

gordiychuk@gordiychuk-ub14:~$ netstat -atn | tr -s ' '| cut -f5 -d ' ' | wc -l
1954
```

### Steps to reproduce the bug

I have a [NameResolver](https://github.com/yandex-cloud/ydb-java-sdk/blob/9b5785c2cb98f76d06847fcc3f25c00f569d2af8/core/src/main/java/com/yandex/ydb/core/grpc/YdbNameResolver.java#L122) that by special endpoint resolve a list of hosts that can be use to execute queries. On some endpoint, this NameResolver can return 2k+ hosts, user can send request to any of them. When NameResolver return a lots of code I faced with a problem, that RoundRobinLoadBalancer try connect to all of hosts, instead of create connect only when it requested(limited active pool). I happens in code https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java#L113

Is it valid use NameResolver + LoadBalancer on ManagedChannel? Or it should be other channel on top of ManagedChannel that implements load balancing and resolving himself?

**Comment by sanjaypujare** [comment] 2020-11-20 22:46
@zhangkun83 can you comment on this? Based on your last changes in `RoundRobinLoadBalancer`?

**Comment by zhangkun83** [comment] 2020-11-23 05:17
It's by design that RoundRobinLoadBalancer keeps a connection to every server, so that it's aware of the healthiness of each server and make sure it doesn't assign RPCs to unhealthy servers. If your desired behavior is to create connections on-demand, you probably have very low traffic. In that case you may want to consider two options:
1. Implement subsetting in your NameResolver, which returns a small subset (e.g., 10) of servers from the whole set.
2. If you have a lot of clients and each of them has very low QPS, pick-first (the default load-balancing policy) with address shuffling in your NameResolver may also work for you.

@ejona86 may have other opinions.

**Comment by ejona86** [comment] 2020-11-23 17:19
> instead of create connect only when it requested(limited active pool)

It sounds like you want the round robin policy to do subsetting. The policy is not in a position to know the correct size of the pool and manage additions/removals. The design calls for your Name Resolver to limit the addresses it provides.

**Comment by ejona86** [comment] 2020-12-07 23:30
Closing since everything is working as intended and there's been no more details to help with.

It's unclear what NameResolver is being used in this setup. Ideally this would be using a custom name resolver that could be modified to perform consistent subsetting. If every update randomizes the subset list, the client will need to frequently change the servers it is connected to which will cause undue connection establishment load.

If there's something specific we can help with, comment, and this can be reopened.

**Closed by ejona86** 2020-12-07 23:30 UTC
