### ISSUE TITLE
io.grpc.netty.NettyClientTransportTest  fails on ARM64 Linux

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-java#7830] opened 2021-01-21 12:46 UTC
Running `./gradlew build -PskipAndroid=true -PskipCodegen=true` consistently results in a failure

I'm not sure if the `[jetty-alpn-agent][ warn] Could not find a matching alpn-boot jar for Java version: 11.0.9.1` could be the root cause.

```
> Task :grpc-netty:test
[jetty-alpn-agent][ warn] Could not parse java.version: 11.0.9.1
[jetty-alpn-agent][ warn] Could not find a matching alpn-boot jar for Java version: 11.0.9.1

io.grpc.netty.NettyClientTransportTest > tlsNegotiationServerExecutorShouldSucceed FAILED
    java.util.concurrent.TimeoutException: Waited 10 seconds (plus 93112 nanoseconds delay) for SettableFuture@33c70478[status=PENDING]
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:508)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:111)
        at io.grpc.netty.NettyClientTransportTest$Rpc.waitForResponse(NettyClientTransportTest.java:844)
        at io.grpc.netty.NettyClientTransportTest.tlsNegotiationServerExecutorShouldSucceed(NettyClientTransportTest.java:719)

io.grpc.netty.NettyClientTransportTest > tlsNegotiationFailurePropagatesToStatus FAILED
    value of           : throwable.getCause().getMessage()
    expected to contain: SSLV3_ALERT_HANDSHAKE_FAILURE
    but was            : Received fatal alert: bad_certificate
        at io.grpc.netty.NettyClientTransportTest.tlsNegotiationFailurePropagatesToStatus(NettyClientTransportTest.java:331)

        Caused by:
        io.grpc.StatusException: UNAVAILABLE: io exception
        Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
            at io.grpc.Status.asException(Status.java:542)
            at io.grpc.netty.NettyClientTransportTest$TestClientStreamListener.closed(NettyClientTransportTest.java:870)
            at io.grpc.internal.AbstractClientStream$TransportState.closeListener(AbstractClientStream.java:459)
            at io.grpc.internal.AbstractClientStream$TransportState.access$400(AbstractClientStream.java:221)
            at io.grpc.internal.AbstractClientStream$TransportState$1.run(AbstractClientStream.java:442)
            at io.grpc.internal.AbstractClientStream$TransportState.deframerClosed(AbstractClientStream.java:278)
            at io.grpc.internal.Http2ClientStreamTransportState.deframerClosed(Http2ClientStreamTransportState.java:31)
            at io.grpc.internal.MessageDeframer.close(MessageDeframer.java:233)
            at io.grpc.internal.AbstractStream$TransportState.closeDeframer(AbstractStream.java:201)
            at io.grpc.internal.AbstractClientStream$TransportState.transportReportStatus(AbstractClientStream.java:445)
            at io.grpc.internal.AbstractClientStream$TransportState.transportReportStatus(AbstractClientStream.java:401)
            at io.grpc.netty.NettyClientStream$Sink$1.operationComplete(NettyClientStream.java:160)
            at io.grpc.netty.NettyClientStream$Sink$1.operationComplete(NettyClientStream.java:148)
            at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
            at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
            at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
            at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
            at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
            at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:109)
            at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:89)
            at io.grpc.netty.WriteBufferingAndExceptionHandler.failWrites(WriteBufferingAndExceptionHandler.java:236)
            at io.grpc.netty.WriteBufferingAndExceptionHandler.exceptionCaught(WriteBufferingAndExceptionHandler.java:90)
            at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
            at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
            at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
            at io.grpc.netty.ProtocolNegotiators$ClientTlsHandler.userEventTriggered0(ProtocolNegotiators.java:606)
            at io.grpc.netty.ProtocolNegotiators$ProtocolNegotiationHandler.userEventTriggered(ProtocolNegotiators.java:1033)
            at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346)
            at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332)
            at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324)
            at io.netty.handler.ssl.SslHandler.handleUnwrapThrowable(SslHandler.java:1300)
            at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1281)
            at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1322)
            at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
            at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
            at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
            at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
            at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
            at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
            at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
            at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
            at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
            at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
            at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
            at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
            at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
            at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
            at java.base/java.lang.Thread.run(Thread.java:834)

            Caused by:
            javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
                at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
                at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
                at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:337)
                at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
                at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:186)
                at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
                at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:681)
                at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:636)
                at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:454)
                at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:433)
                at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637)
                at io.netty.handler.ssl.JdkSslEngine.unwrap(JdkSslEngine.java:92)
                at io.netty.handler.ssl.JdkAlpnSslEngine.unwrap(JdkAlpnSslEngine.java:143)
                at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:282)
                at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1380)
                at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1275)
                ... 20 more

402 tests completed, 2 failed, 16 skipped

> Task :grpc-netty:test FAILED
```

### What version of gRPC-Java are you using?

upstream/master

### What is your environment?

Ubuntu 18.04, aarch64

java -version
```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode)
```

### What did you expect to see?

tests pass

### Steps to reproduce the bug

Just run `./gradlew build -PskipAndroid=true -PskipCodegen=true`

**Comment by dapengzhang0** [comment] 2021-01-21 18:13
> I'm not sure if the [jetty-alpn-agent][ warn] Could not find a matching alpn-boot jar for Java version: 11.0.9.1 could be the root cause.

Jetty-alpn-agent will be skipped for java 11, so it should not be the cause. The problem is the error detail expected is not as expected

```
io.grpc.netty.NettyClientTransportTest > tlsNegotiationFailurePropagatesToStatus FAILED
    value of           : throwable.getCause().getMessage()
    expected to contain: SSLV3_ALERT_HANDSHAKE_FAILURE
    but was            : Received fatal alert: bad_certificate
```

**Comment by dapengzhang0** [comment] 2021-01-21 18:20
@ejona86 The change https://github.com/grpc/grpc-java/commit/8359d0b710a7fff96794115931a5105a1f013415#diff-db452b0dac29b1f1e09c876f2cf70c9529fb46caa19bdd55c6d6a454401f9624R329 seems not handling this case correctly.

**Comment by ejona86** [comment] 2021-01-21 18:23
We're getting a different error here because it isn't using boringssl. It is unrelated to 8359d0b.

**Comment by jtattermusch** [comment] 2021-04-28 13:45
Not that we have the grpc-java linux aarch64 tests running continously on kokoro, can we have someone take a look at this issue (and https://github.com/grpc/grpc-java/issues/8118) and fix it?

It would be good to address the TODOs in https://github.com/grpc/grpc-java/blob/72527708f552036ffcd70923ff12a4b26c9d17d4/buildscripts/run_arm64_tests_in_docker.sh#L35 and have the full grpc-java test suite passing on ARM.

The issue can be reproduced locally (on glinux) by simply `apt install qemu-user-static` and then running `buildscripts/run_arm64_tests_in_docker.sh` (you can also update the script locally to only run e.g. `:grpc-xds:test` to get the same result faster).

**Comment by ejona86** [comment] 2021-04-28 23:49
The timeout for tlsNegotiationServerExecutorShouldSucceed is concerning, as that doesn't seem it should ever time out, even if using a different security provider. Maybe a _test_ assertion failure isn't propagated correctly and is causing the timeout.

For the other, it appears tcnative isn't being loaded. I see the `io.netty:netty-tcnative-boringssl-static:2.0.34.Final` dependency which does have a `libnetty_tcnative_linux_aarch64.so` inside. It looks like that is the incorrect name: aarch64 vs aarch_64. I think that was fixed by https://github.com/netty/netty-tcnative/pull/591 which was in netty-tcnative-parent-2.0.35.Final. Changing the dependency locally fixed all failures in NettyClientTransportTest.

@dapengzhang0, I think we'll expect this to start working after the upgrade of Netty.

```
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_linux_aarch_64
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 53 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_linux_aarch_64.so
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:175)
		... 54 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_aarch_64 in java.library.path: [/usr/java/packages/lib, /lib, /usr/lib]
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
			at java.base/java.lang.System.loadLibrary(System.java:1873)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 54 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_aarch_64 in java.library.path: [/usr/java/packages/lib, /lib, /usr/lib]
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
				at java.base/java.lang.System.loadLibrary(System.java:1873)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:566)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:371)
				at java.base/java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:363)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
				... 55 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_linux_aarch_64_fedora
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 53 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_linux_aarch_64_fedora.so
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:175)
		... 54 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_aarch_64_fedora in java.library.path: [/usr/java/packages/lib, /lib, /usr/lib]
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
			at java.base/java.lang.System.loadLibrary(System.java:1873)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 54 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_aarch_64_fedora in java.library.path: [/usr/java/packages/lib, /lib, /usr/lib]
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
				at java.base/java.lang.System.loadLibrary(System.java:1873)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:566)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:371)
				at java.base/java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:363)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
				... 55 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_aarch_64
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 53 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_aarch_64.so
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:175)
		... 54 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_aarch_64 in java.library.path: [/usr/java/packages/lib, /lib, /usr/lib]
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
			at java.base/java.lang.System.loadLibrary(System.java:1873)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 54 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_aarch_64 in java.library.path: [/usr/java/packages/lib, /lib, /usr/lib]
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
				at java.base/java.lang.System.loadLibrary(System.java:1873)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:566)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:371)
				at java.base/java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:363)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
				... 55 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 53 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative.so
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:175)
		... 54 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path: [/usr/java/packages/lib, /lib, /usr/lib]
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
			at java.base/java.lang.System.loadLibrary(System.java:1873)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 54 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path: [/usr/java/packages/lib, /lib, /usr/lib]
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
				at java.base/java.lang.System.loadLibrary(System.java:1873)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:566)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:371)
				at java.base/java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:363)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
				... 55 more
```

**Comment by jtattermusch** [comment] 2021-04-29 09:27
I created https://github.com/grpc/grpc-java/pull/8126 to upgrade netty-tcnative-boringssl-static.

**Comment by ejona86** [comment] 2021-05-03 17:52
CC @suztomo

**Comment by ran-su** [comment] 2021-09-10 22:10
cc @ran-su

**Closed** 2021-09-21 16:14 UTC
Labels: enhancement
