### ISSUE TITLE
ServerInterceptor close trigger MessageDeframer is already closed

### ISSUE THREAD

**Issue by yinheli** [grpc/grpc-java#1665] opened 2016-04-13 10:21 UTC
I want implements `ServerInterceptor` for intercepting incoming calls to check valid authentication credentials.

Here is my java env and code snippet.

question is:

* invoke `serverCall.close` and return null trigger NPE

exception stack:

```
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1@803a06c
java.lang.NullPointerException: startCall() returned a null listener for method com.elegantpay.merchant.api.DictService/SearchCNAPS
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startCall(ServerImpl.java:371)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$1100(ServerImpl.java:282)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1.runInContext(ServerImpl.java:326)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:54)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

* invoke `serverCall.close` then return `return new ServerCall.Listener(){} // ` empty Listener, trigger `MessageDeframer is already closed` Exception

> Note: this exception is not appear at first time, should invoke client/stub again, the server side exception show up

exception stack:
```
WARNING: Exception processing message
java.lang.IllegalStateException: MessageDeframer is already closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
	at io.grpc.internal.MessageDeframer.checkNotClosed(MessageDeframer.java:222)
	at io.grpc.internal.MessageDeframer.deframe(MessageDeframer.java:168)
	at io.grpc.internal.AbstractStream.deframe(AbstractStream.java:276)
	at io.grpc.internal.AbstractServerStream.inboundDataReceived(AbstractServerStream.java:155)
	at io.grpc.netty.NettyServerStream.inboundDataReceived(NettyServerStream.java:77)
	at io.grpc.netty.NettyServerHandler.onDataRead(NettyServerHandler.java:216)
	at io.grpc.netty.NettyServerHandler.access$300(NettyServerHandler.java:93)
	at io.grpc.netty.NettyServerHandler$FrameListener.onDataRead(NettyServerHandler.java:425)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:245)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:46)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:409)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:240)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:147)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:39)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:106)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:332)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:392)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

env: 

```
java version "1.7.0_72"
Java(TM) SE Runtime Environment (build 1.7.0_72-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.72-b04, mixed mode)
```

grpc version: `compile 'io.grpc:grpc-all:0.13.2'`

> `groovy` code

```groovy
import io.grpc.Metadata
import io.grpc.MethodDescriptor
import io.grpc.ServerCall
import io.grpc.ServerCallHandler
import io.grpc.ServerInterceptor
import io.grpc.Status

class MyInterceptor implements ServerInterceptor {
    @Override
    def <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
            MethodDescriptor<ReqT, RespT> methodDescriptor,
            ServerCall<RespT> serverCall,
            Metadata metadata,
            ServerCallHandler<ReqT, RespT> serverCallHandler) {

        // for test
        serverCall.close(Status.UNAUTHENTICATED, new Metadata())

        return null // if close then return null trigger NPE
    }
}
```

so. is the bug? or what is the best practices doing this.

Thanks.

**Comment by ejona86** [comment] 2016-04-13 16:03
The `IllegalStateException: MessageDeframer is already closed` looks to be a bug. I would expect the interceptor to "serverCall.close then return return new ServerCall.Listener(){}"

**Comment by njovy** [comment] 2016-04-15 08:42
@ejona86 Thanks! I didn't know you can just return ```new ServerCall.Listener<ReqT>() {};```. This resolves my issue!

**Comment by ejona86** [comment] 2016-05-26 18:15
The `IllegalStateException` appears to be a duplicate of #615, which I've fixed but we just need to add some tests for.

**Closed by ejona86** 2016-05-26 18:15 UTC
Labels: bug, P2
