### ISSUE TITLE
Upgrade `protobuf-java` to 3.22.2

### ISSUE THREAD

**Issue by jrhee17** [grpc/grpc-java#10034] opened 2023-04-11 04:54 UTC
### Is your feature request related to a problem?
No

### Describe the solution you'd like
Upgrade protobuf from 3.21.7 to 3.22.2 to keep up-to-date with the ecosystem.

### Describe alternatives you've considered
n/a

### Additional context
- Note that 3.22.2 contains a fix for https://github.com/protocolbuffers/protobuf/pull/12035 concerning java8 compatibility
- Also a related pull request on our side: https://github.com/line/armeria/pull/4820

**Comment by sergiitk** [comment] 2023-04-11 21:38
To clarify - the problem is solved from your side by updating the version of protobuf, right?

From our side - we're currently working on updating protobuf from our side. We don't know yet if this'd be an easy upgrade, so I can't provide you with a timeline. Ideally it'll be out as a patch-release of 1.54.

**Comment by jrhee17** [comment] 2023-04-12 02:03
> To clarify - the problem is solved from your side by updating the version of protobuf, right?

Right, but since we also use `grpc-java` as well as `protobuf` we generally try to align these dependencies.

> But as I mention on it, I think we will hold off for a little bit before merging it to let the ecosystem catch up. Java seems fine, but some of the other languages are having trouble.

I see, understood 👍

**Comment by ejona86** [comment] 2023-04-17 17:08
Note: users are free to upgrade the version of protobuf in their own dependency tree. The main thing is _don't downgrade_. Gradle won't do that, and for Maven users we strongly recommend Maven Enforcer's requireUpperBoundDeps.

**Comment by ejona86** [comment] 2023-04-17 20:18
#10045 is merged. Let's consider this closed, even if C++ is still a TODO, you wouldn't be able to notice.

**Closed by ejona86** 2023-04-17 20:18 UTC
Labels: enhancement
