### ISSUE TITLE
Incompatibility with .exe Files in Maven Configuration for Linux-based Docker Builds

### ISSUE THREAD

**Issue by orkh-sa10** [grpc/grpc-java#11531] opened 2024-09-17 06:46 UTC
I am trying to run my Spring Boot project in a Kubernetes (K8s) environment using Docker. However, I’m encountering issues with .exe configurations in my Maven pom.xml file, as .exe files are not compatible with Linux OS. I’ve been searching for solutions but haven’t been able to find a working configuration, which is preventing me from building my application image successfully. I am using Java version 21

**I am executing the following command to build the Docker image:**

docker build -t my_app . and getting error as below:

49.12 [ERROR] /usr/src/app/src/main/proto/GreetService.proto [0:0]: /usr/src/app/target/protoc-plugins/protoc-gen-grpc-java-1.59.0-linux-x86_64.exe: program not found or is not executable
49.12 Please specify a program using absolute path or make sure the program is available in your PATH system variable
49.12 --grpc-java_out: protoc-gen-grpc-java: Plugin failed with status code 1.
49.12 
49.12 [ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.6.1:compile-custom (default) on project sso_auth: protoc did not exit cleanly. Review output for more information. -> [Help 1]
49.12 [ERROR] 
49.12 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
49.12 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
49.12 [ERROR] 
49.12 [ERROR] For more information about the errors and possible solutions, please read the following articles:
49.12 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**This is my proto file under src/main/proto:**

```
syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.example.grpc";
option java_outer_classname = "GreetingServiceProto";

service GreetingService {
  rpc greet (GreetRequest) returns (GreetResponse);
}

message GreetRequest {
  string name = 1;
}

message GreetResponse {
  string greeting = 1;
}

```

========================================================================
**This is my pom.xml configuration:**
```

<plugins>
        <plugin>
                <groupId>org.xolstice.maven.plugins</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
                <version>0.6.1</version>
                <configuration>
                    <protocArtifact>
                        com.google.protobuf:protoc:3.24.0:exe:${os.detected.classifier}
                    </protocArtifact>
                    <pluginId>grpc-java</pluginId>
                    <pluginArtifact>
                        io.grpc:protoc-gen-grpc-java:1.59.0:exe:${os.detected.classifier}
                    </pluginArtifact>
                    <protoSourceRoot>
                        ${basedir}/src/main/proto/
                    </protoSourceRoot>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>compile-custom</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>

```
===================================================================================

**Here is my Dockerfile::**

```
FROM maven:3.9.8-eclipse-temurin-21-alpine as build

WORKDIR /usr/src/app
COPY pom.xml .
RUN mvn --quiet dependency:go-offline
COPY src ./src


# Generate gRPC Java code from .proto files using Maven
# Ensure your pom.xml is set up with the protobuf-maven-plugin
RUN mvn --quiet clean compile

RUN mvn --quiet clean package

FROM openjdk:21-ea-19-jdk-slim-buster
RUN ln -sf /usr/share/zoneinfo/Asia/Baku /etc/localtime
COPY --from=build /usr/src/app/target/*.jar /usr/app/app.jar
CMD ["java", "-jar", "-Dspring.config.location=/usr/app/application.properties", "/usr/app/app.jar"]

```

**Comment by ejona86** [comment] 2024-09-20 21:00
> FROM maven:3.9.8-eclipse-temurin-21-alpine as build

Alpine is probably the problem. But generally can be addressed by installing a package (e.g., gcompat).

```
# docker run --rm -it maven:3.9.8-eclipse-temurin-21-alpine /bin/bash
# wget https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.59.0/protoc-gen-grpc-java-1.59.0-linux-x86_64.exe
# chmod +x protoc-gen-grpc-java-1.59.0-linux-x86_64.exe
# ./protoc-gen-grpc-java-1.59.0-linux-x86_64.exe < /dev/null
bash: ./protoc-gen-grpc-java-1.59.0-linux-x86_64.exe: cannot execute: required file not found
# LD_PRELOAD=/lib/libgcompat.so.0 ldd ./protoc-gen-grpc-java-1.59.0-linux-x86_64.exe 
	/lib64/ld-linux-x86-64.so.2 (0x7f310e230000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f310e230000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f310e230000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f310e230000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by ./protoc-gen-grpc-java-1.59.0-linux-x86_64.exe)
Error relocating ./protoc-gen-grpc-java-1.59.0-linux-x86_64.exe: __strftime_l: symbol not found
# apk add gcompat
# ./protoc-gen-grpc-java-1.59.0-linux-x86_64.exe < /dev/null
# LD_PRELOAD=/lib/libgcompat.so.0 ldd ./protoc-gen-grpc-java-1.59.0-linux-x86_64.exe 
	/lib64/ld-linux-x86-64.so.2 (0x7fbeec664000)
	/lib/libgcompat.so.0 => /lib/libgcompat.so.0 (0x7fbeec64c000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fbeec664000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fbeec664000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fbeec664000)
	ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7fbeec645000)
	libucontext.so.1 => /lib/libucontext.so.1 (0x7fbeec640000)
	libobstack.so.1 => /usr/lib/libobstack.so.1 (0x7fbeec63b000)
```

Yep. You need `gcompat`. This is caused by using a non-glibc-based distro. gcompat is often needed on alpine.

(The LD_PRELOAD is necessary to replicate what the magic gcompat linker is doing. When you run the binary directly this is done for you by gcompat.)

**Comment by orkh-sa10** [comment] 2024-09-23 04:21
Many thanks @ejona86 , it resolved my problem.Really appreciate your help!

**Closed** 2024-09-23 04:22 UTC
Labels: question
