### ISSUE TITLE
Configure OutlierDetectionLoadBalancer for GrpcClient 

### ISSUE THREAD

**Issue by aditya-32** [grpc/grpc-java#10656] opened 2023-11-10 07:38 UTC
Hi i'm doing a POC for outlierDetection using  grpc with xds for a grpc client, so wanted to use the xds OutlierDetection feature [(link)](https://github.com/grpc/proposal/blob/master/A50-xds-outlier-detection.md) for the client , but cannot find any resource on how to use the OutlierDetectionLoadBalancer present in _io.grpc.util_. Is there a way on how to use it and provide it as loadBalancerPolicy in Managed Channel, Also how to provide the service_config including loadbalancer config to the client while creating channels.

**Comment by ejona86** [comment] 2023-11-13 15:33
Cross-linking: https://stackoverflow.com/questions/77458419/configure-outlierdetectionloadbalancer-for-grpc-client

**Comment by temawi** [comment] 2023-11-13 17:50
Thanks for your question @aditya-32. If you are working on a client that is driven by a configuration provided by a control plane (seems like Istio in your case), the outlier detection configuration would be included in the xDS data from the control plane. You should not need to do anything in your client code. The `service_config` you see mentioned is generated based on the xDS configuration received from the control plane.

As long as Istio provides outlier detection configuration in the way specified in the gRFC you linked to (it should), you can just add your settings on the Istio side. I have not tried Istio with outlier detection, but I did find [this page](https://istio.io/latest/docs/reference/config/networking/destination-rule/#OutlierDetection) with details on how to configure it. Maybe that is helpful.

Let us know if you get it to work!

**Comment by aditya-32** [comment] 2023-11-14 03:59
i'm using proxyless grpc(no envoy), i tried to configure using  DestinationRule but it was unable to trigger the outlierDetection for the server even when i was deliberately returning 5xx and the fields mentioned in gRFC like the _failure_percentage_ejection_. cannot be configured in DestinationRule right right?.

**Comment by ejona86** [comment] 2023-11-15 23:03
I think it may be possible to configure Istio [using an EnvoyFilter](https://istio.io/latest/docs/reference/config/networking/envoy-filter/). I have little clue what I'm doing ([I've only tried once before](https://stackoverflow.com/a/76290373/4690866)), but something in the shape of:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: yolo
spec:
  workloadSelector:
    labels:
      app: myapp
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
        # See https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ClusterMatch
        service: foo
    patch:
      operation: MERGE
      value:
        outlier_detection:
          enforcing_success_rate: 50 # 50%
```

**Comment by anuragagarwal561994** [comment] 2023-11-18 11:18
@ejona86 we have tried different ways but the issue is we are getting eds updates and we are not able to see outlier_detection config in the same, while with envoy proxy we are able to see the configuration properly getting to the cluster.

In the proto message when I tried to check the data I am not seeing the outlier_detection config, any clue on what should we check further?

**Comment by anuragagarwal561994** [comment] 2023-11-18 11:33
@ejona86 I think I understood what is happening

https://github.com/istio/istio/blob/b2338d2c38b0d42ce1604b14a98bf0286c1c48a9/pilot/pkg/networking/grpcgen/cds.go

Here we are getting only the eds updates which is filtering out the outlier_detection config

**Comment by anuragagarwal561994** [comment] 2023-11-20 02:35
@ejona86 I think we can close this issue, since the support needs to be added via istio

**Closed** 2023-11-20 19:35 UTC
Labels: question
