### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method build() Crash in runtime as it is not able to find the build method

### ISSUE THREAD

**Issue by sujeet-kumar-mehta** [grpc/grpc-java#6643] opened 2020-01-27 07:24 UTC
### What version of gRPC-Java are you using?
3.9.2

### What is your environment?
Mac

### What did you expect to see?
I wished it to work normally and give the speech recognition 

### What did you see instead?
Crash with  ".NoSuchMethodError: No virtual method build()"
### Steps to reproduce the bug
1. Start the voice recognition, init the setup  and then call the speech recognition method 
2. 
    private StreamObserver<StreamingRecognizeRequest> mRequestObserver;

   mRequestObserver.onNext(
                StreamingRecognizeRequest.newBuilder().setAudioContent(ByteString.copyFrom(data, 0, size)).build());
    
This build() method is found in compile time but it gives following error in runtime everytime. 

ava.lang.NoSuchMethodError: No virtual method build()
Lcom/google/protobuf/GeneratedMessageLite; in class Lcom/google/cloud/speech/v1/StreamingRecognizeRequest$Builder; 
or its super classes (declaration of 'com.google.cloud.speech.v1.StreamingRecognizeRequest$Builder' appears in /data/app/com.byjus.ela-pQZMutEdi_CFP_872HV-Sg==/base.apk!classes4.dex)

**Comment by creamsoup** [comment] 2020-01-27 19:15
the version doesn't look like a gRPC (our latest is `1.26.0`). from the stacktrace, it looks like the issue is either build related or code in speech library. can you file the bug on the speech repo? unless you believe it is gRPC issue

**Comment by sujeet-kumar-mehta** [comment] 2020-01-27 19:21
Yes, the issue is in cloud speech to text library where I have to include some proto files to generate the build method. I am not very clear on why are we using cloud_speech.proto files. Also the build method come from the proto file. Please share some reference to learn about this.

**Comment by creamsoup** [comment] 2020-01-27 19:39
if you want to learn gRPC and how you can build a service from proto. 
https://grpc.io/docs/quickstart/ is a great reference

**Comment by creamsoup** [comment] 2020-01-30 00:00
also, check out this community maintained grpc resources. 
https://github.com/grpc-ecosystem/awesome-grpc

i am going to close this issue, but feel free to reopen if it is identified as gRPC issue.

**Closed by creamsoup** 2020-01-30 00:00 UTC
Labels: question

**Comment by rmesquit** [comment] 2020-03-09 22:18
@sujeet-kumar-mehta instead of using .build() I used .buildPartial() and it worked!

`       mRequestObserver.onNext(StreamingRecognizeRequest.newBuilder()
                .setStreamingConfig(StreamingRecognitionConfig.newBuilder()
                        .setConfig(RecognitionConfig.newBuilder()
                                .setLanguageCode(getDefaultLanguageCode())
                                .setEncoding(RecognitionConfig.AudioEncoding.LINEAR16)
                                .setSampleRateHertz(sampleRate))
                        .setInterimResults(true)
                        .setSingleUtterance(true))
                .buildPartial()
        );`

**Comment by creamsoup** [comment] 2020-03-09 22:39
imo, `buildPartial` is dangerous and should not be used in production (as the method name suggested). it is not directly related to gRPC, we can't provide any meaningful support. further discussion should be in speech repository.
