### ISSUE TITLE
ClientCalls drops cause

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#2631] opened 2017-01-20 21:00 UTC
ClientCalls.toStatusRuntimeException drops the original cause of the Status when converting a Throwable to an SRE.  This results in somewhat useless stack traces, as the original stack trace is lost.  (or at least not printed).  This also happens in `BlockingResponseStream.hasNext`

**Comment by carl-mastrangelo** [comment] 2017-01-20 21:02
Adding the cause back in would help debug https://github.com/grpc/grpc-java/issues/2157 .  The Exception that was originally thrown in the MessageDeframer is not included, making it difficult to debug.

**Comment by ejona86** [comment] 2017-01-21 00:54
I don't think this would do what you'd want. The original `StatusRuntimeException` backtrace was equally useless at it is created at https://github.com/grpc/grpc-java/blob/8894769/stub/src/main/java/io/grpc/stub/ClientCalls.java#L442 . `toStatusRuntimeException` looks like it's doing the "right thing".

`StatusRuntimeExceptions` don't have useful backtraces. Throwing a `StatusRuntimeException` is used for propagating the Status, not the backtrace. Almost all code in our core passes a Status on failure instead of throwing an Exception. There are just a few places where we throw an exception because it was too hard to plumb the Status.

[NettyClientStream](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyClientStream.java#L260) was probably what (properly) threw away the backtrace.

**Comment by carl-mastrangelo** [comment] 2017-01-21 00:56
The stack trace thrown from MessageDeframer  does not show up when printed from StreamObserver.onError.  This should be fixed.  I think it needs to be in the cause of the exception thrown in ClientCalls.

**Comment by ejona86** [comment] 2017-01-21 01:04
This is working as designed. If you want the backtrace, then include it as a cause to the Status.

**Comment by carl-mastrangelo** [comment] 2017-01-21 01:05
It is included, please look at MessageDeframer

**Comment by DevDmitryHub** [comment] 2021-12-01 18:21
Hi all, I've faced with the same issue. On ClientCalls.toStatusRuntimeException drops the original cause of the exception.
Because when it is converted to the new SRE, so passed only status and trails without other params like cause and description.
Even more there is useless to create a copy of SRE.
Also if throwable argument wasn't SRE then original cause is missing too by the while loop.

I'll create a PR for fixing that.

**Comment by ejona86** [comment] 2021-12-01 18:46
@DevDmitryHub, there was not a useful backtrace in the original exception passed to `ClientCalls.toStatusRuntimeException` (assuming the throwable is a StatusException or StatusRuntimeException). The stack trace will essentially always be [the main call to `responseFuture.setException()`](https://github.com/grpc/grpc-java/blob/27b03c66a64aeae25f3fc867457b02e21ca81dab/stub/src/main/java/io/grpc/stub/ClientCalls.java#L534), and the call stack will only have some interceptors on it.

I don't think there is anything to do here. Closing.

**Closed by ejona86** 2021-12-01 18:46 UTC
