### ISSUE TITLE
Protocol message tag had invalid wire type

### ISSUE THREAD

**Issue by shifefiei** [grpc/grpc-java#5603] opened 2019-04-16 14:17 UTC
```
io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
	at io.grpc.Status.asRuntimeException(Status.java:534)
	at io.grpc.protobuf.lite.ProtoLiteUtils$2.parse(ProtoLiteUtils.java:173)
	at io.grpc.protobuf.lite.ProtoLiteUtils$2.parse(ProtoLiteUtils.java:94)
	at io.grpc.MethodDescriptor.parseRequest(MethodDescriptor.java:293)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messageRead(ServerCallImpl.java:243)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1.runInContext(ServerImpl.java:555)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor.runSerializingExecutor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:115)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.skipField(CodedInputStream.java:692)
	at com.yxbj.service.grpc.payment.ITunesNotificationRequest.<init>(ITunesNotificationRequest.java:53)
	at com.yxbj.service.grpc.payment.ITunesNotificationRequest.<init>(ITunesNotificationRequest.java:9)
	at com.yxbj.service.grpc.payment.ITunesNotificationRequest$1.parsePartialFrom(ITunesNotificationRequest.java:2000)
	at com.yxbj.service.grpc.payment.ITunesNotificationRequest$1.parsePartialFrom(ITunesNotificationRequest.java:1995)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:91)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at io.grpc.protobuf.lite.ProtoLiteUtils$2.parseFrom(ProtoLiteUtils.java:178)
	at io.grpc.protobuf.lite.ProtoLiteUtils$2.parse(ProtoLiteUtils.java:170)
	... 9 more
"},
"threadContext":{}}
```
com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.

com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).

com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.

**Comment by ejona86** [comment] 2019-04-16 15:13
Can you provide more information about how this occurred? These exceptions normally mean either 1) corruption or 2) you aren't parsing a protobuf. Is this seen on client or server, and what is the remote software being used? What is done to trigger this?

**Comment by ejona86** [comment] 2019-04-23 17:40
Closing, since there's not enough information to do anything. If more information is provided, it can be reopened.

**Closed by ejona86** 2019-04-23 17:40 UTC

**Comment by vaikzs** [comment] 2019-05-20 09:02
@ejona86 I'm facing the same issue on the client side. Server progresses till onComplete (I noticed from logs), I uploaded the server to AKS and tested from client by port-forwarding. 

```
io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at com.sams.catalog.dto.CategoryServiceGrpc$CategoryServiceBlockingStub.getCategoryInfo(SomeServiceGrpc.java:284)
	at Client.main(Client.java:54)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
	at io.grpc.Status.asRuntimeException(Status.java:523)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:218)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:118)
	at io.grpc.MethodDescriptor.parseResponse(MethodDescriptor.java:266)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:645)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:130)
	... 2 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message had invalid UTF-8.
	at com.google.protobuf.InvalidProtocolBufferException.invalidUtf8(InvalidProtocolBufferException.java:141)
	at com.google.protobuf.Utf8$DecodeUtil.handleTwoBytes(Utf8.java:1909)
	at com.google.protobuf.Utf8$DecodeUtil.access$700(Utf8.java:1883)
	at com.google.protobuf.Utf8$UnsafeProcessor.decodeUtf8(Utf8.java:1411)
	at com.google.protobuf.Utf8.decodeUtf8(Utf8.java:340)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readStringRequireUtf8(CodedInputStream.java:804)
	at com.google.protobuf.WireFormat$Utf8Validation$2.readString(WireFormat.java:200)
	at com.google.protobuf.WireFormat.readPrimitiveField(WireFormat.java:258)
	at com.google.protobuf.MessageReflection.mergeFieldFrom(MessageReflection.java:855)
	at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:438)
	at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:317)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:867)
	at com.google.protobuf.MessageReflection$BuilderAdapter.parseMessage(MessageReflection.java:474)
	at com.google.protobuf.MessageReflection.mergeFieldFrom(MessageReflection.java:834)
	at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:438)
	at com.sams.catalog.dto.Response$CategoryResponse$1.parsePartialFrom(Response.java:976)
	at com.sams.catalog.dto.Response$CategoryResponse$1.parsePartialFrom(Response.java:968)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:86)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parseFrom(ProtoLiteUtils.java:223)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:215)
	... 9 more

Process finished with exit code 1
```

**Comment by ejona86** [comment] 2019-05-20 20:27
@vaikzs, "Protocol message had invalid UTF-8." Either the remote sent you an invalid proto or there was corruption on-the-wire. To help at all we'd need to know more of how this was triggered. It's useful to know whether this is reproducable, used TLS, and what client/server/proxy implementations were involved.

**Comment by vaikzs** [comment] 2019-05-22 05:23
@ejona86 Thank you for responding. I figured what the problem was, it was because the service (image) deployment didn't have `imagePullPolicy` set in deployment plan which didn't even pull the latest image making it not being in sync with client protocol buffers. 

My Setup - No TLS (I'm working on it, probably a good suggestion/reference would be appreciated) insecure connection with envoy proxy implementation was used.
