### ISSUE TITLE
How to send big packagge through gRPC.

### ISSUE THREAD

**Issue by gzhhong** [grpc/grpc-java#8083] opened 2021-04-14 00:32 UTC
Hello, I call API from other service by gRPC, sometimes the return data is very big, suppose to be 200-300K, I found it may cause the service disconnected and my client application will get error when next time call the API. in this case How can I improve.

**Comment by voidzcy** [comment] 2021-04-14 21:26
200-300K isn't that large. By default gRPC allows [up to 4MB data](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#maxInboundMessageSize-int-). What's the error diid you get?

**Comment by gzhhong** [comment] 2021-04-15 06:08
@voidzcy , thanks for the quick answer. I will try to reproduce this issue to see if I can provide error messages.

**Comment by voidzcy** [comment] 2021-04-16 02:17
If the client receives a message larger than the maxInboundMessageSize, the RPC will be cancelled with a RESOURCE_EXHAUSTED status. If you want to change the default to something other than 4MB, you can do it with [`ManagedChannelBuilder.maxInboundMessageSize()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#maxInboundMessageSize-int-).

But as you mentioned, your message size is far smaller than the default threshold, this might not be the problem. But anyway, we would need to at least know what the error you got to see if there is anything we can help.

**Comment by ejona86** [comment] 2021-04-20 16:35
> I found it may cause the service disconnected and my client application will get error when next time call the API

How long does it take for the RPC to be completed? Could it be that the larger responses take more time for the server to compute and that causes some secondary effect?

**Comment by ejona86** [comment] 2021-04-27 23:27
Still hoping that the issue is reproduced so that we can see an error message. But until then, nothing for us to look into, so closing. More information can be provided and then we can reopen.

**Closed by ejona86** 2021-04-27 23:27 UTC
Labels: question
