### ISSUE TITLE
A memory leak of Recycler$WeakOrderQueue

### ISSUE THREAD

**Issue by wu-sheng** [grpc/grpc-java#2445] opened 2016-11-26 03:17 UTC
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.0.0 and 1.0.1

### What JVM are you using (`java -version`)?
1.8

### What did you do?
If possible, provide a recipe for reproducing the error.
A huge data send from client, use gprc-java async service. Service define is like this:
```
service AgentData {
    rpc store (stream AgentDataRequest) returns (ServiceResponse) {}
}
```

### What did you expect to see?
run and send with high performance.

### What did you see instead?
A memory leak of Recycler$WeakOrderQueue

@ejona86, a memory leak occurs in my app, a memory analysis is following:
![3053e0b1d47cbffe2b509a0a69744989](https://cloud.githubusercontent.com/assets/5441976/20637621/4b30d5ea-b3c8-11e6-971a-63914106ad4d.jpg)

**The leak point** is very obvious. At the same time, I found too many `grpc-default-executor`s is running, thousands of it.
![9cbe708b6bb4e101eedc069ef05f4dad](https://cloud.githubusercontent.com/assets/5441976/20637640/b1002ca4-b3c8-11e6-94ae-a074b616bd9a.jpg)

And I have found #2358 seems to match my issue. But the solution is not very useful, you said should update netty to 4.1.6 and the release is in grpc 1.1 or next 1.0.x , which is not available now.

Is their any solutions? Or can you release hotfix version for 1.0.1, such as 1.0.1.1?

It's a very urgent and mortal issue in my product env.

**Comment by wu-sheng** [comment] 2016-11-26 09:00
Maybe, I exclude the netty-4.1.3 dependency and change to dependency netty-4.1.5 manually?

**Comment by ejona86** [comment] 2016-11-28 19:29
We were trying to release v1.0.2 on Friday, but Travis-CI suffered an outage that delayed it. The update to Netty 4.1.6 is already backported on v1.0.x. We're going to decide today whether we delay the release to resolve #2444.

**Comment by ejona86** [comment] 2016-11-28 21:49
We won't hold off for the other issue. We'll be releasing shortly. Closing since this does seem a duplicate of #2358.

**Closed by ejona86** 2016-11-28 21:49 UTC

**Comment by wu-sheng** [comment] 2016-11-29 01:58
@ejona86 , wonderful!! Thanks.
