### ISSUE TITLE
Using DNS Service Discovery returns UNAVAILABLE: NameResolver returned an empty list

### ISSUE THREAD

**Issue by yutachaos** [grpc/grpc-java#5032] opened 2018-11-06 06:39 UTC
### What version of gRPC are you using?
- 1.15.1

### What did you expect to see?

- One of the scenarios is as follows:
	- Using envoyproxy as Load balancer.
	- Using AWS Service Discovery as DNS Service Discovery
	- DNS Service Discovery server that serves as an A record pointing to that load balancer
	- One "backend", which the load balancer points to
	- Such a flow
		- gRPC client server→ envoy proxy → AWS Service Discovery → gRPC api server

- The gRPC client server will return `UNAVAILABLE: NameResolver returned an empty list` when the ip of envoy is changed.

- It seems that gRPC client server has done DNS cache and it is not updated to new ip. 

#### stacktrace

```
io.grpc.StatusRuntimeException: UNAVAILABLE: NameResolver returned an empty list
    at io.grpc.Status.asRuntimeException(Status.java:526)
    at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
    at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
    at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
    at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
    at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
    at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
    at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
    at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
    at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403)
    at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
    at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by carl-mastrangelo** [comment] 2018-11-06 16:35
@yutachaos There were DNS related changes in 1.16.0, you might try it out.   But that said, if DNS returns an empty list, the best we can do is fail and enter the retry backoff loop.

**Comment by yutachaos** [comment] 2018-11-08 03:34
@carl-mastrangelo
Thank you!
I will try changing 1.16.0.
>But that said, if DNS returns an empty list, the best we can do is fail and enter the retry backoff loop.
I understand the way you said.
However, I would like to retry the process with envoyproxy.
I am having problem getting errors with the gRPC client before the request comes to envoyproxy

**Comment by louizo** [comment] 2018-11-13 14:30
@yutachaos 
Note that if you use it on Android platform, you have to add permission for INTERNET connection in your AndroidManifest.xml. 
Just before "<Application" line add :
    <uses-permission android:name="android.permission.INTERNET" />
and build again.

**Comment by carl-mastrangelo** [comment] 2018-11-13 18:20
cc: @ericgribkoff fyi

**Comment by ejona86** [comment] 2018-11-16 17:59
@yutachaos, the error `NameResolver returned an empty list` is a bug that hides the real error. Have you been able to try out 1.16 to see what the real error is? Was the problem the missing INTERNET permission?

**Comment by yutachaos** [comment] 2018-11-21 07:29
@ejona86 
Tried grpc-java 1.16.1. 
Some error changed from `UNAVAILABLE: `NameResolver returned an empty list` to  `ConnectTimeoutException: connection timed out: dummy-host.es-internal/172.20.215.207:17000`.
But still occured `UNAVAILABLE: `NameResolver returned an empty list` error.

> Was the problem the missing INTERNET permission?
In this case, since it is only the java server to send the request,
it has nothing to do with case https://github.com/grpc/grpc-java/issues/5032#issuecomment-438285730

**Comment by ejona86** [comment] 2018-11-21 16:41
Hmm... I wouldn't expect "NameResolver returned an empty list" any more with 1.16.1. The "ConnectTimeoutException: connection timed out" error seems like something that would have happened only after a successful DNS resolution (so NameResolver returned a non-empty list). So things still don't quite make sense.

The `ConnectTimeoutException` should have had a stack trace. Could you include it? (You can remove lines talking about your application's stack.)

**Comment by yutachaos** [comment] 2018-11-23 04:36
@ejona86 
Thank you for your kindness.

That is its stack trace.

```
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    at io.grpc.Status.asRuntimeException(Status.java:526)
    at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
    at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
    at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
    at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
    at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
    at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
    at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
    at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
    at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403)
    at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
    at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
io.netty.channel.ConnectTimeoutException: connection timed out:  dummy-host.interna/172.20.215.169:17008
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
    at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by ejona86** [comment] 2018-12-05 21:37
@yutachaos, that exception is a connection failure and would happen after the name resolver returned a non-empty list.

Connection failures are semi-normal, but connection timed out may be due to the remote machine crashing on something going wrong in the network (for example, misconfigured firewall).

**Comment by ejona86** [comment] 2018-12-20 18:00
The reported error at this point is pretty good (as in, the best we can provide). It seems the problem is just connectivity issues between the client and host. Closing.

**Closed by ejona86** 2018-12-20 18:00 UTC
