### ISSUE TITLE
Make io.grpc.protobuf.StatusProto available for javalite

### ISSUE THREAD

**Issue by bubenheimer** [grpc/grpc-java#7179] opened 2020-07-02 19:36 UTC
I would like to use io.grpc.protobuf.StatusProto and associated status.proto and com.google.rpc.Status with javalite. I believe the only way to do this right now requires copying io.grpc.protobuf.StatusProto.java and status.proto into my project. This is undesirable as it requires regular manual updates and risks versions going out of sync, and it introduces java code into my pure Kotlin project.

Edit: Perhaps creating a fat jar would work as well, but even if so, it would seem a worse approach than the manual copying route.

An old workaround protobufing grpc-google-common-protos is no longer usable with Android R8 minified builds:
https://github.com/protocolbuffers/protobuf/issues/7094#issuecomment-653139580

Related issues, locked to comments and clarification requests:
https://github.com/grpc/grpc-java/issues/6573 (my prior issue with sample project to also reproduce this newly created issue)
https://github.com/grpc/grpc-java/issues/6554 (closed with invalid workaround and vague suggestion to create new issue, but unclear what that issue would be about)

**Comment by sanjaypujare** [comment] 2020-07-02 20:57
CC @ericgribkoff @ejona86 as they have been following up on the other issues mentioned (specifically https://github.com/protocolbuffers/protobuf/issues/7094)

Also is the suggestion to make StatusProto available in `protobuf-javalite` ? Or is there something in grpc-java to do?

**Comment by bubenheimer** [comment] 2020-07-02 21:27
@sanjaypujare I've intended this issue as a targeted TODO to keep track of this specific problem, as I don't believe there are other current issues addressing this. The issues linked at the bottom of the OP are somewhat related, but they don't specifically address this problem and are closed to comments. As I mentioned @ejona86 offered a related workaround that I believe no longer works. The situation is murky and needs a path forward.

I don't have a specific suggestion how to address the issue. io.grpc.protobuf.StatusProto is provided by grpc-protobuf, but not by grpc-protobuf-lite, and linked discussions indicate that it would be non-trivial to incorporate into the latter. Maybe another workaround can be made available to bridge the gap, and other projects influenced to effect change.

**Comment by ejona86** [comment] 2020-07-06 14:15
The problem is we cannot depend on javalite generated code, except (sorta) for generated code in javalite itself. There is [no API/ABI stability for javalite](https://github.com/protocolbuffers/protobuf/blob/master/java/lite.md), which means we can't really use it from a library. But an even bigger issue is that the generated code must be built for that one specific version of javalite; older generated code is not compatible with newer versions of lite. Those mean it is not feasible to expose protolite from a library.

R8 should not be a problem for StatusProto. That is only a problem for the well-known protos where some are in javalite and some aren't. It is probably best to use include/exclude or some such to only run codegen for the missing protos. You could also potentially use [`pickFirst`](https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html) to ignore the conflict.

**Comment by ejona86** [comment] 2020-07-06 14:19
I provided the skeleton of a workaround in https://github.com/grpc/grpc-java/issues/6554#issuecomment-567653077 . In short, use grpc-protobuf, exclude its protobuf dependency in favor of protobuf-lite, and then generate code for `com.google.rpc.Status` yourself. In no way is it "supported" but "it looks like it would work."

Given the state of upstream Lite, I don't see anything more we can offer.

**Comment by bubenheimer** [comment] 2020-07-06 22:03
@ejona86 thank you for the elaborate summary. Great pointer about `pickFirst`, I will try that as an additional tweak. I'm still unsure how to do the #6554 workaround otherwise, with R8 minified builds. Without minifying, yes, but with minifying, no. I tried it several times.

I have been contemplating using full protobuf on the Android client side to eliminate the build concerns. Are the full protobuf headaches limited to code size/method count and use of reflection? I don't think the first is a big problem these days in application code; the difference in APK sizes for my project is no more than a few hundred KB before minification, and likely almost imperceptible after minification. Method count would also mostly be taken care of by minification and isn't much of a problem anyway since API 21 Lollipop (Android 5.0). I guess the concern here these days would be limited to libraries wanting to stay small.

Can you say what reflection is used for in full protobuf? Is it pervasive or only specific things?

**Comment by ejona86** [comment] 2020-07-07 15:09
Full protobuf also includes proto reflection information (descriptors) as a string. I think there may also be _something_ that causes unused messages to kept by dead-code eliminators. I don't know how pervasive reflection is used.

**Comment by ejona86** [comment] 2020-07-20 21:47
Closing. This seems resolved as best as it can be today. If I missed something it can be reopened.

**Closed by ejona86** 2020-07-20 21:47 UTC
Labels: enhancement
