### ISSUE TITLE
When generating Java code, is it possible to have compatibility with both Jakarta and javax?

### ISSUE THREAD

**Issue by glsong7** [grpc/grpc-java#10793] opened 2024-01-03 07:05 UTC

**Comment by ejona86** [comment] 2024-01-09 22:48
Without you saying more, I have to assume this is a duplicate of #9179, and not actually a Jakarta compatibility issue. To date, I've not heard of any _problem_ caused by gRPC using javax.annotation.Generated, other than the need for a compile-only dependency.

If that's not what's happening here, comment and we can reopen.

**Closed by ejona86** 2024-01-09 22:48 UTC
Labels: question
