### ISSUE TITLE
Channel shutdown without calling shutdown()?

### ISSUE THREAD

**Issue by buchgr** [grpc/grpc-java#3297] opened 2017-08-01 08:05 UTC
We are sometimes seeing `StatusRuntimeException` with `Status.UNAVAILABLE` and the message `Channel requested transport to shut down`.  However, our codebase does not contain a call to `ManagedChannel.shutdown(Now)()`. We never close the channel.

Does gRPC ever invoke `shutdown()` internally i.e. in error cases - I always thought it doesn't, but my knowledge of internals is out of date.

**Comment by buchgr** [comment] 2017-08-01 08:07
From `ConnectivityState.SHUTDOWN`:
> Channels may enter this state either
>  because the application explicitly requested a shutdown or if a non-recoverable error has
>  happened during attempts to connect communicate . (As of 6/12/2015, there are no known errors
>  (while connecting or communicating) that are classified as non-recoverable) Channels that
>  enter this state never leave this state.

So this seems to suggest it's not possible.

**Comment by buchgr** [comment] 2017-08-01 08:41
Ha! We recently switched to using `RoundRobinLoadBalancer`. From inspecting the code, it seems there are two scenarios where a load balancer might shutdown a transport. It goes to idle mode or it receives a different set of addresses from the nameresolver:
```java
      // Shutdown subchannels for removed addresses.
      for (EquivalentAddressGroup addressGroup : removedAddrs) {
        Subchannel subchannel = subchannels.remove(addressGroup);
        subchannel.shutdown();
      }
```
https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/util/RoundRobinLoadBalancerFactory.java#L119

So it seems possible for the library to shutdown a channel even with a stream being active? The RPC that failed, has been sitting there silent for a while (~20min).

**Comment by buchgr** [comment] 2017-08-01 09:11
cc: @zhangkun83

**Comment by zhangkun83** [comment] 2017-08-01 16:38
@buchgr your findings are correct. I can imagine transport shutdown causing new streams to fail spuriously if races are not handled correctly, but it should not break live streams. Can you double check if it is the case?

**Comment by zhangkun83** [comment] 2017-08-15 23:50
Since the application didn't shut down the channel, most likely the error message is from [NettyClientTransport.shutdown()](https://github.com/grpc/grpc-java/blob/v1.5.x/netty/src/main/java/io/grpc/netty/NettyClientTransport.java#L263). The message is no longer accurate when we allow `LoadBalancer` to shut down `Subchannel`s, and when `InternalSubchannel` can [shut down the transport when address changes](https://github.com/grpc/grpc-java/blob/v1.5.x/core/src/main/java/io/grpc/internal/InternalSubchannel.java#L305).

While this bug sounds a legitimate issue, I have sent out #3351 to make the error message more accurate.

**Comment by buchgr** [comment] 2017-08-16 11:23
thanks kun! We have only gotten this bug report from a Bazel customer and so I have a hard time reproducing it :\.

**Comment by buchgr** [comment] 2017-10-26 08:17
Hi Kun,

after your patch our users are seeing "Subchannel shutdown invoked" errors. They are seeing the error happening for very long running RPCs roughly every 250 seconds. I checked the DNS record for their service and it turns out that it has a TTL of 295 seconds. So my theory of the load balancer shutting down sounds more believable. However, as you mentioned it shouldn't kill an existing RPC, because gRPC has no deadline for graceful connection shutdowns.

I ll ask them to provide me with a reproducer so I can debug. Will report back here.

Best,
Jakob

**Comment by ejona86** [comment] 2017-10-27 22:43
@buchgr, 1.7 included a fix for "We now wait until all streams are closed before gracefully terminating a Netty connection. There was previously a five second timeout (#3386)"... So, yeah, we likely _were_ terminating pre-maturely.

**Comment by buchgr** [comment] 2017-10-29 13:11
Ha! Perfect! I report back if this fixes the problem for our customers. Thanks!

**Comment by oillio** [comment] 2017-11-22 17:30
I think we may be seeing this issue on 1.7.

We are using the RoundRobinLoadBalancer and we have a few long running requests.
Occasionally, these requests are failing with the error: UNAVAILABLE: Subchannel shutdown invoked

I will work on getting something reproducible and get back to you.

**Comment by ejona86** [comment] 2017-11-22 17:55
@oillio, I think you likely have a different issue. Since you mentioned the RPCs are long-running, what is probably happening is some other thing is causing a disconnection and we're attributing it to the shutdown. During shutdown it can be hard to determine what the "real" cause of failure is.

**Comment by ejona86** [comment] 2017-11-22 17:58
Since it sounds like all the puzzle pieces fit together, I'm going to close this. @buchgr, please reopen/comment if you're still experiencing the problem.

@oillio, you may want to open a new issue. Most of the effort will be tracking down the _real_ cause for your failure.

**Closed by ejona86** 2017-11-22 17:58 UTC
Labels: bug
