### ISSUE TITLE
Using gprc with gradle 6.8.x gives deprecation warning for gradle 8

### ISSUE THREAD

**Issue by EdGue42** [grpc/grpc-java#8027] opened 2021-03-29 10:47 UTC
### What version of gRPC-Java are you using?

        protoc {
            artifact = "com.google.protobuf:protoc:3.12.0"
        }

        plugins {
            id("grpc") {
                artifact = "io.grpc:protoc-gen-grpc-java:1.36.1"
            }
        }

### What is your environment?
MacOs, Linux.

### What did you expect to see?

No warnings about deprecation.

### What did you see instead?

`Using method NamedDomainObjectContainer<T>.invoke(kotlin.Function1) has been deprecated. This is scheduled to be removed in Gradle 8.0. Recompile your plugin against Gradle >= 6.8 Consult the upgrading guide for further information: https://docs.gradle.org/6.8.3/userguide/upgrading_version_6.html#using_NamedDomainObjectContainer_invoke_kotlin_Function1
`
### Steps to reproduce the bug

Not much to say, simply run with current gradle.

**Comment by EdGue42** [comment] 2021-03-29 10:48
I understand that gradle 8 is quite a way to go, but our mantra is that the build should be warning free.
Which it isn't unless your plugin gets fixed.

**Comment by ejona86** [comment] 2021-03-29 16:58
This looks like an issue with https://github.com/google/protobuf-gradle-plugin/ . This looks like a duplicate of #444. Let's keep discussion there.

**Closed by ejona86** 2021-03-29 16:58 UTC
