### ISSUE TITLE
Circular dependency in grpc-core (Gradle)

### ISSUE THREAD

**Issue by EpariNigam** [grpc/grpc-java#10701] opened 2023-11-23 10:22 UTC
### What version of gRPC-Java are you using?
1.59.0

### What is your environment?
Android

### What did you expect to see?
There shouldn't be circular dependencies in libraries. We are using [google-oss-licenseplugin](https://github.com/google/play-services-plugins/blob/master/oss-licenses-plugin/README.md) in our project to show the licenses of libraries we want to use. But, due to this the project is failing to build release version.

### What did you see instead?
Seeing circular dependencies in grpc-core -> grpc-util -> grpc-core

```
+--- io.grpc:grpc-core:1.59.0
|    +--- io.grpc:grpc-api:1.59.0
|    |    +--- com.google.code.findbugs:jsr305:3.0.2
|    |    +--- com.google.errorprone:error_prone_annotations:2.20.0
|    |    \--- com.google.guava:guava:32.0.1-android
|    |         +--- com.google.guava:failureaccess:1.0.1
|    |         +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
|    |         +--- com.google.code.findbugs:jsr305:3.0.2
|    |         +--- org.checkerframework:checker-qual:3.33.0
|    |         +--- com.google.errorprone:error_prone_annotations:2.18.0 -> 2.20.0
|    |         \--- com.google.j2objc:j2objc-annotations:2.8
|    +--- com.google.code.gson:gson:2.10.1
|    +--- com.google.android:annotations:4.1.1.4
|    +--- org.codehaus.mojo:animal-sniffer-annotations:1.23
|    +--- com.google.errorprone:error_prone_annotations:2.20.0
|    +--- com.google.guava:guava:32.0.1-android (*)
|    +--- io.perfmark:perfmark-api:0.26.0
|    +--- io.grpc:grpc-context:1.59.0
|    |    \--- io.grpc:grpc-api:1.59.0 (*)
|    \--- io.grpc:grpc-util:1.59.0
|         +--- io.grpc:grpc-core:1.59.0 (*)
|         +--- org.codehaus.mojo:animal-sniffer-annotations:1.23
|         \--- com.google.guava:guava:32.0.1-android (*)
```

### Steps to reproduce the bug
Adding `grpc-core` to any library and generating dependency graph.

**Comment by ejona86** [comment] 2023-11-25 16:23
This is essentially a duplicate of #10682. Although that one is more for Bazel. This isn't a "true" circular dependency for most build systems, as it isn't a compile dependency. Looks like there's an existing issue open for that project https://github.com/google/play-services-plugins/issues/239

In truth, it isn't even a real dependency from grpc-core to grpc-util. We split grpc-util out of grpc-core and have the dependency there since users could be surprised at runtime when the round-robin LB (in grpc-util) is not present. And it'd be hard for people to debug.

**Comment by ejona86** [comment] 2023-11-25 16:26
That plugin may be suffering from https://github.com/gradle/gradle/issues/22850 , which was mentioned in #10576.

**Comment by ejona86** [comment] 2023-11-27 20:56
Can someone provide a reproduction example?

> we're currently prevented from upgrading gRPC due to gradle/gradle#22850 and this cyclical dependency.

You're not able to do something like the below?
```gradle
dependencies {
  implementation ('io.grpc:grpc-netty:1.59.0') {
    exclude group: 'io.grpc', module: 'grpc-util'
  }
}
```

**Comment by pkoenig10** [comment] 2023-11-28 18:58
This doesn't work because `grpc-netty` doesn't have a direct dependency on `grpc-core`.

The dependencies here look like:

```
grpc-netty -> grpc-core -> grpc-util -> grpc-core
```

You can workaround this by:
- Adding an explicit dependency on `grpc-core`
- Excluding `grpc-util` from `grpc-core` (to remove the bad dependency)
- Excluding `grpc-core` from `grpc-netty` (so you don't get the bad dependency through the `grpc-core` dependency in `grpc-netty`)

```gradle
dependencies {
  implementation ('io.grpc:grpc-netty') {
    exclude group: 'io.grpc', module: 'grpc-util'
  }
  implementation ('io.grpc:grpc-core') {
    exclude group: 'io.grpc', module: 'grpc-util'
  }
}
```

And you have to repeat process for any other dependency that transitively brings in `grpc-core`.

```gradle
dependencies {
  implementation ('io.grpc:grpc-netty') {
    exclude group: 'io.grpc', module: 'grpc-util'
  }
  implementation ('io.grpc:grpc-core') {
    exclude group: 'io.grpc', module: 'grpc-util'
  }

  // Some other dependency that depends on grpc-netty
  implementation ('com.example:foo') {
    exclude group: 'io.grpc', module: 'grpc-netty'
  }

  // Some other that transitively depends on grpc-netty
  implementation ('com.example:bar') {
    exclude group: 'io.grpc', module: 'grpc-core'
  }
}
```

This also causes problems in tools that detect unused Gradle dependencies. The `grpc-core` dependency isn't actually used by this module but we have to add an explicit dependency just so we can exclude `grpc-util`.

**Comment by pkoenig10** [comment] 2023-11-28 22:38
Ah sorry, you're right. It didn't seem to be working earlier when I tried, but I must have been doing something wrong,. Trying it again and it does seem to work.

**Comment by EpariNigam** [comment] 2023-12-04 12:31
While this helps, can we avoid this? Even if someone migrates their gradle with the fix from their side. There will be other side effects, if it is a large project.

**Comment by ejona86** [comment] 2023-12-04 15:58
I suggest you also post more on https://github.com/gradle/gradle/issues/22850 since changing this in gRPC would be a workaround.

**Comment by sergiitk** [comment] 2023-12-12 22:14
Seems we've done as much as we can for now. Once you have more info or questions, comment, and this can be reopened.

**Closed by sergiitk** 2023-12-12 22:14 UTC
