### ISSUE TITLE
gRPC Java is not usable from Java 9 modules

### ISSUE THREAD

**Issue by aseovic** [grpc/grpc-java#3522] opened 2017-09-29 11:52 UTC
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

`1.6.1`

### What JVM are you using (`java -version`)?
```
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```
### What did you do?

Java 9 allows users to depend on older, non-modularized versions of the libraries by "converting" them to automatic modules. For example, when Maven dependencies on grpc are configured correctly, Java 9 allows me to do the following:
```
module myapp.foo {
    exports com.myapp.foo;
    requires grpc.core;
}
```
This allowed me to use classes from the `grpc-core` within my Java 9 module, but unfortunately it wouldn't compile:
```
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.2:compile (default-compile) on project myapp.foo: Compilation failure: Compilation failure: 
[ERROR] the unnamed module reads package io.grpc from both grpc.core and grpc.context
[ERROR] module grpc.context reads package io.grpc from both grpc.core and grpc.context
[ERROR] module guava reads package io.grpc from both grpc.core and grpc.context
[ERROR] module error.prone.annotations reads package io.grpc from both grpc.core and grpc.context
[ERROR] module jsr305 reads package io.grpc from both grpc.core and grpc.context
[ERROR] module instrumentation.api reads package io.grpc from both grpc.core and grpc.context
[ERROR] module opencensus.api reads package io.grpc from both grpc.core and grpc.context
[ERROR] module grpc.core reads package io.grpc from both grpc.core and grpc.context
```
The issue is that Java 9 does not support split packages across modules and this is exactly what's happening here, as `io.grpc` package exists in both `grpc-core` and `grpc-context`, and to make things worse both `grpc-core` and `grpc-stub` have transitive dependency on `grpc-context`.

I've tried excluding `grpc-context` from both modules using Maven exclusions, which allowed me to compile successfully, as I don't have any direct dependencies on `grpc-context`. However, I was not able to run the test server, because of the missing `Context` class:
```
java.lang.NoClassDefFoundError: io/grpc/Context
        at io.grpc.internal.AbstractServerImplBuilder.build(AbstractServerImplBuilder.java:188)
        at io.grpc.testing.GrpcServerRule.before(GrpcServerRule.java:133)
 ``` 
There are several possible solutions, some better than the others:

1. Merge classes from `grpc-context` into `grpc-core` and leave empty/dummy `grpc-context` module around for backwards compatibility (although most people probably do not depend on it directly).
2. Do the same as above, but get rid of unnecessary `grpc-context` module.
3. Rename the `io.grpc` package in `grpc-context` to `io.grpc.context`, which would eliminate split package issue, but would break existing code that uses classes from the current location.

In any case, I'm happy to help do the work, but someone will need to decide which approach to take.

**Comment by carl-mastrangelo** [comment] 2017-10-01 23:43
The reason for the split is to keep the dependencies down for grpc-context.  

1.  Merging won't work.  It would add the dependencies back in.
2.  Same reason.
3.  This is probably the most reasonable path, but that would break backwards compatibility.  That makes it not so reasonable.  

A package per jar is my own preference, but that ship has sailed.  

How is Java 9 supposed to work with generated classes, that live in a parallel package hierarchy by different jars?

**Comment by adriancole** [comment] 2017-10-02 05:53
cc @bogdandrutu as I remember some chatter about making context a top-level
type (not pinned to grpc). Any related issue on that note can link here for
another reason

**Comment by carl-mastrangelo** [comment] 2017-10-02 06:10
@adriancole the issue isn't that it's in the io.grpc realm, its that the same package is split over multiple jars.    Making grpc-context contain io.grpc.context.Context would solve this.

**Comment by adriancole** [comment] 2017-10-02 06:22
>
> @adriancole <https://github.com/adriancole> the issue isn't that it's in
> the io.grpc realm, its that the same package is split over multiple jars.
> Making grpc-context contain io.grpc.context.Context would solve this.
>
right, but what I meant (and didn't say) is that if we are breaking the
java package anyway, if there were a time to top-level the type, it would
be now

**Comment by aseovic** [comment] 2017-10-02 14:23
@carl-mastrangelo I can think of another option:

1. Change the package name to `io.grpc.context` in `grpc-context` module. That will fix the split package issue going forward, but will break existing clients.

2. Introduce `io.grpc.Context` and `io.grpc.Deadline` into `grpc-core`, which simply extend their `io.grpc.context.*` implementations in `grpc-context`. This would fix the clients that do not depend directly (and only) on `grpc-context` at the moment. It does imply, however, that `io.grpc.context.Deadline` could not be final, which it is at the moment.

Now, the bigger question is whether something like `Context` class even belongs in gRPC implementation, and I believe that's the 'top-leveling' @adriancole mentioned. It is a generally useful feature that most of us have written at least once, and would probably feel more 'at home' as `java.util.concurrent.Context` than anywhere else. The fact that the `com.google.instrumentation:instrumentation-api` depends on it also speaks volumes about where it does and does not belong...

Anyway, I've implemented a [workaround](https://github.com/aseovic/io.grpc) that gets me unblocked for the time being by shading core, stub and context into a single JAR with a proper Java 9 module descriptor, but that's definitely not the right direction and I'm happy to help with both this issue and #3523 in any way I can (signed the CLA the other day, so we should be good to go from that perspective).

**Comment by zhangkun83** [comment] 2017-10-03 17:42
This was discussed in #2847

**Comment by ejona86** [comment] 2018-08-13 23:57
Note: the generated code also can run afoul of Java 9 modules. If nothing else, the gRPC generated code is frequently in a separate JAR from the protobuf generated code, but the two exist in the same JAR.

**Comment by CasterKKK** [comment] 2018-10-11 02:19
So now the problem still exists in Java 11. Anyone can provide a solution(even a temporary one)?
`Module 'xxx' reads package 'io.grpc' from both 'grpc.core' and 'grpc.context'`

**Comment by ejona86** [comment] 2018-10-12 23:27
@CasterKKK, the only workaround I know is to repackage the two JARs into a single one as outlined in https://github.com/grpc/grpc-java/issues/2727#issuecomment-348209549

**Comment by marx-freedom** [comment] 2018-10-15 08:41
Same problem for our projects. Are there any plans to support JPMS?

**Comment by lukecwik** [comment] 2019-08-08 16:39
Users have requested support for Java 11 in Apache Beam and since it uses grpc it would need for grpc libraries to be compatible with Java 11. Hopefully this request helps increase the priority for fixing this.

**Comment by ejona86** [comment] 2019-10-16 14:02
We'll be looking into options this quarter. Main choices are to try to reduce dependencies of grpc-api and then combine grpc-context with grpc-api or to do a trick like com.google.guava:listenablefuture's empty version 9999.0.

**Comment by aseovic** [comment] 2019-10-17 03:50
In the meantime, we have repackaged `grpc-java` (version 1.22.1) as a Java 9+ module as part of Helidon, in order to support our gRPC framework implementation, and have made it available on [Maven Central](https://search.maven.org/artifact/io.helidon.grpc/io.grpc/1.3.1/jar).

This module basically [merges](https://github.com/oracle/helidon/blob/master/grpc/io.grpc/pom.xml) `grpc-core`, `grpc-context` and `grpc-stub` into a single JAR, and adds necessary [`module_info.java`](https://github.com/oracle/helidon/blob/master/grpc/io.grpc/src/main/java9/module-info.java) to it.
 
@ejona86 This is not to say that we are not looking forward to a proper Java 9+ module support in `grpc-java`, which will allow us to get rid of this "necessary evil". But we needed something **now**...

**Comment by baha2046** [comment] 2020-06-25 09:11
its now 2020/06/25, is there any progress here?
Or everyone here still using ancient java 8 and planing to use until 2030+?

**Comment by ejona86** [comment] 2020-06-25 15:20
gRPC is compatible with Java 9+, and we continually test against Java 11. The problem here is for Java 9 modules. Helidon has a workaround by combining jars together, which does enable module support. And yes, we recognize that to be a workaround.

**Comment by cjohnstoniv** [comment] 2020-08-19 03:35
Does recognizing it as a work around also mean that the gRPC maintainers don't intend to solve this problem soon? It was mentioned it would be looked into the next quarter almost a year ago but doesn't seem to have any traction since. Is there any hope for a gRPC solution soon that isn't relying on a non-gRPC project deployed version that requires its own custom artifact management?

**Comment by aseovic** [comment] 2020-08-19 03:51
I would very much prefer if the workaround we had to implement was part of `grpc-java` itself, instead of being "our" module that does nothing but repackages `grpc-java` artifacts. While it works fine for the end users, it makes working on Helidon gRPC support itself quite painful, and requires all kinds of IntelliJ acrobatics to get it to understand where different classes are coming from and stop highlighting gRPC class usage as compilation errors...

It may not be the ideal solution, but short of refactoring `grpc-java` to remove split packages, which would likely be a backwards incompatible change, I'm not sure what else can be done...

**Comment by cjohnstoniv** [comment] 2020-08-19 04:17
I apologize if I am missing something but the problem I see as currently on the 1.30.2 version of gRPC is the split packages only exists between `grpc-api` and `grpc-context` on the `io.grpc` package. Is there any reason we can't put in a short-term, backwards compatible solution that involves possibly the following fairly ugly for a few version process:

1. Copy all classes from `grpc-context` into `grpc-api`. It's already a dependency of the API and one could argue the `Context` is part the API so having a separate artifact of a few classes doesn't buy much. The classes are only **copied** not **moved** so they still exist in grpc-context.
2. `grpc-api` still depends on `grpc-context` (or maybe it doesn't need to)
3. For N number of releases changes to the context classes (I would imagine fairly rare), should be applied in both `grpc-context` and `grpc-api`. This gives time for some planned movement off `grpc-contexts` as a sole-dependency supporting backwards compatibility. The classes yes will exist twice on the classpath, but SHOULD be the exact same so effectively nothing happens for existing Java 8 use cases. Java 11 apps can forcefully exclude `grpc-context` since they know its classes are in `grpc-api` now.
4. Eventually `grpc-context` could remove all its classes and deploy as empty if needed so that the dependency tree never changes
5. Eventually `grpc-context` is just removed and not deployed with gRPC artifacts.

Apologize if this has already been attempted but this seems like an approach that allows modularity support fairly easily within as provided by the gRPC project directly.

**Comment by aseovic** [comment] 2020-08-19 04:24
@cjohnstoniv What you are proposing is effectively the same as option 1 (short term) and option 2 (long term), which were rejected by @carl-mastrangelo because "they would bring dependencies back in".

The problem with leaving classes in both places is that you make `grpc-context` and `grpc-api` mutually exclusive: as soon as *something* brings the dependency on `grpc-context` back in (such as `instrumentation-api`, for example), you end up with split packages again :-(

**Comment by cjohnstoniv** [comment] 2020-08-19 04:35
Is it not possible to also migrate future versions of `instrumentation-api` to depend on `grpc-api` instead of `grpc-context`?  `instrumentation-api` would need to move to `grpc-api` anyway to support anything that depends on it for modularity.

What about "they would bring dependencies back in" is more powerful than gRPC being the only non-modularity supportable dependency for several projects? Maybe I'm missing something about what  "they would bring dependencies back in" means.

I don't think `grpc-context` re-appearing on the classpath through some other dependency transitively is the end of the world. At least in this case the developer of the library/application can fully control just excluding `grpc-context` from their tree. This also wouldn't break backwards compatibility if it occurred because it currently doesn't work today.

**Comment by ejona86** [comment] 2020-08-20 16:35
@cjohnstoniv, it is nowhere near as simple as you think. It is a land of subtle issues and hard trade-offs.

Let's not forget that this is a self-inflicted Java module issue. Java modules enforced new restrictions on existing code. It's also made more difficult by Maven's weak package management. We are trying to shoe-horn an existing system into new constraints without any tools to support such a transition, while not taking anything away in the process. If Java supported type aliases or if Maven supported marking "conflicting" packages this would be a lot easier.

The simplest change is to move grpc-context into grpc-api such that grpc-context is empty and depends on grpc-api. This clearly throws dependency-sensitive grpc-context users "under the bus" as the jar size would change from ~30K to ~280K _and_ add dependencies. It would _also_ make grpc-api harder to maintain because we would start avoiding Guava (probably shading parts of Guava, but then we have to be sensitive to how much of Guava will be copied with each class we use). So while being simplest, this approach actually has the longest-term ramifications.

> I don't think grpc-context re-appearing on the classpath through some other dependency transitively is the end of the world.

It is bad. Really bad. Users aren't able to debug that. The results are effectively non-deterministic. You get really weird errors that appear to have nothing to do with the actual problem. We see something similar already when Maven downgrades packages; which users can't deal with it. But in that case there is requireUpperBoundDeps which helps a lot. With this there is no such checker available and it would require a package format change to add a checker. We _have_ to avoid this.

But maybe with a "trick" we could use the general approach but avoid the duplication on the classpath. ~~Hacks~~ Tricks have been considered; a large variety of ~~hacks~~ tricks. But it's really easy to miss issues that will crop up. And for the issues you find you have to consider cost/benefit while being mostly blind (that is to say, we need to weigh options on cost/benefit, but we don't actually know the cost/benefit; we have to guess).

We _did_ work on this a year ago, but it sort of blew up in our face as we discovered issues with the approaches that made the choice more complex and caused us to consider new options to workaround those issues. We have actually come back to it again this quarter and have made good progress. But it is clear that every solution hurts someone.

**Comment by ejona86** [comment] 2020-08-24 15:38
> could we not just add dependency exclusions for grpc-api dependencies that grpc-context does not need in the grpc-context artifact

That's a good idea, and isn't on the list. _Eric runs off to add it to the internal option list._

It would still increase the size of the jar being used from ~30k to ~280k, but avoids long-term maintenance issues. It does export grpc-context users to dangers if they use other grpc-api APIs, as those implementations may be broken without their necessary dependencies. But that may be a worth-while tradeoff for them.

> At any point in time a dependency (including transitive) can add a new dependency throws off your entire resolution tree, this really wouldn't be much different than that scenario the way I see it.

Yes, but since users aren't commonly able to solve the problem on their own, we do get to consider the clarity of errors triggered since we may need to provide "remote debugging" support to tell users where their dependency tree is broken.

**Comment by RationalityFrontline** [comment] 2020-10-15 03:00
For those looking for a quick and convenient solution, I've created a temporary library that solves the split package problem by merging grpc-api and grpc-context into a single jar. It's available in jcenter. The repository is [here](https://github.com/RationalityFrontline/grpc-api), and the usage is below (gradle kotlin DSL) :
```groovy
repositories {
    jcenter()
}

val grpcVersion = "1.32.2"
//val grpcKotlinVersion = "0.2.0"

dependencies {
    implementation("org.rationalityfrontline.grpc:grpc-api:$grpcVersion")
    //implementation("io.grpc:grpc-netty-shaded:$grpcVersion")
    //implementation("io.grpc:grpc-stub:$grpcVersion")
    //implementation("io.grpc:grpc-protobuf:$grpcVersion")
    //implementation("io.grpc:grpc-kotlin-stub:$grpcKotlinVersion")
    //implementation("javax.annotation:javax.annotation-api:1.3.2")
}

configurations.all {
    exclude(group = "io.grpc", module = "grpc-context")
    exclude(group = "io.grpc", module = "grpc-api")
    //uncomment the following line if you have "javax.annotation:javax.annotation-api" in your dependencies.
    //exclude(group = "com.google.code.findbugs", module = "jsr305")
}
```

**Comment by dubbadhar** [comment] 2020-10-29 18:19
will this ever be fixed?

**Comment by dansiviter** [comment] 2020-11-10 09:24
Not sure if I'm missing something here, but isn't [changing the major version the point of backwardly incompatible](https://semver.org/#spec-item-8) API changes?!

* v1 branch: keep the status quo for the time being but deprecate,
* v2 branch: refactor to `io.grpc.context.*` and implement `module-info.java`.

Progress on this sooner rather than later would have avoided potential impact to things like OpenTelemetry that is now bound to `io.grpc.Context`, however that's still in [pre-release](https://github.com/open-telemetry/opentelemetry-java/releases) (0.10.0 at time of writing) so any package changes could be accommodated.

**Comment by ejona86** [comment] 2020-11-12 21:04
@dansiviter 
> Looks like I jumped the gun on OpenTelemetry, 0.10.0 has specifically moved away from gRPC context due to that exact reason.

No, that's not true. They had to make their own because their spec said they had to if there was not a commonly agreed upon one for the language. And even without this issue, there are many competing contexts in Java.

We cannot accept a v2 major version for this change. And if we did that would cascade downstream to all APIs that use it. If we introduced `io.grpc.context.*` it would just be within our current 1.x branch, since they have different names.

**Comment by dansiviter** [comment] 2020-11-12 21:41
@ejona86 Although a breaking change is diametrically against keeping a major version number, if we can move from this impass with a package change in 1.x I think that will unblock a lot of developers. Any idea when this may happen?

**Comment by klaraward** [comment] 2021-06-29 09:57
@ejona86 Any update on this, is this the best issue to follow?

**Comment by quimodotcom** [comment] 2021-08-04 13:51
would still like support!

**Comment by dpratt** [comment] 2021-08-31 18:50
Is there any particular reason why the various jars can't just have `Automatic-Module-Name` attributes added to their manifests? This doesn't preclude any future behavior or impose any other constraint on the library itself, but rather just makes it so downstream consumers can actually use the gRPC artifacts in their projects and refer to a stable module name.

**Comment by cjohnstoniv** [comment] 2021-09-01 00:24
Following up on this a year later, is there any plans to actually make any required breaking changes to gRPC to fix this issue? I work for a large enterprise that has artifact on boarding requirements and gRPC sits at the core of our services. For many of these it is the lone dependencies that are not modularity compliant and we do not have the luxury of leveraging personal projects that hack around the issue.

It sounds like we have run out of ideas and have spent multiple years trying to figure a way out of this problem that doesn't involve breaking changes somewhere. It ultimately sounds like a path just needs to be picked and go with it, understanding no matter what is done its going to break someone.

IMO worrying about breaking people classpath's/dependency trees on upgrades should be the most minor of concerns. They are an absolute reality of Java and Maven dependency management. This already happens today across several grpc versions when guava is upgraded. The amount of times I've seen guava force multiple artifacts into a diamond dependency problem well surpasses the amount of gRPC projects that would be impacted by any modularity upgrades.

I'm willing to do the work, just need an SME and reviewer of gRPC to pick a path.

**Comment by dpratt** [comment] 2021-09-01 01:41
I’d be willing to help out as well, but only if the maintainers bless the effort and can ensure that there’s at least a chance of it being merged. I’d _really_ like to solve this problem as well, as it is for myself (and I suspect a gigantic number of others) the final bit preventing us from moving to use Java modules.

**Comment by AlexSolorio** [comment] 2021-12-21 23:54
Checking in on this issue- is there any update on timeline for this? My organization is hoping to start using gRPC in our backend services, but our codebase is moving to Java 17 (and uses java modules), so it seems like this is not an option for us at this point. 

I was looking into the `Helidon` workaround mentioned above, but it seems that there is no `Helidon` equivalent to the `protoc-gen-grpc-java` gradle plugin that we would need in order to generate Java classes from our `.proto` services. 

Are there any other workarounds that I could look into for gRPC to be an option for us?

**Comment by aseovic** [comment] 2021-12-22 03:07
> I was looking into the `Helidon` workaround mentioned above, but it seems that there is no `Helidon` equivalent to the `protoc-gen-grpc-java` gradle plugin that we would need in order to generate Java classes from our `.proto` services.

@AlexSolorio Helidon simply repackages existing `grpc-java` JARs into a single module, and adds `module_info` with necessary module configuration to it.

You can still use all standard tooling to generate your Java classes from the `.proto` files, such as `protoc` compiler, Maven and Gradle plugins, etc. We don't really change anything there, unless you are using Helidon gRPC framework, which is not required.

**Comment by AlexSolorio** [comment] 2021-12-22 16:45
> 

@aseovic Thanks for the quick reply 😃. From what I can tell, it seems there might be a conflict between the grpc protobuf plugin (`io.grpc:protoc-gen-grpc-java:1.42.1`) and the Helidon module (`io.helidon.grpc:io.grpc:2.4.1`). When I run a gradle build on my project (see attached `build.gradle` file contents), I run into errors about `package io.grpc.stub does not exist` and `package io.grpc.protobuf does not exist`. 

Is there a Helidon version of `io.grpc:protoc-gen-grpc-java:1.42.1` that I should be using instead?

[build.gradle.txt](https://github.com/grpc/grpc-java/files/7764006/build.gradle.txt)

**Comment by aperrot42** [comment] 2022-02-09 07:13
Did not find a simple a suitable way to import gRPC to our current java projects (we have decided to use modern java and modular builds). 
Is there any chance that official gRPC client side libraries & reps get updated to work with java modules ? This is an important decision architecture-wise for us as it directs our adoption of gRPC.

**Comment by sanjaypujare** [comment] 2022-02-09 16:11
@aperrot42 you can take a look at https://github.com/grpc/proposal/blob/master/P5-jdk-version-support.md  specifically https://github.com/grpc/proposal/blob/master/P5-jdk-version-support.md#rationale . As part of dropping support for Java8 may be Java9 modules will be supported?

**Comment by ejona86** [comment] 2022-02-09 18:41
@sanjaypujare, dropping old version support doesn't magically fix the issues here. We need to manually resolve the grpc-context vs grpc-api issue which is the biggest issue. Then we can work on smaller problems like Automatic-Module-Name which may still have some fallout, e.g., inprocess is in grpc-core and maybe should be split out.

**Comment by sanjaypujare** [comment] 2022-02-09 19:51
@ejona86 thanks. I was thinking that the work done to drop support for Java8 will also include adding support for Java9 modules.

**Comment by pedrolamarao** [comment] 2023-03-30 15:37
I have just been bitten by this issue. If shading gRPC doesn't work, we will be forced to fall back to a raw HTTP interface for this project.

**Comment by ejona86** [comment] 2023-06-26 23:35
This is being addressed in https://github.com/grpc/grpc-java/pull/10313 . It merges grpc-context into grpc-api. grpc-context will then be empty and will depend on grpc-api, but will exclude the unnecessary dependencies from grpc-api if you are just using io.grpc.Context. So the main difference for grpc-context-only users is the jar file increases in size, but at least no extra dependencies.

**Closed** 2023-06-29 01:28 UTC
Labels: gRPC 2.0

**Comment by Leejjon** [comment] 2023-06-29 05:13
I'm happy this has finally been resolved. I'll test it next month.
