### ISSUE TITLE
TLS example fails with ClosedChannelException when using ed25519 certificates

### ISSUE THREAD

**Issue by SanjayVas** [grpc/grpc-java#7774] opened 2020-12-31 00:42 UTC
### What version of gRPC-Java are you using?
HEAD (64d2bf125659d656428d91673904f7dfd25dfe8c)

### What is your environment?
OS: Linux (Debian testing x86_64)
JDK: OpenJDK 11
Build system: Bazel 3.7.2

### What did you expect to see?
Client RPC completes successfully (greets localhost). Note that EdDSA using ed25519 is part of the TLS 1.3 standard as described in [RFC 8446](https://tools.ietf.org/html/rfc8446).

### What did you see instead?

```
WARNING: RPC failed: Status{code=UNAVAILABLE, description=Connection closed while performing TLS negotiation
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0], cause=java.nio.channels.ClosedChannelException
        at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:819)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

### Steps to reproduce the bug
1. Modify `HelloWorldServerTls#getSslContextBuilder()` to call `SslContextBuilder#forServer(PrivateKey, X509Certificate...)`, using `BouncyCastleProvider` to support the EdDSA algorithm with `java.security.KeyFactory` in addition to the existing EC, RSA, and DSA algorithms.
1. Verify that the example still works with the provided certificates/keys for server TLS.
1. Generate new certificates following the instructions at testing/src/main/resources/certs/README, but with the ed25519 algorithm (equivalents of ca, client, and server1). Note that the command lists the wrong extension section for `server1-openssl.cnf`, and it should be `v3_req` instead of `req_ext`.
1. Rebuild and run the example using the ed25519 certificates.

I'm happy to share my modifications and certificates/keys if it helps.

**Comment by sanjaypujare** [comment] 2020-12-31 05:26
You have pasted client side log that shows "Connection closed while performing TLS negotiation" which means the server side closed the connection. Can you capture the server side log (after increasing the logging level if necessary) so we can see why server closed the connection?

**Comment by SanjayVas** [comment] 2021-01-05 18:46
Unfortunately, even with turning the logging level to ALL the server does not output any additional messages after `INFO: Server started, listening on 50440`.

I've created a fork with my modifications. See https://github.com/SanjayVas/grpc-java/pull/1

**Comment by SanjayVas** [comment] 2021-01-05 19:23
I had my logging.properties incorrectly configured. Server logs attached.
[grpc-tls.log](https://github.com/grpc/grpc-java/files/5772154/grpc-tls.log)

**Comment by ejona86** [comment] 2021-01-05 22:18
Error being seen:
```
Caused by: javax.net.ssl.SSLHandshakeException: error:100000ae:SSL routines:OPENSSL_internal:NO_CERTIFICATE_SET
```

**Comment by sanjaypujare** [comment] 2021-01-06 07:03
I saw the code at [SanjayVas#1](https://github.com/SanjayVas/grpc-java/pull/1) and noticed that you are not passing the BouncyCastleProvider to the SslContextBuilder. Shouldn't you call `io.netty.handler.ssl.SslContextBuilder.sslContextProvider(Provider)`  to set your `BouncyCastleProvider` into it?

**Comment by SanjayVas** [comment] 2021-01-06 17:39
>Shouldn't you call `io.netty.handler.ssl.SslContextBuilder.sslContextProvider(Provider)` to set your `BouncyCastleProvider` into it?

That results in the following exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: Java Security Provider unsupported for SslProvider: OPENSSL
        at io.netty.handler.ssl.SslContext.verifyNullSslContextProvider(SslContext.java:488)
        at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:470)
        at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:571)
        at io.grpc.examples.helloworldtls.HelloWorldServerTls.start(HelloWorldServerTls.java:77)
        at io.grpc.examples.helloworldtls.HelloWorldServerTls.main(HelloWorldServerTls.java:124)
```
It appears that `sslContextProvider` is only for JDK and not OpenSSL.

**Comment by sanjaypujare** [comment] 2021-01-06 18:07
So may be your use case is unsupported because of thesedependencies and you see the `OPENSSL_internal:NO_CERTIFICATE_SET` ?

**Comment by SanjayVas** [comment] 2021-01-06 22:06
What I'm trying to determine is precisely why it doesn't work, as I don't see a reason it shouldn't be supported. OpenSSL supports ed25519 as of version 1.1.1, and I believe BoringSSL supported it even earlier. The only reliance on BouncyCastle is to get an EdDSA `KeyFactory` to get a `PrivateKey` instance. `io.netty.handler.ssl.ReferenceCountedOpenSslContext` converts this back into PEM bytes.

I suspect the problem is in Netty rather than gRPC, but as gRPC wraps Netty I'm posting here.

**Comment by sanjaypujare** [comment] 2021-01-07 01:59
If you can narrow down the problem to demonstrate the Netty issue it will be good. @voidzcy @ejona86 may have other suggestions?

**Comment by SanjayVas** [comment] 2021-01-08 02:42
It's a bit difficult to narrow it down to Netty vs. the SSL engine. I tried using Conscrypt instead of netty-tcnative-boringssl-static but get the same error. I assume this is because both are using BoringSSL. Interestingly, I get a different error (same with both) if I use TLSv1.2:
```
Caused by: javax.net.ssl.SSLHandshakeException: error:100000b8:SSL routines:OPENSSL_internal:NO_SHARED_CIPHER
```

My theories are either that somehow EdDSA/ed25519 support isn't properly being handled in BoringSSL, or that something goes wrong when Netty is passing around the private key and/or certificate.

**Comment by sanjaypujare** [comment] 2021-01-08 04:18
> My theories are either that somehow EdDSA/ed25519 support isn't properly being handled in BoringSSL, or that something goes wrong when Netty is passing around the private key and/or certificate.

Is it possible that there is something wrong with your cert/key?

**Comment by SanjayVas** [comment] 2021-01-08 17:05
> Is it possible that there is something wrong with your cert/key?

They're in https://github.com/SanjayVas/grpc-java/pull/1/commits/3b6678a4f7bb9893390a5617232084a5b97f7c28. You're welcome to verify them.

**Comment by sanjaypujare** [comment] 2021-01-08 17:13
> They're in [SanjayVas@3b6678a](https://github.com/SanjayVas/grpc-java/commit/3b6678a4f7bb9893390a5617232084a5b97f7c28). You're welcome to verify them.

Not sure I'll get it to it soon. If you are sure the problem is in BoringSSL's handling, can you look up their (or OpenSSL) issues list to see if you find something? Those findings will be helpful in terms of next steps here otherwise I don't know what else we can do.

**Comment by SanjayVas** [comment] 2021-01-08 17:21
> Not sure I'll get it to it soon. If you are sure the problem is in BoringSSL's handling, can you look up their (or OpenSSL) issues list to see if you find something?

It's more likely that the issue is in Netty, but I couldn't find any relevant issues in their tracker. I suppose I could try to reproduce with Netty directly without gRPC in front of it.

BoringSSL has had TLS with ed25519 supported for awhile. See https://crbug.com/boringssl/187 and https://crbug.com/boringssl/367.

**Comment by sanjaypujare** [comment] 2021-01-08 18:30
> It's more likely that the issue is in Netty, but I couldn't find any relevant issues in their tracker. I suppose I could try to reproduce with Netty directly without gRPC in front of it.
> 
> BoringSSL has had TLS with ed25519 supported for awhile. See https://crbug.com/boringssl/187 and https://crbug.com/boringssl/367.

Not sure if we can make much progress here at gRPC (@ejona86 @jiangtaoli2016 ?) . May be you can try creating an issue at Netty and see if you get more responses?

**Comment by SanjayVas** [comment] 2021-01-08 21:05
I'll file the issue with Netty as I believe I've found the culprit. This is what occurred when I used Netty directly with a certificate w/ed25519:

```
Caused by: javax.net.ssl.SSLHandshakeException: Unable to find key material for auth method(s): [ECDHE_ECDSA, ECDHE_ECDSA, ECDHE_RSA, ECDHE_RSA, ECDHE_RSA, ECDHE_RSA, RSA, RSA, RSA]
        at io.netty.handler.ssl.OpenSslKeyMaterialManager.setKeyMaterialServerSide(OpenSslKeyMaterialManager.java:90)
        at io.netty.handler.ssl.ReferenceCountedOpenSslServerContext$OpenSslServerCertificateCallback.handle(ReferenceCountedOpenSslServerContext.java:229)
        at io.netty.internal.tcnative.SSL.readFromSSL(Native Method)
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:596)
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1203)
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1325)
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1368)
        at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:206)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1387)
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1294)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1331)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
        ... 17 mor
```

The `ECDHE_ECDSA` auth method should also support ed25519 and ed448 keys.

**Comment by sanjaypujare** [comment] 2021-01-08 23:48
Pls close this issue unless you think there is something for the gRPC team to do.

**Closed** 2021-01-09 00:36 UTC
