### ISSUE TITLE
NO_ERROR

### ISSUE THREAD

**Issue by zk19930911** [grpc/grpc-java#7409] opened 2020-09-10 03:40 UTC
code is 
```
              Futures.addCallback(
            response,
            new FutureCallback<ProtoObj.Result>() {
                @Override
                public void onSuccess(@Nullable ProtoObj.Result result) {
                   System.out.println(result.getString());
                    latch.countDown();
                }
                @Override
                public void onFailure(Throwable t) {
                    LOGGER.error(" two <==> " + throwable.getMessage());
                }
            };
```

error is :
```
io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR
Received Goaway
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:515)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sanjaypujare** [comment] 2020-09-10 16:32
@zk19930911  can you add more details such as
- version of gRPC Java you are using (the stack trace doesn't match the latest code).
-  if this is happening consistently or it happened only once? 
- what kind of server you are talking to

**Comment by zk19930911** [comment] 2020-09-11 01:51
1.30.0
Always happen

grpc server

code is：
void futureCallCallback() {

    HelloServiceGrpc.HelloServiceFutureStub stub = HelloServiceGrpc.newFutureStub(channel);
    ListenableFuture<ProtoObj.Result> response = stub.simpleHello(person);
    Futures.addCallback(
            response,
            new FutureCallback<ProtoObj.Result>() {
                @Override
                public void onSuccess(@Nullable ProtoObj.Result result) {
                   System.out.println(result.getString());

                }
                @Override
                public void onFailure(Throwable t) {
                LOGGER.error(throwable.getMessage());

                }
            },
            directExecutor());
}

**Comment by sanjaypujare** [comment] 2020-09-11 05:45
Okay the GOAWAY is generated on the server so it will be good to see the logs on the server to see the root cause.

**Comment by zk19930911** [comment] 2020-09-11 08:28
![image](https://user-images.githubusercontent.com/45647545/92892689-92276000-f44b-11ea-9294-0349753b8f83.png)
You can take a look at this picture.
I debug for errors in the output

**Comment by zk19930911** [comment] 2020-09-11 08:30
I have also used the new GRPC version, both of which have such errors

**Comment by sanjaypujare** [comment] 2020-09-11 15:33
Your screenshot shows more details on the client side whereas the error originates on the server side: the server closed the stream with GOAWAY which is why I was asking to see server side logs.

**Comment by zk19930911** [comment] 2020-09-14 08:55
io.grpc.StatusRuntimeException: INTERNAL: http2 exception
,at io.grpc.Status.asRuntimeException(Status.java:533)
,at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:515)
,at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
,at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
,at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
,at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
,at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
,at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
,at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
,at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
,at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
,at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
,at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.handler.codec.http2.Http2Exception$StreamException: Cannot create stream 2033 greater than Last-Stream-ID 2001 from GOAWAY.
,at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:147)
,at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.checkNewStreamAllowed(DefaultHttp2Connection.java:874)
,at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:748)
,at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:668)
,at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders0(DefaultHttp2ConnectionEncoder.java:201)
,at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:167)
,at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeHeaders(DecoratingHttp2FrameWriter.java:53)
,at io.netty.handler.codec.http2.StreamBufferingEncoder.writeHeaders(StreamBufferingEncoder.java:153)
,at io.netty.handler.codec.http2.StreamBufferingEncoder.writeHeaders(StreamBufferingEncoder.java:141)
,at io.grpc.netty.NettyClientHandler.createStreamTraced(NettyClientHandler.java:579)
,at io.grpc.netty.NettyClientHandler.createStream(NettyClientHandler.java:562)
,at io.grpc.netty.NettyClientHandler.write(NettyClientHandler.java:323)
,at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
,at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
,at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
,at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
,at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
,at io.netty.channel.AbstractChannel.write(AbstractChannel.java:289)
,at io.grpc.netty.WriteQueue$AbstractQueuedCommand.run(WriteQueue.java:213)
,at io.grpc.netty.WriteQueue.flush(WriteQueue.java:128)
,at io.grpc.netty.WriteQueue.drainNow(WriteQueue.java:114)
,at io.grpc.netty.NettyClientHandler.goingAway(NettyClientHandler.java:778)
,at io.grpc.netty.NettyClientHandler.access$300(NettyClientHandler.java:91)
,at io.grpc.netty.NettyClientHandler$3.onGoAwayReceived(NettyClientHandler.java:275)
,at io.netty.handler.codec.http2.DefaultHttp2Connection.goAwayReceived(DefaultHttp2Connection.java:236)
,at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.onGoAwayRead0(DefaultHttp2ConnectionDecoder.java:218)
,at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onGoAwayRead(DefaultHttp2ConnectionDecoder.java:551)
,at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onGoAwayRead(Http2InboundFrameLogger.java:119)
,at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readGoAwayFrame(DefaultHttp2FrameReader.java:591)
,at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:272)
,at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
,at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
,at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174)
,at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
,at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
,at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
,at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
,at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
,at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
,at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
,at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
,at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
,at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
,at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
,at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
,at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
,at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
,at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
,at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
,at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
,at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
,at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
,at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
,... 1 more
io.grpc.StatusRuntimeException: INTERNAL: http2 exception
,at io.grpc.Status.asRuntimeException(Status.java:533)
,at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:515)
,at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
,at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
,at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
,at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
,at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
,at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
,at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
,at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
,at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
,at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
,at java.lang.Thread.run(Thread.java:748)

**Comment by sanjaypujare** [comment] 2020-09-14 15:28
Couple of things:
- this is still on the client side. So we don't have any server side logs
- are you reporting a different problem from the earlier one? Or the same problem with a bigger stack trace?

**Comment by zk19930911** [comment] 2020-09-15 11:00
one problem

**Comment by zk19930911** [comment] 2020-09-15 11:02
How to deal with this error

**Comment by sanjaypujare** [comment] 2020-09-15 15:14
We still don't know why the server sent GOAWAY so we need to know that. FWIW I looked at the long stack trace and one of the frames was `io.grpc.netty.NettyClientHandler.goingAway` and the comment there says this:
> To be of any help, the server has to gracefully shut down the connection with two GOAWAYs.

**Comment by ejona86** [comment] 2020-09-15 21:13
> INTERNAL: http2 exception

This is a bug in gRPC Java. This should have been UNAVAILABLE. I think I broke it in https://github.com/grpc/grpc-java/pull/6918 . So while it is a bug, it doesn't help you much if it is fixed, because it will still produce an error.

> Cannot create stream 2033 greater than Last-Stream-ID 2001 from GOAWAY.

I saw this recently when talking to C core (grpc/grpc repo). It isn't doing graceful shutdown of connections. What language is being used on server-side? Are there any proxies being used?

**Comment by ejona86** [comment] 2020-09-15 21:24
Oh, I did already create a bug to track the INTERNAL error: https://github.com/grpc/grpc-java/issues/7357

**Comment by zk19930911** [comment] 2020-09-16 10:38
python language.
The domain name.

error is:
io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR
Received Goaway
	at io.grpc.Status.asRuntimeException(Status.java:533)

How is this exception caused？

**Comment by ejona86** [comment] 2020-09-16 14:54
> UNAVAILABLE: HTTP/2 error code: NO_ERROR Received Goaway

That error is caused by the server shutting down the connection before the client can react. It should be occur sometimes, as there is a race in the client. But the C core server (which powers Python) lacks graceful shutdown which will cause it _much_ more frequently. The C core server will shutdown connection and kill RPCs that have already been sent by the client.

**Comment by zk19930911** [comment] 2020-09-17 08:36
Is it because of the amount of concurrent client requests?

**Comment by ejona86** [comment] 2020-09-17 16:01
> Is it because of the amount of concurrent client requests?

Yes and no. If the server has MAX_CONCURRENT_STREAMS set (may be exposed as MAX_CONCURRENT_CALLS), then you can also get this same error if you exceed that number of concurrent RPCs. That tends to require at least 100 concurrent RPCs. The underlying cause is a bit different though then the issue I was mentioning with the C core server. I don't think MAX_CONCURRENT_STREAMS could trigger "Cannot create stream 2033 greater than Last-Stream-ID 2001 from GOAWAY."

**Comment by ejona86** [comment] 2020-09-24 20:01
I've filed https://github.com/grpc/grpc/issues/24237 to track the C core issue that is causing these failed RPCs. https://github.com/grpc/grpc-java/issues/7357 is still tracking grpc-java using INTERNAL instead of UNAVAILABLE when this occurs.

Those other issues seem they will address the problem, so closing this one. If I missed something, comment, and it can be reopened.

**Closed by ejona86** 2020-09-24 20:01 UTC
Labels: question
