### ISSUE TITLE
UNAVAILABLE: GOAWAY closed buffered stream. HTTP/2 error code: NO_ERROR

### ISSUE THREAD

**Issue by shivam2146** [grpc/grpc-java#8208] opened 2021-05-26 04:26 UTC
### What version of gRPC-Java are you using?
1.37.0

### What is your environment?
Amazon ECS. With amazoncorretto:11 (jdk) as build and run image. 

### What did you expect to see?
Normal inter-service communication with no errors on client and server.

### What did you see instead?
Errors with message `UNAVAILABLE: GOAWAY closed buffered stream. HTTP/2 error code: NO_ERROR` after every fixed interval in gRPC client.

### Steps to reproduce the bug
1. Create a gRPC server with blocking stub
2. Create a client for this server
3. If the gRPC server stub method takes longer durations to execute we start seeing the above error in logs after every minute or so.

Additional info:
Don't see these errors when the stub method is not doing much processing and just returning some dummy data.
The error rate is increased in following scenarios:
1. When we increase the rpm or concurrent calls to server
2. When the rpc method starts taking more time to process

Error message: `UNAVAILABLE: GOAWAY closed buffered stream. HTTP/2 error code: NO_ERROR`

Stack trace:
```
  at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
  at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
  at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
  at com.demo.gpc.DemoGrpc$DemoBlockingStub.hasAccess(DemoGrpc.java:209)
  at com.demo.service.GrpcClient.hasAccess(GrpcClient.java:27)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ejona86** [comment] 2021-05-26 18:47
A "buffered" stream is one that wasn't sent yet because of the server's MAX_CONCURRENT_STREAMS setting. It seems likely the proxy you are using cycles connections after they reach a certain age. RPCs are eagerly assigned to transports, so if that connection is killed it kills those buffered RPCs.

For more minor cases, enabling retry can address this since there is transparent retry. Unfortunately retry is incompatible with stats-keeping at the moment. It will also only transparently retry in this sort of case _once_. We are considering removing that limit and making it unlimited, though.

Because the client is hitting the server's MAX_CONCURRENT_STREAMS there will be extra latency as gRPC waits for RPCs to complete before it starts new ones. You may consider creating multiple Channels or using a load balancer like round_robin that will create multiple connections.

**Comment by shivam2146** [comment] 2021-05-29 07:11
@ejona86 Thanks for the information. 
We are using AWS ELB and have increased the idle connection timeout there. And also upgraded the grpc-java version to 1.38.0 (based on comments in https://github.com/grpc/grpc-java/issues/8142). 
After this we are receiving less frequent errors but still seeing some errors like below:

Error message: `UNAVAILABLE: Abrupt GOAWAY closed unsent stream. HTTP/2 error code: NO_ERROR
stream id: 20005, GOAWAY Last-Stream-ID:20001`

Stack trace: 
`at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
  at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
  at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
  at com.gpc.demo.ace.AceDemoGrpc$AceDemoBlockingStub.hasAccess(AceDemoGrpc.java:209)
  at com.gpc.demo.service.AceGrpcClient.hasAccess(AceGrpcClient.java:27)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by ejona86** [comment] 2021-06-02 19:18
"Abrupt GOAWAY" is when the HTTP/2 server doesn't do a "graceful" GOAWAY using two GOAWAYs. As seen in the [HTTP/2 spec](https://datatracker.ietf.org/doc/html/rfc7540#page-45):

> A server that is attempting to gracefully shut down a connection SHOULD send an initial GOAWAY frame with the last stream identifier set to 2^31-1 and a NO_ERROR code. This signals to the client that a shutdown is imminent and that initiating further requests is prohibited. After allowing time for any in-flight stream creation (at least one round-trip time), the server can send another GOAWAY frame with an updated last stream identifier. This ensures that a connection can be cleanly shut down without losing requests.

It seems the server is not doing that, and there's nothing the client can do to avoid the race since the race is due to network latency. This case requires retry logic.

**Comment by ejona86** [comment] 2021-06-17 17:40
I've created https://github.com/grpc/grpc-java/issues/8269 to track the use of transparent retries for this sort of use. I expect retries will become stable in Java in 1.40 or the following release; we are making good progress on the stats compatibility and we've only been encountering more instances where people have been happily running retries in production.

**Comment by ejona86** [comment] 2021-06-17 17:42
Closing as this is long-standing expected behavior, but watch #8269 for the solution. If I missed something, comment and we can reopen.

**Closed by ejona86** 2021-06-17 17:42 UTC
