### ISSUE TITLE
go-java interop test fails in large_unary and client_streaming

### ISSUE THREAD

**Issue by zhangkun83** [grpc/grpc-java#614] opened 2015-07-09 23:37 UTC
The breakage started somewhere between 2015-07-07 and 2015-07-09. Commit efbb655 is likely the trigger. The bug is only in TLS test cases.

To reproduce:

Start Java server:
```
$ git clone git@github.com:grpc/grpc-java.git
$ cd grpc-java
$ ./gradlew grpc-interop-testing:installDist -PskipCodegen=true
$ ./run-test-server.sh
```

Start the go client in docker.
```
$ git clone git@github.com:grpc/grpc-docker-library.git
$ cd grpc-docker-library
$ touch grpc_go/service_account
$ docker build -t grpc/go grpc_go
$ docker run --rm=true -it grpc/go /go/bin/client -server_host_override=foo.test.google.fr \
-tls_ca_file="/go/src/google.golang.org/grpc/test/testdata/ca.pem" -test_case=large_unary \
-server_port=8080 -server_host=10.0.42.1 -use_tls=true
```

The client fails with
```
/TestService/UnaryCall RPC failed: rpc error: code = 2 desc = ""
```

The server prints out this error:
```
Jul 09, 2015 4:33:17 PM io.grpc.transport.netty.NettyServerHandler onStreamError
WARNING: Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Flow control window exceeded for stream: 1
        at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:100)
        at io.netty.handler.codec.http2.DefaultHttp2LocalFlowController$DefaultState.receiveFlowControlledFrame(DefaultHttp2LocalFlowController.java:365)
        at io.netty.handler.codec.http2.DefaultHttp2LocalFlowController.receiveFlowControlledFrame(DefaultHttp2LocalFlowController.java:239)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:223)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:46)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:392)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:223)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:130)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:39)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:100)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:293)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:336)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1069)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:939)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:946)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:127)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

@ejona86 @nmittler

**Comment by nmittler** [comment] 2015-07-10 18:34
@zhangkun83 trying to reproduce using your steps.  When I build the go docker image, I get:
```
...
Step 2 : ADD service_account service_account
service_account: no such file or directory
```
Any ideas?

**Comment by nmittler** [comment] 2015-07-10 18:44
FYI, I did notice that commit efbb655 changes the server stream window size from 64KiB to 1MiB. Due to a limitation with Netty 4.1.beta5, we send this as a second `SETTINGS` frame.  This means, that the GO client will receive 2 `SETTINGS` frames at start up.  The first will have `SETTINGS_INITIAL_WINDOW_SIZE` to `65535` and the second will have `1048576`.

**Comment by nmittler** [comment] 2015-07-10 18:50
I think I confirmed that this is a bug in the GO client: https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L603.  They're applying the new value before they send the SETTINGS ack.

**Comment by nmittler** [comment] 2015-07-10 18:51
@iamqizhao can you confirm?

**Comment by nmittler** [comment] 2015-07-10 19:23
@iamqizhao Also, it seems that GO is not handling SETTINGS ack properly: https://github.com/grpc/grpc-go/blob/master/transport/http2_client.go#L568.  The client should not be applying the settings locally until it has received the ACK from the server.

**Comment by ejona86** [comment] 2015-07-10 19:50
Not handling the SETTINGS ACK properly is a known deficiency that I've talked with @iamqizhao about before. Since currently the settings in Go only become more permissive (like increasing the window size), it still works.

**Comment by nmittler** [comment] 2015-07-10 19:51
FYI, I've raise an issue in GO to resolve this: https://github.com/grpc/grpc-go/issues/243

**Comment by zhangkun83** [comment] 2015-07-10 20:42
@nmittler Did you do ``touch grpc_go/service_account`` ?
Why it fails only when TLS is enabled? If you run the test without TLS, it will succeed:
```
$ ./run-test-server.sh --use_tls=false

$ docker run --rm=true -it grpc/go /go/bin/client -server_host_override=foo.test.google.fr \
-tls_ca_file="/go/src/google.golang.org/grpc/test/testdata/ca.pem" -test_case=large_unary \
-server_port=8080 -server_host=10.0.42.1 -use_tls=false
```

**Comment by nmittler** [comment] 2015-07-10 21:22
@zhangkun83 TLS has nothing to do with this error. Perhaps it just changes the timing a bit.

**Comment by nmittler** [comment] 2015-07-13 15:48
Determined that this is a bug in GO ... closing this issue.

**Closed by nmittler** 2015-07-13 15:48 UTC
