### ISSUE TITLE
gRPC-Java Inflater to support reading Z_SYNC_FLUSH mode of zlib

### ISSUE THREAD

**Issue by monsterrev** [grpc/grpc-java#6862] opened 2020-03-26 18:48 UTC
### Is your feature request related to a problem?
 gRPC-Java supports gzip compression, and gzip has various compression flush modes (`Z_SYNC_FLUSH, Z_FINISH`). While deflater supports `Z_SYNC_FLUSH` mode while compressing the data, but it does not have the Z_SYNC_FLUSH mode support while decompressing it. i.e. Inflater (general purpose decompression using the popular ZLIB compression library) does not support reading data sent from the client via Z_SYNC_FLUSH mode. So it becomes impossible to write a client-server application utilizing the compression functionality.

### Describe the solution you'd like

Inflater routines do not support the zlib functionality of Z_SYNC_FLUSH. This functionality needs to be added to Inflater. One other thing to note is grpc-cpp library supports this (https://github.com/grpc/grpc/blob/801eed8387177d05f2205fcdc98d948ff7ec9d0f/src/core/lib/compression/stream_compression_gzip.cc#L179)

**Comment by ejona86** [comment] 2020-03-26 20:09
We had a lengthy discussion on gitter before this issue was filed: https://gitter.im/grpc/grpc?at=5e7a93bbd51d8106aa7d3f6a

@monsterrev, that code you referenced is for `grpc_stream_decompress_gzip`, which is the experimental/incomplete full-stream compression. We went [out of our way](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/GzipInflatingBuffer.java) to reduce memory usage with Z_FINISH flushes ("This also frees the inflate context when the end of a gzip stream is reached without another concatenated stream available to inflate").

`Z_SYNC_FLUSH` is supported by all decompressors. `Z_SYNC_FLUSH` didn't originally exist in zlib, it was added later without changing the wire format (which is why the `00 00 FF FF` is necessary).

The question right now is if the compressed message is being truncated or failing to be Z_FINISHed correctly.

@monsterrev, could you share the code snippet used for the remote end of the connection (either the client or server contacting grpc-java)?

**Comment by monsterrev** [comment] 2020-03-26 20:48
Yes, we had a discussion. 
When you say `Z_SYNC_FLUSH` is supported by all decompressors, but I don't see different modes in current `Inflater` code. 
I have tried this client code across a CPP server (stock grpc) and it works there. And in that code, I do see different modes being handled separately. 

I will share the snippet here..
`do {  
           status = deflate(&self->_deflateStream, Z_SYNC_FLUSH);
           if (status == Z_OK || status == Z_STREAM_END) {
                
               // tries to fill in the buffer...
            }
`

**Comment by ejona86** [comment] 2020-03-26 23:19
A _compressor_ will have direct support for Z_SYNC_FLUSH, which looks like what is happening with the code snippet you shared. But the _decompressor_ doesn't see any Z_SYNC_FLUSH on-the-wire. There isn't a "Z_SYNC_FLUSH frame" or "Z_SYNC_FLUSH symbol". Yes, you can pass Z_SYNC_FLUSH to `inflate`, but it is just a local part of the API; it doesn't really matter how the data was compressed.

I just did a test for per-message compression and everything looked fine. If you could provide a reproduction, that would be very helpful. I don't see any gRPC code doing Z_SYNC_FLUSH except for whole-stream compression code which is not production-ready. I will note that when using inflate you are supposed to continue calling it until it returns Z_STREAM_END at the end of the stream. The C code looks like it is handling this incorrectly, because it treats Z_OK and Z_STREAM_END the same way at the end of the stream.

@monsterrev, could you provide a reproduction example?

I modified [C++'s compression client example](https://github.com/grpc/grpc/blob/master/examples/cpp/compression/greeter_client.cc) to use GZIP (instead of DEFLATE, which Java does not support) and changed `"world"` to a much longer string so that C core would actually compress the request.

I then ran each and it worked successfully. I confirmed the request was compressed in wireshark.
```
grpc-java/examples$ ./gradlew installDist
grpc-java/examples$ ./build/install/examples/bin/hello-world-server
```

```
grpc$ ./tools/bazel build examples:compression_client
grpc$ ./bazel-bin/examples/compression_client
```

**Comment by monsterrev** [comment] 2020-03-27 01:28
@ejona86 Yes, there is no negotiation about the mode of the gzip compression. I was referring to this code (its in master) https://github.com/grpc/grpc/blob/master/src/core/lib/compression/stream_compression_gzip.cc#L179. 
To provide a reproduction example, 
- stock grpc java server
- Objective C client which is using a zlib library to compress the data.

And I checked CPP client, the way library compresses does take Flush mode into consideration.
I will try to share code snippets by removing some of confidential stuff.

**Comment by ejona86** [comment] 2020-03-27 16:23
You might quickly share the API call you are using to enable compression in iOS. You keep referencing "stream compression," but that is not ready for general purpose use.

**Comment by ejona86** [comment] 2020-04-06 16:43
@monsterrev, have you had a chance to work on the example or say which APIs are being used?

**Comment by monsterrev** [comment] 2020-04-15 19:19
@ejona86 I am sorry for the delay, I was out. It does not seem as trivial to get the example. I will work on it today. Will keep you posted. Thanks :)

**Comment by ejona86** [comment] 2020-04-21 21:20
Since there's still not much to go on with this, I'm going to close it. @monsterrev, feel free to comment later with additional information and we can reopen it.

**Closed by ejona86** 2020-04-21 21:20 UTC
