### ISSUE TITLE
NettyServerTransport.notifyTransport() logs at SEVERE

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1768] opened 2016-05-03 19:14 UTC
[Logging at SEVERE](https://github.com/grpc/grpc-java/blob/a3c79e8/netty/src/main/java/io/grpc/netty/NettyServerTransport.java#L106) is probably an overkill most of the time. There are rare cases that something higher would be useful, but I don't think we could easily distinguish between those cases. We should probably reduce the severity to something lower, although I'm sure what makes the most sense.

**Comment by blakeday** [comment] 2016-05-03 19:40
This is an example of an (innocuous?) error that causes the log message.
```
May 03, 2016 3:34:39 PM io.grpc.netty.NettyServerTransport notifyTerminated
SEVERE: Transport failed
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1054)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:245)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:106)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:527)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:484)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:398)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:370)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by blakeday** [comment] 2016-08-18 15:39
Any further thoughts on this? I think if we could just detect (and ignore) "Connection reset by peer", we'd be in good shape.  Not sure how we could do that without checking the exception message.

**Comment by trask** [comment] 2016-10-27 05:38
I get lots of these, with different text, "An existing connection was forcibly closed by the remote host", e.g.

```
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1098)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:112)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)
```

I agree would be nice to drop these to WARNING.

**Comment by JohanNordlinder** [comment] 2016-11-11 11:36
+1

**Comment by oillio** [comment] 2016-12-16 20:34
I also get these when a client attempts to connect with HTTP/1.1
In this case, NettyServerHandler is already posting a WARNING.  It would be nice if NettyServerTransport didn't log anything in this case, but a second WARNING would be better than a SEVERE log.

The NettyServerTransport error:
2016-12-16 13:27:28,033 [grpc-default-worker-ELG-1-8] [] ERROR io.grpc.netty.NettyServerTransport - Transport failed
io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 474554202f20485454502f312e310d0a486f73743a206c6f
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:270)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:211)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:393)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

The NettyServerHandler log entry:
2016-12-16 13:22:40,531 [grpc-default-worker-ELG-1-8] [] WARN  io.grpc.netty.NettyServerHandler - Connection Error
io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 474554202f20485454502f312e310d0a486f73743a206c6f
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:270)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:211)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:393)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

**Comment by carl-mastrangelo** [comment] 2016-12-16 21:12
Perhaps this should be filed under the netty project?

**Comment by extensia** [comment] 2017-01-11 06:41
The SEVERE logging level is extremely annoying since our server sees regular attempts to connect using HTTP/1.1 which floods the log with stack traces. Looked like DoS attack at first. To keep this from happening, logging needs to be dialed back for NettyServerHandler and NettyServerTransport which is a not an acceptable workaround.

Here are the two messages we are seeing sans the stacktrace:
ERROR 24004 --- [-worker-ELG-3-1] io.grpc.netty.NettyServerTransport       : Transport failed
WARN 19624 --- [-worker-ELG-3-1] io.grpc.netty.NettyServerHandler         : Connection Error

Reducing the logging level would help, but a better solution might be to handle common scenarios as a special case. I imagine other people with public facing deployments are running into this issue..

**Comment by carl-mastrangelo** [comment] 2017-01-13 21:15
These should probably be reduce to INFO level.

@zhangkun83 thoughts?

**Comment by zhangkun83** [comment] 2017-01-13 21:59
INFO level sounds appropriate to me. Maybe we can do even better by special-casing some exception types and messages, e.g., "Connection reset", and logging them in FINE level.

**Comment by extensia** [comment] 2017-01-14 04:07
That would be great!

**Comment by fgarsombke** [comment] 2017-02-15 04:10
+1

**Comment by hollinwilkins** [comment] 2017-05-16 20:30
+1 Azure health checks from the load balancer cause this error to show up roughly every second. Having a solid solution for this would be nice, but I'm not sure what the root cause is in TCP land or how Java handles TCP stuff like this enough to suggest one.

**Comment by jchapuis** [comment] 2017-07-10 08:09
Any updates on this issue? Outputting SEVERE logs for normal operation is not ideal.

**Closed** 2017-07-14 20:59 UTC

**Comment by nddipiazza** [comment] 2017-10-10 03:15
I get this error on Windows only. It appears to be the same benign kind of log message that you all are reporting. 

Can I safely ignore this? 

```
2017-10-09T20:11:00,366 - INFO  - [grpc-default-worker-ELG-1-13:io.grpc.netty.NettyServerTransport:grpc.netty.NettyServerTransport@159] - {} - Transport failed
java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_131]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_131]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_131]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_131]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[	]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106) ~[netty-buffer-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-common-4.1.14.Final.jar:4.1.14.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```

**Comment by zpencer** [comment] 2017-10-11 16:13
@nddipiazza do your RPCs complete successfully? It seems a bit worrying that connections are killed so frequently. I am not so familiar with Windows, but my internet search results suggest it may be related to a firewall. I am curious if it is actually indicative of a problem.

In general for this spammy log:
I wonder if it is better to make the connection related messages go to a separate logger that can be independently configured with a logging.properties file (redirect to a separate file, attach a java.util.logging.filter, change the log level, etc). It does not seem scalable to continue adding new cases to this list, especially for platforms that we are not as familiar with.

**Comment by chenhao13579** [comment] 2017-10-18 06:22
@nddipiazza 
I have the same problem as you!Is this a neglect or do you need to do something

**Comment by zpencer** [comment] 2017-10-27 20:18
@nddipiazza @chenhao13579 in future releases of grpc, the connection related info will go to "io.grpc.netty.NettyServerTransport.connections" and can be redirected away from the main log handler. If the logspam right now is causing a lot of pain, it is safe to redirect "io.grpc.netty.NettyServerTransport" because it is not used for any other type of messages.

**Comment by nddipiazza** [comment] 2017-11-28 01:19
Excellent. Thanks so much for taking care of that, this should fix my issue.
