### ISSUE TITLE
grpc-java is not compatible with native-image with Quarkus wich enable the --link-at-build-time option.

### ISSUE THREAD

**Issue by SetoKaiba** [grpc/grpc-java#10781] opened 2023-12-24 18:08 UTC
### What version of gRPC-Java are you using?
1.59.0

### What is your environment?
Ubuntu WSL
GraalVM 21.0.1

### What did you expect to see?
I want to use google cloud client library vertex ai project which has a dependcy to grpc-java.
https://github.com/googleapis/google-cloud-java/tree/main/java-vertexai
grpc-java should be compatible with native-image with Quarkus wich enable the --link-at-build-time option.

### What did you see instead?
grpc-java is not compatible with native-image with Quarkus wich enable the --link-at-build-time option.
Please check the reproduce project in the section Steps to reproduce the bug.
- I will see the problem without GaxGrpcSubstitutions.java.
https://github.com/apache/camel-quarkus/commit/372e221d97e9680cebfecd8788cd3a2802eb3686#diff-045b0cd1db2866c2c9b1e5608edc0d4a5d81acfb3d8b2e0df0ae22fce3298ae2
https://github.com/quarkiverse/quarkus-google-cloud-services/blob/main/common/grpc/src/main/java/io/quarkiverse/googlecloudservices/common/grpc/runtime/graal/GoogleApiGaxGrpcSubstitutions.java

> `Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.grpc.alts.GoogleDefaultChannelCredentials$Builder.callCredentials(io.grpc.CallCredentials).`

This error is reported at image build time because class com.google.api.gax.grpc.InstantiatingGrpcChannelProvider is registered for linking at image build time by command line and command line.

- After I apply the commit above, I will see the problem below.

> `Caused by: org.graalvm.compiler.debug.GraalError: org.graalvm.compiler.debug.GraalError: org.graalvm.compiler.debug.GraalError: com.oracle.svm.core.util.UserError$UserException: Class initialization of io.grpc.xds.internal.security.SslContextProvider failed`

This error is reported at image build time because class io.grpc.xds.internal.security.SslContextProvider is registered for linking at image build time by command line and command line. Use the option

- The problem
  - grpc-java is compatible without --link-at-build-time option.
  - Quarkus enable --link-at-build-time option.
  - Quarkus has to use grpc-netty instead of the grpc-netty-shaded which has a lot of problem in Quarkus. But grpc-xds has a depency to grpc-netty-shaded.

### Steps to reproduce the bug
https://github.com/SetoKaiba/gcp_reproduce
Use the reproduce project to reproduce.

### Related issues
https://github.com/quarkusio/quarkus/discussions/37909
https://github.com/googleapis/google-cloud-java/issues/10180
https://github.com/grpc/grpc-java/issues/9736

**Comment by sergiitk** [comment] 2024-01-02 22:25
This looks like a duplicate of https://github.com/grpc/grpc-java/issues/9736. Since there's a demand for it, we'll revisit this issue at a team meeting next week.

**Comment by ejona86** [comment] 2024-01-09 23:46
There's multiple Gax things listed, which aren't really relevant to gRPC. The gRPC issue appears to be `io.grpc.xds.internal.security.SslContextProvider`. But that error message isn't entirely helpful as it doesn't say what is wrong with SslContextProvider.

I will say that we don't really support Quarkus directly; we have no expertise with it. All fixes up to this point have been community contributions, although the googleapis folks may be able to help us as they have more experience.

https://github.com/googleapis/google-cloud-java/issues/10180#issuecomment-1869648332 provides a lot of good details of what is going on. That does get us back to io.netty.util.internal.logging.Log4J2Logger of #9736, which is really a Netty issue or a "the config rewriting in #8258 doesn't work properly" issue. But I don't think we have expertise to distinguish between them.

> Use the reproduce project to reproduce.

What should I do to see that error?

My attempt to reproduce, which ran without errors:
```
docker run --rm -it docker.io/library/debian:11
cd
apt update
apt install -y git
# download https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_linux-x64_bin.tar.gz
tar xvzpf graalvm-jdk-21_linux-x64_bin.tar.gz
export PATH=$PATH:$PWD/graalvm-jdk-21.0.1+12.1/bin/
git clone https://github.com/SetoKaiba/gcp_reproduce.git
cd gcp_reproduce
chmod +x gradlew
./gradlew build
```

**Comment by SetoKaiba** [comment] 2024-01-10 00:42
> There's multiple Gax things listed, which aren't really relevant to gRPC. The gRPC issue appears to be `io.grpc.xds.internal.security.SslContextProvider`. But that error message isn't entirely helpful as it doesn't say what is wrong with SslContextProvider.
> 
> I will say that we don't really support Quarkus directly; we have no expertise with it. All fixes up to this point have been community contributions, although the googleapis folks may be able to help us as they have more experience.
> 
> [googleapis/google-cloud-java#10180 (comment)](https://github.com/googleapis/google-cloud-java/issues/10180#issuecomment-1869648332) provides a lot of good details of what is going on. That does get us back to io.netty.util.internal.logging.Log4J2Logger of #9736, which is really a Netty issue or a "the config rewriting in #8258 doesn't work properly" issue. But I don't think we have expertise to distinguish between them.
> 
> > Use the reproduce project to reproduce.
> 
> What should I do to see that error?
> 
> My attempt to reproduce, which ran without errors:
> 
> ```
> docker run --rm -it docker.io/library/debian:11
> cd
> apt update
> apt install -y git
> # download https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_linux-x64_bin.tar.gz
> tar xvzpf graalvm-jdk-21_linux-x64_bin.tar.gz
> export PATH=$PATH:$PWD/graalvm-jdk-21.0.1+12.1/bin/
> git clone https://github.com/SetoKaiba/gcp_reproduce.git
> cd gcp_reproduce
> chmod +x gradlew
> ./gradlew build
> ```

```
./gradlew build -Dquarkus.package.type=native
```

**Comment by ejona86** [comment] 2024-01-11 16:28
Let's close this as a duplicate of #10601. There's some details there about what seems to be going on.

**Closed** 2024-01-11 16:29 UTC
Labels: enhancement
