### ISSUE TITLE
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE

### ISSUE THREAD

**Issue by RobinsChens** [grpc/grpc-java#2512] opened 2016-12-13 07:57 UTC
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.0.2
### What JVM are you using (`java -version`)?

1.8
### What did you do?
If possible, provide a recipe for reproducing the error.
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE

**Comment by carl-mastrangelo** [comment] 2016-12-13 18:15
Can you print out the cause?   gRPC Java messages typically include more detail.

**Comment by ejona86** [comment] 2016-12-13 19:17
Easiest way is to call `printStackTrace()` on the exception.

**Comment by RobinsChens** [comment] 2016-12-14 05:22
when I try to use jmeter to test 300 threads with 100 loops ,it return error    

![image](https://cloud.githubusercontent.com/assets/11987492/21170473/5b9bab12-c200-11e6-9539-70062bc6d758.png)

**Comment by awhlee** [comment] 2017-04-26 18:22
I'm running into this also would love to know if there is something that I'm doing wrong or if it is a known issue.

**Comment by ejona86** [comment] 2017-11-08 16:31
Closing since we never received a stack trace. It can be reopened if we get one.

**Closed by ejona86** 2017-11-08 16:31 UTC
