### ISSUE TITLE
Running ./gradlew build leaves behind a javadoc/ directory

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#973] opened 2015-09-08 20:07 UTC
This makes it difficult to do a "git add ." command after running tests.

**Comment by ejona86** [comment] 2015-09-09 01:07
This is caused by the addition of the Android goo. #960 should fix it.

**Comment by ejona86** [comment] 2015-09-16 23:01
This is fixed with the removal of the android subproject.

**Closed by ejona86** 2015-09-16 23:01 UTC
