### ISSUE TITLE
io.grpc.okhttp.OkHttpTransportTest > serverNotListening FAILED

### ISSUE THREAD

**Issue by buchgr** [grpc/grpc-java#2344] opened 2016-10-14 14:52 UTC
```
io.grpc.okhttp.OkHttpTransportTest > serverNotListening FAILED
    Wanted but not invoked:
    listener.transportTerminated();
    -> at io.grpc.internal.testing.AbstractTransportTest.serverNotListening(AbstractTransportTest.java:242)
    Actually, there were zero interactions with this mock.
```

Seen at https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/2345/console

**Comment by ejona86** [comment] 2017-02-28 17:41
Duplicate of #1877.

**Closed** 2018-04-02 22:16 UTC
