### ISSUE TITLE
grpc-netty-shaded and netty issue in PEM reader

### ISSUE THREAD

**Issue by jwojcie** [grpc/grpc-java#11684] opened 2024-11-12 16:29 UTC
I'm using a library which depends on io.grpc:grpc-netty-shaded:jar:1.54.1. While moving to BC FIPS I noticed that there is an issue in netty - it has hardcoded BC non FIPS in PEM reader. So I raised the issue there to fix it. Now the questions:
- what version of netty should I seek to have that change implemented in order to ask you to use it in the next release of grpc-netty-shaded? Is that netty 4 or 5?
- how long does it take for you to adopt new netty release and release new version of grpc-netty-shaded?

Issue raised in netty:
https://github.com/netty/netty/issues/14455

**Comment by ejona86** [comment] 2024-11-12 17:57
Netty 4 is the normal one they'd fix it in, and what we are using. It's going to be a bit before Netty 5 is released.

The time to upgrade varies considerably, depending on the difficulty. But we're already behind on the upgrade as it is more involved. We were hoping to get on 4.1.111+ in Q1 next year.

**Comment by ejona86** [comment] 2024-11-12 17:58
Note: If using grpc-netty, you can choose the version of Netty and wouldn't need to wait for us. But there would be a performance regression if you upgrade to 4.1.111+.

**Comment by jwojcie** [comment] 2024-11-13 23:31
Can you point me to the material explaining how to do that? I thought that since it is shaded I'm stuck with whatever version is there in grpc-java library release.

**Comment by ejona86** [comment] 2024-11-14 05:08
Yes, you are stuck with the selected netty version if using grpc-netty-shaded. I was just saying there's the possible option of using grpc-netty in order to upgrade netty sooner.

**Comment by ejona86** [comment] 2024-11-19 22:19
Since there's not yet a Netty with the change, I'm going to close this for now. If a PR gets merged soon (even if Netty isn't released) this could be reopened or we just create a new issue. We'd want the title to be more like "upgrade to Netty vF.0.0". The more important thing in the short-term is upgrading to 4.1.111+. We'd want to create an issue tracking that as well, as a blocker of this.

**Closed by ejona86** 2024-11-19 22:19 UTC
Labels: question
