### ISSUE TITLE
UNAVAILABLE: HTTP/2 error code: NO_ERROR Received Goaway

### ISSUE THREAD

**Issue by c-s-t-z** [grpc/grpc-java#8310] opened 2021-07-08 14:24 UTC
### What version of gRPC-Java are you using?
1.30.2

### What is your environment?

Linux xxxxx016 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

### What did you see instead?
```
 io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR
Received Goaway
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:460)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### Steps to reproduce the bug

The java grpc client connects to the go grpc service (service grpc version 1.27.1). The above exception occurs. The service uses container deployment and nginx for load balancing. There is a high probability of this abnormal situation.
Of course, we are also working hard to find a solution, but there is no progress. Hope to get your guidance and help.
I will be very grateful.

**Comment by c-s-t-z** [comment] 2021-07-09 06:20
The client language Java uses version 1.30.0, and the server language go uses version 1.27.1. The server uses docker container deployment. If there is anything else I need to provide, please feel free to contact me, thank you very much.

**Comment by ericgribkoff** [comment] 2021-07-12 10:00
Are you able to connect from the client to the server directly without nginx in the middle? Or are you successful when using a gRPC Go client and only the gRPC Java client has an issue? My guess here is that the connection is being interrupted by nginx or some other middle component as generally gRPC servers themselves will not terminate a connection with `NO_ERROR` but rather this is what you'd expect from a proxy in the middle.

**Comment by c-s-t-z** [comment] 2021-07-12 11:21
> 你能在中间没有nginx的情况下直接从客户端连接到服务器吗？或者您在使用 gRPC Go 客户端时是否成功并且只有 gRPC Java 客户端有问题？我的猜测是，连接被 nginx 或其他一些中间组件中断，因为通常 gRPC 服务器本身不会终止与之的连接，`NO_ERROR`但这正是您对中间代理的期望。

Thank you for your reply, can I think that this NO_ERROR exception has no effect on a connection; can this exception call grpc's onError method;
Which link may be the problem or how do I need to deal with this exception?

**Comment by ericgribkoff** [comment] 2021-07-12 13:07
Do you always see the NO_ERROR exception? That is, the client can never connect to the server? Or can your client connect to the server and exchange messages but then periodically sees the exception message and the connection gets broken?

The error indicates that something the gRPC client is connected to has terminated the connection with a GOAWAY frame saying NO_ERROR. This _could_ come from the gRPC server (if you turn on verbose logging in the server, you may be able to see if this is happening) but I think it is more likely coming from an intermediate layer. If your clients can connect but then see this error after some time, it could be that there is a timeout configured in nginx or elsewhere causing it to terminate the stream (just a guess)

**Comment by c-s-t-z** [comment] 2021-07-13 03:58
> Do you always see the NO_ERROR exception? That is, the client can never connect to the server? Or can your client connect to the server and exchange messages but then periodically sees the exception message and the connection gets broken?
> 
> The error indicates that something the gRPC client is connected to has terminated the connection with a GOAWAY frame saying NO_ERROR. This _could_ come from the gRPC server (if you turn on verbose logging in the server, you may be able to see if this is happening) but I think it is more likely coming from an intermediate layer. If your clients can connect but then see this error after some time, it could be that there is a timeout configured in nginx or elsewhere causing it to terminate the stream (just a guess)

Thank you for your reply again. When the amount of data is large, this problem will be reported every time a connection is established; and it is more frequent, because I don't know very much about this, and it is not clear whether it is when creating StreamObserver<ReadAloudRequest> or in requestObserver.onNext (request) When the onError method was triggered, the NO_ERROR exception was reported; so I want to get more guidance and help from you.

**Comment by ericgribkoff** [comment] 2021-07-13 10:03
The NO_ERROR part of the exception message corresponds to the GOAWAY received on the HTTP/2 stream (the spec for this is at https://httpwg.org/specs/rfc7540.html#ErrorCodes). There is in fact an "error" on the stream from the gRPC client's perspective, because the stream has been broken - the GOAWAY with NO_ERROR just indicates that the server or intermediate proxy sending that is terminating the connection is _intentionally_ breaking the stream or rejecting creation of a new stream. To debug further, we would need to identify where this GOAWAY is being generated and why.

**Comment by c-s-t-z** [comment] 2021-07-13 10:24
> The NO_ERROR part of the exception message corresponds to the GOAWAY received on the HTTP/2 stream (the spec for this is at https://httpwg.org/specs/rfc7540.html#ErrorCodes). There is in fact an "error" on the stream from the gRPC client's perspective, because the stream has been broken - the GOAWAY with NO_ERROR just indicates that the server or intermediate proxy sending that is terminating the connection is _intentionally_ breaking the stream or rejecting creation of a new stream. To debug further, we would need to identify where this GOAWAY is being generated and why.

Thank you very much for your prompt response, I understand that you need this information here:
grpc client version 1.30.2, error location at io.grpc.Status.asRuntimeException(Status.java:533);

**Comment by ericgribkoff** [comment] 2021-07-13 22:44
Sorry, the information that is needed for you to debug the problem is identifying where in the network the GOAWAY is being generated. This is being received over the network by the client, so the exception message from the client is expected and doesn't give any further information about where or why the connection was closed. You would need to determine if the gRPC server were sending the GOAWAY, or if it is being created by an intermediate like nginx.

**Comment by c-s-t-z** [comment] 2021-07-14 08:09
> Sorry, the information that is needed for you to debug the problem is identifying where in the network the GOAWAY is being generated. This is being received over the network by the client, so the exception message from the client is expected and doesn't give any further information about where or why the connection was closed. You would need to determine if the gRPC server were sending the GOAWAY, or if it is being created by an intermediate like nginx.

Thank you for your reply. I would like to ask, can I set the number of streams in each connect on the client side? When this value is reached, a new connection will be used. We guess that ng intercepted but let's modify the configuration of this parameter, see Is there any relief?

**Comment by ejona86** [comment] 2021-07-16 15:56
If I had to guess, I'd expect nginx is closing connections very frequently, potentially with you trying to do more concurrent RPCs than its MAX_CONCURRENT_STREAMS. There is a client-side race that can be hit here and you're already on grpc-java 1.30 which reduced the window. 1.34 had improvements to GOAWAY error reporting that now tell us a bit more of what was going on. I suggest upgrading to 1.36.2 or later, which had bug fixes related to GOAWAY error messages.

**Comment by hijerusalem** [comment] 2021-07-20 16:23
From my experience nginx will close connection due to the limit of `http2_max_requests` and `http2_max_concurrent_streams` in nginx.conf.

Before nginx closes connection, it seems nginx  will send only one GOAWAY to client which is not graceful according to https://github.com/grpc/grpc/issues/24237 and this behaviour  will cause `UNAVAILABLE: HTTP/2 error code: NO_ERROR Received Goaway` in client side.

If we use only one thread to send RPC in a loop with  [enableRetry](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#enableRetry--) turn on, despite nginx will close connection due to `http2_max_requests`, everything works fine, no error occurs.

But when we use multiple threads(`parallelStream`) to send concurrent rpcs to nginx, [enableRetry](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#enableRetry--) will only mitigate this issue can't fix it

**Comment by ejona86** [comment] 2021-07-20 22:16
> Before nginx closes connection, it seems nginx will send only one GOAWAY to client which is not graceful according to grpc/grpc#24237

Then the only options are to fix/improve nginx or require retries on the client-side.

**Comment by hijerusalem** [comment] 2021-07-21 02:50
> > Before nginx closes connection, it seems nginx will send only one GOAWAY to client which is not graceful according to [grpc/grpc#24237](https://github.com/grpc/grpc/issues/24237)
> 
> Then the only options are to fix/improve nginx or require retries on the client-side.

We did client-side retry by `enableRetry` when building channel, in my understanding enableRetry will turn on `transparent retry` and it works fine in case 1, single thread sends RPCs to Nginx in a loop.

But in case 2, use `parallelStream` to send concurrent RPCs to Nginx, `transparent retry` will only reduce error frequency, we can still see `UNAVAILABLE: HTTP/2 error code: NO_ERROR Received Goaway` occurs.

It's not uncommon that people use nginx as reverse proxy for their grpc services and C-core based gRPC such as python doesn't do a double goaway when they close connection (grpc/grpc#24237)

If client send councurrent RPCs to Nginx or C-core based gRPC with `MAX_CONNECTION_AGE`  set, they will probably encounter the same problem

So it would be great if gRPC built in retry support can fully handle this situation

**Comment by ejona86** [comment] 2021-07-21 17:29
Case 1 doesn't need `enableRetry` at all. There is no race in case 1.

In case 2, it is hard to say what is happening. I still recommend upgrading grpc-java to improve the error message.

> If client sends concurrent RPCs to Nginx or C-core based gRPC with MAX_CONNECTION_AGE set, they will probably encounter the same problem
>
> So it would be great if gRPC built-in transparent retry can fully handle this situation

It is _much_, _much_ simpler to fix the servers than fix the clients. The servers should be fixed independent of transparent retry, as you'll see increased latency when transparent retry is used. It is so very, very easy for a server to do the right thing here and it benefits all client implementations.

Our main interest in transparent retry is to resolve a client-side race, not for this GOAWAY race.

**Comment by hijerusalem** [comment] 2021-07-22 12:32
> Case 1 doesn't need `enableRetry` at all. There is no race in case 1.
> 
> In case 2, it is hard to say what is happening. I still recommend upgrading grpc-java to improve the error message.
> 
> > If client sends concurrent RPCs to Nginx or C-core based gRPC with MAX_CONNECTION_AGE set, they will probably encounter the same problem
> > So it would be great if gRPC built-in transparent retry can fully handle this situation
> 
> It is _much_, _much_ simpler to fix the servers than fix the clients. The servers should be fixed independent of transparent retry, as you'll see increased latency when transparent retry is used. It is so very, very easy for a server to do the right thing here and it benefits all client implementations.
> 
> Our main interest in transparent retry is to resolve a client-side race, not for this GOAWAY race.

Upgrade grpc-java to 1.37.0,  the error message is:

io.grpc.StatusRuntimeException: UNAVAILABLE: Abrupt GOAWAY closed sent stream. HTTP/2 error code: NO_ERROR

With a service config like this
```
{
  "methodConfig": [
    {
      "name": [
        {
          "service": "my.GRPCService"
        }
      ],

      "retryPolicy": {
        "maxAttempts": 2,
        "initialBackoff": "0.001s",
        "maxBackoff": "0.5s",
        "backoffMultiplier": 2,
        "retryableStatusCodes": [
          "UNAVAILABLE"
        ]
      }
    }
  ]
}
```

in case 2, using multiple threads(parallelStream) to send concurrent RPCs to nginx, no error occurs

I didn't expect the service config above would take effect,  because Retryable Status Codes section in [gRPC Retry Design](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#where-retries-occur) said
> When gRPC receives a non-OK response status from a server, this status is checked against the set of retryable status codes in retryableStatusCodes to determine if a retry attempt should be made.

Nginx didn't return unavailble status code, it simply sent GOAWAY frame to client and closed connection, so the methodConfig would not work in this circumstance.

Suprisingly, it workerd, maybe I misunderstood the grpc retry mechanism

**Comment by ejona86** [comment] 2021-07-22 15:46
> io.grpc.StatusRuntimeException: UNAVAILABLE: Abrupt GOAWAY closed sent stream. HTTP/2 error code: NO_ERROR

"Abrupt GOAWAY" means "the server didn't do a graceful shutdown with two GOAWAYs."

> in case 2, using multiple threads(parallelStream) to send concurrent RPCs to nginx, no error occurs

Excellent. Note: you may not even need the service config. See below.

> I didn't expect the service config above would take effect, because Retryable Status Codes section in gRPC Retry Design said... Nginx didn't return unavailable status code, it simply sent GOAWAY frame to client and closed connection

Exactly. If the server _actually_ responded then that paragraph would be applied.

What's happening in this case is [transparent retries](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#transparent-retries). GOAWAY has a Last-Stream-ID that informs gRPC that some RPCs were never processed. The gRPC client is able to then automatically retry that RPC. Note that the client will only do one transparent retry per RPC, although there's some talk of removing that limit.

**Comment by hijerusalem** [comment] 2021-07-23 03:00
> > io.grpc.StatusRuntimeException: UNAVAILABLE: Abrupt GOAWAY closed sent stream. HTTP/2 error code: NO_ERROR
> 
> "Abrupt GOAWAY" means "the server didn't do a graceful shutdown with two GOAWAYs."
> 
> > in case 2, using multiple threads(parallelStream) to send concurrent RPCs to nginx, no error occurs
> 
> Excellent. Note: you may not even need the service config. See below.
> 
> > I didn't expect the service config above would take effect, because Retryable Status Codes section in gRPC Retry Design said... Nginx didn't return unavailable status code, it simply sent GOAWAY frame to client and closed connection
> 
> Exactly. If the server _actually_ responded then that paragraph would be applied.
> 
> What's happening in this case is [transparent retries](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#transparent-retries). GOAWAY has a Last-Stream-ID that informs gRPC that some RPCs were never processed. The gRPC client is able to then automatically retry that RPC. Note that the client will only do one transparent retry per RPC, although there's some talk of removing that limit.

We always turn on [transparent retries](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#transparent-retries)  by [enableRetry](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html) with [maxRetryAttempts](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html) greater than one in our tests.

But without service config, we saw "io.grpc.StatusRuntimeException: UNAVAILABLE: Abrupt GOAWAY closed sent stream. HTTP/2 error code: NO_ERROR",  [transparent retries](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#transparent-retries) was not working

With service config, in theory, it would not make a difference, but in reality, it did make a difference, no Unavaialable Exception anymore

I'm confused

**Comment by ejona86** [comment] 2021-07-26 18:22
Note: there's no need to call maxRetryAttempts if you are okay with the default value of 5.

> But without service config, we saw "io.grpc.StatusRuntimeException: UNAVAILABLE: Abrupt GOAWAY closed sent stream. HTTP/2 error code: NO_ERROR", transparent retries was not working

Oh, this is because we are working around a nasty bug in Netty
https://github.com/grpc/grpc-java/blob/eb6764841b1771e64d222430de7a12c9a6b4ead7/netty/src/main/java/io/grpc/netty/NettyClientHandler.java#L817-L823
https://github.com/grpc/grpc-java/blob/eb6764841b1771e64d222430de7a12c9a6b4ead7/netty/src/main/java/io/grpc/netty/NettyClientHandler.java#L849-L855

That was fixed in 4.1.54, which gRPC hasn't yet upgraded to. Even after an upgrade, we'll probably need to keep that workaround in place for a while, as the failure mode is pretty ugly. Maybe we can figure out an alternative workaround.

**Comment by ejona86** [comment] 2021-07-30 19:59
I think we can change the workaround to only trigger if the HTTP/2 error-code is indicates an error (anything but NO_ERROR). That would workaround the Netty problem but allow transparent retries to function on servers that use abrupt GOAWAYs.

**Comment by ejona86** [comment] 2021-07-30 20:52
Filed https://trac.nginx.org/nginx/ticket/2224 for nginx's lack of double-GOAWAY.

**Closed** 2021-07-30 23:42 UTC
Labels: enhancement
