### ISSUE TITLE
Memory leaking when using ALPN

### ISSUE THREAD

**Issue by ohad7** [grpc/grpc-java#598] opened 2015-07-03 18:23 UTC
We're experiencing a slow memory leak with 0.7.1 when using ALPN and TLS. The server is built and started with this code : 
```
NettyServerBuilder builder = NettyServerBuilder.forPort(port);
definitions.forEach(builder::addService);
SslContext context = SslContextBuilder.forServer(keyCertPathprivateKeyPath).build();
builder.sslContext(context);
ServerImpl server = builder.build();
server.start();
```

This is the alpn version that we're using.
-Xbootclasspath/p:/usr/lib/java/alpn-boot-8.1.3.v20150130.jar"

Running a heap dump, we're seeing a huge amount of SSLEngineImpl objects stored in a concurrent hash map : 

![image](https://cloud.githubusercontent.com/assets/9012046/8503526/2c2acda0-21c9-11e5-9dfe-ba599b324c12.png)

The server is running behind a Amazon ELB. This might be related since the Amazon load balancer would open connections every once in a while to the server and to ping and make sure the server is live. Unfortunately it takes a long time to replicate, the server would run out of memory after 36 hours or so, but it doesn't seem like the number of requests

**Comment by ejona86** [comment] 2015-07-06 16:40
Thanks for the detailed report! Based on the heap alone, it would seem very obvious that `APLN.remove()` isn't getting called. It does seem that Netty delays calling it, but it should still happen at Netty's Channel shutdown (based on looking at the JdkAlpnSslEngine and SslHandler).

@nmittler, could you take a look at this?

**Comment by nmittler** [comment] 2015-07-06 18:59
FYI, I just raised https://github.com/netty/netty/issues/3941 to discuss this with the Netty folks.

**Comment by nmittler** [comment] 2015-07-06 19:26
@ohad7 I wonder if you might be able to replicate this in a stand-alone application? If you just open up a bunch of connections and shut them down, do you still see entries in the hash map? Oh and BTW, what version of Netty are you using?

**Comment by ohad7** [comment] 2015-07-06 19:41
I'm using grpc 0.7.1 with netty 4.1.0.Beta5

Unfortunately I haven't been able to reproduce it locally - My best bet was on the fact that the backend is behind an Amazon load balancer, and that perhaps this is what causing the leak. Looking at the list of connections it seems that the load balancer keeps the connections open and does not open/close them for every request : 

[ohad@ip-172-31-36-104 ~]$ netstat -na | grep 5050
tcp        0      0 :::5050                     :::*                        LISTEN      
tcp        0      0 ::ffff:172.31.36.104:5050   ::ffff:172.31.47.187:64511  ESTABLISHED 
tcp        0      0 ::ffff:172.31.36.104:5050   ::ffff:172.31.47.187:3210   ESTABLISHED 
tcp        0      0 ::ffff:172.31.36.104:5050   ::ffff:172.31.34.69:28884   ESTABLISHED 
tcp        0      0 ::ffff:172.31.36.104:5050   ::ffff:172.31.32.114:4187   ESTABLISHED 
tcp        0      0 ::ffff:172.31.36.104:5050   ::ffff:172.31.32.114:35650  ESTABLISHED 
tcp        0      0 ::ffff:172.31.36.104:5050   ::ffff:172.31.23.146:8871   ESTABLISHED 
tcp        0      0 ::ffff:172.31.36.104:5050   ::ffff:172.31.23.146:11548  ESTABLISHED 
tcp        0      0 ::ffff:172.31.36.104:5050   ::ffff:172.31.25.232:23969  ESTABLISHED 
tcp        0      0 ::ffff:172.31.36.104:5050   ::ffff:172.31.25.232:45834  ESTABLISHED 
tcp        0      0 ::ffff:172.31.36.104:5050   ::ffff:172.31.34.69:50627   ESTABLISHED 
tcp        0      0 ::ffff:172.31.36.104:5050   ::ffff:172.31.21.41:17338   ESTABLISHED 
tcp        0      0 ::ffff:172.31.36.104:5050   ::ffff:172.31.21.41:49924   ESTABLISHED 

and this stays constant for a few minutes until a connection is arbitrarily closed and replaced with a different connection. 

I haven't tried to replicate this behavior - I was merely trying to open and close connections.

**Comment by nmittler** [comment] 2015-07-06 20:36
@ejona86 and I discussed a bit offline and we think we have some ideas as to what's going on here. In 0.7.1, we have custom code to handle ALPN and are not relying on Netty. Our code assumes that the client is connecting via ALPN, so if no negotiation occurs it seems that we will leak the engine. That being said, it seems that the Amazon ELB is connecting to your backend via TLS but not using ALPN, thus causing the leak.

I think I should be able to cook up a patch for 0.7.x to fix this.  In HEAD, we're no longer using this custom code and are just using Netty's built-in TLS support.  If it's not too much trouble for you, would you mind trying out HEAD to see if this resolves the issue?  I'd hate to fix it in 0.7.x and then reintroduce problems when you upgrade to 0.8.x.

**Comment by nmittler** [comment] 2015-07-07 14:38
@ohad7 I've committed the change (492128e) to the v0.7.x branch. Give that a shot - if that fixes your problem, we can cut a 0.7.2 release with the patch.

**Comment by ohad7** [comment] 2015-07-07 15:42
Will do. Thanks!

On Tuesday, July 7, 2015, Nathan Mittler <notifications@github.com> wrote:

> @ohad7 <https://github.com/ohad7> I've committed the change (492128e
> <https://github.com/grpc/grpc-java/commit/492128e23c559c50e884c4d2b557e0ed0e33ecc4>)
> to the v0.7.x branch. Give that a shot - if that fixes your problem, we can
> cut a 0.7.2 release with the patch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grpc/grpc-java/issues/598#issuecomment-119223940>.
>


-- 
ohad

**Comment by nmittler** [comment] 2015-07-07 17:04
@ohad7 FYI, I've just pushed Maven snapshots for 0.7.2 and 0.8.0.

**Comment by ohad7** [comment] 2015-07-07 20:29
@nmittler Deployed to a production machine, will have results in a few hours.

**Comment by ohad7** [comment] 2015-07-07 22:41
@nmittler memory footprint looking great : 

grpc-0.7.1 : 
jstat -gc 28443 30000
 S0C    S1C    S0U    S1U      EC       EU        OC         OU       MC     MU    CCSC   CCSU   YGC     YGCT    FGC    FGCT     GCT   
512.0  512.0   0.0   410.4   2560.0   2397.5  1058816.0  1049521.9  54616.0 53829.8 6784.0 6633.4   1873   14.858  22      5.331   20.189
512.0  512.0  397.6   0.0    2560.0   939.0   1086976.0  1079357.2  54616.0 53832.8 6784.0 6633.4   1968   15.585  23      5.624   21.209
512.0  512.0  478.2   0.0    2560.0   1133.5  1139712.0  1124997.5  54616.0 53833.8 6784.0 6633.4   2116   16.736  25      6.297   23.033
512.0  512.0  461.6   0.0    2560.0   981.6   1164800.0  1152323.7  54616.0 53833.8 6784.0 6633.4   2204   17.436  26      6.551   23.987
512.0  512.0  410.4   0.0    2560.0   258.2   1188864.0  1173772.8  54616.0 53833.8 6784.0 6633.4   2274   18.002  27      6.855   24.857
512.0  512.0  446.2   0.0    2560.0   992.8   1188864.0  1182736.6  54616.0 53833.8 6784.0 6633.4   2300   18.213  27      6.855   25.069


grpc-0.7.2 : 

jstat -gc 28118 30000
 S0C    S1C    S0U    S1U      EC       EU        OC         OU       MC     MU    CCSC   CCSU   YGC     YGCT    FGC    FGCT     GCT   
9216.0 10240.0 7636.6  0.0   134144.0 95835.7   77312.0    19163.1   49240.0 48489.7 6528.0 6344.1     22    0.178   2      0.132    0.309
10240.0 2048.0  0.0   1739.3 129536.0 77269.6   77312.0    24440.3   50520.0 49657.9 6528.0 6364.2     23    0.191   2      0.132    0.323
6144.0 10240.0 1561.7  0.0   125440.0 75987.2   77312.0    24536.3   50776.0 50101.2 6528.0 6368.6     24    0.195   2      0.132    0.327
9728.0 1536.0  0.0   1530.8 121344.0 100330.9  77312.0    24544.3   51032.0 50164.7 6528.0 6368.6     25    0.199   2      0.132    0.331
9728.0 1536.0  0.0   1448.0 114176.0  9356.2   77312.0    24560.3   51032.0 50262.5 6528.0 6370.1     27    0.206   2      0.132    0.338
5120.0 9216.0 1576.0  0.0   110592.0 90636.2   77312.0    24560.3   51032.0 50362.1 6528.0 6370.1     28    0.210   2      0.132    0.342
8192.0 1536.0  0.0   1366.4 100864.0 32652.5   77312.0    24584.3   51288.0 50534.0 6528.0 6371.1     31    0.221   2      0.132    0.353
5120.0 8192.0 1397.3  0.0   97792.0  33991.8   77312.0    24584.3   51288.0 50562.2 6528.0 6372.6     32    0.225   2      0.132    0.357


over a period of 2 hours, OC and OU is stable, number of YGCT is 10 compared to 437 (!), and no FGC compared to 10 FGC in the old version.

I think we can safely assume this is resolved.

Thank you so much!

**Comment by ohad7** [comment] 2015-07-07 22:43
cc @brunofr @danageva @roiaddi

**Comment by nmittler** [comment] 2015-07-08 14:10
@ohad7 That's great! :)

Would you be able to try the same experiment with 0.8.0-SNAPSHOT? It would be good to know that HEAD doesn't introduce a regression here.

**Comment by ohad7** [comment] 2015-07-08 14:12
Sure thing. I'll stabilize a version on our end and push. Will let you know once I have results.

**Comment by nmittler** [comment] 2015-07-08 14:22
Awesome, thanks!

**Comment by nmittler** [comment] 2015-07-13 16:14
@ohad7 FYI I'm working on releasing 0.7.2 today.  Sorry for the delay ... this had fallen off my radar.

**Comment by nmittler** [comment] 2015-07-13 21:37
Closing this issue since 0.7.2 has been verified.

@ohad7 were you able to verify that 0.8.0-SNAPSHOT is ok?

**Closed by nmittler** 2015-07-13 21:37 UTC
Labels: bug
