### ISSUE TITLE
switch to a logging library from JUL

### ISSUE THREAD

**Issue by jonnyzzz** [grpc/grpc-java#2389] opened 2016-10-30 11:51 UTC
Currently JUL logger is used. It cannot be controlled well in multi-classloader applications. For example Servlet API containers. 

From a web application point of view it's a hacky to configure JUL explicitly from there. The best way to configure logging in that case is to isolate if from container logging (and possible other applications). 

Isolation is implemented as easy as including logger libraries into application package. This makes a container to load logger classes along with the app, and thus all logger configuration that is done on application level is not shared to the whole JVM.

This trick does not work well with java.util.logging (JUL). It is a part of JVM, so one cannot load those classes on application-level classloader. So any attempt to configure JUL from application will make this visible to the whole JVM and vice versa. 

Switching to any Logging library (which in not a part of JRE) will solve the issue and adds more flexibility for library users. Moreover, it's likely such library is already in classpath of most apps. 

For example, slf4j-api is the minimalistic logging library that allows to use any logging backend

**Comment by ejona86** [comment] 2016-10-30 23:41
Duplicate of #1577

**Closed by ejona86** 2016-10-30 23:41 UTC
