### ISSUE TITLE
Http2Exception frame length exceeds maximum

### ISSUE THREAD

**Issue by mfirry** [grpc/grpc-java#4065] opened 2018-02-10 14:23 UTC
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.6.1

### What did you expect to see?

We noticed a sudden disconnection and the only log I could grab from is the following coming from the client side  

> Caused by: io.netty.handler.codec.http2.Http2Exception: Frame length: 1638400 exceeds maximum: 16384

How can I debug this better? Is this frame legth set somewhere? Who can control if it exceeds.

**Comment by carl-mastrangelo** [comment] 2018-02-12 18:59
You could try turning on frame logging:

https://gist.github.com/carl-mastrangelo/49f6d6a8ff29200fcb7d9e25e473b2d0

It's odd that netty would break the frame length.   Also, would it be possible for you to try with v1.9.1 ?

**Comment by mfirry** [comment] 2018-02-22 15:47
I'll try and upgrade this week.

**Comment by ejona86** [comment] 2018-03-03 00:51
1638400 is suspicious, as it is exactly `100 * 16384`. This error should not really ever happen, as the frame size is negotiated ahead-of-time. Generally this is not a bug on the side you see the error. What software was this connected to (if client, what server; if server, what client)? Also, were there any HTTP/2 proxies involved?

**Comment by mfirry** [comment] 2018-03-03 08:57
Setup was mentioned here https://github.com/grpc/grpc-java/issues/3684#issuecomment-343647176 

Server is a Scala app running Marathon-lb (a wrapper around HAProxy).
Client runs on Tomcat.

**Comment by ejona86** [comment] 2018-03-06 16:06
@mfirry, I'd suggest filing a bug against HAProxy (assuming it is in HTTP/2 mode; not TCP proxying).

**Comment by mfirry** [comment] 2018-03-06 16:52
I don't think HAProxy supports HTTP2 yet

**Comment by ejona86** [comment] 2018-03-06 17:25
[HAProxy seems to support HTTP/2](https://www.haproxy.com/blog/whats-new-haproxy-1-8/) since 1.8.

@mfirry, so you're doing TCP proxying via HAProxy with gRPC Java on client-side and server-side? I see that server-side is plain-text; is the client plain-text as well? (As in you aren't doing TLS stripping in the proxy.)

**Comment by mfirry** [comment] 2018-03-06 17:31
Not doing tls right now

**Comment by mfirry** [comment] 2018-03-06 17:40
Yes, grpc-java both sides

**Comment by ejona86** [comment] 2018-03-06 23:35
Hmmm... There's not much to go on. We've seen this error several times, but it's yet to be gRPC's fault. I've seen broken HTTP/2 implementations and I've seen the client connecting to the wrong port/protocol.

Since it is plain-text, that means there are fewer verifications. 1638400 = 0x190000 which could maybe be trash. Nothing jumps out.

Frame logging as @carl-mastrangelo mentioned or a reproduction case would be helpful. Or sometimes simply knowing how you reproduce it can be enough.

**Comment by mfirry** [comment] 2018-03-07 02:47
Thanks a lot for your time. I’ll see if I can reproduce it and let you know.

**Comment by ejona86** [comment] 2018-04-02 21:28
@mfirry, sorry that we couldn't figure this out more. If you end up seeing more you can report back on this issue. Closing for the moment since there's not much for us to do.

**Closed by ejona86** 2018-04-02 21:28 UTC
