### ISSUE TITLE
okhttp: race between receiving data and closing deframer

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1569] opened 2016-03-21 19:24 UTC
As [reported on SO](http://stackoverflow.com/q/36123530/4690866):
```
java.lang.IllegalStateException: MessageDeframer is already closed
    at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
    at io.grpc.internal.MessageDeframer.checkNotClosed(MessageDeframer.java:222)
    at io.grpc.internal.MessageDeframer.deframe(MessageDeframer.java:168)
    at io.grpc.internal.AbstractStream.deframe(AbstractStream.java:276)
```

When receiving a DATA frame, it seems there is a [race between](https://github.com/grpc/grpc-java/blob/v0.13.2/okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java#L659) getStream() and calling transportDataReceived(). Although I wouldn't expect to trigger that race often.

**Comment by makdharma** [comment] 2016-06-23 18:59
@zsurocking Please take a look

**Comment by ejona86** [comment] 2016-06-28 17:50
@zsurocking, @carl-mastrangelo has some time and this seems easy to move to someone else.

**Comment by carl-mastrangelo** [comment] 2016-07-08 18:45
From looking at this, it seems like it must be closed already by an application thread.  From my reading, okhttp will consume the whole data frame from the wire before handing it to the stream.  If there is an error reading from the wire, the `transportDataRecieved`() method won't be called.  

What closed it in the first place is a mystery.  I suppose that detail is long gone.

**Comment by ejona86** [comment] 2016-07-08 19:05
I think this may (now) be fine.

The only way to close the deframer is via [`closeDeframer()`](https://github.com/grpc/grpc-java/blob/v0.15.0/core/src/main/java/io/grpc/internal/AbstractStream.java#L267). Which appears is only called from [`closeListener()`](https://github.com/grpc/grpc-java/blob/v0.15.0/core/src/main/java/io/grpc/internal/AbstractClientStream.java#L263) which is [only called after `transportReportStatus()` changes the `inboundPhase` to `STATUS`](https://github.com/grpc/grpc-java/blob/v0.15.0/core/src/main/java/io/grpc/internal/AbstractClientStream.java#L230).  [`inboundDataReceived()` checks the `inboundPhase()`](https://github.com/grpc/grpc-java/blob/v0.15.0/core/src/main/java/io/grpc/internal/AbstractClientStream.java#L138) and does nothing if it is `STATUS`.

This is still too hard to reason about with the crossing of the threads. We really need to swap to AbstractStream2 to split state based on threads.

@carl-mastrangelo, do you agree it appears fine?

**Comment by carl-mastrangelo** [comment] 2016-07-08 19:39
After looking through this issue, it doesn't seem to be possible (the code may have changed since this was reported).  When trying to make a test that reproduces this issue, it was not actually possible to cause this to happen.  The `data()` call in `OkHttpClientTransport` holds the lock when calling the stream.   Closing the stream early can only be done from a network thread, which also holds the lock, which closes the deframer.  

This should make it impossible to cause this issue, because the stream does check if it is closed when receiving a data frame.  I am going to mark this as closed, since I cannot reproduce it, and it doesn't seem possible based on the source code.

**Closed by carl-mastrangelo** 2016-07-08 19:39 UTC
Labels: android, bug, okhttp, P2
