### ISSUE TITLE
Authentication failure with bidi streaming is not notifying the client

### ISSUE THREAD

**Issue by rimar** [grpc/grpc-java#6964] opened 2020-04-22 07:33 UTC
### What version of gRPC-Java are you using?
1.28.0

### What is your environment?
Java version: 1.8.0_241, vendor: Oracle Corporation,
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"

### What did you expect to see? && ### What did you see instead?

I would expect that when calling 

```java
serverCall.close(Status.UNAUTHENTICATED.withDescription(e.getMessage()).withCause(e), new Metadata());
            return new ServerCall.Listener<ReqT>() {
                // noop
            };
```
inside ServerInterceptor, that client's onError or onComplete will be called in ClientResponseObserver. But there is no notification sent to the client whatsover. With blocking GRPC calls there is an exception raised on the client side when trying to call the method e.g. if changing https://github.com/grpc/grpc-java/tree/master/examples/example-jwt-auth to fail authentication, but not with bidi streaming.

### Steps to reproduce the bug

Exception stack trace on the server side:
```
617 [grpc-default-executor-0] ERROR com.snc.occultus.commons.transport.AuthorizationServerInterceptor - Server AUTH failed
com.snc.occultus.commons.transport.AuthenticationException: always fail
	at com.snc.occultus.commons.transport.GrpcClientServerTest$1.authenticate(GrpcClientServerTest.java:214)
	at com.snc.occultus.commons.transport.AuthorizationServerInterceptor.doAuth(AuthorizationServerInterceptor.java:45)
	at com.snc.occultus.commons.transport.AuthorizationServerInterceptor.interceptCall(AuthorizationServerInterceptor.java:20)
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:229)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:648)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startCall(ServerImpl.java:626)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$1900(ServerImpl.java:417)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInternal(ServerImpl.java:556)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInContext(ServerImpl.java:531)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by voidzcy** [comment] 2020-04-24 00:53
It's probably because you shut down the client too early (before receiving result from server).

I guess you just modified the jwt-auth example by changing its [blockingStub](https://github.com/grpc/grpc-java/blob/95b0550c591f6398593e712635bade46b6832106/examples/example-jwt-auth/src/main/java/io/grpc/examples/jwtauth/AuthClient.java#L60) to an async stub (i.e., `GreeterGrpc.newStub(channel)`)  and invoke the RPC with `stub.sayHello(request, responseObserver)` where `responseObserver` is your client side response handler. The problem is you need to keep your client process running after the request is sent. You can verify its behavior by putting an infinite loop after the line invoking the streaming RPC.

**Comment by rimar** [comment] 2020-04-24 08:58
I actually do have an endless loop on the client side waiting to receive the error
here's the client code:
`
LogStreamerGrpc.LogStreamerStub stub = LogStreamerGrpc.newStub(channel);
        if (glideCredentials != null) {
            stub = stub.withCallCredentials(glideCredentials);
        }
        ClientResponseObserver<DataInputOutput, Response> observer = new ClientResponseObserver<DataInputOutput, Response>() {
            ClientCallStreamObserver<DataInputOutput> requestStream;
            Thread loopThread;

            @Override
            public void beforeStart(ClientCallStreamObserver<DataInputOutput> requestStream) {
                debug("BEFORE START");
                this.requestStream = requestStream;
                requestStream.setOnReadyHandler(() -> {
                    loopThread = Thread.currentThread();
                    debug("ON READY");
                    try {
                        while (requestStream.isReady() && active) {
                            DataInputOutput event = inQueue.take();
                            requestStream.onNext(event);
                        }
                    } catch (InterruptedException e) {
                        log.error( "INTERRUPTED!!!", e);
                    }
                    debug("ON READY HANDLER EXITED");
                });
            }

            @Override
            public void onNext(Response value) {
                // For now server response has no use
                log.info("Got a message from server: {}", value);
            }

          
            @Override
            public void onError(Throwable t) {
                log.error("Got a error on the gRPC channel: ",  t);
            }
`

And the test code does not exit too - there's an infinite loop there waiting to get the error.
`
        BlockingQueue<DataInputOutput> in2 = new LinkedBlockingQueue<>();
        BlockingQueue<DataInputOutput> out2 = new LinkedBlockingQueue<>();
        GrpcClient client2 = new GrpcClient(HOST, 50052, in2, false);
        client2.setCredentials(new GlideCredentials("usr", "pwd", "123"));
        client2.setDebug(true);
        GrpcServer server2 = new GrpcServer(50052, out2);
        server2.setGlieAuthenticator(new GlideAuthenticator() {
            @Override
            public void authenticate(String userName, String password, String midId) throws AuthenticationException {
                throw new AuthenticationException("always fail");
            }
        });
        server2.start();
        client2.connect();
        in.put(msg1k());
        in.put(msg1k());
        in.put(msg1k());
        while (client.getConnectivityState() != ConnectivityState.TRANSIENT_FAILURE) {
            Thread.sleep(1000);
            System.out.println("STATE: " + client2.getConnectivityState());
        }
`

**Comment by voidzcy** [comment] 2020-04-24 17:43
It's unclear how `GrpcServer#setGlieAuthenticator(...)` is implemented. So I am not able to tell anything about that part.

Btw, I noticed that you run your client and server in the same process and your observation is client side not receiving error notification for authentication failures. It is likely that the client is blocked somewhere because of threading issues.

As I mentioned above, you can try out the jwt-auth example by changing it's blockingStub to an async stub and experiment with the server streaming RPC of `sayHello` (there is a server streaming signature generated for unary RPC definitions). Put an infinite loop to keep client running. You will see `onError` is invoked with `UNAUTHENTICATED` on the client side.

**Comment by rimar** [comment] 2020-04-27 10:39
Hi, thanks a lot for looking into this. Your help is really appreciated. You are right, i do receive onError callback on the client when i modify the jwt-auth example. I think the problem with my implementation was that it did the send loop inside the onReadyHandler set in the beforeStart callback. Now i moved the send loop to a separate thread and all seems to work as expected.

Thanks again.
Yuval

**Comment by voidzcy** [comment] 2020-04-29 17:17
Closing as the problem seems to be resolved.

**Closed by voidzcy** 2020-04-29 17:17 UTC
Labels: bug
