### ISSUE TITLE
HTTP1.x Support for grpc-java

### ISSUE THREAD

**Issue by hanjiezm** [grpc/grpc-java#4067] opened 2018-02-12 09:22 UTC
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.8.0

Since grpc server do not support http1 stream, I have to use a web server in my application, for health check and some debug method.

Will it be possible to support this feature? When

**Comment by carl-mastrangelo** [comment] 2018-02-12 19:01
HTTP/1.1 upgrade might be possible, but using HTTP/1.1 directly would not.   The http protocol does not allow gRPC to multiplex RPCs or do flow control, both of which are needed for normal operation.

**Comment by ejona86** [comment] 2018-03-03 00:45
@hanjiezm, you're not asking for HTTP/1 for grpc, right? You're asking to be able to do other HTTP/1 traffic on the same port as gRPC, right?

If so, this is likely a duplicate of #3458

**Comment by ejona86** [comment] 2018-03-08 21:51
Closing as a duplicate of #3458

**Closed by ejona86** 2018-03-08 21:51 UTC
