### ISSUE TITLE
tls handshake error details are not reported to client code

### ISSUE THREAD

**Issue by risenberg** [grpc/grpc-java#3286] opened 2017-07-27 16:55 UTC
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.3.0

### What JVM are you using (`java -version`)?
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

### What did you do?
If possible, provide a recipe for reproducing the error.
Here is the code for reproducing the issue (I do not attach the proto definitions, you can replace them with any):
```
import io.grpc.ManagedChannel;
import io.grpc.netty.GrpcSslContexts;
import io.grpc.netty.NettyChannelBuilder;
import org.testng.annotations.Test;

import javax.net.ssl.KeyManagerFactory;
import javax.net.ssl.SSLContext;
import javax.xml.bind.DatatypeConverter;
import java.io.*;
import java.net.InetSocketAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.security.KeyFactory;
import java.security.KeyStore;
import java.security.cert.Certificate;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.security.interfaces.RSAPrivateKey;
import java.security.spec.KeySpec;
import java.security.spec.PKCS8EncodedKeySpec;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;

public class GrpcTest {
    @Test
    public void test() throws Exception {
        InetSocketAddress address = new InetSocketAddress("localhost", 11111);
        ScheduledExecutorService executorService = Executors.newScheduledThreadPool(1);

        CertificateFactory cf = CertificateFactory.getInstance("X.509");
        InputStream is = new FileInputStream("server.pem");
        X509Certificate cert = (X509Certificate)cf.generateCertificate(is);

        String keyPath = "server.key8";
        File privKeyFile = new File(keyPath);
        BufferedInputStream bis =  new BufferedInputStream(new FileInputStream(privKeyFile));
        byte[] privKeyBytes = new byte[(int)privKeyFile.length()];
        bis.read(privKeyBytes);
        bis.close();
        String base64 = new String(privKeyBytes);
        KeyFactory keyFactory = KeyFactory.getInstance("RSA");
        KeySpec keySpec = new PKCS8EncodedKeySpec(DatatypeConverter.parseBase64Binary(base64));
        RSAPrivateKey privKey = (RSAPrivateKey) keyFactory.generatePrivate(keySpec);

        KeyStore keyStore = KeyStore.getInstance(KeyStore.getDefaultType());
        keyStore.load(null);
        keyStore.setKeyEntry("key", privKey, "".toCharArray(), new Certificate[]{cert});
        KeyManagerFactory kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
        kmf.init(keyStore, "".toCharArray());

        SSLContext serverContext = SSLContext.getInstance("TLS");
        serverContext.init(kmf.getKeyManagers(), null, null);

        executorService.submit(() -> {
            try {
                ServerSocket serverSocket = serverContext.getServerSocketFactory().createServerSocket();
                serverSocket.bind(address);
                Socket socket = serverSocket.accept();
                socket.getOutputStream().write(0);
                socket.getOutputStream().flush();
            } catch (Exception e) {
                e.printStackTrace(System.err);
            }
        });

        ManagedChannel channel = NettyChannelBuilder.forAddress(address)
                .sslContext(GrpcSslContexts.forClient().build())
                .build();
        NodeTrackerServiceGrpc.NodeTrackerServiceBlockingStub stub = newBlockingStub(channel);
        stub.handshake(NodeTracker.TReqHandshake.newBuilder().setFqdn("fqdn").build());
    }
}
```

server.pem:
```
-----BEGIN CERTIFICATE-----
MIICuzCCAaMCAhACMA0GCSqGSIb3DQEBCwUAMB4xDzANBgNVBAoMBllhbmRleDEL
MAkGA1UEAwwCY2EwIBcNMTcwNzI3MTU1NjA3WhgPMjExNzA3MDMxNTU2MDdaMCYx
DzANBgNVBAoMBllhbmRleDETMBEGA1UEAwwKc2VydmVyLnRsZDCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBANXXpA3bc6SDJCqzJ8CnXZiATvyDP0i5HSfx
QQ20dQXkkYtmcC5B/kacGs5vSiPTsqg91fQEG6mZEa4Bs8tZeI5CIhyvXLkq+i/G
N90dcLkOKdGkFmxe3GjppZV7UZXHszEXRHuay5ICb6o6ZKBJxIPsOQMUL6gZP3as
iM6aAMJEMjA/wqQCXTqVJgQqDTcoOQAOBGMqJFB378M3h8EdXOeAWZPb42BDd6iC
/VD8FUyfR5L6zndqi67l0k5xncJc/t6+UDPLaSTUI8PBuvGKefjw8gzZ7QVUnRRm
9WUlZRZfYr9Tdp3pwWx7Kk9vMXZvL7E5T/MBZNVD6g2lWQBpZZMCAwEAATANBgkq
hkiG9w0BAQsFAAOCAQEAl4rzLPeR8CTd/jilMGNYlJS7CR5SlI1PD/NcW9V7R6aP
oRGMAonRj0tS6nDI2gOU5/raMbX2Fxe2d43XcHEROTn6VTeS3itWlqoaeqIlIqI1
jUh0T62H90VEx2DB2N+j379JX8nVbaLlXIRdw5QvYyGdP+QttSx2hGsqJ6+5UEMZ
bMGBV4bufksWToQP/mkK3i15K9QAo0o7j7zeD0gbevBCum+myNqJ2gUdcakX9bd1
ERHCcHqgF/Ne1nlD7TdkRayf8WvgynpzG0NV3BrEo3pXeDqJfseBU8TWxHginMbD
Uxv6Y8cACW40DPGGOHMqRuRrbnclfr8TvgNfHRTLCw==
-----END CERTIFICATE-----
```

server.key8:
```
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDV16QN23OkgyQq
syfAp12YgE78gz9IuR0n8UENtHUF5JGLZnAuQf5GnBrOb0oj07KoPdX0BBupmRGu
AbPLWXiOQiIcr1y5KvovxjfdHXC5DinRpBZsXtxo6aWVe1GVx7MxF0R7msuSAm+q
OmSgScSD7DkDFC+oGT92rIjOmgDCRDIwP8KkAl06lSYEKg03KDkADgRjKiRQd+/D
N4fBHVzngFmT2+NgQ3eogv1Q/BVMn0eS+s53aouu5dJOcZ3CXP7evlAzy2kk1CPD
wbrxinn48PIM2e0FVJ0UZvVlJWUWX2K/U3ad6cFseypPbzF2by+xOU/zAWTVQ+oN
pVkAaWWTAgMBAAECggEAIgXEITxIIuWGjJCig4FdX9USPBS5rd1d6Sv2OLL8Z2qd
SXuL36A6T4uorC2Csz6MTz4/WyqIKCylZnT44SKkDqYw/TVdYEyZL56u5qw3cgnx
11vvAWD6WmrKIIVVTqpONUJJcA0J1Ho0v/W4atQxwveDfpzolCsoML50qcJQ2pdq
es/Ph6xuVI1Nk2LZD+bhiUkSqBrVVKBB15eXermTk8m8go4bIntksEHCyBMio043
iEUrb3OFnWq1XTzC3RuoVV/HR/NiIZo6ZCRpwv7RQQ+4W1st+rLnTApHbPe8kT57
3SAuJTda46FYgmTVLOoW5yTHu07EygwB10I0voh3aQKBgQD4bhtCF1YNUPG7QL6s
7WkHDtK6fKO2zxlH/pJoVyIb15EqVHikRCpz27RX3gFEUGOUgoG4B7/U9MzXn9z9
nd/w/xEj4bRn/tdCyzlJkaiYfllPgKiUMD87XhzD5wtsWy4DdhVBOv3ScSiokSxV
yHh8aYGLf6iWb0nBqMwr5MrPNQKBgQDcW7sFF4nElR20pZp0hld6aih1f/X60DcX
VaLpS107euXr2J+5jxWr8DMcVQ2njktkVv4dnVV+TwtiC7OuT+IMf4FCOjWYBMK3
UnhwA6CqXQhj8GY/YBLBOCdkaBlkztuDMLC19CHe8ypWPnxq8dFi5HBTPaPh/r4V
Kdl+zDCSpwKBgQDZqjdNz/6AilRSOacXAqhMG8u8w2n5yTigYMdMjlN/S3+QNBTD
8Em122EGv6gif8DQJQyc/oUwhBBaOGI7ADFvCTyuUJptp9ZZWo/mCq5KdiGwS8zo
keFFFe9kIbJbjQQi2jpDPfmYgbcbAp9yxcPzVcnAPOisbfOUr128c6jSpQKBgB2S
Zd/CD+gExu7GRpsaqESyWGmkWYNmS+5ivLEoPwPLc22aLZ0+WX8whftoYqO40d9O
WV3qDl4cB4AJ5/wdlk1tExCrNSQIh4UImUcXBYm3YHfg/CfHId0yRv8PhVDk/cp2
T1CryZvc8DKQwiur9hiaZYSWQhcDE8lNS3Xbuy0DAoGALVlL6q6Oc4LvSIQn1v/9
II2qdJoP0yhjn+Q8nUBqsyIIS0JcmSL2yHDFT9nqa9mOQAe43W1pAGECc01Ig9n3
Q2RxbAIIFUKSda4uxzz64Ss3TgaZhRrWenOUXJTdZyheeboKFKUX2QysMQ+gkUKj
RbWIOMUIa54H7On0oWR6f2s=
```

### What did you expect to see?
I expected to get a StatusException with an SSLException as a cause containing details of what has failed.

### What did you see instead?
I get 
`io.grpc.StatusRuntimeException: UNAVAILABLE: Channel closed while performing protocol negotiation`
without any cause. By turning on debug logging for netty I can see the cause
```
2017-07-27 19:38:25.256 [grpc-default-worker-ELG-2-1] DEBUG i.n.h.s.ReferenceCountedOpenSslContext - verification of certificate failed
java.security.cert.CertificateException: No name matching localhost found
```
But without debug logging there is no way to see this exception, and even now I cannot match the StatusException with CertificateException.

Looks like this code:
```
                    // SSLEngine has been closed already.
                    // Any further write attempts should be denied.
                    pendingUnencryptedWrites.removeAndFailAll(SSLENGINE_CLOSED);
```
in SSLHandler causes termination of all pending write futures, including the result of `channel.write(NettyClientHandler.NOOP_MESSAGE)` in `NettyClientTransport::start`, with a default exception, without passing the actual error to them.

**Comment by ejona86** [comment] 2017-09-12 17:50
@risenberg, I've improved error handling in a couple different ways. This may be fixed in later releases, especially (the upcoming) 1.7. Could you try once with 1.6 and see if it is better?

**Comment by risenberg** [comment] 2017-09-13 20:23
Checked with 1.6.1, the behaviour is still the same as in 1.3.0

**Comment by ejona86** [comment] 2017-09-13 20:58
@risenberg, I'm not reproducing the unhelpful error with 1.6.1. That may be because the problem is timing-based, and so on my machine it is racing differently.

Could you try testing with [my repro-3286 branch](https://github.com/ejona86/grpc-java/tree/repro-3286) (run gradle test in the examples/ directory)?

I get this exception:
```
io.grpc.StatusRuntimeException: UNAVAILABLE
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:210)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:191)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:124)
	at io.grpc.examples.helloworld.GreeterGrpc$GreeterBlockingStub.sayHello(GreeterGrpc.java:159)
	at GrpcTest.test(GrpcTest.java:70)
	...
Caused by: javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:647)
	at io.netty.internal.tcnative.SSL.readFromSSL(Native Method)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:481)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1019)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1126)
	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:210)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1215)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1127)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1162)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:934)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	... 1 more
Caused by: java.security.cert.CertificateException: No name matching localhost found
	at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:221)
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:95)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:252)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136)
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:221)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:643)
	... 26 more
```

**Comment by risenberg** [comment] 2017-09-14 12:11
I've found the problem in my setup, my netty version was pinned to 4.1.13.Final. Updating it to 4.1.14.Final produced the error message you posted, even with grpc 1.5.0. Looks like it is related to this change - https://github.com/netty/netty/pull/6720/commits/38cbf344dac410d19385a75c882ef02e668150c1

**Comment by ejona86** [comment] 2017-09-14 15:49
@risenberg, ah, yeah, incompatible Netty version can cause weird behavior. That might have been because of an incompatible mix of Netty and tcnative versions, but if updating to 4.1.14 fixes it, then that works for me.

**Closed by ejona86** 2017-09-14 15:49 UTC
Labels: usability

**Comment by ejona86** [comment] 2017-09-14 15:52
PS @risenberg, thanks so much for the reproduction case. It would have been _really_ helpful if there was a bug and it greatly eased looking into it. I am sorry it took so long to respond.

**Comment by nddipiazza** [comment] 2018-01-23 05:06
I'm also getting this generic error message with no cause. I'm on netty 4.1.14.Final, grpc 1.9.0, nettyTcNativeVersion 2.0.7.Final
How do I get this useful stacktrace?
