### ISSUE TITLE
RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor

### ISSUE THREAD

**Issue by antranvn** [grpc/grpc-java#7028] opened 2020-05-10 15:47 UTC
### What version of gRPC-Java are you using?
'io.grpc:grpc-okhttp:1.29.0'
### What is your environment?

Android 9
### What did you expect to see?
No exception
### What did you see instead?
RejectedExecutionException
### Steps to reproduce the bug
Add Google Cloud Speech client into the android app.

Full crash log.
```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@fd8f90 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@25a7a53[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 4]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2085)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
        at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:334)
        at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
        at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:654)
        at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:93)
        at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:86)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closedInternal(ClientCallImpl.java:755)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closed(ClientCallImpl.java:705)
        at io.grpc.internal.DelayedStream$DelayedStreamListener$5.run(DelayedStream.java:475)
        at io.grpc.internal.DelayedStream$DelayedStreamListener.delayOrExecute(DelayedStream.java:417)
        at io.grpc.internal.DelayedStream$DelayedStreamListener.closed(DelayedStream.java:472)
        at io.grpc.internal.ForwardingClientStreamListener.closed(ForwardingClientStreamListener.java:39)
        at io.grpc.internal.InternalSubchannel$CallTracingTransport$1$1.closed(InternalSubchannel.java:661)
        at io.grpc.internal.AbstractClientStream$TransportState.closeListener(AbstractClientStream.java:471)
        at io.grpc.internal.AbstractClientStream$TransportState.access$400(AbstractClientStream.java:233)
        at io.grpc.internal.AbstractClientStream$TransportState$1.run(AbstractClientStream.java:454)
        at io.grpc.internal.AbstractClientStream$TransportState.deframerClosed(AbstractClientStream.java:290)
        at io.grpc.internal.Http2ClientStreamTransportState.deframerClosed(Http2ClientStreamTransportState.java:31)
        at io.grpc.okhttp.OkHttpClientStream$TransportState.deframerClosed(OkHttpClientStream.java:316)
        at io.grpc.internal.MessageDeframer.close(MessageDeframer.java:229)
        at io.grpc.internal.MessageDeframer.closeWhenComplete(MessageDeframer.java:191)
        at io.grpc.internal.AbstractStream$TransportState.closeDeframer(AbstractStream.java:183)
        at io.grpc.internal.AbstractClientStream$TransportState.transportReportStatus(AbstractClientStream.java:457)
        at io.grpc.okhttp.OkHttpClientTransport.startGoAway(OkHttpClientTransport.java:886)
        at io.grpc.okhttp.OkHttpClientTransport.access$1600(OkHttpClientTransport.java:108)
        at io.grpc.okhttp.OkHttpClientTransport$ClientFrameHandler.run(OkHttpClientTransport.java:1112)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by ericgribkoff** [comment] 2020-05-14 00:59
The stack trace indicates that the `ScheduledThreadPoolExecutor` has already shutdown and consequently rejects new tasks. Can you provide more detailed steps to reproduce this bug? Is there an additional stack trace included in the output? And is this actually causing the app to crash or just showing up in the log output?

**Comment by antranvn** [comment] 2020-05-15 03:31
I integrate [SpeechRecognitionClient](https://github.com/GoogleCloudPlatform/android-docs-samples/tree/master/speech/SpeechRecognitionClient) into my application. I saw that when I shutdown [speechclient](https://github.com/GoogleCloudPlatform/android-docs-samples/blob/a49dd7157ee56e5ff8d05d29416f44403b241a46/speech/SpeechRecognitionClient/app/src/main/java/com/google/cloud/examples/speechrecognition/MainActivity.kt#L154), the issue will happen. When I remove that line, it will be ok. Yeap, this is actually causing the app to crash.

**Comment by ericgribkoff** [comment] 2020-05-15 06:09
Are you running the sample code directly from https://github.com/GoogleCloudPlatform/android-docs-samples and seeing that app crashing? ~~If so, you should probably open an issue on that repository.~~ I saw you filed https://github.com/GoogleCloudPlatform/android-docs-samples/issues/123 already; that may end up being the most appropriate place to investigate but I have some questions that can help us triage this further.

Can you clarify if the crash is reproducible just by installing and running https://github.com/GoogleCloudPlatform/android-docs-samples/tree/master/speech/SpeechRecognitionClient or if the crash is only occurring when you add the client to your own code? I would like to figure out if there is a bug somewhere in the speech client library itself or if it's possible the crash is due to how the library is being used by the app. If you have your own code using SpeechRecognitionClient it would be helpful to see where and how that code is calling shutdown. Thanks!

**Comment by antranvn** [comment] 2020-05-19 08:24
The crash is only occurring when I add to my own code. You can see a part of the code [here](https://git.io/JfuXO).

**Comment by ericgribkoff** [comment] 2020-05-19 20:52
From your code:

```
        /*if (mSpeechClient != null) {
            mSpeechClient.close();
            mSpeechClient = null;
        }*/
        if (requestStream != null) {
            requestStream.onCompleted();
        }
```

It looks like (without the commented out portion) you are closing the client and then calling onCompleted on the stream. Closing the client will, among other things, close the associated executor and should terminate any active streams. I believe the RejectedExecutionException when you subsequently call `onCompleted` on the request stream is expected.

If you just close the speech client and do not include the call to `requestStream.onCompleted()` do you still see the exception and crash?

**Comment by antranvn** [comment] 2020-05-20 09:04
Hi @ericgribkoff ,
I commented out the closing of mSpeechClient because it raises the exception, even if I do not include the call to `requestStream.onCompleted()`, it still has the exception. I add `requestStream.onCompleted()` is just for try ending the active stream.

**Comment by 6unpk** [comment] 2020-05-29 17:42
@antranvn 
Hi, I experienced the same issue. 
Maybe I think it is problem of sample android code regardless of grpc library. 
https://github.com/GoogleCloudPlatform/android-docs-samples 

As you know, ```BidiStreamingCall``` was deprecated. even though i tried to call ```requestStream.onCompleted()``` i got error too. It looks like a bug due to ```BidiStreamingCall```

After replace ```ApiBidStreamCall``` with ```splitCall``` i solved this error.

You can find example code of ```splitCall``` from here
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/speech/cloud-client/src/main/java/com/example/speech/InfiniteStreamRecognize.java

**Comment by ericgribkoff** [comment] 2020-06-02 20:38
Thanks @6unpk! I also did not see anything that looked wrong from the gRPC side, and since the rejected execution exception is expected when the executor is already closed (as it appears to be from the stack trace), I'm going to mark this closed since I don't see anything further to do here from the gRPC side. @antranvn If I've missed something, feel free to comment again here and we can reopen.

**Closed by ericgribkoff** 2020-06-02 20:38 UTC
Labels: bug
