### ISSUE TITLE
How to transform nullvalues as java pojo fields with protobuffer?

### ISSUE THREAD

**Issue by tangmin823** [grpc/grpc-java#8076] opened 2021-04-11 17:25 UTC
Is this library supports null as default value, right? but google protobuffer dosen't, you know.

**Comment by sanjaypujare** [comment] 2021-04-11 22:27
Sorry not clear about what the issue is. Can you give an example to clarify?

**Comment by tangmin823** [comment] 2021-04-12 09:08
I have seen this, please open this link:[Default Values](https://developers.google.com/protocol-buffers/docs/proto3#default)
If I set the field as null, then it will set the default  value.
I see Protocol Buffers dosen't support null? But I need null, how do I do? I use your help, thanks a lot.
@sanjaypujare

**Comment by sanjaypujare** [comment] 2021-04-12 16:45
You will have to open the issue with [protocol buffers](https://github.com/protocolbuffers/protobuf/issues). This is not a grpc-java issue.

**Comment by voidzcy** [comment] 2021-04-12 23:20
> I see Protocol Buffers dosen't support null? But I need null, how do I do? I use your help, thanks a lot.

Starting from [protobuf 3.15](https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0), you can use `optional` keyword to preserve field presence for primitive types. The protobuf compiler will emit a `hasXXX()` method for fields with `optional`.

Effectively, this isn't something new. Wrapping a primitive type with `oneof` achieves the same thing.

Also, there are [wrapper types](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto). They are " for places needing to distinguish the absence of a primitive typed field and its default value".

**Comment by tangmin823** [comment] 2021-04-13 00:14
@voidzcy Thank you very much, I will try it. I wish it'll dose.

@sanjaypujare Thank you too.

**Comment by ejona86** [comment] 2021-04-13 19:55
To be a bit more clear, protobuf has always supported presence for messages. Only primitives (integer types, string, etc) lacked presence. No presence for integer types probably doesn't surprise Java programmers, but string probably does. I'll note that even with presence, Protobuf's API doesn't return `null`; you need to use the separate `has*()` methods.

Seems this issue is resolved, so closing. But if I missed something comment and we can reopen.

**Closed by ejona86** 2021-04-13 19:55 UTC
Labels: question

**Comment by tangmin823** [comment] 2021-04-20 07:44
Using protoc below version3.12,  When I compile the proto code below, This didn't work. 
```shell
message CarBrandVO {
    optional string user_id;
    optional int64 id;
}
```
```python
Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
```

But I use ``oneof`` instead ``optional``,  it's ok, like this:
```shell
message CarBrandVO {
    oneof oneof_user_id {
      string user_id;
   }
   oneof oneof_id {
      int64 id;
   }
}
```

In order to use `optional`, I upgrade the protoc plugin version to 3.12 ~ 3.13, the exception changed:
![image](https://user-images.githubusercontent.com/13765160/115355971-c4711b00-a1ed-11eb-813c-b0895a899a4c.png)

In the end, I go on to upgrade the protoc to newer version 3.15.8, and it still didn't work, the error info changed again.
![image](https://user-images.githubusercontent.com/13765160/115357105-ddc69700-a1ee-11eb-9b32-f8796a6d914c.png)

@voidzcy @ejona86 
**I need your help, How can I use  `optional` with proto3.0 which version is  above 3.12 ?**

**Comment by ejona86** [comment] 2021-04-20 16:14
@tangmin823, this issue is unrelated to yours. Please open a separate issue instead.

**Comment by voidzcy** [comment] 2021-04-20 17:46
@tangmin823 

> car.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-grpc hasn't been updated to support optional fields int proto3.

Which gRPC-Java (its protoc plugin) version are you using? You need to use v1.31.0 or later, as this was added in #7054.

**Comment by tangmin823** [comment] 2021-04-21 01:31
> ~@tangmin823, this issue is unrelated to yours. Please open a separate issue instead.~ nm. I misread the flow through this issue.

Thanks for your response, it's ok!

**Comment by tangmin823** [comment] 2021-04-21 03:07
> @tangmin823
> 
> > car.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-grpc hasn't been updated to support optional fields int proto3.
> 
> Which gRPC-Java (its protoc plugin) version are you using? You need to use v1.31.0 or later, as this was added in #7054.

@voidzcy I used the older version `io.grpc:protoc-gen-grpc-java:1.28.0`.

then I upgraded it to `v1.31.0`, the `.proto` compilation did work, but I encounter another problem, maybe there is some incompatibility existed.
```log
2021-04-21 10:08:00.509 ERROR [tid=] [main] [SpringApplication] Application run failed
org.springframework.context.ApplicationContextException: Failed to start bean 'grpcServerLifecycle'; nested exception is java.lang.NoClassDefFoundError: io/grpc/InternalNotifyOnServerBuild
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185)
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:894)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at org.cango.mid.dictionary.CangoDictionaryApplication.main(CangoDictionaryApplication.java:20)
Caused by: java.lang.NoClassDefFoundError: io/grpc/InternalNotifyOnServerBuild
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at org.cango.mid.grpc.server.autoconfig.server.GrpcServerConfiguration.configureServices(GrpcServerConfiguration.java:82)
        at org.cango.mid.grpc.server.autoconfig.server.GrpcServerConfiguration.configure(GrpcServerConfiguration.java:67)
        at org.cango.mid.grpc.server.autoconfig.server.GrpcServerConfiguration.createServer(GrpcServerConfiguration.java:48)
        at org.cango.mid.grpc.server.autoconfig.server.GrpcServerLifecycle.createAndStartGrpcServer(GrpcServerLifecycle.java:89)
        at org.cango.mid.grpc.server.autoconfig.server.GrpcServerLifecycle.start(GrpcServerLifecycle.java:49)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
        ... 14 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.grpc.InternalNotifyOnServerBuild
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 32 common frames omitted
```
so I looked for the corresponding soution.[incompatible with grpc 1.30.0 #370](https://github.com/yidongnan/grpc-spring-boot-starter/issues/370) the issue was the same as mine. 
my grpc-services version was `v1.27.2`, I upgraded it to `v1.31.0` too.
![image](https://user-images.githubusercontent.com/13765160/115487921-31d38900-a28c-11eb-8935-3a7a3673f328.png)
![image](https://user-images.githubusercontent.com/13765160/115488019-69423580-a28c-11eb-9582-776895823f2f.png)

In the end, it's been solved, and it also support nullvalue fields(fieldType: String, Number) transmission.
the client received the response message, there's fields that have null values.
![image](https://user-images.githubusercontent.com/13765160/115490973-ac52d780-a291-11eb-839f-a30f5d71d769.png)

Thank you very much!
