### ISSUE TITLE
In geperated xxxGrpc.java,  remove javax.annotation, use jakarta.annotation.Generated

### ISSUE THREAD

**Issue by anborg** [grpc/grpc-java#10343] opened 2023-07-04 20:12 UTC
In generated xxxGrpc.java,  remove javax.annotation, use jakarta.annotation.Generated

https://github.com/anborg/corp-model/blob/7e5bc349e542e89a615203f4bc42c05185c6a07b/src/zgen/proto/java/corp/service/CaseServiceGrpc.java#L7C1-L7C29

https://github.com/anborg/corp-model/blob/7e5bc349e542e89a615203f4bc42c05185c6a07b/pom.xml#L142

Generated class 
```java

@javax.annotation.Generated(
    value = "by gRPC proto compiler (version 1.56.0)",
    comments = "Source: case-service.proto")
@io.grpc.stub.annotations.GrpcGenerated
public final class CaseServiceGrpc {

  private CaseServiceGrpc() {}

  public static final String SERVICE_NAME = "corp.model.CaseService";

  // Static method descriptors that strictly reflect the proto.
  private static volatile io.grpc.MethodDescriptor<corp.model.Model.ById,
      corp.model.Model.Case> getGetMethod;

  @io.grpc.stub.annotations.RpcMethod(
      fullMethodName = SERVICE_NAME + '/' + "get",
      requestType = corp.model.Model.ById.class,
      responseType = corp.model.Model.Case.class,
```

**Comment by sanjaypujare** [comment] 2023-07-04 21:28
There is already an issue https://github.com/grpc/grpc-java/issues/9179 which talks about `jakarta.annotation.Generated` not being appropriate. @anborg if you agree this can be closed as duplicate of that.

**Comment by ejona86** [comment] 2023-08-01 21:16
Seems like this is resolved. If not, comment, and it can be reopened.

**Closed by ejona86** 2023-08-01 21:16 UTC
