### ISSUE TITLE
java.lang.NoClassDefFoundError: com.squareup.okhttp.internal.spdy.Http2

### ISSUE THREAD

**Issue by gorgepm** [grpc/grpc-java#968] opened 2015-09-08 10:06 UTC
when launch to the following line[ HelloReply reply = stub.sayHello(message) ] , runtime exception occurs,java.lang.NoClassDefFoundError: com.squareup.okhttp.internal.spdy.Http2

Following the the MainActivity:
```java
package grpc.pm.com.grpcclient;

import android.os.AsyncTask;
import android.support.v7.app.ActionBarActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;

import com.squareup.okhttp.ConnectionSpec;

import java.util.concurrent.TimeUnit;

import io.grpc.ManagedChannel;
import io.grpc.examples.GreeterGrpc;
import io.grpc.examples.nano.Helloworld.HelloRequest;
import io.grpc.examples.nano.Helloworld.HelloReply;
import io.grpc.okhttp.NegotiationType;
import io.grpc.okhttp.OkHttpChannelBuilder;


public class MainActivity extends ActionBarActivity {
    Button mBtn;
    EditText mSendText;
    TextView mResult;
    public static final String TAG = "MainActivity";

    public void findViewById(){
        mBtn = (Button) findViewById(R.id.sendBtn);
        mSendText = (EditText) findViewById(R.id.sendEt);
        mResult = (TextView) findViewById(R.id.result);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        findViewById();

        initView();

        mBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                sendToServer();
            }
        });

        Thread.setDefaultUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
            @Override
            public void uncaughtException(Thread thread, final Throwable ex) {
           
                ex.printStackTrace();
                System.exit(0);
            }
        });

    }

    public void initView(){

    }

    public void sendToServer(){
        mBtn.setEnabled(false);
        new GrpcTask().execute();

        /*new Thread(new Runnable() {
            String mHost = "192.168.1.2";
            String mText = mSendText.getText().toString();
            int mPort = 50051;
            @Override
            public void run() {
                ManagedChannel channel = OkHttpChannelBuilder.forAddress(mHost, mPort).build();
                HelloRequest message = new HelloRequest();
                message.name = mText;
                GreeterGrpc.GreeterBlockingStub stub = GreeterGrpc.newBlockingStub(channel);
                HelloReply reply = stub.sayHello(message);
                String res = reply.message;
                Log.d(TAG,res);
                mResult.setText(res);
            }
        }).start();*/
    }

    private class GrpcTask extends AsyncTask<Void, Void, String> {
        private String mHost;
        private String mMessage;
        private int mPort;
        private ManagedChannel mChannel;

        @Override
        protected void onPreExecute() {
            mHost ="192.168.1.2";
            mPort = 50051;
            mMessage = mSendText.getText().toString();
            mResult.setText("");
        }

        private String sayHello(ManagedChannel channel) {
            GreeterGrpc.GreeterBlockingStub stub = GreeterGrpc.newBlockingStub(channel);
            HelloRequest message = new HelloRequest();
            message.name = mMessage;
            HelloReply reply = stub.sayHello(message);
            Log.d(TAG, "send successfully");
            return reply.message;
        }

        @Override
        protected String doInBackground(Void... nothing) {
            try {
                Log.d(TAG,"doInBackground begin......");
                OkHttpChannelBuilder builder = OkHttpChannelBuilder.forAddress(mHost, mPort);
                //builder = builder.connectionSpec(ConnectionSpec.CLEARTEXT);
                builder = builder.negotiationType(NegotiationType.PLAINTEXT);
                mChannel =  builder.build();
                String res = sayHello(mChannel);
                return res;
            } catch (Exception e) {
                e.printStackTrace();
                return "sayHello Failed... : " + e.getMessage();
            }
        }

        @Override
        protected void onPostExecute(String result) {
            try {
                Log.d(TAG, "onPostExecute"+result);
                mChannel.shutdown().awaitTermination(1, TimeUnit.SECONDS);
            } catch (Exception e) {
                Thread.currentThread().interrupt();
            }
            mResult.setText(result);
            mSendText.setEnabled(true);
        }
    }

}
```

**Comment by ejona86** [comment] 2015-09-08 15:54
Currently we depend on OkHttp internals, and some of those changed since okhttp `2.4.0`. #182 is tracking fixing any breakages caused by it. We don't expect to stop using the internals soon though.

If you swap to okhttp 2.4.0, you shouldn't have problems. If you want some of the fixes in 2.5 for your own application's usage of okhttp, then we can turn this issue into "upgrade to okhttp 2.5 for grpc-java".

**Comment by ejona86** [comment] 2015-09-16 23:02
Closing. Please comment if changing OkHttp version did not fix the issue. The better solution is already being covered in #182.

**Closed by ejona86** 2015-09-16 23:02 UTC

**Comment by gorgepm** [comment] 2015-10-13 15:48
Changed the OkHttp version,the issue can not be reproduced,thanks!
I am sorry that had not response your comment in time.

2015-09-17 7:02 GMT+08:00 Eric Anderson <notifications@github.com>:
