### ISSUE TITLE
Maven Build Issue from Setting `Class-Path` in the jar manifest for grpc-netty-shaded

### ISSUE THREAD

**Issue by michaelli321** [grpc/grpc-java#8606] opened 2021-10-14 23:40 UTC
### What version of gRPC-Java are you using?

1.41.0

### What is your environment?

JDK 16, Maven version 3.8.1, MacOS Catalina 10.15.7

### What did you expect to see?

a clean build of my project

### What did you see instead?

```
[WARNING] [path] bad path element "/Users/mli/.m2/repository/io/grpc/grpc-netty-shaded/1.41.0/grpc-core-1.41.0.jar": no such file or directory
[WARNING] [path] bad path element "/Users/mli/.m2/repository/io/grpc/grpc-netty-shaded/1.41.0/grpc-api-1.41.0.jar": no such file or directory
[WARNING] [path] bad path element "/Users/mli/.m2/repository/io/grpc/grpc-netty-shaded/1.41.0/guava-30.1-android.jar": no such file or directory
[WARNING] [path] bad path element "/Users/mli/.m2/repository/io/grpc/grpc-netty-shaded/1.41.0/error_prone_annotations-2.9.0.jar": no such file or directory
[WARNING] [path] bad path element "/Users/mli/.m2/repository/io/grpc/grpc-netty-shaded/1.41.0/perfmark-api-0.23.0.jar": no such file or directory
[WARNING] [path] bad path element "/Users/mli/.m2/repository/io/grpc/grpc-netty-shaded/1.41.0/failureaccess-1.0.1.jar": no such file or directory
[WARNING] [path] bad path element "/Users/mli/.m2/repository/io/grpc/grpc-netty-shaded/1.41.0/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar": no such file or directory
[WARNING] [path] bad path element "/Users/mli/.m2/repository/io/grpc/grpc-netty-shaded/1.41.0/jsr305-3.0.2.jar": no such file or directory
[WARNING] [path] bad path element "/Users/mli/.m2/repository/io/grpc/grpc-netty-shaded/1.41.0/checker-compat-qual-2.5.5.jar": no such file or directory
[WARNING] [path] bad path element "/Users/mli/.m2/repository/io/grpc/grpc-netty-shaded/1.41.0/j2objc-annotations-1.3.jar": no such file or directory
[WARNING] [path] bad path element "/Users/mli/.m2/repository/io/grpc/grpc-netty-shaded/1.41.0/gson-2.8.6.jar": no such file or directory
[WARNING] [path] bad path element "/Users/mli/.m2/repository/io/grpc/grpc-netty-shaded/1.41.0/annotations-4.1.1.4.jar": no such file or directory
[WARNING] [path] bad path element "/Users/mli/.m2/repository/io/grpc/grpc-netty-shaded/1.41.0/animal-sniffer-annotations-1.19.jar": no such file or directory
[WARNING] [path] bad path element "/Users/mli/.m2/repository/io/grpc/grpc-netty-shaded/1.41.0/grpc-context-1.41.0.jar": no such file or directory
```

### Steps to reproduce the bug
I added some other dependencies to an existing project in my `pom.xml` such as 
```   
 <dependency>
      <groupId>org.grpcmock</groupId>
      <artifactId>grpcmock-junit5</artifactId>
      <version>${grpc-mock.version}</version>
</dependency>
```

This issue has happened with other projects that we take a dependency on, see [here](https://github.com/launchdarkly/java-server-sdk/issues/240). Taking a look at the `MANIFEST.MF` of the grpc-netty-shaded jar, the `Class-Path` attribute is set which seems to be causing the bug.

```
Manifest-Version: 1.0
Implementation-Title: grpc-netty-shaded
Implementation-Version: 1.41.0
Class-Path: grpc-core-1.41.0.jar grpc-api-1.41.0.jar guava-30.1-androi
 d.jar error_prone_annotations-2.9.0.jar perfmark-api-0.23.0.jar failu
 reaccess-1.0.1.jar listenablefuture-9999.0-empty-to-avoid-conflict-wi
 th-guava.jar jsr305-3.0.2.jar checker-compat-qual-2.5.5.jar j2objc-an
 notations-1.3.jar gson-2.8.6.jar annotations-4.1.1.4.jar animal-sniff
 er-annotations-1.19.jar grpc-context-1.41.0.jar
```

**Comment by dapengzhang0** [comment] 2021-10-15 06:05
Can you try by adding

```
 <compilerArgs><arg>-Xlint:unchecked</arg></compilerArgs>
```

in your pom.xml as described in [this document](
http://maven.apache.org/plugins/maven-compiler-plugin/examples/pass-compiler-arguments.html)?

**Comment by michaelli321** [comment] 2021-10-18 20:55
@dapengzhang0 sorry I'm not able to provide a complete reproducible project since the project is for my company.

I'm able to get around the warnings using `<arg>-Xlint:-path</arg>` but I was hoping that this would be a temporary work around. My understanding is that if you were planning on others to use your jar as a library jar as opposed to a stand-alone application jar, then you shouldn't be setting the `Class-Path` attribute in the manifest since those dependencies could come elsewhere versus solely from the `grpc-netty-shaded/` directory. 

references: 
- https://stackoverflow.com/questions/1344202/bad-path-warning-where-is-it-coming-from
- https://stackoverflow.com/questions/41944939/maven-build-failure-involving-manifest-mf-classpath-in-dependency-jars
- http://samskivert.com/blog/2010/09/why-maven-sucks-act-ii/

**Comment by danielnorberg** [comment] 2022-01-03 22:49
@ejona86 Hey, I found this issue debugging the same "bad path element" warning in one of our internal projects where we're using `grpc-netty-shaded` and noticed the above comment that `grpc-netty-shaded` should only be in runtime scope. Is that documented somewhere? The [usage example in the readme](https://github.com/grpc/grpc-java#download) doesn't seem to be specifying any scope.

**Comment by dapengzhang0** [comment] 2022-01-04 03:32
> Is that documented somewhere? The usage example in the readme doesn't seem to be specifying any scope.

In the helloworld example
https://github.com/grpc/grpc-java/blob/v1.43.1/examples/build.gradle#L37
https://github.com/grpc/grpc-java/blob/v1.43.1/examples/pom.xml#L39
we do specify `grpc-netty-shaded` in runtime scope since the commit 3202fcc7d9321888af49064b57d8d5d6ca35bf85. The [REAME](https://github.com/grpc/grpc-java#download) seems not in sync.

**Comment by danielnorberg** [comment] 2022-01-04 16:22
@dapengzhang0 Got it, thank you. Took the liberty of submitting a PR to add the runtime scope to the readme.

**Comment by ijioio** [comment] 2022-01-28 15:37
I have a similar problem in Spring Boot application if run in Eclipse IDE. Here is my investigation of what is the cause of it:

The problem is about transitive dependency of `io.honeycomb` and classpath available for IDE. Not sure about IDEA, but in Eclipse all dependency classes are included to classpath.

Honeycomb adds a bunch of dependencies among which is also `grpc-netty-shaded-1.41.0.jar`:

```
...
|    ...
+--- io.honeycomb:honeycomb-opentelemetry-sdk:0.8.0
|    +--- io.opentelemetry:opentelemetry-exporter-logging:1.9.1
|    +--- io.opentelemetry:opentelemetry-exporter-otlp:1.9.1
|    +--- io.opentelemetry:opentelemetry-sdk-extension-resources:1.9.1
|    +--- io.grpc:grpc-netty-shaded:1.41.0
|    ...
...
```

Project have also implicit embedded tomcat dependency via `spring-boot-starter-web`, as well as explicit dependency of `tomcat-embed-jasper-9.0.56.jar`. Since we have `tomcat-embed-jasper` dependency a `org.apache.jasper.servlet.TldScanner` will be used to scan for Tag Library Descriptors during `org.apache.jasper.servlet.JasperInitializer.onStartup(Set<Class<?>>, ServletContext)` call.

Scanner will load available classpath entries resolving each of them. Library `grpc-netty-shaded-1.41.0.jar` is found successfully in local gradle cache:

```
file:/C:/Users/123/.gradle/caches/modules-2/files-2.1/io.grpc/grpc-netty-shaded/1.41.0/43fee785c101b3bfa3f7d916d8b47d5d736cbff2/grpc-netty-shaded-1.41.0.jar
```

Since it is a JAR file, an additional processing applied to check JAR file's `MANIFEST.MF`. It will extract all the entries of `Class-Path` of the manifest. Here is a list of all classpath entries of `grpc-netty-shaded-1.41.0.jar`:

```
Class-Path: grpc-core-1.44.0.jar grpc-api-1.44.0.jar guava-30.1.1-andr
 oid.jar error_prone_annotations-2.9.0.jar perfmark-api-0.23.0.jar fai
 lureaccess-1.0.1.jar listenablefuture-9999.0-empty-to-avoid-conflict-
 with-guava.jar jsr305-3.0.2.jar checker-compat-qual-2.5.5.jar j2objc-
 annotations-1.3.jar gson-2.8.9.jar annotations-4.1.1.4.jar animal-sni
 ffer-annotations-1.19.jar grpc-context-1.44.0.jar
```

Based on each of the entry an additional candidate will be added to the scan list. URL of the candidate is build in following way:

```java
    private void processManifest(Jar jar, boolean isWebapp,
            Deque<URL> classPathUrlsToProcess) throws IOException {
        ...
        Manifest manifest = jar.getManifest();
        if (manifest != null) {
            Attributes attributes = manifest.getMainAttributes();
            String classPathAttribute = attributes.getValue("Class-Path");
            ...
            String[] classPathEntries = classPathAttribute.split(" ");
            for (String classPathEntry : classPathEntries) {
                classPathEntry = classPathEntry.trim();
                ...
                URL jarURL = jar.getJarFileURL();
                URL classPathEntryURL;
                try {
                    URI jarURI = jarURL.toURI();
                    URI classPathEntryURI = jarURI.resolve(classPathEntry);
                    classPathEntryURL = classPathEntryURI.toURL();
                } catch (Exception e) {
                    if (log.isDebugEnabled()) {
                        log.debug(sm.getString("jarScan.invalidUri", jarURL), e);
                    }
                    continue;
                }
                classPathUrlsToProcess.add(classPathEntryURL);
            }
        }
    }
```

As a result it will create a list of additional entries similar to following:

```
file:/C:/Users/123/.gradle/caches/modules-2/files-2.1/io.grpc/grpc-netty-shaded/1.41.0/43fee785c101b3bfa3f7d916d8b47d5d736cbff2/grpc-core-1.41.0.jar
file:/C:/Users/123/.gradle/caches/modules-2/files-2.1/io.grpc/grpc-netty-shaded/1.41.0/43fee785c101b3bfa3f7d916d8b47d5d736cbff2/grpc-api-1.44.0.jar
file:/C:/Users/123/.gradle/caches/modules-2/files-2.1/io.grpc/grpc-netty-shaded/1.41.0/43fee785c101b3bfa3f7d916d8b47d5d736cbff2/guava-30.1.1-android.jar
...
```

Files above doesn't exists in a context of `grpc-netty-shaded`, they are all resided in their own contexts within the gradle cache. As a result I've got a lot of errors:

```
2022-01-28 18:28:24.475 [main] WARN  o.a.t.util.scan.StandardJarScanner   - Failed to scan [file:/C:/Users/123/.gradle/caches/modules-2/files-2.1/io.grpc/grpc-netty-shaded/1.41.0/43fee785c101b3bfa3f7d916d8b47d5d736cbff2/grpc-core-1.41.0.jar] from classloader hierarchy
java.io.IOException: java.lang.reflect.InvocationTargetException
	at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:209)
    ...
Caused by: java.nio.file.NoSuchFileException: C:\Users\123\.gradle\caches\modules-2\files-2.1\io.grpc\grpc-netty-shaded\1.41.0\43fee785c101b3bfa3f7d916d8b47d5d736cbff2\grpc-core-1.41.0.jar
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
    ...
```

**Closed** 2022-06-15 00:39 UTC
Labels: bug
