### ISSUE TITLE
Consider replacing java.util.logging with SLF4J. Or a custom logger.

### ISSUE THREAD

**Issue by ccleve** [grpc/grpc-java#2197] opened 2016-08-24 17:40 UTC
Very few libraries use java.util.logging these days because of all the problems. Netty uses their own logging facade into which you can plug your own implementation. It's not a bad approach, but it's easier to just use slf4j directly.

**Comment by carl-mastrangelo** [comment] 2016-08-24 17:43
Duplicate of https://github.com/grpc/grpc-java/issues/1577

**Comment by carl-mastrangelo** [comment] 2016-08-24 17:43
Specifically, see comment: https://github.com/grpc/grpc-java/issues/1577#issuecomment-228377170

**Closed by carl-mastrangelo** 2016-08-24 17:43 UTC
