### ISSUE TITLE
Building gRPC with Bazel: Guava lists don't have collectors

### ISSUE THREAD

**Issue by popovicu** [grpc/grpc-java#6921] opened 2020-04-11 09:02 UTC
I'm including the gRPC repository into my Bazel WORKSPACE like this:
```
http_archive(
    name = "com_github_grpc_grpc_java",
    strip_prefix = "grpc-java-1ee322cc1545762e253e9f950ef3f0f083dacb77",
    urls = [
        "https://github.com/grpc/grpc-java/archive/1ee322cc1545762e253e9f950ef3f0f083dacb77.tar.gz",
    ],
)
```

I have also copied over the Maven dependencies from Github.

Now, when I try to include Guava in my BUILD dependency, I add this: `"@com_google_guava_guava//jar",`.
The following results in an error:
```
import static com.google.common.collect.ImmutableList.toImmutableList;
```

The exact error is as follows:
```
.../EchoClient.java:3: error: cannot find symbol
import static com.google.common.collect.ImmutableList.toImmutableList;
^
  symbol:   static toImmutableList
  location: class ImmutableList
```

Is this maybe not supported in the Guava version used in gRPC?  
Would I be able to override which Guava version I'd like to use if building with Bazel?

**Comment by sanjaypujare** [comment] 2020-04-13 05:36
Are you building for Android?  `guava-28.2-android.jar` doesn't have this function defined but `guava-27.0.1-jre.jar` does. And querying deps using blaze for grpc I see:
```
@maven//:com_google_guava_guava
@maven//:v1/https/repo.maven.apache.org/maven2/com/google/guava/guava/28.2-android/guava-28.2-android.jar
```

**Comment by ejona86** [comment] 2020-04-14 23:08
There are simply [two versions of Guava available](https://github.com/google/guava#adding-guava-to-your-build). As a library that may be used on Android, gRPC uses the Android version which is a subset of the API provided by the JRE version. Just add a dependency on the JRE version and you should be fine:

```
maven_install(
     ...
     artifacts = [
      "com.google.guava:guava:28.2-jre",
     ...
)
```

**Comment by ejona86** [comment] 2020-04-21 21:18
Closing, since the last comment should address the issue. If it doesn't, comment again and we can reopen.

**Closed by ejona86** 2020-04-21 21:18 UTC
Labels: question

**Comment by naturalwarren** [comment] 2020-05-13 04:04
Specifying in `artifacts` did not resolve the issue for me. I had to explicitly declare a `dep` at the call-site that uses `java_grpc_library`. Then I got hit with this warning:

```
DEBUG: /private/var/tmp/_bazel_warren/53ddd15adde433e5548437923fc7d951/external/io_grpc_grpc_java/java_grpc_library.bzl:195:9: Multiple values in 'deps' is deprecated in identity_java_grpc
```

**Comment by ejona86** [comment] 2020-05-13 16:51
> Specifying in artifacts did not resolve the issue for me. I had to explicitly declare a dep at the call-site that uses java_grpc_library.

What error did you get if you _didn't_ declare the dep in the usage of java_grpc_library? Adding the dep is _really_ broken, as the generated code doesn't use ImmutableList. Please don't do that. I will remove the multiple-deps support in the future and you will break.

I think the problem is you are getting another copy of Guava in your dependencies. I suggest doing something like `bazel query 'deps(//your/target)' | grep guava` and making sure there is only one version of Guava in the dependency list.

**Comment by naturalwarren** [comment] 2020-05-14 20:17
I get a variety of no such method found errors. The targets that produce these errors also explicitly compile against Guava. 

```
java.lang.NoSuchMethodError: com.google.common.base.Stopwatch.elapsed()Ljava/time/Duration;
       com.css.identity.server.PasswordUtilTest.hash_runtimeIsSufficient(PasswordUtilTest.java:32)
       sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       java.lang.reflect.Method.invoke(Method.java:498)
       org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
       org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
       org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
       org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
       org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
       [...]
```

```
  => java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.toImmutableList()Ljava/util/stream/Collector;
       org.jdbi.v3.guava.GuavaCollectors$Factory.<init>(GuavaCollectors.java:256)
       org.jdbi.v3.guava.GuavaCollectors.factory(GuavaCollectors.java:85)
       org.jdbi.v3.guava.GuavaPlugin.customizeJdbi(GuavaPlugin.java:26)
       org.jdbi.v3.core.internal.exceptions.Unchecked.lambda$consumer$0(Unchecked.java:35)
       org.jdbi.v3.core.Jdbi.installPlugin(Jdbi.java:233)
       [...]
       Suppressed: org.postgresql.util.PSQLException: ERROR: relation "sessions" does not exist
         org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
         org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
         org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
         org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
         org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
```

**Comment by ejona86** [comment] 2020-05-14 20:28
"java.lang.NoSuchMethodError: com.google.common.base.Stopwatch.elapsed()Ljava/time/Duration;" is still a `-android` vs `-jre` problem. Since you compiled successfully but failed at runtime, it means a duplicate Guava is in your classpath. The only real solution is to check your deps and remove the duplicate.
